### ISSUE TITLE
Button to copy Organization contact to event contact

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#100]
When there are more than 1 org in organizer, take the first organizer in the list.

![Image](https://user-images.githubusercontent.com/419491/221879141-7205f1f5-9aa2-463a-858c-0bcdf4b11281.png)

The designs for the Copy organizer contact are now displayed in figma 12. Here are screenshots of the English and French screens.
**English:**

![Image](https://user-images.githubusercontent.com/64489312/221931100-aece8318-82d1-42ad-91dd-a75a991cfa4c.png)

**French:**

![Image](https://user-images.githubusercontent.com/64489312/221931142-3d3114a3-69e5-41d2-a5ec-a00b4848d69d.png)

**Comment by AbhishekPAnil** [comment]
ESTIMATES 2-3hrs

Subtasks 
1.Add button to copy organizer contact
2.Add the functionality to display the copied contacts.

**Comment by AbhishekPAnil** [comment]
@SuhailAliyar Would you please update the { https://staging.api.cms.footlight.io/entities?query=&classes=Organization&classes=Person } api's response with their respective contact details :

Contact details fields needed:
1.Name(both fr and en)
2.website/url
3.Phone number 
4.Email

Thanks!

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
Tested for both signe laval and outaouais in Chrome: PASSED
