### ISSUE TITLE
Revert to draft button not working

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1001]
For Pending review events, the button in the event details "Revert to draft" doesn't work.
If this could possibly be fixed and pushed to production next week that would be great. Hopefully just a small thing. :)
Steps to repeat:
1. Admin open an event for review
2. Try to revert to draft. 
3. Note the rightclick menu in the event listing works. Only the button in Event details is not working.
[See this event](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65d4e1df78764100a267780f)

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil
 The error happeneed due to a missing line of code .Refer the commit [b09a415](https://github.com/culturecreates/footlight-app/pull/981/commits/b09a415c270f48f2b161158f33fa9e403d2664fe).

The line 823 didn't have the reviewPublishHandler function to toggle the state.
