### ISSUE TITLE
Display video in Event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#101]
Enter a Youtube or Vimeo video link.

- [x] Display the video below the url field.
- [x] DONE in backend - Maybe you will still need to validate in front - Validate that url is either Youtube or Vimeo. Throw a validation error for any other platform.
- [x] DONE in backend - Reformat youtube to embed url format (if not already in the right format)

Example of reformatting Youtube: When the user enters the https://youtu.be/qqIH9ez7d9A share link, the backend needs to transform it to an embed URL of https://www.youtube.com/embed/qqIH9ez7d9A so it can be embedded in the iFrame.  The display in the video link field should remain the way the user entered it, which can be either the share link or embed link.

See copy for video url validation check if not youtube or vimeo: 
https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=727653462

**Comment by saumier** [comment]
@saumier Add details on discussion with Minimal

**Comment by saumier** [comment]
@AbhishekPAnil Here is the approach taken with Minimal on the front-end.  As a way to test if the iframe is good, please use the same approach in the CSM.

---------

The following iFrames directly copied from Youtube and Vimeo.  The width and height can vary.

YouTube: 
- Our updated API provides the embed url https://www.youtube.com/embed/gHL8EEITt7M.

<iframe width="560" height="315" src="https://www.youtube.com/embed/gHL8EEITt7M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Vimeo: 
- Our updated API provides the embed url  https://player.vimeo.com/video/296373541.

<iframe src="https://player.vimeo.com/video/296373541?color=ffffff&title=0&byline=0&portrait=0&badge=0" width="560" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

**Comment by saumier** [comment]
@AbhishekPAnil Please check with @SuhailAliyar about the implementation of the video validation and reformatting to an embed url.  I believe the embedUrl was only added to the Footlight Open API for Minimal, and not to the Footlight CMS API, but please check with Suhail. I realize that the embedUrl will only be generated after the event is saved, so I am not sure of the solution for the CMS. One idea is to only display the video after the event is saved. That way you wouldn't need to re-implement the business logic to reformat URLs.

**Comment by AbhishekPAnil** [comment]
ESTIMATE 4-6hrs

**Comment by saumier** [comment]
@SyamBabu-M  This did not pass my test.  If I read the description of this issue, when I enter either type of video url I get an error message in red under the field.  I expect both urls to work and display the video without an error message in red.



https://youtu.be/qqIH9ez7d9A

![Image](https://github.com/culturecreates/footlight-app/assets/419491/bea942f7-7a98-4d06-be01-590b54375098)

https://www.youtube.com/embed/qqIH9ez7d9A


![Image](https://github.com/culturecreates/footlight-app/assets/419491/8f259b21-be96-4bd4-a5f0-5e73646934c3)

**Comment by saumier** [comment]
@SyamBabu-M Looks great.
