### ISSUE TITLE
delete taxonomy concept modal - wrong label on button

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1014]
NOTE: the mislabeled popup is okay in the mobile view (the label is correct); this seems to only be an issue on desktop.

In both french and english, one of the button labels is wrong - the RED delete button that appears when you are confirming you want to delete a concept. The label is  'Leave' / 'Quitter' 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f428e71b-f2ec-4d81-8d5a-624be838b43e)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/81831b87-eb8d-4ada-b894-ef1d7a76e846)

### Correct labels for each language
French
Supprimer

English
Delete

**Comment by saumier** [comment]
@SyamBabu-M Looks good. Pass.
