### ISSUE TITLE
error when trying to send to review

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1015]
Error reported by Tout Culture and Signe Laval:
A few different guest users are unable to use the Send to Review button. They can save as draft only. When they try to 'Send to review' the get an error (taken from emails):

### User: yproulx shared this:
He wasn't able to save a draft, but the name of the event he was trying to add was “Petite Nation en fête”
He was able to create and submit one event, “Dominic and Martin”

### Username: dsavoie
Every time they tried to submit for approval it would send them to the same error page as the other users. They've since recreated the events and saved them as drafts. 
Here is some details regarding this user:
**Events**
07-MARCH-2024
**Tristan Guay**
Square Distillery
Draft
Created on 07-MARCH-2024 by dsavoie

30-MARCH-2024
**Emmanuelle Querry**
Square Distillery
Draft
Created on 07-MARCH-2024 by dsavoie

12-APR-2024
Etienne Fletcher
**Square Distillery**
Draft
Created on 07-MARCH-2024 by dsavoie

17-MAY-2024
**The Bronze**
Square Distillery
Draft
Created on 07-MARCH-2024 by dsavoie

### Signe Laval

Username: kcentropolis
I just created our event, but when I clicked "Send for Review" an error occurred. 
She recreated this event as a draft to be pushed by the Admin to published: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/65e78b4fbec01b00642f41b0

### Caitlin's Tested and Confirmed
Steps to repeat:
1. log in as guest
2. create a complete event
3. Click send to review.
4. This error appears.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d5e63ff9-a4f1-49c0-8420-30da545eccc6)

**Comment by sahalali** [comment]
It appears that there is an issue with the App's user interface. This issue occurs when a guest user attempts to create an event and simultaneously selects "save and send to review". In order to address this issue, there are two suggested approaches:

1. First, set the publish state to "PendingReview" before saving the event. This will ensure that the event is created in the review state.

2. Alternatively, you can save the event first using the save event API, and then use the toggle publish API to publish the event.

I hope this helps!

Assigning to @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
@saumier Were you unable to send the events to review?

**Comment by saumier** [comment]
@AbhishekPAnil This is not working.

# Test 1 - Steps to repeat:

1. log in as guest
2. click "+ Event"
3. create a complete event
4. Click send to review.
This error appears, but the event is saved as draft.



![Image](https://github.com/culturecreates/footlight-app/assets/419491/9333c370-2c30-4a00-982a-3ec3bba67589)


# Test 2 - Steps to repeat:

1. log in as guest
2. click "+ Event"
3. Click send to review without filling in any fields.

This error appears.

![Image](https://github.com/culturecreates/footlight-app/assets/419491/5091d900-625e-42f9-af81-73d3653470be)

**Comment by AbhishekPAnil** [comment]
@saumier I have updated the PR with the fix for the above issue.Please check it out and let me know if there are other issues .

**Comment by saumier** [comment]
@AbhishekPAnil This is working. There are several "flashes" but the result works. Please push into production.
