### ISSUE TITLE
Bug: Event page loads for mismatched calendar

### ISSUE THREAD

**Issue by dev-aravind** [culturecreates/footlight-app#1023]
When viewing an event details page in the CMS, if we manually change the URL to another calendar's URL, the page loads with no details even though the event does not belong to the calendar and the API call for event details fails. 

![Image](https://github.com/culturecreates/footlight-app/assets/132546883/54ad1d49-fbbe-47b4-94ce-6a549217456c)

For example, in the above image, event with id: 648b1d845526a70064502449 does not belong to calendar id: 63457978637093005071a053.

P.S: This happens only on the Super Admin user. (admin@culturecreates.com)

**Comment by saumier** [comment]
Ok. This passed my test of manually changing urls as super admin.
