### ISSUE TITLE
Name change: Culture Mauricie Calendar

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1024]
Changing the official name of the Culture Mauricie calendar to DICI.ca

**Comment by tammy-culture** [comment]
@sahalali Can you please do the following:

- [ ] Change the official name of Culture Mauricie to DICI.ca
- [ ] Please add a favicon.  Here is a link to their [site](https://dici.ca/)

**Comment by sahalali** [comment]
@tammy-culture 
Could you please request a logo from DICI.ca that is suitable for our CMS? The current logo, which can be found on their site https://dici.ca/, is vectorized and has each letter in DICI separated, making it unusable for our purposes.

**Comment by sahalali** [comment]
@saumier, thank you for providing the favicon URL. The calendar icon has been updated with the favicon.
