### ISSUE TITLE
Reload events from users acogeco and ashawinigan to DICI.ca (Culture Mauricie) production CMS.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1025]
The DICI.ca calendar (Culture Mauricie) is currently live.  Next steps for the client is to load events from following users to their production CMS:
- acogeco 
- ashawinigan

**Comment by tammy-culture** [comment]
For now just focus on acogeco and ashawinigan.  

We will revisit atourisme mauricie at a future date.

**Comment by tammy-culture** [comment]
@sahalali There seems to be a problem with the ashawinigan user. The aggregator is picking up multiple incorrect event types.

Please see the example below.  The event type should only be "humour". not improvisation and not lecture.  

Is there a way that we can fix this?

Many thanks,
Tammy



![Image](https://github.com/culturecreates/footlight-app/assets/45608438/12c2563b-66ef-4533-b831-1ba869598372)

**Comment by tammy-culture** [comment]
@sahalali Note: 

The client also mentioned that he noticed wrong times appearing in the CMS for the ashawinigan user.

He said that for several Culture Shawinigan shows, the times that arrive are not the right ones. Most shows are at 8pm, but they arrive in the CMS with the indication that it's at 3pm or 4pm.  Unfortunately he didn't take any screenshots of this problem, and he rectified the issue himself.  

Please take a look into this situation as well.  Thank you.

**Comment by sahalali** [comment]
The event "Jay Du Temple Fu" having _eventgenrename_ : "Spactacle" and _eventsubgenrename_ : "Humour".
We consider both _eventgenrename_ and _eventsubgenrename_ for additionalType.
The mapping file maps spectacle or spectacles to Improvisation and Lecture and Humour to Humour.
That is the reason why we have **Improvisation, Lecture and Humour**

@tammy-culture Can you please confirm for me if we need only eventsubgenrename to consider.

**Comment by sahalali** [comment]
The issue with time issue is fixed in the aggregator. The new events imported will have the correct time,

**Comment by tammy-culture** [comment]
@sahalali I am writing to confirm that the  eventsubgenrename for ashawinigan should only be considered.

Many thanks.
Tammy

**Comment by sahalali** [comment]
The change is now done. This change will be reflected in the new events while importing new events or updating unedited events to CMS.

**Comment by sahalali** [comment]
@tammy-culture Both Cogeco and Shawinigan are not yet scheduled. We will manually import both sources by running the workflow.

**Comment by tammy-culture** [comment]
@sahalali Can we put it in an automated schedule daily?  Thanks.

**Comment by sahalali** [comment]
Scheduled daily runs for Cogeco (4:00 AM ET) and Shawinigan (5:00 AM ET).
