### ISSUE TITLE
Link to Artsdata broken

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1032]
When clicking on the Artsdata link in a Person detail screen, the server displays a 404.
https://cms.footlight.io/dashboard/63457978637093005071a053/people/65b92c258468f400648408da

The first 3 people in signe-laval have the same problem.

**Comment by sahalali** [comment]
@AbhishekPAnil 
It appears that there is a problem with the user interface. The Artsdata ID must be taken from the 'sameAs' property of the entity consistently in both the entity listing and the entity read-only page. The 'derivedFrom' property should be used to identify the source of the entity. However, it is important to note that the source may not necessarily be Artsdata alone in the future.

The artsdata link displaying in the entity listing page is correct. The sameAs property should be used for the Artsdata link in both the entity listing page and the entity read-only page.

Can you please make that change?

**Comment by AbhishekPAnil** [comment]
I have updated the code in frontend .
Now the artsdata link is taken from the sameAs property across all the workspaces.

**Comment by saumier** [comment]
@sahalali @AbhishekPAnil Thanks for this rapid diagnostic and fix.

**Comment by saumier** [comment]
@troughc I tested this and it looks good.
