### ISSUE TITLE
Feature: ability to add multiple images to entities

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1033]
Update the settings section and image settings for each entity so that users can add multiple images (a gallery) if needed.
New settings for adding multiple images:
Here is the Figma link for you: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=9647%3A90906&mode=design&t=cdlTJ3b9H8WfrcKD-1

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/39544473-7033-4c9a-a47c-9cf9883e3a95)

Background
In an initial meeting with ArtscultureNB and their technical web service provider [National](https://www.national.ca/en/), they requested the ability to add multiple images for organizations.

**The launch date for ArtscultureNB's new website is currently scheduled for June 15th.**

\

**As per our discussion, we will only complete the image gallery upload in this issue.

Cropping images in the image gallery has a bug where the crop values are not persisting properly. Hence, it will be dealt with in a separate issue.cc @AbhishekPAnil Once the new issue is created please link it to this**

@troughc **_Please find the test cases below:_**
**Test Cases.**

1. Login as an admin and go to Settings > Calendar settings tab.Try to enable/disable image gallery and save the settings. 

- If the image gallery is enabled,then all the users should be able to see Main image field as well as Additional Image field in all the forms.
- - If the image gallery is disabled ,then all the users should be able to see Main image  field only in all the forms.

2.If image gallery is enabled:(Save and publish depending on the mandatory fields in the calendar)

- Try to create an event/person/place/organization with main image and additional image
- Try to create an event/person/place/organization with main image only.
- Try to create an event/person/place/organization with additional image only.
- Try to create an event/person/place/organization with neither main image nor additional image.
- Check if the images are shown in the respective read only pages.

3.If the image gallery is disabled.

- Try to create an event/person/place/organization with main image.
- Check if the images are shown in the respective read only pages.

**Comment by tammy-culture** [comment]
FYI

**Some background info. on National**
National is a large private PR firm with offices in every major city across Canada and approximately 300 employees.  They have a wide range of services: pr, communications, brand management, marketing, stakeholder relations, advocacy, integrated solutions, digital solutions, technology and financial communications.  They have list sectoral expertise in many sectors (consumer goods and services, energy, financial services, healthcare, manufacturing, mining, public sector, retail and e-commerce, sports marketing, technology and transportation).

**Comment by troughc** [comment]
@sahalali @AbhishekPAnil please take a look at the screenshot to estimate how much time is needed for backend and frontend work. Also the other figmas are still a work in progress (coming soon).

**Comment by sahalali** [comment]
Backend:
1. Update the APIs: add calendar and update calendar to support the new image settings.
2. Update the image URL generation method to generate the Image URL with the new image settings.
3. Add support in the backend to upload multiple images for all entities(Event, Place, Person, Organization). 

Estimate: 16H

**Comment by AbhishekPAnil** [comment]
Frontend : 11H
1.Add the layout for the image gallery.
2.Add thumbnail and large settings fields.
3.Add the logic to prevent adding additional fields after all the workspace are added.
4.Add api integration changes to support image config changes.

**Comment by troughc** [comment]
@AbhishekPAnil I would like to talk with you about the workflow from adding multiple image to displaying to editing. I am thinking of changing the order of things. This would slightly impact the edit image modal.
@sahalali I don't think it would impact your work.

**Comment by troughc** [comment]
@AbhishekPAnil I added translations to the footlight copy document (highlighted in yellow).

**Comment by AbhishekPAnil** [comment]
@troughc I need read only page ,how should we show multiple images?

**Comment by troughc** [comment]
@AbhishekPAnil I took a look at the read only pages (logged in as a guest). I think we should release this first version with the display of "Additional images" as a list only. 


If we get feedback from our users requesting to show the Large version of additional images, we can make an revisit the display as an enhancement. And, if we do decide to display Large versions, my first thought on that is we could design it so that each image would be 'opened' in the page to display the large version (accordian style).

**Comment by AbhishekPAnil** [comment]
Questions for Caitlin.

1. How to show the Use for field in Customize image ?
2. What if the user chooses only a single workspace as Use for ?

**Comment by troughc** [comment]
@AbhishekPAnil @SuhailAliyar, for this first release, let's reduce the scope of this feature. 
We will NOT include a Use for field nor the "+ Add new image details" button for the main image details. Instead we will only offer one set of options for aspect ratio, max width that will be applied to all workspaces/classes. 

For the Additional images /  image gallery toggle - I have renamed it to Add image gallery | Ajouter la galerie d'images
(updated in CMS copy document).

**Comment by sahalali** [comment]
@AbhishekPAnil So, for now, please add all classes (Event, Place, Organization, Person) to the only image detail in that case so that no backend changes will be required.

**Comment by sahalali** [comment]
@AbhishekPAnil The issue with listing events is fixed. Please continue testing.

**Comment by dev-aravind** [comment]
@troughc The test server is updated with all the fixes now. You can test it in the linked PR. Let me know if you have any questions.

**Comment by troughc** [comment]
Tested: PASSED 
Note: there are a couple of very minor issues that does not block us pushing this live. I will log them in a separate issue.

**Comment by troughc** [comment]
@AbhishekPAnil given that @sahalali may not be available, can you please deploy this one?

**Comment by tammy-culture** [comment]
@saumier I received an answer from National on when they need access to the API for multiple images starting July 10th.
