### ISSUE TITLE
Complete Calendar Widget Configuration for DICI.ca

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1039]
Configure calendar widget for [DICI.ca](https://dici.ca/evenements):

- link events pages to appropriate events in widget
- Link see all events to event listings page of DICI.ca

**Comment by sahalali** [comment]
@tammy-culture Can you please provide an example event page URL and event listing URL?

**Comment by tammy-culture** [comment]
@sahalali 

Event listing: https://dici.ca/evenements

Event Page: https://dici.ca/evenements/devon-griffiths-femme-made

**Comment by dev-aravind** [comment]
@tammy-culture 

I updated the widget settings so that the widget fot culture mauricie points to the dici.ca website. Please let me know if you need any changes.
