### ISSUE TITLE
Bulk upload of JSON files to ArtsNB calendar

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1050]
Upload files to ArtsNB calendar so web team can start working with data in the Footlight CMS.

[venues-export-fr.json](https://github.com/culturecreates/footlight-app/files/14838074/venues-export-fr.json)
[venues-export-en.json](https://github.com/culturecreates/footlight-app/files/14838076/venues-export-en.json)
[events-export-fr.json](https://github.com/culturecreates/footlight-app/files/14838077/events-export-fr.json)
[events-export-en.json](https://github.com/culturecreates/footlight-app/files/14838075/events-export-en.json)

**Comment by sahalali** [comment]
@tammy-culture The ArtsNB data has been curated and imported to CMS (staging). Please review it to ensure accuracy. If everything is correct, we can create a calendar and import the data into production. You have been invited to the test calendar.

**Comment by tammy-culture** [comment]
Hi @sahalali,  

I notice that the staging CMS is not displaying all the information available for PLACES.

Here is an example: A&R Musik:

It looks like staging was able to display the description, but did not the address, postal code, city, province and country.

[{"id":7244,"title":"**A&R Musik**","description":"<p>Sale of DVDs, TV series and CDs of all kinds. Many local artists.<\/p>","websiteUrl":null,"ticketsUrl":null,"address":"**8, 3409 Rue Principale**","city":"**Tracadie-Sheila**","postalCode":"**E1X 1C7**","province":"**New Brunswick**","country":"**Canada**","coordinates":"47.521165100000,-64.912273100000","socialLinks":{"Facebook":"https:\/\/www.facebook.com\/profile.php?id=100057266267156"},"category":"Record Stores","venuesIndex":true},



![Image](https://github.com/culturecreates/footlight-app/assets/45608438/2004a5a7-8cee-412d-b0fb-c38acf476f88)

I have checked several PLACES in the staging CMS and none of them are displaying any street addresses, postal codes, cities, provinces or country.  

Thanks.

**Comment by tammy-culture** [comment]
@sahalali Also can we do the following:

- Grab ArtsNB's "category" field as a controlled vocabulary for PLACE types.
- To include their socialLinks to PLACES, can I create a custom field?

**Comment by sahalali** [comment]
@tammy-culture 

- Grab ArtsNB's "category" field as a controlled vocabulary for PLACE types. => I will add this
- To include their socialLinks to PLACES, do I need to create a custom field? => Currently the custom field in CMS should be mapped to a taxonomy. Alternatively, I can keep the social media links in the sameAs property if that makes sense. Otherwise, we need to add support in the CMS for places to record social media links.

cc @saumier

**Comment by tammy-culture** [comment]
@SuhailAliyar I contacted ArtsNB and they have provided a list of organizations that go along with their PLACES so we can capture the the websites url and social media links and put them as properties in the appropriate Class.

Here is the file they sent with Place ids, Place Names and associated Organization Name in both English and French.
https://docs.google.com/spreadsheets/d/1f_46m7aZ7tk56oAMjY3qlux3aa4thEb3ADfoANew3Ac/edit?usp=sharing

**Comment by sahalali** [comment]
As per the discussion,
@sahalali to create organizations from the list above. Each organization in the list will be linked to the corresponding place.

**Comment by sahalali** [comment]
The organizations are now uploaded and linked to places.

**Comment by tammy-culture** [comment]
Hi @sahalali,  Is there anyway we can load the website URLs and social media links from the venue list (PLACE) provided by ArtsNB to the appropriate ORGANIZATION?

The whole point of separating out Organizations and from Places was to make sure that we  could capture the appropriate properties of website URL and social media links in the right Class or Organization.  In the ARtsNB Venues list, website urls and social media links are listed as properties which is (as you know) not how our Footlight CMS works.

If you need me to do any manually editing and data management before uploading please let me know. I am happy to do this work, but I would need the ARtsNB venue list in a format that I could manage.  

Many thanks.

**Comment by sahalali** [comment]
The website URL and social media links are now added to OrganizatIONS

**Comment by tammy-culture** [comment]
@sahalali ArtsNB staging is looking good. Can we push to the Production CMS please.

Many thanks.

**Comment by tammy-culture** [comment]
@sahalali I noticed a PLACE upload problem.  It is my bad that I did not catch it. 

PLACES in English and French are not aligned. Please see examples below:

[English: Aberdeen Cultural Centre / French: Académie Sainte-Famille](https://cms.footlight.io/dashboard/65eeaf8ebec01b0064312f94/places/661f6eb60796c30064529357)

[English: Académie Sainte-Famille / French: Ancienne réserve de St Mary's
](https://cms.footlight.io/dashboard/65eeaf8ebec01b0064312f94/places/661f6eb60796c30064529361)

[English: Aitken University Centre / French: Apple Art Gallery
](https://cms.footlight.io/dashboard/65eeaf8ebec01b0064312f94/places/661f6eb60796c3006452936b)

There are 11 pages of PLACES and they are all like this, except for the first PLACE A&R Musik.

Please fix and re-load PLACES thanks.
Tammy

**Comment by tammy-culture** [comment]
@sahalali FYI, there are different ids for each Place.

In the CSV PLACE file that the client provided, I can see that Aberdeen Cultural Centre id is the same(ID:6417) in both the English and French CSV and that the Académie Sainte-Famille has an ID:6419 in both CSV files.  

However, they do not occupy the same order in each file.  Does this make sense?

Many thanks,
Tammy
