### ISSUE TITLE
Ability to change the font appearing in the widget.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1053]
Culture Mauricie would like to know whether it would be possible to have the ability to change the font that appears in the widget

**Comment by tammy-culture** [comment]
@troughc Caitlin, can you help me assign where this needs to go.  Thanks.

**Comment by troughc** [comment]
@tammy-culture this would be a feature request. We would need to add a font choice section in the UI. @saumier do you know of any other approach the customer could take? Could they override the font we use for example (on the destination website)?

**Comment by troughc** [comment]
Next steps: 
- feasiblity study on abilty to customize fonts
- research and prepare a list of standard fonts

@SyamBabu-M can you please do the above and come back to us.

**Comment by SyamBabu-M** [comment]
@troughc I have created documentation for this issue. Please find it [here](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit#heading=h.b9en78q7gr4a)

**Comment by troughc** [comment]
@SyamBabu-M I added a couple questions for you.

**Comment by troughc** [comment]
@SyamBabu-M the fonts look good - approved by Caitlin and the designer. Please go ahead.

**Comment by SyamBabu-M** [comment]
@troughc I believe the design of the dropdown will be consistent with the other dropdowns on that page. If that is the case, just the label and position of the dropdown field in the form will be enough.

**Comment by troughc** [comment]
Caitlin to add labels and position.

**Comment by troughc** [comment]
@SyamBabu-M I tagged you in the figma for position and label of Font selectin dropdown. 
English label: Font selection
French label: Sélection de la police

**Comment by troughc** [comment]
@SyamBabu-M when the font changes, it doesn't change on the buttons, default text or other 'permanent' things in the widget is that right? 
I think the font should change everywhere to be consistent. Is this possible? If yes, how long would it take?
I agree, Merriweather doesn't look great (but let's tackle the above question first). 

I also would like to discuss this with you, @tammy-culture - in terms of what your customer was looking for specifically.

**Comment by SyamBabu-M** [comment]
@troughc this has been fixed. Now the entire widgets font will change.

**Comment by troughc** [comment]
Tested: PASSED!
