### ISSUE TITLE
Aggregators with similar "Places" 

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1054]
Hi @sahalali Can you please answer the following question: When different aggregators for a single calendar have similar "Places" are they reconciled or do duplicate "Places" appear in the production CMS?

**Comment by sahalali** [comment]
When different aggregators for a single calendar have similar "Places" they SHOULD BE reconciled otherwise, we will have duplicates. So, we ensure the data is reconciled.
