### ISSUE TITLE
Aspect ratio for Culture Mauricie (DICI.ca)

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1058]
Please change the image aspect ratio for Culture Mauricie to the following:

- thumbnail aspect ratio: 1.91 : 1
- event image: 1200 x 630 px
```[tasklist]
### Tasks
```

**Comment by sahalali** [comment]
@tammy-culture Updated Image ratios to Large: 40:21 (1220 x 630) with max width 1200.
For thumbnails, the ratio is set as 1.91, assuming no change in the max-width (623) 

cc @saumier
