### ISSUE TITLE
BUG: Problem with Acogeco aggregator - it does not display the correct showtime in the Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1059]
Hi @sahalali I noticed a bug with the Acogeco aggregator.  It consistently does not display the correct show times in the production CMS.

I will share examples below.

**Comment by tammy-culture** [comment]
For this performance of Sara Dufour, the performance time should be 8:30 PM and not 4:40PM.
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/66102c1a14060600646538a0



![Image](https://github.com/culturecreates/footlight-app/assets/45608438/2d490b37-42dc-4557-b790-a8b2bf7f33f0)

**Comment by tammy-culture** [comment]
Here are links to several other examples with incorrect show times in the production CMS:

https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/661027c914060600646515b8
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/661028e514060600646520be
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/66102b121406060064652e38
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/66102d4a140606006465485b
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/66102cd7140606006465409f

**Comment by dev-aravind** [comment]
@tammy-culture This bug was fixed in the Aggregator by @sahalali a while back. So the issue only persists in the older events that are Published/ Updated by an Admin as those events cannot be updated by Aggregator. Let me know if you have any more questions.
