### ISSUE TITLE
Event listing dates

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1067]
By chance I came across this bug in production for the culture-mauricie calendar. Spot the error ;-).

Screen shot taken 2024-04-14 at 4.51.07 PM time in Montreal.
![Image](https://github.com/culturecreates/footlight-app/assets/419491/f051ef04-2ed4-4bdd-b2e6-975ea9fbe5c2)

**Comment by dev-aravind** [comment]
@saumier This issue is now fixed in staging. Please test it out and let me know if you see any issues.

**Comment by saumier** [comment]
@dev-aravind @SuhailAliyar I actually would like to know the expected behaviour for listing events by date. Otherwise it is difficult to confirm that it is fixed.  Can you write it down in a concise and elegant way? Not an east task.  I am also wondering why we don't show the time of the event in the widget and if this is by design or not.  The expected behaviour should be confirmed with Caitlin.

**Comment by dev-aravind** [comment]
@saumier 

- For daily events, the next upcoming date will be chosen for sorting. 
- For recurring events, the next upcoming subevent start date will be chosen for sorting.
- For single day events, the normal start date will be chosen. 
- In the case of 2 events happening on the same day, the event with the lesser rarity score will be shown first.

**Comment by saumier** [comment]
@dev-aravind This is looking good but I need a bit more time to test.

**Comment by troughc** [comment]
I am okay with this. I did notice one thing though - english is appearing in the list when French is selected (the word 'to' in a date range. This is also in Production.  Let's fix this.



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5229c32c-9e9e-4747-8daf-5d25d13ad8a0)

**Comment by troughc** [comment]
@SyamBabu-M where do I test this please?

**Comment by troughc** [comment]
Tested: PASSED
