### ISSUE TITLE
user blocked from adding a discipline in Signe Laval

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1075]
This error was discovered by a user of Signe Laval (guest user): https://cms.footlight.io/dashboard/63457978637093005071a053/settings/user-management/65d8ea52bec01b00642c2b4d
It was brought to our attention by the ADMIN (Maude).

The guest user has a problem when she adds a discipline in a new event. She gets the message below. In english it translates to something like:
Remove child failed on node: the node to be removed is not a child of this node

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f7e9ca39-c953-4c3c-b8a6-cbf1ba9d8dbd)

She then gets an error when she logs in, which tells her she is not authorized. This error happens just after the discipline message:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/73cb7fd6-6ed3-4477-9677-09ea89d3bea7)

@sahalali  I am assigning this to Abhishek and cc you in case it is a backend error.

**Comment by troughc** [comment]
@AbhishekPAnil and @sahalali, please look at the logs to see if you can figure out what went wrong. I am reassigning this to you @sahalali .

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend seems fine here. Please check the frontend for possible errors related to this. Thanks.

**Comment by troughc** [comment]
FYI: The discipline was musique classique

**Comment by saumier** [comment]
@AbhishekPAnil @SyamBabu-M  @troughc I wrote a little webpage that clears the browser storage and then redirects the user to the login screen. I then sent the link to the user that was blocked. The user emailed me back shortly after to say that it worked, and that she was unblocked and able to create her first draft event. So it could be an idea for other customer support cases.

Here is the temporary webpage that I put in the S3 bucket for cms.footlight.io.  You may want to add it to source control.

BTW, I called it medecin because that means doctor in French ;-)


```<!DOCTYPE html>
<html>
<body>
  <h1>Medecin Footlight</h1>
  Merci.
  <script>
    function clearLocalStorage() {
      localStorage.clear();
      console.log('Local storage has been cleared');
    }

    function clearCookies() {
      var cookies = document.cookie.split(";");
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i];
        var eqPos = cookie.indexOf("=");
        var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
        document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
      }
      console.log('Cookies have been cleared');
    }

    function clearSessionStorage() {
      sessionStorage.clear();
      console.log('Session storage has been cleared');
    }

    function runFunctionsAndRedirect() {
      clearLocalStorage();
      clearCookies();
      clearSessionStorage();

      window.location.href = "https://cms.footlight.io";
    }
    window.onload = runFunctionsAndRedirect;
  </script>
</body>
</html>
```
