### ISSUE TITLE
not able to switch calendars easily

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1076]
When i click the calendar drop to switch from Signe Laval to another calendar, it doesn't always work.
Steps to reproduce:
I was in settings for signe laval. I switched my language from french to english, and saved. Then I tried to switch calendars to Tout Culture. and it didn't work until I refreshed the page.

This happens sporadically, not every time. It seems that after I refresh, it's fixed (so I can reproduce the behavior). But it has happened to me 3 or 4 times in the last few days. Can we please keep an eye on it? Maybe someone in the dev team will come across this issue (be able to reproduce it)...

**Comment by SyamBabu-M** [comment]
@troughc I tried to reproduce this issue but unfortunately, I was not able to do so. I am constantly keeping an eye on this. 
If you encounter this again, please drop in the steps to reproduce or a screenshot of the console, as it would be helpful in debugging this.

**Comment by troughc** [comment]
Difficult to reproduce this intermittent error so closing without fixing.
