### ISSUE TITLE
Setup Crow's Theatre calendar

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1077]
As part of the work to fix event series data flow, please setup a new calendar in production and load events using aggregator from Artsdata's artifact [culture-creates/footlight/crowstheatre-com](http://kg.artsdata.ca/culture-creates/footlight/crowstheatre-com)

The events can be viewed in Artsdata [here](http://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20crowstheatre-com%20%281228%20triples%29&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/footlight/crowstheatre-com) 

This will give us an environment to test the changes of how Artsdata mints event series and how CMS imports them.  This calendar is only for internal purposes and will not be used by the client.

**Comment by sahalali** [comment]
A new calendar is created: https://cms.footlight.io/dashboard/6628c7600796c300645636b0/events?page=1&order=asc&sortBy=upcomingEventDate

The API with the given source is not returning any result.
API: https://api.artsdata.ca/query?sparql=query_footlight_events&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/crowstheatre-com&limit=5&offset=0

**Comment by saumier** [comment]
@sahalali  Thanks for creating the new calendar for Crows. 

The Artsdata API was not returning any results because there were no events minted with Artsdata URIs. I minted some using the new strategy of minting only individual events instead of event series. Total of 13 events.

**Comment by saumier** [comment]
Here is the updated sparql https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events.sparql


You can use this call to the Artsdata query API:
https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/crowstheatre-com&limit=5&offset=0

**Comment by saumier** [comment]
@sahalali Lets continue in the [Doc](https://docs.google.com/document/d/1RyxNVXH1KieJ-ey-cGAp60pb8J7foiCu_Yv7o1tsVN0/edit)
