### ISSUE TITLE
Potentially adjust maximum width of aspect ratio from 1200 to 1920

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1078]
As per our brief discussion during our morning stand up, there is a judgement call to be made whether it would be possible to enlarge the current aspect ratio maximum width from 1200 to 1920. 

It will depend on the quality and resolution of images currently being uploaded from the various sources used in the Production CMS.

@sahalali It will be your judgement call.

**Comment by dev-aravind** [comment]
@tammy-culture Most of the images in Mauricie seems to have image width less than 1920. Here's the [data](https://docs.google.com/spreadsheets/d/1ZnRdhtJYeqZGqbk3YzFh1OBINg-sl9ddLqGxw65OB-M/edit#gid=0) for your reference.

**Comment by tammy-culture** [comment]
1. Most images do not have enough resolution for a maximum width of 1920.
2. Clients has some images that are even smaller than the max width of 1200, so what do we do in this case?
