### ISSUE TITLE
Create a way for the users to clear the cookies/redux cache or Implement a reload button.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1079]
Work out these two implementations and review it with @troughc to conclude on one.
1.Add a reload button which reloads the page whenever the user gets stuck in an error page. 
2.Add a button to clear the cookies/redux cache with respect to our app.

Supply the necessary screenshots to Caitlin for the user guide(Trouble shooting page)

3.Implement logging in frontend.

**Comment by troughc** [comment]
Thanks @AbhishekPAnil.  I set an April release but I realize this may not be done before May and that is okay (this is why I set it to low priority even though you will be working on it).

**Comment by troughc** [comment]
Can you guys propose a way to cache the data entered by the user -  at the browser level - before reloading the browser? In this way the user won't lose what data they entered. 
This idea came through a discussion I had with Kim on how we can preserve a user's work so they aren't losing precious time. 
One idea: you could use cookies. What other ideas do you have?
cc @AbhishekPAnil @SyamBabu-M

**Comment by SyamBabu-M** [comment]
@troughc I created a [document](https://docs.google.com/document/d/1pRgBsRSyrizk0-Qqed5m1rAD-H0_EQeGnVeuuQ10sp4/edit). I have added the necessary screenshots and a draft of the steps for the user to follow in there.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil @SyamBabu-M 
Discuss and come up with a permanent solution .

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil @SyamBabu-M 

1. Add logging .
2.May be add a button like Reset in the error page whenever an infinite loop occurs .

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil 
As per discussion, implement logging in frontend.( Updated the same in issue description )

**Comment by SyamBabu-M** [comment]
@saumier What logger service should we use for the front end? I found [RUM Datadog](https://www.datadoghq.com/product/real-user-monitoring/) to be a good choice.

**Comment by sahalali** [comment]
As per the discussion,

@sahalali to Design and develop an API in admin-api to be log errors from CMS (app)
@SyamBabu-M To document the learning after the logging service researching UI. Please add this to our company wiki once reviewed.

**Comment by sahalali** [comment]
@SyamBabu-M Please see [this API in staging now] and please test it to log CMS logs in datadog(https://staging.api.cms.footlight.io/api/#/Miscellaneous%20APIs/MiscellaneousController_logCmsApp)

**Comment by sahalali** [comment]
@SyamBabu-M The logging API is now hot fixed. Please test it.

**Comment by troughc** [comment]
@SyamBabu-M remind me how to test this? Also, did you see this update to the screens for the can't go back scenario (so you have to exit to login: https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=4654-46737&m=dev
