### ISSUE TITLE
Aggregate a new source from Artsdata.ca into D'ICI.CA Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1080]
Please aggregate the following source: http://kg.artsdata.ca/culture-creates/footlight/culturemauricie_lepointdevente-com into the Production CMS for Culture Mauricie.

**Comment by dev-aravind** [comment]
@saumier I couldn't find any events for this source using the [Artsdata API](https://api.artsdata.ca/query?sparql=query_footlight_events&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/culturemauricie_lepointdevente-com&limit=5&offset=0) in the aggregator. Can you look into this?

P.S : 3 events appear if you change the limit of the API to 150.

**Comment by saumier** [comment]
@dev-aravind The issue is that most of the Places from this data source called `culturemauricie_lepointdevente-com` are not linked to an Artsdata ID. Today I will link these places to their existing Artsdata Places and then the events will come through.

**Comment by saumier** [comment]
@dev-aravind I changed the rules about getting Places. I am allowing a Place to not have an Artsdata ID.

This is the new API query to Artsdata for the list of events.
http://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/culturemauricie_lepointdevente-com&limit=10&offset=70

This is the way an individual place details is fetched
http://api.artsdata.ca/query?uri=http://kg.artsdata.ca/resource/K2-224&format=json&frame=ranked_place_footlight&sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-place-v2.sparql

I have already setup these urls in the artsdata url constants file and manually run a couple of aggregator workflows. It is looking good. There is not a lot of tests but I think you should go ahead and add the new workflow for [culturemauricie_lepointdevente-com](http://kg.artsdata.ca/culture-creates/footlight/culturemauricie_lepointdevente-com)

**Comment by dev-aravind** [comment]
@saumier All the sources for Tout Cullture and Signe Laval use the reusable workflow now. Please have a look and let me know if you see any issues.
