### ISSUE TITLE
Organization name "Flûte alors" not sorting properly

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1088]
In Tout Culture CMS, the first organization you see when sorting by name is Flûte alors 
It is first whether I am looking at the UI in English or in French.
It doesn't have an english name. 
Please investigate. :)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/26154b4a-41e6-48a6-b40c-852a5169bda8)

**Comment by AbhishekPAnil** [comment]
After initial investigation :
The bug occurs because there is an empty space infront of " Flûte Alors!".

**Comment by troughc** [comment]
Can the extra space be automatically removed? Can you think of a case where the user would want a space kept? I can't...
@saumier ?

**Comment by dev-aravind** [comment]
@troughc I can remove the extra space manually. In our front-end side we actually remove the trailing blank spaces in the starting and ending of a string. Not sure how this organization got through. Do you want me to implement this in the backend as well?

**Comment by troughc** [comment]
note that before doing anything @AbhishekPAnil is checking into whether this issue was created before or after we fixed trailing blank spaces.

**Comment by AbhishekPAnil** [comment]
Please find below the similar issue that we created :
https://github.com/culturecreates/footlight-app/issues/568
