### ISSUE TITLE
Canadian Time Zones

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1101]
> ### Time Zones in Canada
> 
> BTW, the idea of time zones was invented by Scottish Canadian railway engineer Sandford Fleming, who pioneered the use of the 24-hour clock, the world's time zone system, and a standard prime meridian.[2]
> 
> This is a very good summary in Wikipedia https://en.wikipedia.org/wiki/Time_in_Canada
> 
> There are generally 6 time zones in Canada, but if you take into account that some regions shift the clock an hour forward for daylight savings in the summer and some don't, then for about half the year there are 10 regions to consider. So we need to allow users to select from a list of 10.
> https://en.wikipedia.org/wiki/Time_in_Canada#/media/File:Canada_time_zone_map_-_en.svg
> 
> 
> For coding, here is the spec from the ECMA standards body:
> ECMAScript® 2023 Internationalization API Specification
> https://402.ecma-international.org
> 
> This allows us to lookup all the supported time zones for a locale programatically:
> Type the following into your browser console:
> new Intl.Locale("fr-CA").getTimeZones()
> new Intl.Locale("en-CA").getTimeZones()
> 
> Both commands give a list of 23 time zones mostly organized by region/city.
> 
> 0 "America/Blanc-Sablon"
> 1 "America/Cambridge_Bay"
> 2 "America/Coral_Harbour"
> 3 "America/Creston"
> 4 "America/Dawson"
> 5 "America/Dawson_Creek"
> 6 "America/Edmonton"
> 7 "America/Fort_Nelson"
> 8 "America/Glace_Bay"
> 9 "America/Goose_Bay"
> 10 "America/Halifax"
> 11 "America/Inuvik"
> 12 "America/Iqaluit"
> 13 "America/Moncton"
> 14 "America/Rankin_Inlet"
> 15 "America/Regina"
> 16 "America/Resolute"
> 17 "America/St_Johns"
> 18 "America/Swift_Current"
> 19 "America/Toronto"
> 20 "America/Vancouver"
> 21 "America/Whitehorse"
> 22 "America/Winnipeg"
> 
> 
> That is a lot to display, so rather than list all 23, we can select timezones grouped together (aliases) and obtain a unique list with fewer names to display.
> 
> The ECMAScript 2023 Internationalization API Specification identifies time zones using the Zone and Link names of the IANA Time Zone Database.
> https://www.iana.org/time-zones
> 
> But rather than download the official Time Zone Database, you can view them in a table in Wikipedia here
> [List of tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
> 
> I have extracted the related ones in this table from the 48 Canadian TZ Identifiers including aliases.
> 
>  TZ Identifier |  English Abbreviation Standard Time | English Abbreviation Daylight Time | English UI | French UI 
> -- | -- | -- | -- | -- | 
> Canada/Atlantic  |  AST | ADT | Atlantic Time  | Heure de l'Atlantique
> America/Blanc-Sablon | AST | -- | Blanc-Sablon Time| Heure de Blanc-Sablon
> Canada/Central | CST |  CDT | Central Time | Heure du Centre 
> Canada/Saskatchewan | CST | --  | Saskatchewan Time | Heure de Saskatchewan
> Canada/Eastern |  EST | EDT  | Eastern Time | Heure de l'Est
> America/Coral_Harbour  | EST |  -- | Coral Harbour Time | Heure de Coral Harbour
> Canada/Mountain |  MST | MDT   | Mountain Time | Heure des Rocheuses
> Canada/Yukon |  MST | --  | Yukon Time | Heure du Yukon
> Canada/Newfoundland |  NST |  NDT |  Newfoundland Time| Heure de Terre-Neuve
> Canada/Pacific |  PST | PDT | Pacific  Time | Heure du Pacifique
> 
> 
> 
> Note: The French translations are inspired by this site http://www.statoids.com/tca.html except for Canada/Saskatchewan, Blanc-Sablon, Atikokan which I translated to Heure de -- because it follows the pattern for provinces like Heure de Terre-Neuve.
> 
> ## Concerns
> 
> The UI display labels for 2 timezones are not well established.  I am having some debate around the actual labels. Should settler names of villages be used like Coral Harbour instead of the inuktitut name like Salliq / Salliit.  Or a different village further south that is also used in the TZ identifier list like Atikokan but has no Wikipedia entry. Or else should the same general name be used with a mention of all year, for example "Atlantic Time (no daylight savings) | Heure de l'Atlantique (pas d'heure avancée )". Or should be switch to the longer list of all 23 supported time codes by city instead of using the larger regions.
> 
> 
> ## Examples
> 
> Display the current date using the **French** Canadian locale.
> 
> ```
> console.log(
>   new Intl.DateTimeFormat('fr-CA', {
>     dateStyle: 'full',
>     timeStyle: 'long',
>     timeZone: 'Canada/Saskatchewan',
>   }).format(Date.now()),
> );
> // output: "jeudi 9 mai 2024 à 08:19:11 HNC"
> ```
> 
> Display the current date using the **English** Canadian locale.
> 
> ```
> console.log(
>   new Intl.DateTimeFormat('en-CA', {
>     dateStyle: 'full',
>     timeStyle: 'long',
>     timeZone: 'Canada/Saskatchewan',
>   }).format(Date.now()),
> );
> // output: "Thursday, May 9, 2024 at 8:22:22 AM CST"
> ``` 

 _Originally posted by @saumier in [#635](https://github.com/culturecreates/footlight-app/issues/635#issuecomment-2102658073)_

**Comment by saumier** [comment]
@troughc I created a new issued specifically for Canadian timezones. If you could look at the section "concerns" I'd greatly appreciate it. Thx.

**Comment by troughc** [comment]
@tammy-culture assigning to you to bring you up to date.

**Comment by troughc** [comment]
Regarding: Concerns
The UI display labels for 2 timezones are not well established. I am having some debate around the actual labels. Should settler names of villages be used like Coral Harbour instead of the inuktitut name like Salliq / Salliit. Or a different village further south that is also used in the TZ identifier list like Atikokan but has no Wikipedia entry.
- My thought is that it should be easy for people to know what to choose (easily understood, recognizable) because it should be a quick thing to do. To be inclusive and moving in a good directions,perhaps an info popup could be used to educate people. 

 Or else should the same general name be used with a mention of all year, for example "Atlantic Time (no daylight savings) | Heure de l'Atlantique (pas d'heure avancée )". 
- that could be good too.

Or should be switch to the longer list of all 23 supported time codes by city instead of using the larger regions.
- I think this is overkill. I am not in favour.

@tammy-culture please add your thoughts so we can close this issue.

**Comment by tammy-culture** [comment]
@troughc I am with Caitlin on this to make it easy as possible for people to know what to choose. An inclusive pop-up educating people on the appropriate indigenous names of regions and cities is a nice to have at this point and something I hope we will be able to do in the future.
