### ISSUE TITLE
Convert the test server for calendar settings from http to https

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1102]
Right now the test server hosted to test out calendar settings and mandatory fields serves in http.Since the calendar widget serves in https ,the calendar widget page in CMS currently gives mixed content error .So make the test server https.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The serve is now https supported and the swagger docs are available [here](https://3.96.201.67/api/).
