### ISSUE TITLE
New client calendar

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1106]
Please create a new client calendar in Production CMS for the National Arts Centre.  Please name the calendar: NAC

**Comment by sahalali** [comment]
@tammy-culture What should the content language be?

**Comment by tammy-culture** [comment]
@sahalali It will definitely be a bilingual calendar

**Comment by dev-aravind** [comment]
@tammy-culture I've created the calendar for you and invited you as an Admin too. Let me know if you need anything else.
