### ISSUE TITLE
Add Culture Mauricie's published events to the Tourisme Mauricie Calendar in Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1107]
Tourisme Mauricie would like to aggregate events form the Culture Mauricie (DICI.ca) calendar

**Comment by sahalali** [comment]
As discussed during today's standup, we must design sharing events and other entities between calendars in CMS.
cc @saumier @troughc

**Comment by saumier** [comment]
@sahalali I need your help.  Can you please do a one-time import of the culture-mauricie-cms-events from Artsdata into tourisme-mauricie for Thursday (my morning).  I promised Tammy that she could have it by Thursday.

I am getting errors running Aggregator on my local machine. Looks like I am unable to login to the CMS in production. I tried by doing a login in production using admin API and then copying the token to the Aggregator "authorize" popup. But I still get 403. 

The import runs and completes with the message "Successfully synchronised 87 Events and linked entities."  But each event has an error.

Params for CMS in production:
source=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie-cms-events calander=661e5a8818a64f7829aeae24 (Tourisme-mauricie)


![Image](https://github.com/culturecreates/footlight-app/assets/419491/e8218189-b27f-4eff-a617-bc05ac3fa5aa)




This is the query to Artsdata which looks good:
 https://api.artsdata.ca/query?frame=event_footlight&format=json&sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&source=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie-cms-events

This is a sample of my log:
```
Fetching current user info
Unable to fetch URL https://api.cms.footlight.io/users/current Error ::, AxiosError: Request failed with status code 403
Fetching taxonomies
Unable to fetch URL https://api.cms.footlight.io/taxonomy?include-concepts=true&page=1&limit=100&taxonomy-class=EVENT Error ::, AxiosError: Request failed with status code 403
Validating identifiers from the mapping file for additionalType
Validating identifiers from the mapping file for audience
Fetching Events From ArtsData.
        Source: http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie-cms-events
        Url: http://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie-cms-events&limit=10&offset=0.

Batch 1 :: (1/10)
        Adding postal-addresses...
Some thing went wrong.{"uri":"http://kg.artsdata.ca/resource/K2-224#PostalAddress","addressCountry":{"fr":"CA"},"addressLocality":{"fr":"La Tuque"},"addressRegion":{"fr":"QC"},"postalCode":"G9X 3B4","streetAddress":{"fr":"725, boulevard Ducharme"}}
Batch 1 :: (1/10). Error while adding Event 
            {"uri":"https://www.complexeculturelfelixleclerc.com/event-details/cordame"}InternalServerErrorException: Some thing went wrong Event: undefined, message: undefined, 
                      same as: undefined
Batch 1 :: (2/10)
        Adding postal-addresses...
Some thing went wrong.{"uri":"http://kg.artsdata.ca/resource/K5-465#PostalAddress","addressCountry":{"@none":"CA"},"addressLocality":{"fr":"La Tuque"},"addressRegion":{"fr":"QC"},"postalCode":"G9X 3B4","streetAddress":{"fr":"725 Bd Ducharme"}}
Batch 1 :: (2/10). Error while adding Event 
            {"uri":"https://www.complexeculturelfelixleclerc.com/event-details/cabaret-artistique-pour-adultes-18-ans-et-plus"}InternalServerErrorException: Some thing went wrong Event: undefined, message: undefined, 
                      same as: undefined
```

**Comment by sahalali** [comment]
The events are now added [here](https://cms.footlight.io/dashboard/661e5a8818a64f7829aeae24/events?page=1&order=asc&sortBy=upcomingEventDate)
