### ISSUE TITLE
Admin only checkbox in Taxonomies - display issue

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1108]
To do:
There is a small display issue with setting the Admin only field in Taxonomies. 

Steps to reproduce:

1. Select Admin only and save. Everything works properly.
2. Go back into the taxonomy. Admin only is displayed in the field. However if you open the dropdown, the checkbox is empty. Note that everything is working properly as in Admin only still is being used for this taxonomy (it is selected even though the checkbox isn't checked in the display)
3. So if you want to deselect Admin only, you have to click the checkbox twice (once to put the checkbox in, again to remove it). 
Expected result: checkbox remains checked when Admin only is selected.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/23f2bd13-9d7e-4a45-8e2a-0ee698b0de94)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a21b33b6-7f33-4287-b4c7-2e6240ce16b9)

**Comment by troughc** [comment]
@AbhishekPAnil @SyamBabu-M I wasn't sure who to assign this to. Please decide between yourselves.

**Comment by SyamBabu-M** [comment]
@dev-aravind I have updated the frontend changes required for this. There is a backend change needed as "isAdminOnly" field is always false. Please look into this. Thank you.

**Comment by dev-aravind** [comment]
@troughc This was actually fixed as part of  #635. Do you want me to do this in the staging server?

**Comment by troughc** [comment]
@SyamBabu-M will let me know when to test (note to @troughc )

**Comment by troughc** [comment]
Tested: PASSED
