### ISSUE TITLE
Fix the image stretching in the list view while uploading an image in different forms.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1114]
![Image](https://github.com/culturecreates/footlight-app/assets/117100211/531ee2f8-51c6-4989-9e31-07c64a225ca9)

1. Fix the smaller image getting stretched according to different aspect ratios.
2. Fix the edit and delete button going out box.

**Comment by troughc** [comment]
Tested: PASSED
