### ISSUE TITLE
update info popups related to blue text on rightside of forms

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1116]
### Event form
The info popup for Event language blue text item on right side of the Event form needs to be updated. Right now it suggest you can only choose English French or bilingual:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/406583f8-3244-4bc3-8fe1-b1c410bbbfc5)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/05c93f47-db28-446a-bb4a-e8a77f4d2e02)

**However,** you can add as many languages as you want to this taxonomy. Please update info text to:

English
Select languages used in the event.
French
Sélectionnez les langues utilisées dans l'événement.

### Organizations form
Image is missing info text popup
English
Add an image for the organization. 
French
Ajoutez une image de l'organisation.

**Comment by SyamBabu-M** [comment]
@AbhishekPAnil @dev-aravind Since the organization form is done in data-centric approach, the tooltip text is added in the backend. What field name should we use for this?

**Comment by dev-aravind** [comment]
@AbhishekPAnil Can you provide the info pop-up text for the fields in all entities?

**Comment by AbhishekPAnil** [comment]
@dev-aravind Please find the tooltip translations here:
https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit?pli=1#gid=0

**Comment by dev-aravind** [comment]
@AbhishekPAnil The changes are up in staging. Please review them and let me know if you have any issues.

**Comment by troughc** [comment]
Tested: PASSED
