### ISSUE TITLE
Aggregate a new source from Artsdata.ca into Toutculture Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1117]
Please aggregate the following source: (http://kg.artsdata.ca/culture-creates/footlight/minotaure-ca) into the Production CMS for Toutculture.

**Comment by sahalali** [comment]
This issue is now blocked by https://github.com/culturecreates/footlight-app/issues/1124

**Comment by sahalali** [comment]
@saumier It looks like the type/keyword in the API response is now a complete URI. It is due the change the sparql query.
Can you please take a look into it once.

**Comment by sahalali** [comment]
Here is the API that is used to upload the events from the source: minotaure-ca
URL: https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/minotaure-ca&limit=20&offset=0

In the response:
{
"additionalType": [
        ["http://kg.artsdata.ca/resource/MusicPerformance"](http://kg.artsdata.ca/resource/MusicPerformance)
      ]
}

The above response contains the complete URL, however, it was previously the label before. 

Another example:
1. [co-motion](https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/co-motion-ca&limit=20&offset=0)
2. [salle-odysse](https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca&limit=20&offset=0)
