### ISSUE TITLE
Unable to invite a new user

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-app#1124]
As an admin of the CMS, I am not able to invite a user in the 'Tout culture' calendar.

![Image](https://github.com/culturecreates/footlight-app/assets/139197166/06e65f5f-ff77-4b24-af05-ddd619783a29)

**Comment by AbhishekPAnil** [comment]
Test Cases:

1. Try to invite a new user as a super admin.
2. Check if the organization and people in user settings are shown after the user accepts invitation.
3.Try to invite an existing user in the cms to calendar.Check if the existing cases work as before.

**Comment by AbhishekPAnil** [comment]
Bug report: The error happened only for a super admin as s super admin does not have roles in their user login/current user response.Hence this issue had to be handled separately.
**Fix:**
While a super admin tries to invite a new user ,all the calendars in the cms are shown in the calendars section.
Refernce : 


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/8df91697-aa43-43ac-a28b-3ce9d9439ae4)

**Comment by troughc** [comment]
Tested in Chrome as an Admin: PASSED

**Comment by troughc** [comment]
Tested as Admin and as super admin: PASSED

(tested adding new users and adding existing users to another calendar) - looks good. 
I noticed that the staging and pr calendar users seem to be linked but I don't think it matters. 

Only thing to make sure @AbhishekPAnil  is that the invitation sends the use to the correct environment (right now, the invitation sent from the PR is sending me to staging).

**Comment by troughc** [comment]
When the link in the email invitation is correct @AbhishekPAnil please add the to be deployed tag and push this live.

**Comment by AbhishekPAnil** [comment]
> Tested as Admin and as super admin: PASSED
> 
> (tested adding new users and adding existing users to another calendar) - looks good. I noticed that the staging and pr calendar users seem to be linked but I don't think it matters.
> 
> Only thing to make sure [@AbhishekPAnil](https://github.com/AbhishekPAnil) is that the invitation sends the use to the correct environment (right now, the invitation sent from the PR is sending me to staging).

This happened because the this PR link is connected to staging backend.
