### ISSUE TITLE
bugs when creating a new taxonomy

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1129]
- there is no admin only field included when you are mapping a new taxonomy to an **existing field.**

- You should not be able to change class type in the second screen (you choose it on the first screen). This is not true when you are creating a taxonomy for an existing or new field. the class type should be grayed out
- I am getting an error in staging when I try to create and SAVE a new taxonomy in Tout Culture - (test taxonomy). It said it already existed, however, it then created it anyway

I think Taxonomies needs to be retested thoroughly.

**Comment by SyamBabu-M** [comment]
@dev-aravind there seems to be a backend issue while saving taxonomy. Please look into this.

**Comment by SyamBabu-M** [comment]
@dev-aravind I just found a new bug in taxonomy. There is an issue with how adminOnly is handled in the add taxonomy API. It works fine with edit taxonomy API. Please look into this.

**Comment by dev-aravind** [comment]
@troughc This is fixed in staging now. You can check the linked PR to test this.

**Comment by troughc** [comment]
Tests:
Tested: there is no admin only field included when you are mapping a new taxonomy to an **existing field**. PASSED

Tested: You should not be able to change class type in the second screen (you choose it on the first screen). This is not true when you are creating a taxonomy for an existing or new field. the class type should be grayed out: PASSED

Tested: I am getting an error in staging when I try to create and SAVE a new taxonomy in Tout Culture - (test taxonomy). It said it already existed, however, it then created it anyway
- this worked, I was able to save a new custom taxonomy. However, I was able to create a taxonomy of the same name as another (Place type in places) and, then when I wanted to delete it I got the following message (and my taxonomy is not connected to anything):

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a760ef43-c061-4cd8-839c-06157010ed6a)



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a0ab879a-2827-4ca5-acfa-6af4d6465b78)

**Comment by troughc** [comment]
Two new issues have been discovered when testing this:
- the error shown above _(regarding a wrong count in the popup message that appears when I trash the taxonomy)_ happens when I don't add any concepts during taxonomy creation. In other words, I am creating a taxonomy without any controlled vocabulary. Once you add at minimum one concept the error count goes away.
**Expected behaviour:** error count is 0 until a taxonomy is actually used for an entity
- a user can create a taxonomy of exactly the same name for the same class type. For example, I can create multiple taxonomies named Place type for Place class. @sahalali and @saumier, will this cause problems in the backend API? In terms of the CMS this seems like it would be confusing for users. 
**Expected behaviour:** taxonomies should be uniquely named within a class type. 

@saumier @sahalali should these bugs be addressed in this issue or should we open a new issue?

**Comment by sahalali** [comment]
Can you please review this in prod?

**Comment by AbhishekPAnil** [comment]
> Can you please review this in prod?
@sahalali 
I tested this in prod and this is working fine in production.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil Test the issue Caitlin in the above comment https://github.com/culturecreates/footlight-app/issues/1129#issuecomment-2153095291.

**Comment by AbhishekPAnil** [comment]
cc @SyamBabu-M Please check and rectify this code and its other parts .
```
<Col style={{ flex: '1' }}>
                        <DateAction
                          iconrender={<PlusOutlined style={{ fontSize: '24px' }} />}
                          label={t('dashboard.taxonomy.selectType.newField')}
                          style={{ height: '104px', padding: 16 }}
                          onClick={() => navigationHandler('not-dynamic')}
                        />
                      </Col>
                      <Col style={{ flex: '1' }}>
                        <DateAction
                          data-cy="button-taxonomy-existing-field"
                          iconrender={<DatabaseOutlined style={{ fontSize: '24px' }} />}
                          label={t('dashboard.taxonomy.selectType.existingField')}
                          disabled={standardFields.length < 1 && selectedClass.label !== '' ? true : false}
                          style={{
                            height: '104px',
                            padding: 16,
                            ...(standardFields.length < 1 && selectedClass.label !== '' && buttonStyles),
                          }}
                          onClick={() => navigationHandler('dynamic')}
                        />
                      </Col>
```
I think there might be a logical issue here and that might have caused the mappedToField to appear in the backend.

**Comment by troughc** [comment]
### Tested on Chrome

1. Make sure that user cannot create two taxonomies of same name in the same class: 
When I try to save a new taxonomy with same name of an existing taxonomy in the same class, I get sent to an error page:
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/83a676d7-71aa-489d-82b4-d21101225030)

**Expected behaviour:** Instead, I should see this message but stay on the page (similar to the one shown above, but reworded). Ideally I would like the message to appear in red below the Taxonomy name field.  If this is not possible, please use a popup message.
English
This taxonomy name is already taken. Please choose another name.  
French
Ce nom de taxonomie est déjà pris. Veuillez choisir un autre nom.

2. Make sure that standard and dynamic taxonomies can be created and updated: PASSED
3. copy paste current create a new taxonomy link into a new tab and try to create a new dynamic taxonomy from there:
I copied the link of the first page (where you select your class) to a new tab and then continued creating a new taxonomy: PASSED
I then copied the link of the next page, (where you fill in the details) to a new tab: the new tab always shows a  CUSTOM details page, with Event selected (irregardless of what i selected - for example if I selected place/standard taxonomy, in the copied URL, I go to event custom details). That's a bit strange, but it doesn't cause any problems so I am not worried about it: PASSED

**Comment by troughc** [comment]
@AbhishekPAnil can you deploy this one too? 
cc @SyamBabu-M
