### ISSUE TITLE
Guest publish flow

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#113]
As a guest, I can send my completed event for review. Once my event is sent for review or published, I can no longer edit it.

As an admin or editor, I want to view events created by guests that are up for review so I can publish them or set them back to draft if further changes are needed by the guest.

### Test case - using new CMS

1. Log in as guest
2. Create an event and send to review
3. Try to edit the event that is waiting for review --> should go to readonly with a message at the top
4. Log in as admin
5. Make some changes in the event and publish it from the event details screen
6. In the event listing screen use the menu to make it draft, and then back to publish.
7. Log in as the same guest
8. Try to edit the event that is published --> should not be possible to change anything in the event
9. Log in as admin
10. Set the event to draft from the event details screen.
11. Log in as the same guest
12. Edit the event and re-send it for review.

**Comment by saumier** [comment]
@saumier Need to fix the constant for "review pending"

**Comment by SuhailAliyar** [comment]
@raseemayatt The publish state 'Pending Review' is changed to "PendingReview". Please modify the validation in the old cms show the publish state of the event.

**Comment by saumier** [comment]
@troughc Changes in new CMS are done. Please test in new CMS. Thx.

**Comment by troughc** [comment]
Testing on Chrome - Failed
Alicia Moffett event - http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/63dbd4e6f26497007034fc9c

At step 3: when I try to edit the event, i.e. change the contents of a field, I can. Then when I click send to review, I get kicked out (logged out to log in screen) and the message Not Authorized appears multiple times. I cleared the cache but the problem persists.

**Comment by saumier** [comment]
@troughc As discussed, please comeback with a confirmation for step 3 to go to read only view.

**Comment by troughc** [comment]
At step 3 I should be taken to a read only view (as a guest) with a message at the top. For messages, see issue #116

**Comment by saumier** [comment]
@AbhishekPAnil Please take up this issue next.

**Comment by saumier** [comment]
@troughc Please test in staging

**Comment by troughc** [comment]
Tested staging New cms - on Chrome

@saumier I just tried to create an event as a guest and send it to review, which didn't work (step 2). I get message that says I am offline when I click send to review (I am not offline). Is it me?

![Image](https://user-images.githubusercontent.com/64489312/220203370-db7b84b1-865e-43a9-b39b-b938b22a1cce.png)

I can try again at another time.

**Comment by troughc** [comment]
Tested on Chrome 'Caitlin guest test event' 
1. Steps 1-3 AS GUEST: Was able to create event, save as draft and send to review. PASSED
One caveat/issue: I was not able to save/send for review with an image of 2.4 mb. I was only able to do complete this part of the test by choosing a smaller image.

2.Steps 4-10 as ADMIN/Guest: everything worked as it should with one issue related to the publication filter:
Issue: as an admin, when I first tried to use the publication filter to search for pending review, it did not work. However after I opened the event as Admin, it started working. Will try again at the end of the steps.

3. Steps 11-12 as Guest. This worked except for temporary issue with filter 
ISSUE
At step 12 I saw that the FILTER for pending review stopped working (screenshots), still logge in as guest. There should be 2 events displayed Pending Review.

Before selecting pending review
![Image](https://user-images.githubusercontent.com/64489312/220382885-45be1791-d9c3-4d37-902e-e4ac3409e06e.png)


After selecting Pending review
![Image](https://user-images.githubusercontent.com/64489312/220382957-b2a718a4-a62a-4bb9-b1f0-5248b932a753.png)

What I observed about the Publication filter, still logged in as guest: these combination of options seem to work as expected:
Published
Published + draft
Published  + Pending review 

These did not:
Draft
Pending review
Draft + Pending Review

I then switched to my Admin user and all the filters were working as expected.

**Comment by AbhishekPAnil** [comment]
@troughc Was the page number changed before selecting the filters ? I am able to reproduce the issue only when selecting a different page number other than 1.

**Comment by troughc** [comment]
@AbhishekPAnil I just retested with a new event and yes, the page number is changed before selecting the filter - so the issue is when I am on any page other than the first one. Good catch!

**Comment by AbhishekPAnil** [comment]
@troughc I have fixed the above issue and deployed it in staging .Please do test and let me know .Thanks.

**Comment by troughc** [comment]
Tested filter fix: PASSED
