### ISSUE TITLE
Artsdata links not working

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1134]
Artsdata links not working as expected.

### Repro steps
1. View the details of this place in Culture-Mauricie calendar (DICI) https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/places/664854259f43170063fbd015
2. Scroll down to see the list of places it contains
3. Click on "Salle Louis-Philippe-Poisson" or "Salle Anaïs-Allard-Rousseau"
4. System open wrong url https://culturemauricie.caligram.com/api/venues/7841

### Expected behaviour 
System should open Artsdata URL like http://kg.artsdata.ca/resource/K5-454 for  "Salle Louis-Philippe-Poisson"  etc.

**Comment by SyamBabu-M** [comment]
![Image](https://github.com/culturecreates/footlight-app/assets/139208017/49a7b47d-4ee5-46bc-9039-fd8ba79af4f4)

See the network tab.

The derived-from field of contained in places is returning the wrong URI. There should be an artsdata uri there.

**Comment by sahalali** [comment]
The derivedFrom is the property used to persist the source from which the entity is created and it should not be the property used to display the external link(here Artsdata URL). The Artsdata URl will be available with the property sameAs. The sameAs property for containsPlace was not part of the API response ever.

I've added the property sameAs in the Api response of get place by Id and is now live in staging.

Assigning back to @SyamBabu-M for the UI fixes.

**Comment by troughc** [comment]
Tested: PASSED
