### ISSUE TITLE
Logo on Mobile squished

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1135]
In the hamburger menu on Mobile, the icon of the calendar is squished.

In this screen grab the Tout-culture logo is squished in the header, but not in the drop down list.

![Image](https://github.com/culturecreates/footlight-app/assets/419491/b2eb3da9-e3bc-4f1e-9462-77ab126ac6de)

**Comment by troughc** [comment]
Checked on google device: confirmed it is happening there too (apple and google).

**Comment by troughc** [comment]
Tested: PASSED
