### ISSUE TITLE
Images in list view are squished

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1136]
Image thumbnails in the event list view are squished.

### Repro steps 
See Culture-Mauricie (DICI) list of events https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events?page=1&order=asc&sortBy=upcomingEventDate

### Expected behaviour
Image should not be squished.

Not sure about the solution. In general I would not show a squished image, but these images are quite wide (2:1) so there are 4 choices that I will leave @troughc to make a decision if not already done so.
1. show complete thumbnail by fixing height
2. show complete thumbnail by fixing width
3. show complete thumbnail in a fixed rectangle (stretch image) --> current
4. show thumbnail in a fixed rectangle using flow (will loose a bit on the sides to avoid squishing)

@troughc Please take a look if not already done.

**Comment by troughc** [comment]
I would go with option one or two depending on how much real estate fixing the width would take - at minimum, there must be enough room for the date data to appear on one line.

Also, I though we changed this @saumier @tammy-culture ? See screenshot - the aspect ratio numbers, didn't we change those?


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/36f6930c-ed7a-450c-a466-c60fc96e487c)

**Comment by saumier** [comment]
@SyamBabu-M Looks great. Thx.

**Comment by troughc** [comment]
Tested: PASSED
