### ISSUE TITLE
Settings and calendar widget label / display improvements

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1141]
### Setting top bar tabs
update labels - Calendar widgets and Calendar Settings
- please see the copy document for the updates (highlighted in blue)

### Spacing needs to be fixed in some places
in Listing widgets, the space under "Dominant colour" field (between the field and the text below) is too big in both French and English. It should be the same spacing as you see in the General settings like this:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/815a66e0-d56b-4ddd-a67c-9936a288a031)

### Nice to have
In the widget (preview and on website), when possible for single date events, display the start time. 
- see update in Figma, in french and english

**Comment by troughc** [comment]
FYI @SyamBabu-M we will also have to update some of the fields in General settings but I haven't gone through them yet.

**Comment by troughc** [comment]
@SyamBabu-M I have added translations into the CMS copy document and highlighted them in teal blue - I tagged you in the spreadsheet. These updates are in the Listing widget section and the general settings section.

For Mandatory fields, there is one additional change to the sentence below the title
English: Select which fields are required.
French: Sélectionnez les champs obligatoires.


I hope I didn't miss anything!

**Comment by troughc** [comment]
Tested on Chrome:

Updates to setting top bar tabs and other labels - Calendar widgets and Calendar Settings: **PASSED**

Spacing needs to be fixed in Listing widgets, the space under "Dominant colour" field (between the field and the text below) is too big in both French and English: **PASSED**

Mandatory fields text change: **PASSED**

### Followup required
@SyamBabu-M I think something is going on with the nice to have (adding time for single dates). Has this been implemented?

If it has, it is not working consistently. Sometimes a time - the hour of the event (but the wrong hour) - is displayed; sometimes an event has an hour, but it is not displayed. See two examples below.

In Signe Laval, i found some events listed in the widget with a time set to midnight. In the screenshot, the example is the "Fanmi..." event. However, in the actual event (in the CMS and on the website), the time is 8PM Eastern time

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8ed800a9-15ff-42a4-aa98-ec6427961572)

CMS event link: https://pr-1173.dla06mbe0wyl7.amplifyapp.com/dashboard/63457978637093005071a053/events/add-event/65f28913997b81006371de9b

Website link: https://signelaval.com/fr/evenements/65f28913997b81006371de9b/fanmi-se-fanmi-presente-famille-en-fete

In DICI, this event has a start time and end time set: https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/66158d8114060600646939fd

However, in the widget, no start-time (hour of the event) is displayed in the preview (just the date). there are example of this behaviour in the other calendars as well.

**Comment by SyamBabu-M** [comment]
@troughc There was an issue in the widget during date conversion. I have fixed this issue. Can you test this again?

**Comment by troughc** [comment]
Tested: PASSED
We found an edge case which I will document in a separate issue to tackle at another time. 
Ready to deploy!
