### ISSUE TITLE
Aggregate a new source from Artsdata.ca into Tourisme Mauricie Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1146]
Please aggregate the following source: [http://kg.artsdata.ca/culture-creates/footlight/tourisme-troisrivieres-com](https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Ftourisme-troisrivieres-com) into the Production CMS for Tourisme Mauricie.

Please put it on a daily schedule.

**Comment by tammy-culture** [comment]
@sahalali It is a green light.  Please load this new source to the Tourisme Mauricie site.

**Comment by sahalali** [comment]
@saumier Can you please check why this API doesn't produce any results:
https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Ftourisme-troisrivieres-com&limit=100&offset=0

**Comment by saumier** [comment]
> [@saumier](https://github.com/saumier) Can you please check why this API doesn't produce any results:
> https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Ftourisme-troisrivieres-com&limit=100&offset=0

Your parameter for the source is wrong.

It should have the URI to the graph like this `source=http://kg.artsdata.ca/culture-creates/footlight/tourisme-troisrivieres-com`

Here is the complete url:
`https://api.artsdata.ca/query?sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-events-v2.sparql&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/tourisme-troisrivieres-com&limit=100&offset=0`

**Comment by sahalali** [comment]
The events are now uploaded to CMS.
Please see the the events [here](https://cms.footlight.io/dashboard/661e5a8818a64f7829aeae24/events?page=1&order=asc&sortBy=upcomingEventDate&users=6667f0fa92cafd0064969ff7).
