### ISSUE TITLE
Event series update: for event series that are reduced to one event

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1152]
### Current design: 
Users can create multiple dates events for event series. On occasion, a user may delete all events but one from the multiple dates event, leaving ONLY one event in the event series. 
After this change is made and the event is saved:
- the event appears as a multiple date event in the List view with only one occurrence;  
- multiple dates remains the selected option in the Dates section of the Event details view (and it will probably be set to Custom).

**List view**
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/9df45ea7-53bd-4717-9058-f86e7dbdde71)

**Event details view**
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8cab103e-56ee-4ddb-b5e1-4d29a3129cfa)

### Update - expected behaviour:
If a user removes (deletes) all dates except 1 from a multiple dates event, change this event to a single date event upon saving. 
In the list view, the event will look like a single date event:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d2ee0f2c-f718-4465-ad66-c38f0407e0c6)

The next time the user opens the event in the Event details, the Dates section will be set to single date:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/c290002f-a5d6-408e-98e1-cb060f28e4ec)

**Comment by SyamBabu-M** [comment]
note: Block the user from selecting same date as start and end date in date range selector.

**Comment by troughc** [comment]
Tested existing weekly recurring with start and end time: PASSED
Tested existing custom with start time only: PASSED
Tested existing custom with start and end time: PASSED
Tested new daily recurring: PASSED
new multi date event with many dates, then reduced to one: PASSED
new multi-date with only date: PASSED
Tested not being able to select same start and end date in calendar: PASSED
