### ISSUE TITLE
Display notification at top

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#116]
When editing an event, if there is any error when clicking save|publish... a notification should appear.  

NOTE: Use existing notification system (popup in center) - not the yellow warning style shown in the image. 

See copy (row 6 of User flow - notifications/alerts tab):  https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=2114823229
Note: the copy covers 3 cases so there are 3 corresponding texts to be added.

![Image](https://user-images.githubusercontent.com/419491/216374939-32966da9-fcd7-45ee-9a1a-dbdd7bde8d35.png)

**Comment by AbhishekPAnil** [comment]
@troughc

 The standard way for notification represented in antd is a title and the description for the notification :


![Image](https://user-images.githubusercontent.com/117100211/220705560-eecabc1f-7ee3-460b-8a15-24acc7e96312.png)

Or do we need something like this --->



![Image](https://user-images.githubusercontent.com/117100211/220705913-70b3ca22-ac13-4efa-ae20-b0773da887f1.png)

**Comment by troughc** [comment]
@AbhishekPAnil the second one matches what we have today right? But with an x to close (like you have on the log in screens). Does that make sense?

some notes:
We will sometimes need an "x" to close a warning message or notification message and sometimes not; again this matches  second option (without a title) but want it to be able to include an 'x' to close. 

Soon we will need to add a button (and maybe a title) - would this be a different kind of component?

Example:
User tries exiting a screen or entity without saving their work.
Warning looks like this: 
You have unsaved changes. Click Cancel to save your work before exiting this screen.  <Exit> <Cancel>

Example 2: 
User is asked to confirm a deletion of an entity that is used in many events:
TITLE: Confirm delete 
Are you sure you want to permanently delete this [taxonomy/organization/person/place]? This action will also delete all its associated data and everywhere it was used, including in events. 
BUTTONS: <Delete>  <Cancel>"



Note: Stephanie created some alert components to guide us. (but I'm okay with what you've done thus far in the log-in pages - we can decide if we need these colour etc at a later time) They are at the bottom of this figma page: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates?node-id=7%3A2&t=i00BUSoqf6amCDy1-0

**Comment by troughc** [comment]
@AbhishekPAnil I am unable to publish your event Francois Faubert - I receive the message that the event needs more information before it can be published but I do not know what information is missing. 

I tried by changing pricing type from Free to Paid - I got the right error messages so that was good. I added a ticket price and tried to publish, but I could not. I changed the ticket back to free and I still could not publish. 

I thought it might be a French title (because there was only an english one) but adding a french title did not change the message (I still could not publish). I removed the french title and saved as draft.

I then tried to publish from the event list, and this I could do. 

I unpublished the event in the event list and tried again from the event details. It didn't work. Here is a screenshot with Network open:


![Image](https://user-images.githubusercontent.com/64489312/221593189-bb2e9203-39c6-4934-9576-0e46388c5953.png)




Can you try to publish this event from the event details?

**Comment by troughc** [comment]
Other tests on chrome in this event as Admin : http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/63fcc10a2b26ce006402faac
Title: Robert Frost - Stopping by Woods on a Snowy evening

1. create event with just title and tried to save as draft - got correct error message(s): PASSED
2. added date and tried to save as draft - worked: PASSED
3. Added other details and tried to publish without image: got correct error message(s): PASSED
4. added image tried to Publish - got the error message at the top when I should not: DID NOT PASS
5. tried to publish from event list - I could. I have unpublished it so you can try.


Tested as Guest
http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/63fcc8382b26ce006402ff45
Title: caitlin test event - Robert Frost 2
1. create event with just title and tried to save as draft - got correct error message(s): PASSED
2. added date and tried to save as draft - worked: PASSED
3. Added other details and tried to save as draft without image: PASSED
4. Added image and tried to save as draft: got message 'internet appears to be offline.  And then more errors afte that.
Here is some screenshots of errors, and the image for my guest event. The image is 1.1 Mb (maybe too big)>


![Image](https://user-images.githubusercontent.com/64489312/221603553-625f6d17-0bf1-47e3-99f3-13c3fe0432e4.png)



![Image](https://user-images.githubusercontent.com/64489312/221603617-1d50f782-3c28-4313-abef-6f36f870cf41.png)



![Image](https://user-images.githubusercontent.com/64489312/221603747-8d228fcc-18a3-4f15-b6a4-958ef810bf8f.png)

**Comment by AbhishekPAnil** [comment]
@troughc  
<--------------------I am unable to publish your event Francois Faubert --------------------->
I have added the fix for the above and updated the staging.

For the second issue,was the image size greater than 500kb for admin as well?

**Comment by troughc** [comment]
@AbhishekPAnil yes the image is 780 kb, but I was able to add it to the event and save it (just not publish). Here is the image if you would like to try it.

![Image](https://user-images.githubusercontent.com/64489312/221670377-a6306a9e-7616-4c59-93f9-93c07719436d.png)

**Comment by troughc** [comment]
@AbhishekPAnil I just tried again as Admin with the 780Kb imageand it worked. I can both save as draft and publish.  I will now try as guest

**Comment by troughc** [comment]
TESTED as guest
See  Event called: francis faubert caitlin test as guest
http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/63fd0ea92b26ce00640315ac
I am able to do everything (including uploading an image of reasonable size) and error messages are working, 
Except for when I want to send the complete event for review. 
When I try to send for review as a guest, I get  'this event needs more information.....' message even though I have met all requirements.

**Comment by saumier** [comment]
The fix for this is to display a message on the problem image, when the image cannot get uploaded. Otherwise the image is blocked.

**Comment by troughc** [comment]
@AbhishekPAnil here is the error when I try to upload a big image.


![Image](https://user-images.githubusercontent.com/64489312/225305946-be685139-01aa-40cf-89fb-a9ea73db3135.png)

**Comment by troughc** [comment]
I added the message to the footlight cms copy spreadsheet.

**Comment by troughc** [comment]
Tested staging on CHROME: PASSED
