### ISSUE TITLE
Multiple images are not uploaded if the main image is missing.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1165]
1. While uploading multiple images to a new event without a main image and saving,the uploaded images are not shown in edit/read only page for an event.
To reproduce: Create an event as draft by uploading multiple images and not main images.Reopen the event in edit view and the images  are not seen.

2.The image thumbnail for multiple images looks squished.
3.Remove "Les images doivent être au format paysage ou carré et mesurer au moins 600 px de large." from image french tranlsations across workspaces.

![Image](https://github.com/culturecreates/footlight-app/assets/117100211/61bfbcef-fe00-473e-b13a-e371b4251e0f)

4.The text title for Additional images is too small in french AND english in Organizations and Persons

![Image](https://github.com/culturecreates/footlight-app/assets/117100211/abe49277-5921-48d9-84a5-c58f23a49728)

5.Try to delete the main image from an existing event and save it.The payload still contains the previous deleted image.
6. 3 dots were added to move them.

cc @AbhishekPAnil Please also see https://github.com/culturecreates/tech-support-tickets/issues/70#issuecomment-2178299363

**Comment by troughc** [comment]
Tested in chrome:

I found a new issue. I am not getting a warning to save my work after I add additional images and then click to leave the edit page. I can leave and my images aren't saved.

Tests:
1. While uploading multiple images to a new event without a main image and saving,the uploaded images are not shown in edit/read only page for an event: **PASSED**
2. The image thumbnail for multiple images looks squished: **NEEDS FOLLOW-UP.** The images still looked squished in my test. See the [Caitlin test image upload](https://pr-1177.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/667b15c2f7c67200a007957e) event
3. Remove "Les images doivent être au format paysage ou carré et mesurer au moins 600 px de large." from image french tranlsations across workspaces: **NEEDS FOLLOW-UP.** Organizations workspace still has the sentence in French (there is a screenshot below). 
4. The text title for Additional images is too small in french AND english in Organizations and Persons: **PASSED**
5. Try to delete the main image from an existing event and save it.The payload still contains the previous deleted image: I am not sure how to test this, but when I tried in Signe Laval with [this event](https://pr-1177.dla06mbe0wyl7.amplifyapp.com/dashboard/63457978637093005071a053/people/add-person?id=65b92c258468f400648408da), I was able to delete the main image (headshot) and save, but when I tried to go back in I got an error (see screenshot below). The Person's name is **Adam Johnson, Chef d’orchestre**
6. 3 dots were added to move them: **PASSED but needs f/up**. The way the two hand icons works is a bit strange. When I hover over the dots, the finger hand shows up. We can discuss.

**Here is a screenshot for number 3**
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/e901dcfe-a1ae-493e-af44-1f3089441434)

**Here is a screenshot for number 5**
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/82255d5c-ce6f-4793-9bc8-fe748050dff6)

**Comment by AbhishekPAnil** [comment]
@dev-aravind Could you update and remove text that Caitlin mention below for the data centric forms.


> 3. Remove "Les images doivent être au format paysage ou carré et mesurer au moins 600 px de large." from image french tranlsations across workspaces: **NEEDS FOLLOW-UP.** Organizations workspace still has the sentence in French (there is a screenshot below).

**Comment by dev-aravind** [comment]
@AbhishekPAnil The text is removed from the data centric forms.

**Comment by AbhishekPAnil** [comment]
I am pulling out the below bug and creating a separate issue,since its happening for both main image and image gallery.
Here is the issue https://github.com/culturecreates/footlight-app/issues/1190
>The image thumbnail for multiple images looks squished: NEEDS FOLLOW-UP. The images still looked squished in my test. See the [Caitlin test image upload](https://pr-1177.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/667b15c2f7c67200a007957e) event

**Comment by AbhishekPAnil** [comment]
@troughc The fixes are updated in the PR .

**Comment by troughc** [comment]
Tested : PASSED
