### ISSUE TITLE
system hangs when I switch from Tout Culture to Signe laval

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1168]
when I try to switch to Signe laval from Tout Culture in the CMS (after a fresh login) the system hangs (spinner just keeps spinning). However, if I go to another calendar first (for example, Artbi or DICI) and then switch to Signe Laval, I get in.
this happened several times.

**Comment by saumier** [comment]
@AbhishekPAnil Can you take a look into this please and assign to another team member as needed.

**Comment by AbhishekPAnil** [comment]
@SyamBabu-M Could you look into this and check if it was caused by the lateset release .
