### ISSUE TITLE
Unhelpful error messages when publishing

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1175]
When a field is missing, like description, and the event is saved, then a Publish triggers two error messages, one on top of the other. This is an issue especially since the error's explanation is the message hidden by a generic unhelpful "Bad request" error message. 

![User messages hidden](https://github.com/culturecreates/footlight-app/assets/44624797/80ee8dc1-3a6c-4ced-965c-36de09ebe582)

**Comment by troughc** [comment]
@kmdvs can you please test this one and then assign back to me? You can test it here: https://pr-1180.dla06mbe0wyl7.amplifyapp.com/

**Comment by kmdvs** [comment]
It works now by having only one (helpful) message :)
