### ISSUE TITLE
Client notices a text formatting problem between what they see on the CMS versus what is published on the front end of their website.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1181]
I asked the client to take some screen shots of the problem that he notices.

In the CMS Culture Mauricie sees 1 space return in the text. (see below)

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/689a0d7d-144d-4544-921c-4d29a54689a8)

VERSUS

What appears on his website.

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/dbfef53d-14f6-4686-b6c7-41a2ff5443ec)

**Comment by tammy-culture** [comment]
Please advise what next steps are required or what information is needed to look into this problem.  Many thanks for your help.

**Comment by troughc** [comment]
Hi @AbhishekPAnil please investigate and either fix or provide reason this happens. Thanks!

**Comment by AbhishekPAnil** [comment]
> Hi @AbhishekPAnil please investigate and either fix or provide reason this happens. Thanks!

Can you provide the link to the event in their website here.Thanks!

**Comment by AbhishekPAnil** [comment]
I took the below event for investigation .
https://dici.ca/evenements/paule-de-chateauneuf-vibration-coloree.
Report : 
The edited html that we are passing is :
`"<p><span style=\"color: black;\">Cette exposition se veut colorée sans géométrisme comme l’exprime Cézanne. Elle s’affirme par la couleur et la forme.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Coloriste et peintre de l’imprévisibilité, Paule de Châteauneuf</span></p><p><span style=\"color: black;\">cherche à créer un nouveau monde sur chacune des surfaces qu’elle utilise pour créer ses oeuvres. L’œil prend possession de l’acte créatif et produit une nouvelle réalité du monde et une illusion possible de l’objet.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Que la toile représente un personnage, un paysage, une nature</span></p><p><span style=\"color: black;\">morte ou une abstraction , une certaine représentation du monde réel apparaît suite à des choix de couleurs en interaction avec différentes formes qui semblent aléatoires, mais qui sont décidées par le cerveau droit. L’image se concrétise en objet concret.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Un tableau atteint son autonomie lorsque l’œil peut se promener</span></p><p><span style=\"color: black;\">sans entraves visuelles et lorsque le spectateur prend plaisir à le regarder et en possède un souvenir qui le pousse à vouloir revivre les sensations ressenties.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><strong style=\"color: black;\">À PROPOS DE L’ARTISTE</strong></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Oser le monde en moi, voilà ma devise. La couleur afflue sur ma</span></p><p><span style=\"color: black;\">palette et me permet de créer sur tous les supports, surtout sur la toile et le papier. L’esprit libre, sans contrainte, je travaille la matière avec le pinceau. Touche après touche, la couleur en juxtapose une autre selon un choix très sélectif et cela, que ce soit pour un travail d’observation ou en mode création.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Le dessin d’observation et le modèle vivant me procurent une belle</span></p><p><span style=\"color: black;\">assurance. Les encres, le fusain, le crayon Conté, le pastel sec, l’aquarelle et l’acrylique sont les médiums qui m’intéressent.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Lorsque le processus créatif s’impose, le sujet s’efface pour</span></p><p><span style=\"color: black;\">faire place à l’émotion et au temps qui prédominent. La peinture abstraite se présente dans une vérité criante supprimant toutes les théories apprises. La couleur se mélange en mille aspects dans un fragment de lumière et si, par hasard, une peinture abstraite devient une peinture figurative, le mystère pictural s’amplifie. Grâce à ces dialogues incessants, la matière écrit mon histoire. Les thèmes sont variés. Mes œuvres sont exposées depuis 1994.</span></p><p><span style=\"color: black;\">&nbsp;</span></p><p><span style=\"color: black;\">Rebelle et toujours en recherche, je laisse la place au tableau</span></p><p><span style=\"color: black;\">suivant qui, je l’espère, m’apportera une multitude de réponses. Je trouve que c’est une belle façon de toucher à l’infini…</span></p><p><span style=\"color: black;\">– Paule de Châteauneuf</span></p>"`

They are rendering this correctly without any change in the data but they have added a global css for p tag.If you inspect their site there is actually only single space between the paragraphs .They have added a global css for p tag with margin bottom 28.6px or 1.3em.I think this might be causing the feel of additional space.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/0a38dfd1-d136-43c6-88da-f00d99c7f11a)

**Comment by tammy-culture** [comment]
@AbhishekPAnil I have a question, if the Culture Mauricie is applying a global css on their site is there a way for us to provide text in format where we would not have this problem?  Thank you.

**Comment by AbhishekPAnil** [comment]
> [@AbhishekPAnil](https://github.com/AbhishekPAnil) I have a question, if Culture Mauricie is applying a global css on their front end website page is there a way for us to provide text in a format where we would not have this problem? Thank you for letting me know if that is possible.

Sorry for not responding @tammy-culture ,I didn't get a notification for the above comment.

It would be hard for us to manually edit the formatting of the text inside the editor.

**Comment by tammy-culture** [comment]
Thank you @AbhishekPAnil
