### ISSUE TITLE
warning to save popup appears when nothing to save

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1191]
### BUG in Staging and Production
The warning to save popup appears when leaving a screen that has already been saved. I have seen this happening in two places, in two different ways: 

- **the Settings environment** (because you have to manually switch from the saved tab to another tab / left nav after you save). In this environment, the success message appears first. Then you click to go somewhere else and the warning appears.
- **The user profile, when you access it from the top menu and change your UI language choice**. Three things happen here: 

1. First, I have to select the language choice twice for it to take (the first time I select it from the dropdown, nothing changes; the second time it does
2. when I save my language choice, the unsaved changes message pops up. I can click either OK or Cancel and then the success message pops up and my language is saved. If I click Ok, I leave the screen and my changes are saved.
3. As mentioned: the first time I click save after changing the language of my profile, I get an unsaved changes warning. If I click Cancel I get the success message and stay in the User profile screen. I try to leave and cannot because the warning keeps popping up until I click OK (and there is nothing to save)

### screenshots of messages

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ba308e3a-38ed-4c70-87d4-eaec42ef977b)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/06fc04d5-5c03-44cb-96b8-68fbc46cb9fb)

**Comment by SyamBabu-M** [comment]
@dev-aravind Can you do a peer review for this?

**Comment by dev-aravind** [comment]
Tests:

Language does not get selected when clicked once in user profile page:  PASSED
Unsaved message popup when saving the user progfile : PASSED

**Comment by troughc** [comment]
Tested all the scenarios: PASSED
