### ISSUE TITLE
NULL error message in settings for ARTBI calendars

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1192]
Steps to reproduce:
Go to Artbi calendar in staging or production
Go to General settings
Change the name of the calendar (add a space or character) and then save. YOu get the error:

From today (friday jUne 28)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/16a7410f-be97-4d3b-a13f-70805055a28e)

from yesterday: (Thursday june 27)
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/17d7762b-995f-4bd0-b602-70366f769612)

**Comment by sahalali** [comment]
@troughc  Can you please add more details in this ticket?

**Comment by troughc** [comment]
@sahalali is. there enough detail above now?

**Comment by sahalali** [comment]
@troughc This issue is fixed in staging.

**Comment by troughc** [comment]
Tested: PASSED
