### ISSUE TITLE
Error saving Event - Admin - "Bad request" error message 

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1195]
When trying to save an event, as an admin, a "Bad request" can be triggered.

![Bad request](https://github.com/culturecreates/footlight-app/assets/44624797/bad5cc6c-ea01-4350-a302-743805b7b717)

It seems, looking at the event, that EventType is empty according to the app, even if it is saved and present in the UI (see UI and JavaScript console)

![EventType empty](https://github.com/culturecreates/footlight-app/assets/44624797/3b2ea0af-b0f2-4de7-8251-2b47e67f3e55)

Further inconsistency: Event Type is not flagged as mandatory. 

Repro steps: 
 - create an event with all mandatory fields as admin and try to publish
 - add and Event Type and try to publish

or 

See https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/667d07e8f7c67200a0088f52 and try to publish

**Comment by troughc** [comment]
@SyamBabu-M please take a look at this issue, found by Kim.

**Comment by SyamBabu-M** [comment]
@SuhailAliyar @dev-aravind @AbhishekPAnil When I debugged this yesterday, I found that event type taxonomy was infact dynamic. But inside mandatory fields, I was able to find the Standard field Event Type taxonomy. I believe this could be what is caused the issue.
Is there any chance that this was added manually in the staging DB as part of some testing?

**Comment by AbhishekPAnil** [comment]
@SyamBabu-M The standard field taxonomies getting the isDynamicField as true is happening because of this code .


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/cd3d2db6-f881-4133-aa76-d06d8466bbe0)

Please resolve this and test the edge cases.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend changes are up in staging. The affected calendars are now fixed and a safety check is there in the backend to avoid this.

**Comment by troughc** [comment]
@SyamBabu-M I can't seem to reach the PR build when I click the link...can you please add it here?
