### ISSUE TITLE
Spelling / grammar issues in FR

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1196]
Some spelling / grammar issues / inconsistencies in translationFR: I reviewed about half the document

1. 
    "firstName": "Prenom" ==> Prénom
    "confirmNewPassword": "Confirmer votre nouveau mot de passe" ==> Confirmez votre nouveau mot de passe.
    "acceptInvitationSuccess": "Success ! Invitation acceptée." ==> Succès ! Invitation acceptée.
    "readOnlyMode": "Read-only mode" ==> Mode lecture seule
    "titleLabel": "English" ==> Anglais
    "placeHolderFrench": "Entrez titre en français" ==> Entrez le titre en français.
    "placeHolderEnglish": "Entrez titre en anglais" ==> Entrez le titre en anglais.
    "placeHolderEventType": "Sélectionnez type de l'événement" ==> Sélectionnez le type de l'événement.
    "placeHolderTargetAudience": "Sélectionnez public cible" ==> Sélectionnez le public cible.
    "addTimeToAllDatesWarning": "Vous êtes sûr de vous ? Cette action ne peut être annulée." ==> Êtes-vous sûr ? Cette action ne peut être annulée.
    "subHeading": "Ajuster la position de l’image si nécessaire." ==> Ajustez la position de l’image si nécessaire.
    "placeHolderKeywords": "Entrez des mots clés supplémentaires" ==> Entrez des mots-clés supplémentaires.
    "copyOrganizerContact": "Copier le contact de l’organisateur" ==> Copiez le contact de l’organisateur.
    "eventLanguageTooltip": "Sélectionnez le français, l'anglais ou le bilingue." ==> Sélectionnez le français, l'anglais ou bilingue.
    "placeHolderEventAccessibilityFrenchNote": "Ajouter des informations supplémentaires sur l'accessibilité" ==> Ajoutez des informations supplémentaires sur l'accessibilité.
    "placeHolderEventAccessibilityEnglishNote": "Ajouter des informations supplémentaires sur l'accessibilité" ==> Ajoutez des informations supplémentaires sur l'accessibilité.
    "noteTooltip": "Fournir plus de détails sur les options d'accessibilité sélectionnées, telles que les dates." ==> Fournissez plus de détails sur les options d'accessibilité sélectionnées, telles que les dates.
    "changeToFreeTooltip": "À utiliser lorsque votre événement est gratuit et ne nécessite pas d'inscription." ==> À utiliser lorsque l'événement est gratuit et ne nécessite pas d'inscription.
    "saveAsDraft": "Succès! Votre événement a été enregistré comme brouillon." ==> Succès ! Votre événement a été enregistré comme brouillon.
    "sendToReview": "Succès! Votre événement a été envoyé pour validation." ==> Succès ! Votre événement a été envoyé pour validation.
    "publish": "Succès! Votre événement a été publié." ==> Succès ! Votre événement a été publié.
    "updateEvent": "Succès! Votre événement a été mis à jour." ==> Succès! Votre événement a été mis à jour.
    "editFailedReviewForGuest": "Cet événement a besoin de plus d'attention. Réviser et mettre à jour si nécessaire, puis envoyer pour validation." ==> L'événement a besoin d'être révisé. Réviser et mettre à jour si nécessaire, puis envoyer pour validation.
    "emptyPaidTicket": "Un lien d'achat de billet, un prix de billet ou une note est requis." ==> Un lien d'achat, un prix ou une note sont requis.
    "emptyRegister": "Un lien d'achat de billet, un prix de billet ou une note est requis." ==> Un lien d'achat, un prix ou une note sont requis.
    "required": "Un organisateur est requise." ==> Le champ "Organisateur" ne peut être vide. // or // Le champ ne peut être vide.
    "description": "Êtes-vous sûr de vouloir supprimer définitivement cette organisation? Cette organisation sera supprimée partout où elle est utilisée." ==> Voulez-vous supprimer les données concernant cette organisation ? Elles seront supprimées partout où elle est utilisée.
    "text": "Recherchez pour établir un lien avec une instance existante de l'organisation dans d'autres sources de données. Si vous ne trouvez pas l'organisation, vous pouvez la créer." ==> Recherchez pour lier une instance existante de l'organisation dans d'autres sources de données. Si non trouvée, vous pouvez la créer.
     "addSuccess": "Succès ! Votre organisation a été créé." ==> Succès ! Votre organisation a été créée.
     "editSuccess": "Succès ! Votre organisation a été mis à jour." ==> Succès ! Votre organisation a été mise à jour.
     "saveError": "Cet organisation a besoin de plus d'informations avant d'être enregistré." ==> Cette organisation a besoin de plus d'informations avant d'être enregistrée.
      "website": "Website" ==> Site Web
      "text": "Recherchez un lien vers une instance existante du lieu dans d'autres sources de données. Si vous ne trouvez pas le lieu, vous pouvez le créer." ==> Recherchez pour lier une instance existante du lieu dans d'autres sources de données. Si non trouvée, vous pouvez le créer.
      "english": "Entrer la province en anglais" ==> Indiquez la province en anglais
      "french": "Entrer la province en français" ==> Indiquez la province en français
      "english": "Entrer la pays en anglais" ==> Indiquez le pays en anglais
       "french": "Entrer la pays en français" ==> Indiquez le pays en français
       "placeholder": "Sélectionnez le région" ==> Sélectionnez la région
       "placeholder": "Entrez l'url des heures d'ouverture" ==> Indiquez le lien vers les heures d'ouverture
       "subheading": "Uniquement les fichiers .jpeg et .png sont acceptés." ==> Seuls les fichiers de formats .jpg/.jpeg et .png sont acceptés.
       "saveError": "Cet lieu a besoin de plus d'informations avant d'être enregistré." ==> Ce lieu a besoin de plus d'informations avant d'être enregistré."
       
2. Many messages use the anglicism "Entrer le/la ...". It is better to use "Indiquez le/la/un/une/..."
    
3. Some messages have a "." at the end. Some don't. I suggest adding the "." at the end except for 
 - when the message ends with a URL
 - titles, headings and subheadings
 Multi-sentences messages should always end with a period (full stop). 

4. Some messages use the -er verb suffix (infinitif présent à l'impératif) and some use the -ez verb suffix (impératif présent 2e personne pluriel). To keep consistency in our communication, a more general review would be needed. I suggest since most messages already use -ez to do the review just checking the verbs using the "infinitif présent à l'impératif" 

5. As seen above, some messages use a possessive ("votre" événement) while most use an impersonal voice ("l"'événement). I left the possessive pronoun for the Save messages, since it is a "key" operation. Mostly a more or less "personal" voice for the app

**Comment by troughc** [comment]
Thanks @kmdvs ! I will take a look through and see how best to update the translations.

**Comment by AbhishekPAnil** [comment]
@troughc Please find below the link to the wiki page which has the necessary instructions while editing the translation files.
https://github.com/culturecreates/culture-creates-wiki/wiki/How-to-edit-the-translation-files-in-CMS.

Please review it and let me know if there are any change required.

**Comment by troughc** [comment]
@AbhishekPAnil nice instructions, thank you! 
@kmdvs I discussed with Abhishek having you update the french translations and it would be great if you could do so. So I am assigning this (and another issue) to you. Let me know if you have any reservations. 
Here is the link to the Wiki instructions: https://github.com/culturecreates/culture-creates-wiki/wiki/How-to-edit-the-translation-files-in-CMS.

**Comment by kmdvs** [comment]
I created a new [commit](https://github.com/culturecreates/footlight-app/pull/1255/commits), and pull request

But the [checks failed](https://github.com/culturecreates/footlight-app/pull/1255/checks?check_run_id=28205020450). I can't sign in on AWS to see what failed, so I don't know what the issue is.

**Comment by kmdvs** [comment]
Found that there were a few missing hyphens from one replace... Corrected it, now a new check on AWS.

**Comment by kmdvs** [comment]
Found a missing comma... Fingers crossed the file is good now :)

**Comment by kmdvs** [comment]
OK, [passed all essential tests](https://github.com/kmdvs/cypress-gha-tests/actions/runs/10197061580) in Cypress (that was expected). 
Needs a final screen-by-screen text verification, I'll complete that today.

**Comment by troughc** [comment]
@kmdvs @AbhishekPAnil I found english in the French version of the User settings (under Calendar | Oganizations)
@kmdvs maybe you already caught this mistake? If not, can you please translate and then fix? See screenshot


![Image](https://github.com/user-attachments/assets/ff62c621-edb6-4f6f-9097-8a3e64d0a6da)

**Comment by kmdvs** [comment]
Yes, I already translated it :)

**Comment by AbhishekPAnil** [comment]
@troughc I can confirm there aren't any layout issues related with the changes.

**Comment by troughc** [comment]
@AbhishekPAnil I did a spot check and it seems okay to me. cc @kmdvs

**Comment by troughc** [comment]
@AbhishekPAnil there are a couple workspaces where one of the translations did not get through for disambiguating description in french: in organizations and People.
Let's take a look together.

**Comment by troughc** [comment]
Translation in Places (good) - it is for 'disambiguating description' label in French pages 

![Image](https://github.com/user-attachments/assets/123b5db5-586a-40b9-9df2-9d57b5412d95)

Translation in People (did not get updated in People and in Organization)

![Image](https://github.com/user-attachments/assets/56b4cd44-4266-4be7-b0a1-e95f0d42ad63)

**Comment by troughc** [comment]
@AbhishekPAnil I will close this issue and open a separate one.
