### ISSUE TITLE
Aggregate a new Artsdata source ArtscultureNB (The Playhouse)

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1205]
Please aggregate the following Artsdata source and add it to ArtscultureNB's production CMS:

http://kg.artsdata.ca/culture-creates/footlight/theplayhouse-ca
--

[http://kg.artsdata.ca/culture-creates/footlight/theplayhouse-ca](https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Ftheplayhouse-ca)

**Comment by tammy-culture** [comment]
@saumier Please turn on auto-minting in the Artsdata. Thank-you.

**Comment by sahalali** [comment]
The aggregator is run once again after the database is reloaded. 
This source has images with URLs containing a query param after the URL, which is now handled in the aggregator.

**Comment by tammy-culture** [comment]
@sahalali I have asked the client whether they would like us configure a new scraper for The Playhouse to add missing information.  I will get back to you when I get a response.
