### ISSUE TITLE
Client request - fix missing geo-coordinates - Bulk download 

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1207]
Request: Geo-coordinates are missing in some places - can they always be there? They are often used for maps on sites.

Tourisme Mauricie has requested if it would be possible add an additional 'sort' filter in the "Places" workspace.  Please refer to image below.

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/3ba80828-b1fe-432e-8b4b-3985f1a50080)

Client would like to know if it is possible to add a sort that allows them to see missing information.  They would like to know if any files are missing information, namely missing geo-coordinates.  Please advise.  Thank you.

**Comment by troughc** [comment]
Example, this place from Artsdata has no geocoordinates: https://cms.footlight.io/dashboard/65eeaf8ebec01b0064312f94/places/668b88e2200e900063ee8f53

**Comment by troughc** [comment]
@saumier @sahalali  bringing this to the top of mind. Gregory, Suhail, can you provide some insight as to what could be done to ensure that geo-coordinates are always available. Some places don't have geocoordinates (see previous comment).
cc @tammy-culture

**Comment by sahalali** [comment]
@troughc 

If the places are created by a user in the CMS, then the geo-coordinates are prefilled and added using Google's Places API. If the geo-coordinates are missing in the source when created using an aggregator, we can add the missing geo-coordinates at the aggregator level using the Google Places API.


@tammy-culture Implementing a filter in all workspaces to remove entities with missing mandatory fields is a more sensible approach than implementing sorting. However, this will require backend work, and the APIs for listing entities will need to be improved.

Introducing sorting with conditions will increase the complexity of the queries and have a negative impact on the performance of the APIs.

cc @saumier

**Comment by saumier** [comment]
@troughc I think a button should be added to the UI to batch download the data of an entity like places.

**Comment by saumier** [comment]
@tammy-culture @troughc I added geo-coordinates to all places, and I replaced the location for an event which was incorrectly linked to "Esplande" (see place in map in Montreal) with the correct "Esplanade Trois-Rivières sur St-Laurent".

All 59 places have geo-coordinates.

![Image](https://github.com/user-attachments/assets/7ced9e36-4ecc-4649-9bc2-5f5269766f00)
