### ISSUE TITLE
People image is not showing in the listing pages

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1208]
![Image](https://github.com/culturecreates/footlight-app/assets/117100211/d9613d25-2711-4173-9179-e22f9fe0101b)

In the listing page for people ,the images shown are place holder images.

Expected behaviour : 
Display the ithumbnail image of a person.

**Comment by SyamBabu-M** [comment]
![Image](https://github.com/culturecreates/footlight-app/assets/139208017/5b020f99-d47a-47e6-9aed-9f1f70cdfa29)

@dev-aravind @sahalali This is a backend issue. This get API /people is returning the image field as an array of null values(see the ss above). /people/{id} returns the data properly, hence we are able to view the images in edit and read-only pages.

**Comment by AbhishekPAnil** [comment]
> 
> 
> ![Image](https://github.com/culturecreates/footlight-app/assets/139208017/5b020f99-d47a-47e6-9aed-9f1f70cdfa29)
> 
> @dev-aravind @sahalali This is a backend issue. This get API /people is returning the image field as an array of null values(see the ss above). /people/{id} returns the data properly, hence we are able to view the images in edit and read-only pages.
> 
> 
> cc @AbhishekPAnil 

@SyamBabu-M Please also check and confirm if the null values were initially given from the frontend or not

**Comment by SyamBabu-M** [comment]
@AbhishekPAnil I rechecked this. This is not a frontend issue.
 - All the images are null in listing pages but they are available in details pages.
- Null values are not send from FE during creation of a person.
- If I create a person and immediately find it listing page the image will be null. But as described above it will be available in details page.

**Comment by sahalali** [comment]
This issue is fixed

**Comment by troughc** [comment]
Where do I test this @sahalali, in staging? If yes, it looks okay to me and I will PASS.

**Comment by sahalali** [comment]
@troughc You may please review this in production and in staging.
This [URl](https://cms.footlight.io/dashboard/63457978637093005071a053/people?page=2&order=asc&sortBy=name) will help yo to verify the images of people are displaying in the listing page.

**Comment by troughc** [comment]
Tested by using the link to the production CMS provided by @sahalali : PASSED
