### ISSUE TITLE
Setting up General Settings for Widget and Listing Widgets

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1215]
### User experience improvement
**Problem:**

As the admin, I want to set up my new CMS so I can start adding events and other types of entities to the different workspaces. I may not have a website yet but I want to start populating my cms with data. Since i don't have a website, i do not know the URLS for the 'Event template' and 'Search results template' so I cannot enter anything into those fields in General settings. I do not want to be blocked from using my CMS because of this.

**Proposed Solution:**
1. The **Widget settings section in General settings are not mandatory** so i can start using the CMS without them.
However, without the 'Event template' URL, listing widgets would not work the way I expect if I were to generate and share some when i DO have a calendar.
2. To protect me, the **Listing widget page should be disabled until those settings are entered.** Once the admin adds those settings, the listing widget page becomes available.
3. To inform me, we should **add a popup on the DISABLED listing widget page** that tells me what I need to do to turn on my listing widget. The popup goes away once I add the setting.
Text for popup 
English: Go to General settings and add the Event template URL to start using Listing widgets.
French: Allez dans Paramètres généraux et ajoutez l'URL du modèle d'événement pour commencer à utiliser les widgets de liste.

**Comment by saumier** [comment]
@troughc Looks good. Thx for writing this up.

**Comment by troughc** [comment]
@AbhishekPAnil does this go to you?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil does this go to you?

Yes you can assign it to me

**Comment by troughc** [comment]
Testing results
@SyamBabu-M Step 1 of "Proposed solution" needs to be implemented.
To do:
Please change the settings in the Widget settings section in General settings so that they are NOT mandatory so that an Admin and others can start using the CMS without using the widget. Note that the asterisk must be removed from the Event template title as well.

Right now, when I try to delete a URL from Event template field, I am notified that it is required and I cannot save my settings:
![Image](https://github.com/user-attachments/assets/f22d1eaa-337b-445f-ad73-83a55dbb96a3)
What should happen is I can have this field be empty and I can save. 
The result of an empty field is that the widget will not be available (you have implemented that).

**Comment by troughc** [comment]
Tested: this is working, PASSED
Just one small thing @SyamBabu-M   If i hover over the Listing widgets tab near the edge of the grey box that outlines the words, I get the little icon that indicates it is not available: however, if I click in that area anywhere around the edge, the message doesn't pop up. 
Can you fix it so that whenever that little icon appears and you click, the message appears?

**Comment by troughc** [comment]
Tested PASSED
