### ISSUE TITLE
Required Field validation in calendar settings not working properly

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1217]
I am able to save the calendar settings without a contact email even thought the email is mentioned as required.This may be happening for other required fields also.Please test and resolve.
To reproduce:
1.Go to the calendar settings page and remove the contact email.Try to save it.
2.You are able to successfully save the calendar settings.

Expected behaviour :
The validations for required fields should be shown properly.

**Comment by SyamBabu-M** [comment]
These issues are already addressed in this PR - https://github.com/culturecreates/footlight-app/pull/1204. Please take a look.

**Comment by troughc** [comment]
Tested: PASSED
