### ISSUE TITLE
Cannot update mandatory fields in calendar settings for Event and Place

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1220]
As a user, I am not able to add more mandatory fields Event and Person Type.

How to reproduce - 

Step 1: add a field to the mandatory field list and save.
Step 2: Refresh the app

Result: A new field is not added to the mandatory field section.

Expected behavior - New field must be added to the mandatory field section.

**Comment by troughc** [comment]
Tested: PASSED. Ready for you @AbhishekPAnil
