### ISSUE TITLE
STAGING: when I try to update an existing event, it disappears

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1221]
I can create an event and save. I cannot update an existing event (even one I just created myself).
I noticed this bug whilst testing issue #1194. It does NOT exist in Production; it ONLY exists in staging, in all calendars.
I had Tammy test it as well and she encountered the same issue.
Steps to reproduce.

Try to change and then save or publish any existing event. The system tells you that it succeeds, but the event is no longer present in the event list.

I did not test the other workspaces. Thanks!

**Comment by sahalali** [comment]
This issue is fixed. This issue also appeared in the Production after today's update.
Both the problems are fixed.
Thanks, @AbhishekPAnil for the working session, that helped to figure out the issue.

**Comment by troughc** [comment]
Tested: PASSED. The hotfix seems to have worked, thank you!

**Comment by troughc** [comment]
Fyi @tammy-culture this is fixed. No action required as we do not think it impacted any clients.
