### ISSUE TITLE
PLACES workspace is not working correctly in the ArtscultureNB CMS.  When you try to open the workspace there is an error message.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1227]

**Comment by tammy-culture** [comment]
Here is the error message:


![Image](https://github.com/user-attachments/assets/2512267a-734b-4c1b-8096-b992ebf689de)

**Comment by sahalali** [comment]
The issue has been resolved in production. Please test it on your end. The problem occurred because the source "scensfracophones" contains places with no language tags for place names, which are manually updated. Hopefully, this issue will be resolved when "scenesfrancophones" reuploads their data.

**Comment by tammy-culture** [comment]
It looks good and thank you.
