### ISSUE TITLE
Max width minimum value for images

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1229]
This issue was found whilst testing #1202 
In Artbi, the max width can be set to 0 and the ADMIN can save this setting. This should be disallowed in the software.

**SUGGESTED MINIMUM WIDTH ALLOWED: 100 Pixels**
### Expected Behaviour
Add validation to back-end to expect a minimum of 100 pixels for maximum width.

And when the minimum amount is not entered, or the Max Width field is left empty:
**English**
CHANGE
Information is required
TO
A minimum value of 100 pixels is required.

**French**
CHANGE
Des informations sont requises
TO
Une valeur minimale de 100 pixels est requise.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ed5ea52d-3576-41ee-aac0-7582a0665cbc)

**Comment by troughc** [comment]
@troughc add validation method and minimum number allowed for max width.

**Comment by sahalali** [comment]
@AbhishekPAnil Backend changes have been released. Please review this and move the ticket to the review phase.

**Comment by troughc** [comment]
Tested in Staging. 

- the numbers that are displayed when i start editing are a bit confusing. I think they are from numbers entered in past, which is okay but they don't guide for minimum requirements.... (see screenshot at bottom)
- when I press enter after entering a number, nothing happens (it doesn't 'enter' the number and the cursor stays in the field; I have to click out of the field to leave it)
- No message appears when I don't enter a minumum of 100 (see screenshot at bottom)
- if field is empty, wrong message appears (see last screenshot at bottom)

- a message about width appears on save if not correct (and nothing else is missing) but messages have issues in both languages. And the field are not highlighted
- width message doesn't appear if something else is missing. Because the field doesn't highlight when it doesn't meet minumum requirements, you don't know it needs to be fixed.
(there are screenshots at bottom)

### Popup message
Message at the top when I save is accurate in English. However, it needs to be translated in French popup. Also, the field should be highlighted with appropriate message

### English
<img width="726" alt="Screenshot 2024-09-13 at 7 44 49 AM" src="https://github.com/user-attachments/assets/0b025d14-b8ae-43d1-a410-040cc6b3ec3e">

### French
<img width="863" alt="Screenshot 2024-09-13 at 7 49 39 AM" src="https://github.com/user-attachments/assets/b35de3b7-72d8-4f39-a464-60712daae261">

### NEW MESSAGES in Popup
Updated sub-message in English:
Image width must be at least 100 pixels.
Updated sub-message in French:
La largeur de l'image doit être d'au moins 100 pixels.

### Screenshots for top points


<img width="364" alt="Screenshot 2024-09-13 at 7 45 58 AM" src="https://github.com/user-attachments/assets/3e13335f-9633-43ca-a4fe-e0cb9afb9090">

<img width="625" alt="Screenshot 2024-09-13 at 7 45 27 AM" src="https://github.com/user-attachments/assets/815698c0-4c33-43db-9c01-802b2f7128fb">

Message hasn't been updated to new text
<img width="526" alt="Screenshot 2024-09-13 at 7 44 40 AM" src="https://github.com/user-attachments/assets/0484430c-b340-48af-bf71-8e9ed5f98e96">
