### ISSUE TITLE
French and English UI text corrections

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#123]
There is english text in the French UI.
Also, we need to edit the sentence in the English UI to remove the Role selection (Not MVP).

Please replace the english text in the English UI AND the French UI as follows:

Change: 
Add an organizer for your event and assign a role.
To:
**English:**
Add an organizer for your event.
**French:**
Ajoutez un organisateur pour votre événement.

Change: 
Add a main performer for your event and assign a role.
To:
**English:**
Add a main performer for your event.
**French:**
Ajoutez un interprète principal pour votre événement.

Change: Add a supporter for your event and assign a role.
To:
**English:**
Add the organization supporting or sponsoring this event. 
**French:**
Ajoutez le commanditaire ou l'organisme qui soutient l'événement.

Note: text in not updated in image
![Image](https://user-images.githubusercontent.com/64489312/217077196-f7ca9dec-f55e-4835-9dbf-b2897b807740.png)

**Comment by troughc** [comment]
@saumier Before we change this text, let's confirm that the user will be able to assign a role at launch. 
If NOT, then the text at launch would be as follows.
English: Add an organizer for your event.
French: Ajoutez un organisateur pour votre événement.

**Comment by AbhishekPAnil** [comment]
ESTIMATE 0.5 hr

**Comment by troughc** [comment]
Tested Staging in Chrome and PASSED!
