### ISSUE TITLE
cannot delete subcategories in Taxonomies

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1230]
This issue was found by ArtsCulture NB.
I can't delete a sub-category. I have the Delete button but clicking on it doesn't do anything. The window stays like I haven't clicked on Delete yet. Actually, I fixed the bug by renaming the sub-category first, then I could delete it. 

Steps to reproduce:
Open a taxonomy that has items with subcategories. Try to delete a subcategory. Nothing happens.
Expected behaviour: I can delete any item in the taxonomy list.

**Comment by dev-aravind** [comment]
@SyamBabu-M This seems to be a UI issue. Please look into this and let me know if you have any questions.

**Comment by troughc** [comment]
Tested: PASSED
