### ISSUE TITLE
typos in french sections

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1232]
Found by Arts Culture NB
typos in French on the Taxonomies page...

Éffacer => Effacer 
Remove accent

...in listings pages on the right where we say who created the event/place/org/person

Crée => Créé
Add second accent

...in Calendar Widget Settings:

Font selection => Sélection de la police de caractères
Replace english with French

**Comment by troughc** [comment]
@AbhishekPAnil I am reassigning this one to you, to do at the same time as you do the other translation fixes in #1196

**Comment by troughc** [comment]
@AbhishekPAnil I have corrected the french language errors. They are here: https://pr-1242.dla06mbe0wyl7.amplifyapp.com/

I added the PR link to the developement section on the left - how do I add it to the top? 
FYI: the WIKI instruction step 5 - did I raised the pull request correctly? Did I put the right link in the Development section (instruction says "Try to copy/paste the issue link in the description or mention the issue from the development section in the bottom right corner.")?

thanks.

**Comment by AbhishekPAnil** [comment]
> I added the PR link to the developement section on the left - how do I add it to the top? FYI: the WIKI instruction step 5 - did I raised the pull request correctly?
Yes you have raised the PR correctly.Well done @troughc 💯 .
>I added the PR link to the developement section on the left - how do I add it to the top?
You don't need to add it to the top.You have added it correctly in the description as well as in the development section.
> Did I put the right link in the Development section (instruction says "Try to copy/paste the issue link in the description or mention the issue from the development section in the bottom right corner.")?
Sometimes you will unable to find the issue number in the development section.This may happen because the issue may be present in another repository.You can only link the issues present in the respective repositories.

Do you want me to add a screenshot to the wikipage to get more clarity?

**Comment by AbhishekPAnil** [comment]
Tested in Chrome : PASSED

**Comment by troughc** [comment]
> Do you want me to add a screenshot to the wikipage to get more clarity?

@AbhishekPAnil I don't think it's necessary but if you think it might help another user in the future, then yes. :)
