### ISSUE TITLE
Custom fields not appearing in the Footlight CMS Open API

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1235]

**Comment by tammy-culture** [comment]
@sahalali Client is noticing that a few fields don’t seem to be present in the API output – probably the custom fields that have been added. 

Could you check the API outputs and add any of the missing fields that are not coming through.
 e.g. Events: https://api.footlight.io/calendars/artsculturenb/events?page=1&limit=1000

They are not seeing Audience, Event Discipline, and Additional Images (although, I am not sure that is ready yet.)

Please let me know if you need anything.

Thanks.

**Comment by sahalali** [comment]
@tammy-culture audience, event discipline and image gallery are not return in the Event listing API (https://api.footlight.io/calendars/artsculturenb/events?page=1&limit=1000), however its returned in the details API (https://api.footlight.io/events/669017f3ee118d00649c69db?include-json-ld=false).

If we do have a usecase to return these properties, lets think about enhancing the listing response.

**Comment by tammy-culture** [comment]
@sahalali Question: Do the clients have access to the details API?

**Comment by sahalali** [comment]
Please make a note of the following information:

We have 2 APIs for fetching event details:

1. Event Listing API (**https://api.footlight.io/calendars/artsculturenb/events?page=1&limit=100**):
The event listing API will return a list of events based on the applied limits and filters. The response will contain a limited set of properties. It's beneficial to retrieve events with a small limit.

2. Event Details API (**https://api.footlight.io/events/{**event-id**}**):
The event details API response will include all properties of the event.

**Comment by tammy-culture** [comment]
Thank you
