### ISSUE TITLE
MIssing account for regression testing

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1236]
Periodically, the DB is refreshed. But CMS-R needs a minimum set of data to work without failure.

1. Account
1 account for each role-locale pair is needed, so 4 for now (in the future when more languages are introduced, dynamically changing languages may be used instead).
3 accounts seem persistent after updates, 1 isn't (the one with address taliesen@use.startmail.com). 

![MIssing account](https://github.com/user-attachments/assets/d296190f-52ed-4578-99dc-46141aaf70c7)

![MIssing account - restored](https://github.com/user-attachments/assets/7d3f826a-b633-466d-9edc-62911b6b0fc6)

This account needs to be copied to the base DB deployed on release. 

**All 4 accounts are needed to test, so all DB used for dev also need to have those accounts.**

**Comment by kmdvs** [comment]
The accounts need to be present in order to make sure all tests for all roles / locales are done. That means they need to exist for any environment tested: staging certainly, possibly production (with caveats), but also (test /) dev environments.

**Comment by sahalali** [comment]
Sure, I'll make it clearer for you:

Yes, when the production data is next restored in Staging, the account will become active in staging as well. The account will then be persisted in both the Production and Staging instances.

Also, I'd be happy to understand more about the Dev environment setup. How are you managing the database?

**Comment by saumier** [comment]
@kmdvs This issue is getting stale. Should it be closed?

**Comment by kmdvs** [comment]
Yes, concerns are addressed, and we discussed test data requirements to ensure more robust tests even in case of previous test failures (test isolation is not completely possible, for example for the deletion step)
