### ISSUE TITLE
SuperAdmin: cannot change UI language in profile

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1238]
Note: lower priority as it only affect us. This can be fixed when you have time.
Steps to reproduce (in staging and in production):
1. log in as superadmin.
2. go to your user profile and change language preference to French.
3. Click Save. Nothing happens. You cannot change language preference from English.
Expected behaviour: super admin can change their language preference.

**Comment by AbhishekPAnil** [comment]
Bug report:
The issue occurred in the frontend because of an undefined value in organizations, people, and userType. As this is not required for the super admin, I have implemented a conditional check to prevent this.

**Comment by troughc** [comment]
Tested: PASSED. Thanks @AbhishekPAnil
