### ISSUE TITLE
Signe Laval is getting a 404 error when loading certain events from Centropolis

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1244]
These events are causing the error: https://signelaval.com/fr/evenements?q=centropolis
CMS link: https://cms.footlight.io/dashboard/63457978637093005071a053/events?page=1&order=asc&sortBy=upcomingEventDate&query=centropolis

To reproduce: click one of the events on the listing page of the website. You are directed to a 'page non-trouvee' (page not found)

Please investigate what is causing this error.

**Comment by saumier** [comment]
@sahalali I can confirm this is a problem seen calling directly the Footlight Open API.

Test 1: 
https://api.footlight.io/events/646e3076cac2d700645ac654

Test of another event 

Gives `502 Bad Gateway`

Test 2:
https://api.footlight.io/events/669e8894af84a60064068b43

` "error": "Cannot read properties of null (reading 'find')"`

Test 3:
https://api.footlight.io/events/646e3076cac2d700645ac654

Not in Centropolis and works

**Comment by sahalali** [comment]
This issue is fixed and now deployed to production after testing in Staging.

**Comment by troughc** [comment]
Tested:PASSED
