### ISSUE TITLE
The 'atourisme trois rivieres' aggregator is not displaying dates properly in the Tourisme Mauricie Production CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1249]
Can we check the `atourisme trois rivieres` aggregator to see how dates are going into the Tourism Mauricie Production CMS?

The CMS does not seem to be able to show individual dates when an event series is imported from Artsdata.

See this example:
**Sous pression - Louis Morissette**
https://cms.footlight.io/dashboard/661e5a8818a64f7829aeae24/events?page=1&order=asc&sortBy=upcomingEventDate&users=6667f0fa92cafd0064969ff7&query=sous+pression

NOTE: the sub-events in **Sous pression - Louis Morissette** have only a startDate and not startDateTime. The absence of time may not be handled correctly in CMS and may be the condition that causes this bug.

Data for this event coming from Artsdata
https://api.artsdata.ca/query?frame=event_footlight&format=json&sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-event-uri-v3.sparql&uri=http%3A%2F%2Fkg.footlight.io%2Fresource%2Ftourisme-troisrivieres-com_sous-pression-louis-morissette&source=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Ftourisme-troisrivieres-com

### Repro steps
1. Run workflow to load data from Artsdata
2. Check events with multiple occurrences (event series) that have updated (not yet edited by another user)

Expected behaviour:
- In CMS listing view, the `# occurences` appears (not appearing for **Sous pression - Louis Morissette**)
- In CMS event edit view, the individual dates should appear in the dates popup (for **Sous pression - Louis Morissette** the dates appear invalid)

**Comment by troughc** [comment]
@saumier should this issue be moved to the Artsdata board?
cc @tammy-culture

**Comment by saumier** [comment]
@troughc As discussed by phone, please check with @tammy-culture and if we don't need to import the source "trois rivière" from Artsdata then please close this issue as "Won't fix".

**Comment by saumier** [comment]
@sahalali Please look at the details in the issue description at the top. I have added information after working with Tammy and Caitlin. I also renamed the user from `atrois rivieres` to `atourisme trois rivieres` in order to reduce confusion with the other aggregator user 'aculture-3r' which stands for culture trois rivieres.

**Comment by sahalali** [comment]
The issue was related to formating subEventConfiguration while the sub-event has just startDate or endDate but no time.

**Comment by saumier** [comment]
@tammy-culture Please take a look at the events in Tourisme Mauricie in production 

Example: 
https://cms.footlight.io/dashboard/661e5a8818a64f7829aeae24/events?page=1&order=asc&sortBy=upcomingEventDate&users=6667f0fa92cafd0064969ff7&query=sous+pression

**Comment by tammy-culture** [comment]
@saumier The Louis Morissette event looks good.  Thanks.
