### ISSUE TITLE
Client request for a CSV/Excel/Google Sheet file of their Places updated with the appropriate MRC regions be uploaded to their production CMS.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1254]
Client is creating a custom field for Places to indicate region.  And instead of individually updating each entry manually in the Production CMS they would like to do that work in a Google Sheet file that can then be uploaded in their Produciton CMS with the appropriate region.

**Comment by tammy-culture** [comment]
@SuhailAliyar Please download into a Google Sheet file the list of Places for Tourism Mauricie.  Thanks.

**Comment by sahalali** [comment]
[export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv](https://github.com/user-attachments/files/16452447/export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv)
Here is the CSV file with all the places  for Tourism Mauricie,

**Comment by saumier** [comment]
@sahalali I downloaded the Places from Admin API, and I fixed the geo-coordinates, but I didn't find any regions (custom taxonomy). How do I edit the MRC region in batch?

**Comment by sahalali** [comment]
I've downloaded the newly exported CSV, this contains dynamic field column. Now we can add the values and reupload.
[export-csv-file_Place-04f8dd8c-0e07-46fd-995d-5d5622d7c569.csv](https://github.com/user-attachments/files/16467127/export-csv-file_Place-04f8dd8c-0e07-46fd-995d-5d5622d7c569.csv).

Note: The dynamic field will only appear if at least one entity has a value mapped from the dynamic field.
Other wise, we should add a column with the header "dynamicFields[${dynamicfield-index}].${taxonomy-id}.id[${value-index}]" example: dynamicFields[0].668563399d0a290064b9706e.id[0] (in this case). the name fields are optional.

**Comment by tammy-culture** [comment]
@tammy-culture Tammy will update the MRC taxonomy to use the standard field.

**Comment by tammy-culture** [comment]
Here is the upload file: 

[export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv](https://github.com/user-attachments/files/16500622/export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv)

**Comment by tammy-culture** [comment]
@saumier The MRC taxonomy has been updated.  Please upload the Places CSV with the associated MRC when you can. Thanks.

**Comment by saumier** [comment]
@sahalali It is late here in Montreal. Can you please upload the MRC regions (using the new district standard field that Tammy setup) using the MRCs from Tammy's Places CSV? [export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv](https://github.com/user-attachments/files/16500622/export-csv-file_Place-6fcd588d-9b26-4e2f-99cb-98d0c15d099c.csv)

**Comment by sahalali** [comment]
@saumier Please make a note of the following information.
Uploaded MRC regions to Tourisme-Mauricie places.
 This process was completed by following these steps:
1. A new column 'regions.entityId[0]' was added to the CSV file, and region concept identifiers were included by matching with the MRC column provided.
2. The CSV file was then uploaded.

Currently, the calendar contains 73 places. MRC regions were added to only 58 of them. It seems that the others are new places added recently.

**Comment by tammy-culture** [comment]
@sahalali When you get a chance can you provide with a list of the 15 Places missing MRCs and I will get the client to add them manually.  Thank you.

**Comment by sahalali** [comment]
@tammy-culture Here are the list of places missing region:
Esplanade Trois-Rivières sur St-Laurent
Salon Wabasso du Trou du Diable
Parc des Chenaux
Parc des Prairies
PARC PIE-XII
Salle Philippe-Filion
Ville de Trois-Rivières
Parc du Moulin
La Taverne Royale
Backstore (Dep Frida)
Camping Rouillard
Terrasse de la salle J.-Antonio-Thompson
Amphithéâtre - Parc récréoforestier
Rock Café Le Stage
Esplanade

**Comment by tammy-culture** [comment]
Thank you
