### ISSUE TITLE
Live issue: "hello" string appearing in new event date type choice 

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1257]
An extra "hello" appears in the live / staging / test sites. This is a code issue, that string is not in the translation files. Appears in both Fr and En

![hello bug](https://github.com/user-attachments/assets/0dd76909-28fd-4e79-a82f-8d31bb08d52a)

**Comment by troughc** [comment]
@AbhishekPAnil please see the unwanted 'hello' in the dates section.

**Comment by kmdvs** [comment]
In the code:

{className:"add-event-date-heading","data-cy":"heading-dates",children:[Ut("dashboard.events.addEditEvent.dates.heading")," hello"]})})})
