### ISSUE TITLE
Calendar Read only alignment wrong

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1261]
The alignment of the read only toggle button in the general settings page seems to off.

![Image](https://github.com/user-attachments/assets/73dbb317-636b-4016-9a40-66088b2744d1)

Expected layout :

![Image](https://github.com/user-attachments/assets/ebf0e6ed-45d9-45f2-b120-56c4b19d6f8a)

**Comment by troughc** [comment]
Looks good, thanks @AbhishekPAnil
