### ISSUE TITLE
switching from Signe Laval - Tout Culture at 9:30 AM august 2 - also affecting other calendars

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1264]
This happens sporadically. I am setting it to low, because for now, it only affects culture creates team. 
I had the cms open and in the Signe Laval calendar.
I tried to switch to Tout culture and nothing happened
See screenshots with tabs open - I cleared them and then tried to switch multiple times. It never worked.
I then switched to another calendar successfully and then switched to tout culture successfully)
I could then switch back and forth between Signe Laval and Tout Culture

![Image](https://github.com/user-attachments/assets/ee1155c2-423b-4bcb-a18a-dc30ff2c70e5)

![Image](https://github.com/user-attachments/assets/d11ac486-6498-4b0c-aece-fbbd58e4f712)

Test Cases :

1. Open the cms in two different tabs with the same logged in user.
2. Switch the calendar in any one of the tabs.
3. Check if you are able to switch between calendars in the other tab.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil To reproduce :Try to manually change the `calendarId` from the Cookies/Local Storage/Session storage.

**Comment by troughc** [comment]
@AbhishekPAnil I am now experiencing this issue when I try to switch between DICI and Tourisme Mauricie. The conditions are that I am looking at an event that was imported from DICI into Tourisme Mauricie and I had switched back and forth between calendars several times before it happened. The same problem (not being able to switch) happened at the same time to Tammy. (around 9:20 on Tuesday August 20)

**Comment by troughc** [comment]
I can't test, please push to production.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil will rework on this issue as the calendar switching occured when opening the app in two tabs.

**Comment by troughc** [comment]
Tested by opening 2 instances of the cms in the same browser. Then switched each cms around to different calendars. Seemed to work for me. PASSED
@AbhishekPAnil was this the correct way to test? If so please deploy,

**Comment by AbhishekPAnil** [comment]
> Tested by opening 2 instances of the cms in the same browser. Then switched each cms around to different calendars. Seemed to work for me. PASSED
> @AbhishekPAnil was this the correct way to test? If so please deploy,

Yes.
