### ISSUE TITLE
Add cms.footlight.io/.well-known/change-password

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1268]
To facilitate apps like Safari, that prompt users to change their passwords when they are found in security breaches, a request to https://cms.footlight.io/.well-known/change-password should bring the user to a change password screen. This is a proposed standard. See https://datatracker.ietf.org/doc/html/rfc5785

**Comment by troughc** [comment]
@saumier what priority would you set for this issue?

**Comment by troughc** [comment]
@syam demoed the fix for me, looks good. will do a final check after this is pushed to staging.

**Comment by troughc** [comment]
@SyamBabu-M please assign back to me after you push to staging. Thanks.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil  The above reference was accidental.
