### ISSUE TITLE
Prevent Users from drag/drop and copy/paste images into the text editor

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1270]
Currently, users can copy/paste and drag/drop images directly into the text editor. This behavior can lead to slowing down of the listing api's , since the images are not passed through our image server. To maintain a consistent user experience and prevent potential problems, we need to disable the ability to copy/paste and drag/drop images into the text editor.
Ref slack message : https://culturecreates.slack.com/archives/C02B18SN3FU/p1722702723875049

Expected Behavior

- Users should not be able to paste images into the text editor.
- Users should not be able to drag and drop images into the text editor.

Steps to Reproduce

1. Open the any form(Event, People, Place, Organization).
2. Copy an image from any source (e.g., web page, local file).
3. Paste the image into the text editor.
4. Drag an image from any source and drop it into the text editor.
5. Save the entity. The image is embedded into the text editor.

Proposed Solution

- Disable the copy/pasting using the `quill format`.
- Disable the drag/drop using the `onDrop` function.

Also ,ensure that other types of content (e.g., text, links) can still be copied/pasted and dragged/dropped into the text editor.

**Comment by troughc** [comment]
Caitlin needs to discuss this change with customer.

**Comment by troughc** [comment]
@AbhishekPAnil can users add (embed) video content to descriptions?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil can users add (embed) video content to descriptions?

Need to test if they can embedd videos to description.
We already have an additional field to embed the url.Right?

**Comment by troughc** [comment]
Yes we do already have a field for that. I am asking just to know what the text field currently supports. Not suggesting people _should_ add video to descriptions. :)
If memory serves me right, they CANNOT add videos.

**Comment by troughc** [comment]
I was able to embed in this test event (draft), but I don't know what the impact is or if it works.
https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66b0e05ace7a2500a39f9c5c

**Comment by kmdvs** [comment]
A mitigation possibility: _Is there a way to set up a MB limit, to accommodate any combination of number of files / filesize?_

**ChatGPT**
Yes, you can set up a total file size limit (in MB) that accommodates any combination of the number of files and their individual sizes. This approach allows you to enforce a maximum total upload size, regardless of how many files are selected or their individual sizes.

Here's an example of how you can implement this in a React component:

_Example React Component with Total File Size Limit_
```

import React, { useState } from 'react';

function ImageUpload() {
  const [files, setFiles] = useState([]);
  const [totalSize, setTotalSize] = useState(0); // Total size in MB
  const maxTotalSize = 10; // Maximum total size in MB

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  const handleDrop = (event) => {
    event.preventDefault();
    const droppedFiles = Array.from(event.dataTransfer.files);
    let newTotalSize = totalSize;

    // Calculate the total size of new files
    droppedFiles.forEach(file => {
      newTotalSize += file.size / 1024 / 1024; // Convert size to MB
    });

    // Check if the total size exceeds the maximum allowed size
    if (newTotalSize > maxTotalSize) {
      alert(`Total file size cannot exceed ${maxTotalSize} MB. Please select smaller files.`);
      return;
    }

    // Set the new files and update the total size
    setFiles((prevFiles) => [...prevFiles, ...droppedFiles]);
    setTotalSize(newTotalSize);
  };

  return (
    <div>
      <div
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        style={{
          width: '300px',
          height: '200px',
          border: '2px dashed #ccc',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          margin: '50px auto',
        }}
      >
        Drop images here
      </div>
      <div>
        <p>Total size: {totalSize.toFixed(2)} MB</p>
        {files.map((file, index) => (
          <p key={index}>
            File {index + 1}: {file.name}, Size: {(file.size / 1024 / 1024).toFixed(2)} MB
          </p>
        ))}
      </div>
    </div>
  );
}

export default ImageUpload;
```


**Explanation**
State Management:

files: An array that holds the dropped files.
totalSize: A state variable that tracks the total size of all files in MB.
maxTotalSize: A constant representing the maximum allowed total file size in MB.
handleDragOver Function:

Prevents the default behavior to allow the drop event.
handleDrop Function:

Prevent Default Behavior: Prevents the default drop action.
Convert Files: Converts the FileList object to an array using Array.from.
Calculate Total Size: Iterates over the dropped files and calculates their total size in MB, adding to the existing totalSize.
Check Total Size: Compares the new total size with maxTotalSize. If it exceeds the limit, an alert is shown, and the function returns, preventing the addition of new files.
Update State: If the total size is within the limit, the new files are added to the existing state, and the totalSize state is updated.
Rendering:

The drop zone is defined with onDragOver and onDrop event handlers.
The total size of the uploaded files and details of each file are displayed.
Additional Features
File Removal: You can add functionality to remove individual files from the list, which would also update the totalSize state accordingly.
File Validation: Additional checks, such as file type validation or individual file size limits, can be incorporated to provide a more comprehensive validation.
This implementation ensures that the total size of all files does not exceed a specified limit, allowing for any combination of file numbers and sizes within that limit.

**Comment by troughc** [comment]
NOTE: These are the only upcoming events that I found with images embedded into descriptions, in both French and English pages.
[https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd7a7d09b4d00634bdb15](https://www.google.com/url?q=https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd7a7d09b4d00634bdb15&sa=D&source=calendar&ust=1723320352038911&usg=AOvVaw1WT9jatjbfBDw2U6Tewd1V)

[https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd44fd09b4d00634bd9d4](https://www.google.com/url?q=https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd44fd09b4d00634bd9d4&sa=D&source=calendar&ust=1723320352038911&usg=AOvVaw0-5D4jbWNPmr_dNzH3k3PS)

[https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd9ecd09b4d00634bdcf4](https://www.google.com/url?q=https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66acd9ecd09b4d00634bdcf4&sa=D&source=calendar&ust=1723320352038911&usg=AOvVaw02ZyzOhOP73UJcTeNHohVW)

**Comment by troughc** [comment]
Note to @AbhishekPAnil: For now, stop users from embedding video into the text field.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil 
As per discussion ,

1. disable drag/drop of image/video into the editor.
2. Add a button to upload image/video.
3. Check if its possible upload the image directly from the editor to our image server.

**Comment by AbhishekPAnil** [comment]
The only issue face now is ,while uploading the  image from the local system into the editor,the image is saved in the form of an image tag with a base64 src data

**Comment by AbhishekPAnil** [comment]
> The only issue faced now is ,while uploading the image from the local system into the editor,the image is saved in the form of an image tag with a base64 src data

This will be solved by uploading the image to the s3 and then using the url from the api response to update the src inside the image tag.

**Comment by sahalali** [comment]
@AbhishekPAnil 
I've added support to return the original image URL in the image upload API response. This is now live in staging.

**Comment by troughc** [comment]
For my test: To check the image data, I will inspect the image in the read-only page. Otherwise, I can check with Abhishek

**Comment by troughc** [comment]
@AbhishekPAnil 
### 1. Image tests:
 https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66ba19674be0ab00a039defa
I was able to copy paste an image from google. Then, when I inspected it, I see this - it says base64 in the text when I hover over it? Is that okay? 

<img width="1295" alt="Screenshot 2024-08-12 at 10 25 51 AM" src="https://github.com/user-attachments/assets/e9f25e9e-de5b-4dd0-a605-fab026a6e401">
<img width="1050" alt="Screenshot 2024-08-12 at 10 26 02 AM" src="https://github.com/user-attachments/assets/b22aaa03-94d8-4924-910e-dfbce8d2110b">


**Please check these three events.** https://pr-1275.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=upcomingEventDate&query=caitlin
(Search on Caitlin and you will see three test events)

In test event 3, some of the images also look like they are base64. Even ones that I uploaded from my desktop using the upload button. Test 2 seems okay, but please check




### 2. Video link test:
https://pr-1275.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/66ba327c4be0ab00a039e5b3

I can add the video link but the link is not completely visible:
<img width="605" alt="Screenshot 2024-08-12 at 12 03 30 PM" src="https://github.com/user-attachments/assets/72d90db1-8865-4cea-83f6-fd0ff5ffa4ba">


### 3. When I publish, too many popups
I get to success messages instead of one. You can reproduce it by saving any of my test events as draft and then republish.
<img width="1058" alt="Screenshot 2024-08-12 at 11 57 41 AM" src="https://github.com/user-attachments/assets/df21433d-c8c8-4dbb-a8cf-a6f80c7187f6">

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil 
> ### 1. Image tests:
>  https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/66ba19674be0ab00a039defa
> I was able to copy paste an image from google. Then, when I inspected it, I see this - it says base64 in the text when I hover over it? Is that okay? 
> 
> <img width="1295" alt="Screenshot 2024-08-12 at 10 25 51 AM" src="https://github.com/user-attachments/assets/e9f25e9e-de5b-4dd0-a605-fab026a6e401">
> <img width="1050" alt="Screenshot 2024-08-12 at 10 26 02 AM" src="https://github.com/user-attachments/assets/b22aaa03-94d8-4924-910e-dfbce8d2110b">
> 
> 
> **Please check these three events.** https://pr-1275.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=upcomingEventDate&query=caitlin
> (Search on Caitlin and you will see three test events)
> 
> In test event 3, some of the images also look like they are base64. Even ones that I uploaded from my desktop using the upload button. Test 2 seems okay, but please check
> 
> 
> 
> 
> ### 2. Video link test:
> https://pr-1275.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/66ba327c4be0ab00a039e5b3
> 
> I can add the video link but the link is not completely visible:
> <img width="605" alt="Screenshot 2024-08-12 at 12 03 30 PM" src="https://github.com/user-attachments/assets/72d90db1-8865-4cea-83f6-fd0ff5ffa4ba">
> 
> 
> ### 3. When I publish, too many popups
> I get to success messages instead of one. You can reproduce it by saving any of my test events as draft and then republish.
> <img width="1058" alt="Screenshot 2024-08-12 at 11 57 41 AM" src="https://github.com/user-attachments/assets/df21433d-c8c8-4dbb-a8cf-a6f80c7187f6">
> 

Let me check with the images .The images shouldn't be in base64.


The video link layout issue exists since our editor is only manually expandable.

**Comment by AbhishekPAnil** [comment]
> 3. When I publish, too many popups
I get to success messages instead of one. You can reproduce it by saving any of my test events as draft and then republish.


cc @AbhishekPAnil Will solve this bug in this issue.

**Comment by troughc** [comment]
@AbhishekPAnil let's hold off on implementing this feature (i.e. adding buttons for images and video). Furthermore, we will not add the video option at all (remove that button completely).

Main point: this is on hold so I will unassign you and assign myself.

After discussing this with @saumier and I want to go back to the customer at Tout Culture to see if they can use our existing solution (image gallery). If they really want to keepimages in the descriptions, then we may implement this as a special feature that would only be available for Tout Culture (it would not be available in any other CMS for any other customer).

I will let you know the final decision.

**Comment by troughc** [comment]
Note that we will definitely be removing the ability to drag/drop or copy/paste images into descriptions. Stay tuned!

**Comment by AbhishekPAnil** [comment]
> > 3. When I publish, too many popups
> >    I get to success messages instead of one. You can reproduce it by saving any of my test events as draft and then republish.
> 
> cc [@AbhishekPAnil](https://github.com/AbhishekPAnil) Will solve this bug in this issue.

We may have to treat this as a separate issue.
This needs debugging.This might have occured when we added the logic that when user changes the publish state of an event ,the modifier details shouldn't be updated.Creating duplicating event also has this issue.

**Comment by AbhishekPAnil** [comment]
> Note that we will definitely be removing the ability to drag/drop or copy/paste images into descriptions. Stay tuned!

I have updated the PR with the above changes.

**Comment by troughc** [comment]
Here is the new design for image gallery https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=9647-90907&t=ESgAxxnpWTxhlWcJ-1
to discuss

**Comment by troughc** [comment]
Hi @AbhishekPAnil I tested copy/paste and drag and drop of images into the description. This works, as in, nothing is getting added to the description. PASSED
Also tested that I could copy links: PASSED

**Comment by troughc** [comment]
@AbhishekPAnil Please deploy this one. We can work on improving the image gallery functionality next, which will be covered here https://github.com/culturecreates/footlight-app/issues/1229

**Comment by troughc** [comment]
@sahalali @AbhishekPAnil this is now approved to be deployed to PRODUCTION. thanks!
