### ISSUE TITLE
Dates in Widget appear in English rather than in French

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1279]
@AbhishekPAnil @SyamBabu-M please fix this bug as soon as possible as the client wants to give the widget to an online newspaper as soon as possible.

The listing widget displays MONTHS and the ENGLISH DATE STYLE the French listing widget (in previews and in the publicly displayed widget).  For example, see the D'ICI.CA calendar: this is a French listing widget for a french calendar.  

What is correct (fixed previously) is the usage of 'au' in french and 'to' in English in events that are date ranges.

Please see image attached below. 
For example, notice the usage of ENGLISH for AUG  
In FRENCH, AUG is AOÛT 

![Image](https://github.com/user-attachments/assets/69dec333-4aad-4b1b-8d42-26f7d6168b52)

In the French UI, the dates are correclty displayed in the list view if you need an example / source for setting this up correctly in the Widget.

![Image](https://github.com/user-attachments/assets/2f1eb700-de8d-4db8-8cf6-880119817646)

Expected behaviour: Dates should appear in FRENCH in FRENCH widgets.

**Comment by troughc** [comment]
@AbhishekPAnil is this bug for you to fix or for @SyamBabu-M ?

**Comment by AbhishekPAnil** [comment]
I will assign this to @SyamBabu-M

**Comment by SyamBabu-M** [comment]
@tammy-culture, I have implemented the required changes. You can test this in CMS staging.

**Comment by SyamBabu-M** [comment]
@tammy-culture When a date or date range is selected, the selected date is displayed as text in the top heading. Should this text be presented in all capital letters?

![Image](https://github.com/user-attachments/assets/c45617f6-1e2c-4942-bf6e-d1414cb7d801)

**Comment by tammy-culture** [comment]
Hello @SyamBabu-M I think that that is fine that they are all capital letters. And thank you.

**Comment by tammy-culture** [comment]
@SyamBabu-M It looks good can you please deploy to the Production CMS.  Many thanks.
