### ISSUE TITLE
Quick Create Organization

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#129]
As a user, when I am creating a new event, and I search for an organization but cannot find it in the list, I can click a "create" button to create a new Organization without leaving the event.

Note: In the screen grabs below, we have removed the "full details" button. The other fields are always present: name, website, Logo. **You can find the current designs in Sprint 12.**

Note: In the popup offering to create a Person or Organization, the choice of Person should be present but disabled.

Prerequisite:  
- https://github.com/culturecreates/footlight-calendar-api/issues/328

Related to:
- https://github.com/culturecreates/footlight-app/issues/266

![Image](https://user-images.githubusercontent.com/419491/221878368-0381a3c3-ccb8-4f1f-af2b-3631aeeb8048.png)

![Image](https://user-images.githubusercontent.com/419491/221877971-7731bd4b-007d-4aee-9cb5-bb8d6381ad58.png)

**English:**

![Image](https://user-images.githubusercontent.com/64489312/221937644-e5c76615-e4c6-48b1-b2dc-c126c6e6e6ff.png)

**French:**

![Image](https://user-images.githubusercontent.com/64489312/221937742-74b0379e-0e97-4e3b-ab39-38156367461b.png)

**Comment by AbhishekPAnil** [comment]
ESTIMATES 10 hrs

Subtasks
1.Add create button to bottom of organizer,performer and supporter search.
2.Create a modal to display the person and organization.
3.Create a modal to enter the organization details.
4.Add the api integration for creation of organization.

**Comment by troughc** [comment]
@saumier can we move this issue up again (now that we have a few more days)

**Comment by AbhishekPAnil** [comment]
The estimated tasks for the issue have been completed.After implementing the trunk based approach ,this issue will be deployed inn staging.

**Comment by saumier** [comment]
I wanted to look into the build process to see why the toggle is not working when the React build is made. But I ran into a problem with node packages that are incompatible and prevented my from building.

From the log, it looks like rc-year-calendar@1.0.2 only works with  react@"^16.8.4" .

How do you get around this? Do we need to update something?

```
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.4" from rc-year-calendar@1.0.2
npm ERR! node_modules/rc-year-calendar
npm ERR!   rc-year-calendar@"^1.0.2" from the root project
```

**Comment by saumier** [comment]
@troughc Please test in staging by adding an Organizer that does not already exist in CMS.

**Comment by troughc** [comment]
Tested in Chrome and this works - you can add an organizer that doesn't exist yet.
A couple of ux comments @AbhishekPAnil 
- I tested this using the French and English UIs. The French UI is fine. There is an issue if I am using the English UI. When I addd a name to the field, and then click create new, the Quick Create module opened with the french field displayed and empty. To see that my English text is there, I have to switch to english tab. And there is no indicator letting me know that there is text there. Ideally, the text that I entered, in the language of my UI, should be displayed in the field. Is this possible?
- After I save the new organziation in quick create, the Organizer field still displays the text I entered at the beginning of this task. I think that the organization should be selected and the text cleared out of the field.

**Comment by AbhishekPAnil** [comment]
> I tested this using the French and English UIs. The French UI is fine. There is an issue if I am using the English UI. When I addd a name to the field, and then click create new, the Quick Create module opened with the french field displayed and empty. To see that my English text is there, I have to switch to english tab. And there is no indicator letting me know that there is text there. Ideally, the text that I entered, in the language of my UI, should be displayed in the field. Is this possible?

@troughc  Please do test these features in staging .

**Comment by troughc** [comment]
@AbhishekPAnil I don't see a change in Staging for when i am using the English UI on a bilingual site (tout culture). In Quick Create,the French tab for the name is displayed and empty when I click create new. The text I typed is added to the English tab (which is hidden).
Steps to reproduce
1. Set your UI language to English.
2. Go to Add event and go to the organizer field. 
3. Type in the name of an organization that doesn't exist, and then select + create <name>
4. select organization
5. the quick create module is displaye wiht the French tab showing and empty
6. Click the EN tab to see the text you entered in teh organizer field.

**Comment by troughc** [comment]
@AbhishekPAnil yes, let's do it next standup. I had an appointment today.

**Comment by troughc** [comment]
Tested in CHROME staging:

The issue with English/French tab is fixed thankyou.

@AbhishekPAnil as discussed, I will open an issue about displaying the logo for an organizer/performer/supporter if it has been added to the organization. 

I found another issue with displaying the name of the organization in the dropdown after saving.
Steps to reproduce
1. Create the organization using quick create and save. Add only one language name - it doesn't matter which language. You can do this step from French or English UI.  The organizer is added the the details page and hte name is displayed.
2. Save the event (or publish the event).
3. reopen the event. The name of the organization is no longer displayed in the selected box under the dropdown. 
4. Select the organization (type the name into the field and then select it. The name now appears. See screenshots below

### After saving and reopening, the name is gone

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/251f362b-400f-4dd0-a73b-fa14ec06df8d)

### After saving, reopoening and adding the organizer(s) that now exists in the Organization tab.



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/af8e8603-eb08-47f2-9008-d6fbaff62de9)


As you can see, the name appears for the ones I added after saving. But the names are NOT displayed for the ones I created using Quick Create. 

I am available if you have questions.

**Comment by saumier** [comment]
@AbhishekPAnil I am wondering why you are assigning to Dev, or if that was a mistake. Please leave a note to give your reason. thx.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil I am wondering why you are assigning to Dev, or if that was a mistake. Please leave a note to give your reason. thx.
> 

Once an organisation has been created with quick create and the user saves the the event,when the user comes back to the event details page the created organisation details is empty.It is because the api response doesn't have the necessary details of the selected organizer.It only provides the type and entity id.

**Comment by dev-aravind** [comment]
@AbhishekPAnil, It seems like to save Organizer's details, the type for organization is passed as "ORGANIZATION" instead of "Organization" which is causing an error in type checking thus returning data without entity details.

**Comment by troughc** [comment]
Tested in Chrome for both unilingual and bilingual website. Looks good. PASSED
