### ISSUE TITLE
Quick Creates Place

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#130]

**Comment by AbhishekPAnil** [comment]
ESTIMATES 12 hrs

Subtasks
1.Add create button to bottom of place search.
2.Create a modal to enter the place details.
3.Add the api integration for creation of place.
4.Add the api integration to get the details google api.
5.Additional api integration if needed.

**Comment by AbhishekPAnil** [comment]
Added the feature flag = REACT_APP_FEATURE_FLAG_QUICK_CREATE_PEOPLE_PLACE

**Comment by troughc** [comment]
@AbhishekPAnil just to note how the name field should work 
The name you enter should persist. The address name should not replace it with whatever it would display - this is different from how it works in the old cms.

**Comment by troughc** [comment]
Tested staging on Chrome and Safari: PASSED
