### ISSUE TITLE
Enhancement: Taxonomy concepts with multiple languages

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1302]
This is an enhancement following up on #1189 (multiple language support). 
Please refer to Figma titled "Taxonomy concepts - Spreadsheet approach - Updates to multiple languages" found [here](https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=10755-65743&t=gbXHhFMAB8bW1g8x-1)

This will be a significant change as the user will now do editing directly in the fields (No popup).

**Comment by SyamBabu-M** [comment]
@troughc This new design will need a complete rework of the concepts section. 
My estimate is 180 hours, this includes research time into new components as there are limitations for the current Antd component we are using.

**Comment by SyamBabu-M** [comment]
1 - Edit card UI design and integration into tree - 24h
2 - Language literal - 32h
3 - New drag and drop feature - need research
4 - styling - 8h

**Comment by troughc** [comment]
@SyamBabu-M FYI: after our discussion, I asked Stephanie to increase the space (margin) between the language literal tag and the next column/cell. She adjusted it in the figma

**Comment by dev-aravind** [comment]
Hi @SyamBabu-M 

I encountered 2 bugs here

1 - not able to drop a concept as a child to another concept unless it already has child concepts. The interaction works fine if there are already child concepts.
2 - color during the hover movement is not consistent

**Comment by troughc** [comment]
it's looking really good. Just a few things.
When you expand a group, the language literal isn't showing up:

<img width="744" alt="Screenshot 2024-11-14 at 2 11 29 PM" src="https://github.com/user-attachments/assets/3da2f467-e4eb-474c-a55d-0163396cdf1c">



Is it possible to wrap text that doesn't fit in the field? You can see 2 things in the following screenshot
- text doesn't wrap 
- the language literal is overtop of the text (instead of beside it)

<img width="764" alt="Screenshot 2024-11-14 at 2 00 33 PM" src="https://github.com/user-attachments/assets/f032df27-fc95-470b-872f-4676a87dd39b">

For example, in the dropdown for the field in the event, the text does wrap - this works well. 

<img width="481" alt="Screenshot 2024-11-14 at 2 01 33 PM" src="https://github.com/user-attachments/assets/70bf4862-e0f4-4766-9c16-1da54fcee41c">

We can discuss different ways of solving this.

**Comment by troughc** [comment]
Sorry, I forgot we need to be able to delete a concept. can you add a delete button as a quick fix before we move to the next stage of develping this feature.

**Comment by troughc** [comment]
@SyamBabu-M @dev-aravind I looked at the update [here](https://pr-1427.dla06mbe0wyl7.amplifyapp.com/dashboard/65eeaf8ebec01b0064312f94/taxonomies?page=1&order=asc&sortBy=name)

The delete button works well: PASSED
The accordian works well: PASSED

Two questions: 
@dev-aravind did you guys implement the behaviour we discussed the other day? We discussed the idea that an unused concept would go away if it wasn't filled with real text before saving? 
@SyamBabu-M did you change the colour of the line (that appears when you drag) to match the blue used in the right navigation (the blue of the selected workspace)?

**Comment by SyamBabu-M** [comment]
> [@SyamBabu-M](https://github.com/SyamBabu-M) did you change the colour of the line (that appears when you drag) to match the blue used in the right navigation (the blue of the selected workspace)? I don't see it.

My apologies. I have updated the color to #1B3DE6. Please check again.

> did you guys implement the behaviour we discussed the other day? We discussed the idea that an unused concept would go away if it wasn't filled with real text before saving? I don't see this.

Can we discuss this? I am not entirely sure what this is about.

**Comment by troughc** [comment]
Make language title bold
outline concept when dropping another concept inside it (as a sub concept).
After that, good to go!

**Comment by SyamBabu-M** [comment]
@troughc I have made the changes. Please test this.

**Comment by troughc** [comment]
Tested that a fallback language is used if a field is empty: PASSED
Title is bold: PASSED
outline concept when dropping another concept inside it (as a sub concept): PASSED
