### ISSUE TITLE
Wrong message when event is saved.

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1307]
A message for saving as a draft is shown when a published event is saved. Identified during testing of [#1001](https://github.com/culturecreates/footlight-calendar-api/issues/1001)

copied over by Caitlin attn: @SyamBabu-M 
When I create an EVENT and immediately publish, the wrong message appears TWICE (it says I successfully saved as draft).

![Image](https://github.com/user-attachments/assets/51ad21ae-5296-40fc-891f-cd6c30650452)

This doesn't happen if I save as draft first, then go back into an event, add missing data and publish. Instead, I get two messages, one that says I succcessfully update and anotehr that I successfully published.

![Image](https://github.com/user-attachments/assets/03b63f04-6932-480f-bb74-7f0c6137d9f9)

**Comment by troughc** [comment]
@SyamBabu-M agreed that you can take this one up next.

**Comment by SyamBabu-M** [comment]
Note: Validation message for the editor is not working. This is a bug closely related to this issue.

**Comment by SyamBabu-M** [comment]
@troughc This can be tested in staging.
