### ISSUE TITLE
minimum word count for description should not be mandatory

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1308]
During testing, I noticed that in ArtscultureNB, the description field is demanding a minimum of 25 words. There should be no minimum word count of 25 words for any sites except Tout Culture (tout culture set a minimum word count for description and is a special case). This should NOT be the default setting for future new cms listings (calendars) as the Admin cannot set a minimum word count for Descriptions in their general settings. 

![Image](https://github.com/user-attachments/assets/68d05c70-e6f1-4fa2-addd-f76fc115fc4f)

![Image](https://github.com/user-attachments/assets/2e772c91-afb1-49c2-bc1d-3e1121b5d5d7)

Description field is either mandatory or not. 

Can you please check for all recently added sites. 

cc @tammy-culture @sahalali

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil When the description is required and the minimum word count is 1 ,don't show the helper text.

**Comment by AbhishekPAnil** [comment]
@troughc I think the above mentioned enhancement is already implemented.You can check this in production.

**Comment by troughc** [comment]
Tested in production: PASSED
Thanks @AbhishekPAnil 
NOTE: in STAGING, for ArtsCultureNB it isn't working (there is a minimum word count required). However, it is correct in PRODUCTION.
Maybe it should also be corrected in staging?

cc @sahalali
