### ISSUE TITLE
mismatched display of field names

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1309]
copied over from https://github.com/culturecreates/footlight-calendar-api/issues/1001

For Signe Laval, notice that in Mandatory fields you see "Event Type" and "type d'evenement" in both the english and french UIs. In the case of Signe Laval, "Event type" was renamed "Discipline" in the form (Maude from Signe Laval renamed this field - Event type was the default name). 
this is also the case for District/Region/Quartier. It is not the same name in Mandatory fields as it is in Taxonomies and in the forms/quick create menus.

Expected behaviour is that the names/labels of the fields in Mandatory fields update to match the labels in the forms when an admin updates it. This probably can only happen with taxonomy fields.

**Comment by troughc** [comment]
@SyamBabu-M @AbhishekPAnil I am assigning this to myself because there are other minor changes I want made in Mandatory fields. For example, I want to make a rule on how groups of parameters are labeled - like we did for event type dropdowns.

**Comment by troughc** [comment]
@SyamBabu-M @AbhishekPAnil I created a separate issue #1348 for grouping parameters. 
Let's use this issue to fix the labeling problem mentioned in the description. I will assign to @AbhishekPAnil since he is working on 1348.

**Comment by SyamBabu-M** [comment]
@dev-aravind @SuhailAliyar This requires backend changes. Please look into it.

**Comment by troughc** [comment]
Tested
- existing fields (disciplines and quartier) look correct: PASSED
- Renamed taxonomy "Quartier" to Quartier 5 and checked in mandatory fields: PASSED
- Created a new custom (dynamic) taxonomy and checked name in mandatory fields: PASSED
- created a new **standard** taxonomy that maps to Discipline and renamed it Discipline 2 in Signe Laval [here](https://staging.cms.footlight.io/dashboard/63457978637093005071a053/settings). **DID NOT PASS**
It doesn't appear correctly in the mandatory fields (see screenshots). Instead the name is still the original standard name (Discipline)

### Name in Taxonomy form:
![Image](https://github.com/user-attachments/assets/e521dd60-6adb-4e2a-8962-73c7587066ee)

### Name in Mandatory fields
As you can see it kept the original name
![Image](https://github.com/user-attachments/assets/b3556036-b0d4-4f9a-83d1-39c117a1386a)

**Comment by dev-aravind** [comment]
@SyamBabu-M This is a front-end error, when @troughc created the taxonomy, even though Signe-Laval is a French calendar, an English taxonomy name was also set.

@troughc When you go to the mandatory fields section, you see the English name of the taxonomy because your user language is set to English, if you set it to French, you should see the below page:

![Image](https://github.com/user-attachments/assets/89fbf37b-76bf-40dd-9a4e-be4e24a58ec2)

I will be working on a migration to fix the existing taxonomies.

**Comment by SyamBabu-M** [comment]
@dev-aravind @troughc  I will look into this.

**Comment by troughc** [comment]
Guidance: you should only save what you can edit. What this means is:
- if you have a single language listing (calendar), like DICI and Signe Laval, you should only save the terms and the names of the taxonomy in that language. So, in this case, do not save / create a taxonomy with an english name. Only create/save the taxonomy with a french name.
- this means that the french name will appear in the english UI - in mandatory fields and everywhere else.

**Comment by dev-aravind** [comment]
@sahalali This can be deployed to production along with the front end changes.
