### ISSUE TITLE
missing mandatory fields do not always have red message indicating what is missing when saving

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1319]
When saving a person or organization (and maybe for places) the red message is not displayed under images when the image is mandatory. The message appears at the top:
![Image](https://github.com/user-attachments/assets/de31968d-96f8-489d-bff2-9935943ae22a)

It should be the same as Events (same text in red), here is an example in English:
![Image](https://github.com/user-attachments/assets/7ad0dfee-b749-4a35-be9f-a03caa962c30)

**Comment by AbhishekPAnil** [comment]
![Image](https://github.com/user-attachments/assets/291301fa-ebbd-431c-bbb5-640226bc7be1)
![Image](https://github.com/user-attachments/assets/452d9c59-5d8b-4030-8091-4ebfc0120ec9)
![Image](https://github.com/user-attachments/assets/1009790c-6717-4431-962a-502fcce8e761)
I see that some other fields ,when added as mandatory doesn't show the validation message.I am handling this in this issue.

**Comment by troughc** [comment]
note from @AbhishekPAnil: this seems to only be happening in data-centric forms.

**Comment by troughc** [comment]
Tested: PASSED
