### ISSUE TITLE
Assign Featured event in new CMS

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#132]
Only in event listing page as per Figma (full vision), not needed in event detail.

**Comment by saumier** [comment]
@troughc I have a UX question: should a guest who cannot edit "featured event" property still see the star on the thumbnails, or should the front-end hide "featured" event start from everyone except admins?

**Comment by saumier** [comment]
@AbhishekPAnil I added a place holder estimate of 8 hrs. Please add a note and change the estimate when you have discussed with Suhail.

**Comment by troughc** [comment]
> @troughc I have a UX question: should a guest who cannot edit "featured event" property still see the star on the thumbnails, or should the front-end hide "featured" event start from everyone except admins?

Yes, hide the star on the thumbnails from everyone else. Only the Admin can see that.

**Comment by AbhishekPAnil** [comment]
@saumier @troughc Have discussed it with @SuhailAliyar and we think it would be good to have featured event option in the event details page.We discuss this during our stand up stand up meeting.

**Comment by saumier** [comment]
@AbhishekPAnil @troughc Please proceed with adding the "featured event" on detail page. We will not need to edit the "featured event" in the event list page.  We also want the "featured event" star to appear only for Admins. @SuhailAliyar will be able to remove the flag if the user is not admin role.

**Comment by troughc** [comment]
@AbhishekPAnil here are some ideas to get us started:
I suggest we use the checkbox component. It should be placed close to the publish button since it is a feature specifically related to publishing rather than event data.
The label is: 
English: Featured event
French: to be updated (Événement à l'honneur, Événement en vedette...)

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
Tested in Chrome: PASSED
