### ISSUE TITLE
Listing page title doesn't match UI language choice

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1324]
The titles in the listing pages for Events, People, Places, Orgs do not update to match the UI language choice on bilingual (multilingual) calendars. Instead, they always display the first choice selected from the language dropdown in settings.
Examples: 
- Tout Culture listings always display french titles (even when I am using English UI)
- ArtscultureNB always displays English titles (even when I am using a French UI)

Screenshots
### English UI, French titles
![Image](https://github.com/user-attachments/assets/1eca9670-f9cf-4675-897b-bdbece8ba68a)
This is because the French language is the default (first) language. In the List view, I should see the title displayed at top of this page.
![Image](https://github.com/user-attachments/assets/f2a12c74-8a1d-4c56-8507-7defa8d2bb12)

### French UI, English titles
![Image](https://github.com/user-attachments/assets/c696cb02-1725-48fb-9409-a5e745ce3d92)

### Expected behaviour
Titles in list view match language choice for the UI regardless of what default (first) language is selected in the General settings | Languages.

**Comment by SyamBabu-M** [comment]
@troughc This can be tested in production.

**Comment by troughc** [comment]
Perfect, thank you @SyamBabu-M @AbhishekPAnil !
