### ISSUE TITLE
[Live - Staging] Unable to select containedInPlace or containAPlace: Uncaught TypeError: t.apply is not a function

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1328]
When quick creating or modifying a place, selecting in containInPlace triggers an error. Result: no selection is made

The error is: Uncaught TypeError: t.apply is not a function

![cypress-place-containedInPlace select exception](https://github.com/user-attachments/assets/b4799abe-7168-4a10-a9b5-4d0384aa68dc)

**Comment by kmdvs** [comment]
Same for containedInPlace or containsAPlace

**Comment by troughc** [comment]
@AbhishekPAnil please remind me where to test this? Production or staging or either? 
My understanding is that, to test, I do two things: 
1. Add a containedIn place to a place and save.
2. Add a contains place and save.

Thanks

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil please remind me where to test this? Production or staging or either? 
> My understanding is that, to test, I do two things: 
> 1. Add a containedIn place to a place and save.
> 2. Add a contains place and save.
> 
> Thanks

You can test in the pr link

**Comment by troughc** [comment]
Tested: PASSED

**Comment by troughc** [comment]
@kmdvs do you want to take a look before we deploy?

**Comment by kmdvs** [comment]
Yes, passed :)

**Comment by AbhishekPAnil** [comment]
Deployed to production
