### ISSUE TITLE
Question: Can we aggregate the NAC Artsdata source into the NAC Production Calendar?

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1339]
@saumier Do you think the following ([http://kg.artsdata.ca/culture-creates/artsdata-planet-nac/nac-events](https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-nac%2Fnac-events))  is ready to be aggregated into the NAC Production Calendar?

**Comment by saumier** [comment]
@tammy-culture I loaded 10 events into NAC Osaka. That should be enough for placeholder events to Verb Interactive can play around with the widget. I also have a demo yesterday to Dan and Jason.
