### ISSUE TITLE
Mandatory settings: Implement Parent term - Child term rule

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1348]
Also see related issue #1309 

Context
In mandatory settings, most parameters (Fields) are listed by label name. However, some labels are not obviously associated with a particular section. This is the case for Contact parameters. 

To make it easier for users to choose what to make mandatory, let's follow the [parent term - child term approach we used for event types](https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=6869-127869&t=DrJiVWotf4OT0wl3-1). This would not affect the display of labels anywhere else.

**Action:** We will start with Contacts only. Contact fields appear in Events and Organizations.
- prepend the name of the field with the name of the section.
Examples in English: 
"Contact title" would be displayed as "Contact - Contact title"
"Website" would be displayed as "Contact - Website"

**Additional change request:** please reorder the mandatory fields sections to match the left nav (move Place after Event)

Outstanding design question that needs further thought:
Currently we are implementing this approach for Contact fields, but it may also be used for Address fields in Places. This needs further thought.

**Comment by troughc** [comment]
@AbhishekPAnil we can discuss this next week. No action required yet.

**Comment by troughc** [comment]
@AbhishekPAnil as discussed we will start with Contacts only. 
We will not change how we handle/dislplay Address fields in the Mandatory fields section. I will add this decision to the description at the top of this issue. Thanks!

**Comment by SyamBabu-M** [comment]
> **Additional change request:** please reorder the mandatory fields sections to match the left nav (move Place after Event)

@dev-aravind I believe rearranging the forms array in response of [get calendar API](https://staging.api.cms.footlight.io/api/#/Calendar%20Metadata%20APIs/CalendarController_getCalendarMetadataById) will be the best way to approach this. How should we proceed on this?

**Comment by dev-aravind** [comment]
@SyamBabu-M The forms are now rearranged. Please test this.

**Comment by troughc** [comment]
Tested: 
Events section: PASSED 
Still to do: Organization section - this also has contact fields:
in mandatory fields
![Image](https://github.com/user-attachments/assets/2b11ea46-f276-46eb-aae5-d1b757efe551)

In organiziaitons form
![Image](https://github.com/user-attachments/assets/3f8fb5bd-c5ef-42d4-8ca6-8fab3c857b66)
