### ISSUE TITLE
Images for people/person: Display the Image (headshot) of a person (if there is one) if linked to from an Event or other entity. 

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1353]
With Organizations, the Organization Logo image is displayed in the top right of the read only page. The logo is also displayed in the list view AND in an event when an organization is selected. This helps users identify the organization at a glance.
With People, the (main) image is displayed in the top right corner (the justification is that people generally don't have logos, they usually have headshots), and in the list view. This image helps users identify the person at a glance.

For example, see [this person, Adam Johnson](https://cms.footlight.io/dashboard/63457978637093005071a053/people/65b92c258468f400648408da)

Notice the image in the top right - this is his headshot. The same image is displayed in the list view; however, it is not currently displayed in Events (or anywhere else it the person enitity could be linked to)

**Enhancement request:** Display the main image/headshot in the Person component that is used in Events and elsewhere.

This is related to support issue: https://github.com/culturecreates/tech-support-tickets/issues/90

**Comment by AbhishekPAnil** [comment]
Frontend tasks:
1.Add the image to the list component across search dropdown and selected item.

**Comment by troughc** [comment]
@AbhishekPAnil I was thinking that @SyamBabu-M could take this one on?

**Comment by troughc** [comment]
@SyamBabu-M maybe also consider picking up this one.

**Comment by SyamBabu-M** [comment]
@dev-aravind Currently the image is not returned in the response. Please add this to the API response. Thank you!

**Comment by dev-aravind** [comment]
@troughc The image is now visible in the search tab. Please review this and let me know if you need any more changes.

**Comment by troughc** [comment]
Tested in staging with [this person, Adam Johnson](https://cms.footlight.io/dashboard/63457978637093005071a053/people/65b92c258468f400648408da)

PASSED
