### ISSUE TITLE
Can't save Person when modifying even if all mandatory fields filled (including image)

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1354]
On Staging, trying to save a Person fails even when an image is given, when modifying

![savePerson](https://github.com/user-attachments/assets/1f739d84-377d-449a-b998-034ca6c1adf8)

Create New functions... And saves... It is the modification that fails... 

Repro steps:
- Create a new Person with mandatory fields
- Save Person
- Edit to Modify
- Without any changes, try to Save again
- Error message: "This person needs more information before it can be saved."

**Comment by kmdvs** [comment]
Is the error that image is now mandatory?

**Comment by kmdvs** [comment]
This stops Cypress tests from working, in the Modify Person section

**Comment by troughc** [comment]
Is this is the same as #1319 or is it something else @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil This is dependent on #1319

**Comment by kmdvs** [comment]
The same happens in Organizations... A fully filled Org cannot be modified.

**Comment by troughc** [comment]
@kmdvs do you want to test this one? Please assign back to me after. :)

**Comment by kmdvs** [comment]
@troughc Yes, it works for me :)

**Comment by troughc** [comment]
@kmdvs thank you. :) I am testing too. 

Tested: PASSED
