### ISSUE TITLE
Corrupt data in 4, 3, 2, 1... Santé event

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1362]
I don't know what is causing this issue. After some investigation with Gregory we think that a migration script is needed to update old events. The reason is, we refreshed another event (re-saved) and it updated to reflect the correct data everywhere).

This event should be a multiple date event with (20 occurrences), as it is on the[ client site](https://signelaval.com/fr/evenements/64415af5d6f5e7006431e633/exposition-permanente-4-3-2-1-sante)

**TEST CASE:** To check that the migration script is correct, make sure this event is a multiple date event with 20 occurences.

[this event](https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/64415af5d6f5e7006431e633) named "Exposition permanente « 4, 3, 2, 1... Santé! »" in Signe Laval has not been refreshed and:
- the date type in the list view and the read only view looks like a mulitple date event; 
- the date type in the edit form looks like a date range event;
- When I look at the page developer mode / Preview, it looks like there are subevents. 

Here are screenshots
### List view of event with OCCURENCES
![Image](https://github.com/user-attachments/assets/e1db9d13-85b4-42ff-9c1c-c9a1495a3221)
### Read-only view of event's date type (multiple dates - CUSTOM)
![Image](https://github.com/user-attachments/assets/d689e687-a3f9-4976-bd46-002e4699c26c)
### Edit form view of event  as DATE RANGE (THIS IS WRONG)
![Image](https://github.com/user-attachments/assets/d3c07f43-e5f9-48c3-a3a0-9502d2c48d3d)

**Comment by troughc** [comment]
@AbhishekPAnil @sahalali sorry the above event looks the same to me. I don't see a change. Let's revisit next time we meet.

**Comment by AbhishekPAnil** [comment]
@troughc Did you check this in staging or production?

**Comment by troughc** [comment]
I checked in staging and in the PR. Here are the issues:

List view both look like multiple dates:
![Image](https://github.com/user-attachments/assets/7c819ec5-dbb4-4c93-a367-db8fd68470bd)

Read only in staging (multi-date):
![Image](https://github.com/user-attachments/assets/356ed579-6e57-4843-a361-add3f6e9399a)

Read only in PR (date range):
![Image](https://github.com/user-attachments/assets/2b1f4d4b-aade-4fa6-9d86-036371e4990e)

Edit in staging (date range):
![Image](https://github.com/user-attachments/assets/1ee1b184-515a-4d65-9c0b-28febc6f1307)


Edit form in PR (date range):
![Image](https://github.com/user-attachments/assets/0dd5bba0-d8a8-4e2a-b997-200dd8b03da0)

should be multi-date (custom).

**Comment by AbhishekPAnil** [comment]
Bug report : 
You are right ,the staging was showing the corrupt data as well.It was happening because the data in staging was replaced by the production data accidentally after it was fixed.

This is now updated in staging.Please check and let me know if you face anymore issues.

**Comment by troughc** [comment]
@AbhishekPAnil it looks okay to me now (looking at the one event). PASSED
