### ISSUE TITLE
Overnight events

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1363]
Changes needed for this issue (Copied from comment below). Please be sure to review the story in the description and subsequent comments to make sure the goal is achieved. :)

- [x] Update the UI to display +1 day or +1 jour.
- [ ] **TBD: may not be relevant:** '+1' will appear even if the event is a multi-day event completed within 24 hours from the start time. 
- [x] Fix the issue in the UI: When creating a single-day event, the end date time should not be set as the next calendar date.
- [x] In the list view, the date that is display should only be the date that correlates to the start time.
- [ ] Searching and listing using admin-api and open-api will work as expected. However, one round of testing would be nice.

**Expected behaviour:** when a user creates a single day event, and then adds an end time that is after midnight (local time), the plus one appears in the end time field. The event is still treated as a single date event. After saving, the event appears in the list view with a single date (the date of the start time, the date selected by the user in the date field).

NOTE/Question for @sahalali : multi-date events (date range events) do not support adding times so I am not sure this will ever happen in the front end display.

# Story

Some single date events go past midnight / overnight and a CMS user wants to include a start time and an **end time that is on the next day.** 
Two examples are 'nuit blanche' in [Montreal](https://macm.org/en/activities/nuit-blanche-at-the-mac/) and 'nuit blanche' in [Toronto](https://www.toronto.ca/explore-enjoy/festivals-events/nuitblanche/)

For these special-case events, the user enters a start time on the selected date of the event and an end time that is on the next date. 

### Other products
For reference here is a loosely related feature in the **ICS Calendar** plugin for Wordpress related to configuring how overnight events are displayed in a calendar. 
https://icscalendar.com/icsdocs/#extendmultiday

# Solution

**Where could a user enter these overnight events?** In Single date events and Multiple dates events.
- The most common case is to enter it in the Single date section of the UI. Here you can add a single date, a start time and and end time.
- The other case would be to enter it in the Multiple dates section of the UI. you have several ways to set this up: you can create a recurring daily or weekly event series, where start time and the optional end time is the same for every event; you can create a custom event series where you have complete flexiblity over start times and end times.

### Enhancement/Expected behaviour: 
- **CMS UI:** Explicitly display in the UI that the end time in on the next day 
- **Client site:** Make sure that the data that is shared (via Footlight Open API) to the client site is correct (end time is on the next day)
- **CMS and Client site Search results** include these single date events on both dates (the date it starts and the date it ends). For example, if an event starts Saturday night at 10PM and ends Sunday morning at 6AM, searches of Saturday's date include this event and searches of Sunday's date include this event.
- **Listing Widget** Explicitly display in the UI that the end time in on the next day

### Design change
We need to show the user in the CMS that their end time is the next day.
Flights and bus trips have a standard way of displaying this. They add +1 to the end time (screenshots below).

Change request: append "+1 day" in English and "+1 jour" in French to the end time in superscript. Do this in the event form and in the read only pages.

**Flight example**
![Image](https://github.com/user-attachments/assets/6bcb581d-007b-457f-b8cf-26391a6fab66)

**bus example**
![Image](https://github.com/user-attachments/assets/3d1fb96a-cf42-4389-9a7c-26d393b4ee48)

**Comment by troughc** [comment]
@saumier please review this story. 
@SyamBabu-M FYI here is the user story for overnight events. Gregory will take a look before we are ready to schedule this.

**Comment by saumier** [comment]
@troughc I made a few small changes to the description (updated the title to "CMS and Client site Search results" and added "Listing-widget".  It looks good. However, I need some clarifications around the expected behaviour for search.  I have listed some questions to help us figure out what the expected behaviour should be. Once we figure this out, it should be added back to the top of this issue into the main description.

Use cases related to search:

Sample data:
Event 1 - starts 20 ET, ends 22 ET (17-19 PT)
Event 2 - starts 22 ET, ends 1 ET (19-22 PT)
Event 3 - starts at 1 ET, ends at 6 ET (22-3 PT)

Event 4 Vancouver - starts 20 PT, ends 22 PT (23-2 ET)
Event 5 Vancouver - starts 22 PT, ends 1 PT (1-4 ET)
Event 6 Vancouver - starts at 1 PT, ends at 6 PT (4-9 ET)

1. A user in Montreal, searches for events for Sunday, Sep 29 (on Client website). 
Expected behaviour:  Events 1,2,4,5 ?

2. A user in Montreal, searches for events happening Monday, Sep 30 (on Client website)
Expected behaviour: Events 2,3,5,6 ?

3. A user in Vancouver, searches for events on Sunday, Sep 29 (on Client website)
Expected behaviour:  Events 1,2,4,5 ?

4. A user in Vancouver, search for events on Monday, Sep 30 (on Client website)
Expected behaviour: Events 2,3,5,6 ?

**Comment by troughc** [comment]
@saumier regarding what a user would see; here is my opinion. 
The timezone of the website/location of the event is what matters. Whether the person is in Vancouver or Montreal when searching, if they are looking for an event in Montreal (that is in the future for them), and the start time falls within the time they selected  in the calendar (in Montreal time) search should display the event. 

For your example (Event 3) of an event that starts at 1AM ET on September 30, and your scenario 2, where a person searches for Monday September 30, the event should show up because it is on Monday and no time is specified.

If a person is looking for an event TODAY (same day - scenario 4), but the event already passed (it happened earlier than the time they are searching TODAY), then, ideally, it shouldn't be included in the search results. If it is happening very soon, we could add a warning 'happening soon'


People generally expect the timezone to match a local timezone. For example, when you look for a flight, you see the time of departure in the local time of the departure city and the time of arrival in the local time of the arrival city. Flights also display number of hours of flight, but we don't need that. 
For example, i am in MOntreal looking at flights between montreal and london. Where I search from doesn't matter.
### My search Montreal - London (departure time in montreal, arrival time in london)
![Image](https://github.com/user-attachments/assets/2ebadd9c-6e85-45e4-8898-949b346f5325)

### My search London - Montreal (departure time in london, arrival time in montreal)
![Image](https://github.com/user-attachments/assets/a8a64e21-74ed-43fa-b71a-db5f68679409)

**Comment by saumier** [comment]
@troughc If I understand, you agree with all the expected behaviour I listed above. You also add that the display should always show the event in the time zone of where the event happens.

My use cases above should be analyzed by the team, and a solution designed.  This is much bigger than displaying the + 1 for overnight events.

**Comment by sahalali** [comment]
@AbhishekPAnil Can you look into the above comment and revert with estimates?

**Comment by AbhishekPAnil** [comment]
Frontend tasks : 5h

1. Modifythe display in the event listing page to satisfy overnight events.
2. Api integration for overnight events in listing page.
3. Modify the display in the read only page to satisfy overnight events.
4. Api integration for overnight event in read only page.

**Comment by troughc** [comment]
> 1. UPDATE: WE DON'T NEED THIS FUNCTIONALITY AS IT IS NOT THE CURRENT PRACTICE IN THE ARTS SECTOR.  Add a tag "Happening soon" if the event in the list is occurring in the next 2 hours. [@troughc](https://github.com/troughc), please suggest a time frame if not specified:
> 2. Update the UI to display +1 day or +1 jour.
>    [@saumier](https://github.com/saumier) '+1' will appear even if the event is a multi-day event completed within 24 hours from the start time.
> 3. Fix the issue in the UI: When creating a single-day event, the end date time should not be set as the next calendar date.
> 4. In the list view, the date that is display should only be the day of the start time.
> 5. Searching and listing using admin-api and open-api will work as expected. However, one round of testing would be nice.

@sahalali I have updated this "to do" list and have copied it into the Description at the top. I have one question regarding your additional comment:
_[@saumier](https://github.com/saumier) '+1' will appear even if the event is a multi-day event completed within 24 hours from the start time_
Since Multi-date events (date range events) do not support adding times in the FE of the CMS I am not sure this will ever happen. Or is this for BE work?
thanks.

**Comment by AbhishekPAnil** [comment]
@troughc 
Please see below the "+1" being added to the edit and read only pages:
![Image](https://github.com/user-attachments/assets/79c6915b-6fff-4d37-90f5-647fdca74365)
![Image](https://github.com/user-attachments/assets/a7b1db5e-b06c-4ed6-9bb1-8b521c8cac9f)

**Comment by AbhishekPAnil** [comment]
cc @
Actual time take to complete : 10H
Reason :

-  Had to remove the changes in the listing page and add the changes in the edit page.
- Rewrite the logic to display +1 day in read only page.

**Comment by AbhishekPAnil** [comment]
cc @troughc @AbhishekPAnil 
Searching and listing using admin-api and open-api will work as expected. However, one round of testing would be nice.
- admin-api will be tested by @AbhishekPAnil 
- open-api can be test in the widget.

**Comment by AbhishekPAnil** [comment]
@troughc You can test this in the [PR](https://pr-1497.dla06mbe0wyl7.amplifyapp.com)https://pr-1497.dla06mbe0wyl7.amplifyapp.com/ link

**Comment by AbhishekPAnil** [comment]
Tested search in admin api:
admin-api is working with the use cases provided.

**Comment by troughc** [comment]
Tested on Chrome in Tout Culture, this event: https://pr-1497.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/6750311adcd6ef00a4211f9d

The display in the CMS: PASSED
Widget shows it as a two date event rather than a single date event. Please see screenshots of test event below.

### LIST VIEW - looks good

![Image](https://github.com/user-attachments/assets/028fddc7-d79d-4a80-bcc6-ae030e21b969)

### READ-ONLY VIEW - looks good
![Image](https://github.com/user-attachments/assets/f201cb9c-03ce-4c57-954c-dd36d019669d)

### WIDGET VIEW - 2 days instead of single date (the event below my event (Jacques Falquet) is what i would expect to see in terms of date-time)
![Image](https://github.com/user-attachments/assets/3b421f15-87e0-44d6-9f65-092bc0321986)

**Comment by AbhishekPAnil** [comment]
> WIDGET VIEW - 2 days instead of single date (the event below my event (Jacques Falquet) is what i would expect to see in terms of date-time)

I think this change must be done in the widget side.Correct me if I am wrong @SyamBabu-M

**Comment by SyamBabu-M** [comment]
@AbhishekPAnil @troughc Currently, the widget does not consider overnight events. It just shows the data it receives from the backend.

**Comment by troughc** [comment]
okay, let's deploy this and create a separate issue to do the work on the widget side.
