### ISSUE TITLE
Cannot save org/person: red text displayed and popup message appears when it should not

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1379]
This may be related to the recent deployment of #1374 ?
Or maybe it will be fixed with #1354  (which I just tested). **If so, we can close this issue.** 
NOTE: in 1354, I also tested with Organization (Not just person) and I had no issue. :)

High level problem: I am blocked from updating/saving an organization and person (maybe others as well) because of a popup message and missing fields that are not missing:
- Red text is appearing below a (mandatory) image field after it has been added and saved to a new organization.
- Popup is opening and cannot be closed.

Steps to reproduce:
1. create an organization with all the fields and save. For example, I created [this one in the Artbi](https://cms.footlight.io/dashboard/64873209371b8f0064913ad0/organizations/add-organization?id=66fc231ca7faf200649d611d)
NOTE: also see [this person for similar behaviour](https://cms.footlight.io/dashboard/64873209371b8f0064913ad0/people/add-person?id=66e1b22220b0270064b11618)
2. Open the edit page for the organization/person and then click Save.
3. a popup appears and the red text is displayed under the image. i cannot close the popup with the x - it is still there event when I go back to the list view.

![Image](https://github.com/user-attachments/assets/16bceaeb-acae-4310-8a2d-a8defc1418ec)

![Image](https://github.com/user-attachments/assets/4ff34be0-32d6-414f-ae10-688369cde5f5)

Expected behaviour: no red text, no popup when fields are filled.  Again this may be a duplicate of #1354

**Comment by AbhishekPAnil** [comment]
I was able to save the organization with the recent fix #1354 .Could you please verify this @troughc .
