### ISSUE TITLE
event gets buggy when remove content from one language in bilingual site

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1380]
event that was published cannot have language content removed without issues.
Please see [this event](https://pr-1378.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/66e2922e20b0270064b1b3fa)

This event started as a draft. I published it, and then went back into it and removed the english language title and description. when I tried to save it as a published event but I could not (error that mandatory fields were missing). So I saved it as a draft event. 
I went back in and the english language title and description fields were still empty.

Expected behaviour:
- can publish an event that doesn't have content in all languages that was created by me in all fields 
- I remove it)
- I can remove content from a language field if I want and still save it/publish it. The content might be transferred from the fallback language (next point). Question: what would I see next time I open the published event - language literal.
- language literal content should be transferred to empty field?
-  when I reopen the event the language literal content should be back.

We need to revisit the logic of how language literals work.

**Comment by troughc** [comment]
@SyamBabu-M something isn't working for me, let's look together monday if necessary.
For [this event ](https://pr-1388.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/660ebdaa1406060064633245)(and others)
I removed the Japanese field then repeated the steps and still got the error. In addition, the different screens don't line up:
Read only view shows content in the field for japanese:
![Image](https://github.com/user-attachments/assets/fba1f02a-cbd6-4309-81d2-4dd0e9cb5217)
Edit form shows it empty in it:
![Image](https://github.com/user-attachments/assets/4692c54a-e66d-4234-8d0c-b8534b60e565)

Then when I try to save, i get the error.

**Comment by troughc** [comment]
when try to create a new event and click save (as draft) an error is thrown in the console.

**Comment by troughc** [comment]
Tested: PASSED 
@SyamBabu-M just in case - how do I check to see if an error was thrown in the console? I didn't see one but maybe i need to test something specific?

**Comment by SyamBabu-M** [comment]
@troughc The error we were facing earlier was thrown during the payload generation(the function that create data that needs to be send to backend). This can be seen in the console.
To open the console press cmd + option + j
find the console and open the errors section from the sidebar. You can find all the warnings and errors there.
If a critical error is thrown, the app will redirect to the error page by itself.
![Image](https://github.com/user-attachments/assets/23f3750a-28a5-4f7f-89de-b3a616971dff)
