### ISSUE TITLE
Bulk download 2 separate files for ArtscultureNB for PLACES and ORGANIZATIONS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1387]
Bulk download 2 separate files for ArtscultureNB, one for PLACES and another for ORGANIZATIONS into a Google Sheet file so the client can fill in the missing French translations and then upload into their Production CMS.

As they require a bilingual calendar, client has noticed that not all their addresses or names of PLACES and ORGANIZATIONS are appropriately translated.

**Comment by sahalali** [comment]
@tammy-culture Please find the Google sheet with the downloaded organizations and places here: https://docs.google.com/spreadsheets/d/1BXrFZIdE09s7Z_ZQ2bCdB4EtLFOxfppI0jmynyV9buE/edit?gid=1132108872#gid=1132108872

**Comment by tammy-culture** [comment]
I am now waiting for the client ArtscultureNB to make the necessary changes to the French translations and once done, we will upload Places and Organizations into their production CMS.

**Comment by tammy-culture** [comment]
Hi @sahalali ArtscultureNB have made their updates in the following document: https://docs.google.com/spreadsheets/d/1BXrFZIdE09s7Z_ZQ2bCdB4EtLFOxfppI0jmynyV9buE/edit?usp=sharing

The client highlighted in yellow the columns where they made changes: addresses (English/French); disambiguating descriptions (English/French), municiplality names, places and organizations.

Question: When this document gets re-uploaded into the ArtscultureNB Produciton CMS will the curent links remain?

**Comment by sahalali** [comment]
@tammy-culture I've reuploaded the data to the ArtsCultureNB calendar.
