### ISSUE TITLE
Add sort by "Date modified"

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1395]
reference user story: https://github.com/culturecreates/footlight-app/issues/1371

Allow users to sort lists by the date an entity was last modified. This may require changes in both the FE and BE.

In the FE, the user should be able to use a date something was modified to order the list according to what was most recently updated (or least recently updated). 
To do this they need an option in the Sort dropdown:
ENGLISH: Add 'Date modified' after 'Date created' in dropdowns
FRENCH: Add 'Date de modification' after 'Date de création' in dropdowns
This means it appears above "Event date" in Events list

English example of current dropdowns
Events sort dropdown
![Image](https://github.com/user-attachments/assets/354fca31-f842-477b-9400-61e28a4edbd9)

Places sort dropdown
![Image](https://github.com/user-attachments/assets/e6f5bb71-de47-4474-976a-849d2dd0d9df)

FYI: @saumier

**Comment by sahalali** [comment]
This will not require backend changes. Use the sort value as "asc(metadata.modifiedAt)" or "desc(metadata.modifiedAt)" to sort by modified date.

@AbhishekPAnil Could you please give an estimate for the frontend work?

**Comment by AbhishekPAnil** [comment]
Frontend tasks -  1h
1.Add  date modified option to the array with respective integration keyword.

**Comment by troughc** [comment]
fixed a 2 Clear button issue that happens when you change the sort filter choice to anything other than the default, and changing the descending / ascending order.

**Comment by AbhishekPAnil** [comment]
> fixed a 2 Clear button issue that happens when you change the sort filter choice to anything other than the default, and changing the descending / ascending order.

Refer this :
![Image](https://github.com/user-attachments/assets/13c51e51-4f63-4ae3-a5e7-2de20dea3c0a)

**Comment by troughc** [comment]
Tested:PASSED
