### ISSUE TITLE
Simplest Draft Event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#14]
As an admin or editor, I can create a simple event with title (en/fr), a single date and then save as draft.

To make it as easy as possible to save as draft, ONLY **title** (in one language) and a **start date** is required. Error messages are displayed if the required fields are missing.

## Tasks
- [ ] https://github.com/culturecreates/footlight-admin/issues/68

## Test Cases
1. Create a new event with title, date from a real Tout Culture event like:  https://toutculture.ca/evenements/lise-dion-1/21885?date=2023-01-23_15-00-00. 
3. Save a draft of the event
4. Check that it is visible in the event list screen as a draft
5. Make a change in the event and save it
6. Check that either a french title or an english title is needed.
7. Take out both titles, and check that the error message is displayed.
8. Take out date, and check that the error message is displayed.
9. Delete the event

**Comment by saumier** [comment]
@AbhishekPAnil Is this a good size User Story for you to estimate, develop and do a PR to the develop branch?  I would like us to make PRs related to User Story so we can review and test during a sprint. Your feedback is appreciated.

**Comment by saumier** [comment]
@AbhishekPAnil Here is the demo I reviewed with Caitlin. I hope it helps answer all UI/UX questions. https://tnth7q.csb.app/

**Comment by troughc** [comment]
Tested and found a couple issues @AbhishekPAnil 
I tested as both admin and as a guest
- I can't save without adding a description - (I cannot add a title and date only).
- Also, small thing, but once I enter a date in the date field (for a single event), I can't remove it (i.e. return it to a blank state). I can only change it.
