### ISSUE TITLE
addPlace triggers Oops page

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1415]
I got a few times the Oops page when trying to modify a place

A number of errors in the console: 
![2024-10-23 02_59_10-Greenshot](https://github.com/user-attachments/assets/63138a18-3296-4ccf-94b6-3e4a4c65559e)

Repro:
- Go to Places
- New Place
- Search for CMS-R
- choose the 2nd ('New French Name or Title')
- Oops page

**Comment by AbhishekPAnil** [comment]
Bug report :
The issue happened with the introduction of new feature to display maps in the create place page #1294 .Some place didn't have coordinates ,hence the map was throwing an error.I have handled this in the frontend.
The fix is now updated in staging.

**Comment by troughc** [comment]
@kmdvs we are curious, how did you discover this bug? Was it found by using the regression test?
cc @saumier @dev-aravind

**Comment by troughc** [comment]
> [@troughc](https://github.com/troughc) Yes, it was discovered as I was updating the code for regression tests and I was repeatedly getting the Oops page.
> I tested it after Abhishek put a fix on staging and I didn't get the error page anymore.

FYI @saumier
