### ISSUE TITLE
Reordering taxonomy terms (bubbles) inside destination fields

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1419]
(this is related to this [support ticket](https://github.com/culturecreates/tech-support-tickets/issues/97))
How hard would it be to add functionality to reorder selected terms (from taxonomies) in fields? How much effort/time and what are the risks (if any)?

For example, to reorder these terms in the 'Discipline' field shown in the screenshot.
The idea is that a user could drag the bubbles (with terms) to reorder them. And then in the backend they would also be reordered so that they were sent from the API in the selected order. 

![Image](https://github.com/user-attachments/assets/a977fc70-8ce1-4647-a435-a2a64d57f7ba)

**Comment by AbhishekPAnil** [comment]
By default, Ant Design's TreeSelect component does not support reordering selected nodes within a multi-select field. To implement this, the component needs to be customized, likely requiring each field's value change to be managed with an individual or object-based state. While this presents a challenge, it is achievable.

UI tasks : 7-8 hrs

1. Research and Setup (30-60 minutes)
2. State Management and Customization (1-2 hours)
3. Integration with Drag-and-Drop (1-2 hours)
4. Testing (1-2 hours)

**Comment by AbhishekPAnil** [comment]
Actual time taken : 12H

**Comment by troughc** [comment]
Tested in Chrome and Safari: PASSED
@AbhishekPAnil I noticed that it's a bit wonky when you drag a bubble from one line to another line; however, it works well if you stay on the same line (reorder bubbles on the same line). That said, I think it works well enough to put it in production. Let's go for it! Thanks.

**Comment by AbhishekPAnil** [comment]
> Tested in Chrome and Safari: PASSED [@AbhishekPAnil](https://github.com/AbhishekPAnil) I noticed that it's a bit wonky when you drag a bubble from one line to another line; however, it works well if you stay on the same line (reorder bubbles on the same line). That said, I think it works well enough to put it in production. Let's go for it! Thanks.

Thanks for letting me know @troughc .I will deploy this and we can tackle the animation as an enhancement.

**Comment by troughc** [comment]
@AbhishekPAnil I also just noticed that the user isn't warned to save their changes after they reorder their taxonomy terms. Let's tackle that in a separate issue as well.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil I also just noticed that the user isn't warned to save their changes after they reorder their taxonomy terms. Let's tackle that in a separate issue as well. 

Ok,that is also considered a change, got it.
