### ISSUE TITLE
Add user access to Help

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#142]
Add access to Help (documentation) to the Username dropdown menu at top right of the UI. Different links (URLs) are used for the French and English UI

**English Help for English UI:** https://footlight.gitbook.io/footlight-cms-guide
**French Help for French UI:** https://footlight.gitbook.io/guide-footlight-cms

Below are screenshots the updated dropdown menus (Figma, Sprint 11), French and English.
Notice the Help option includes an icon.
The Help option is for Documentation (user guide) when it is ready. 
Help should open in new browser tab/window.

![Image](https://user-images.githubusercontent.com/64489312/219677080-6d220739-c1cb-4d00-a8a7-4709d4fe3143.png)

![Image](https://user-images.githubusercontent.com/64489312/219677770-c07fd4ab-9f29-4838-9c5d-82ebbbf74c32.png)

**Comment by saumier** [comment]
@troughc I think the link should open a new browser window. 

What is the URL to open?  I’m assigning back to you. Please add the URL here and assign to Abhishek. Thx.

**Comment by AbhishekPAnil** [comment]
ESTIMATE: **0.5 hrs**
 
Subtasks : 
1.Add the "HELP" text and icon to the user profile dropdown.
2.Add the functionality  on onClick to redirect to the required URL.

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
Tested in Chrome - French and English - PASSED
