### ISSUE TITLE
custom and standard fields not displayed in Mandatory fields

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1420]
2 things:
### Custom fields are not appearing in the Mandatory fields list. 
Steps to repeat:

1. create a custom taxonomy with some vocabulary for Events and save. 
2. Look in mandatory fields: the custom taxonomy is not included in the events section (no custom field is). 
3. Look in events page: the custom field is included and open in the top section.

**Expected behaviour:** Custom taxonomies should be included in mandatory fields so that the user can make them mandatory or optional. **If they are optional, they should be displayed as blue text.** 

### Languages used in the event in Tout Culture is not appearing in mandatory fields list
This one is a standard taxonomy.
Steps to repeat:

1. look in taxonomies for Tout Culture in staging, Languages used in the event is there and completed. Good.
2. Open a new event: languages used in the event is in the blue text (because it is not mandatory). Good
3. Open mandatory fields. Languages used in the event is not included in the events section.

**Expected behaviour:** Custom and standard fields should all be included in Mandatory fields. **If they are not mandatory, they should be displayed as blue clickable text** in the destination workspace (entity) Edit form.

### Screenshot of missing fields from Mandatory UI
![Image](https://github.com/user-attachments/assets/62eb01b0-df28-43d2-adfc-5851918b804b)

**Comment by troughc** [comment]
@SyamBabu-M can you please investigate this bug?

**Comment by SyamBabu-M** [comment]
@dev-aravind The taxonomy [inLanguage](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/taxonomies/add-taxonomy?id=63bc4e251c6b6c005aad54e1) is not added in the response of [getCalendatMetadata API](https://staging.api.cms.footlight.io/api/#/Calendar%20Metadata%20APIs/CalendarController_getCalendarMetadataById). 
This is the reason why it's not shown in the mandatory fields section.
I am assigning this to you to do the backend changes needed.
Please look into [#1452](https://github.com/culturecreates/footlight-app/issues/1452) also as [Recommandé par Le Pressoir](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/taxonomies/add-taxonomy?id=640f7796af65a800652da5f0) missing from UI list is related to this issue.

**Comment by dev-aravind** [comment]
@troughc @SyamBabu-M The inLanguage and discipline taxonomy were missing from the form data and the calendar creation template. It is now added and will be visible in the mandatory fields section, if created.

**Comment by troughc** [comment]
Tested in Staging: PASSED thanks
