### ISSUE TITLE
popup blocker solution

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1431]
KNOWN ISSUE: 
Many customers have popup blockers turned on in their browsers which blocks our software from working.  A real-world case happened with one of the guest users of the Signe Laval CMS.  This user had some sort of popup blocker in Safari that is blocking the popup that would allow her to save drafts. So she wasn't able to proceed and save her work. The user looked into it and was able to figure out the problem.
Case details according to user:
- Uses Safari on Mac
- browser security that blocks the opening of other windows prevented submission of her event
- To set up popup blocker setting on Safari, a user goes Websites, then the Pop-ups tab, and then selects Block and notify, or Allow. Selecting "Allow" allows the user to save a draft and submit.
Not everyone is able or willing to do this.

**How do we solve this so users do not have to 'Allow' popups?**

I conferred with Syam and learned that in the CMS, some popups are generated outside the application, some from inside. For example, the save/discard changes popup is generated from the browser (outside), activating a popup blocker and stopping the CMS from working. (and the user cannot proceed and doesn't know what happened).

Possible solution: Replace all messages that use the browser default popup with AntD popups that are generated inside the application (instead of from the browser).
@SyamBabu-M will do some research to see if this is possible and then provide an estimate.

**Comment by troughc** [comment]
Tested in chrome: PR looks good to me - the popup style has changed. However, I can't seem to block popusp so I don't feel like I can do a proper test.
@AbhishekPAnil please test as we discussed. Thank you so much! cc @SyamBabu-M

**Comment by AbhishekPAnil** [comment]
The PR looks good to me too but I am unable to reproduce the issue
@SyamBabu-M 
 Please check and revert back.
