### ISSUE TITLE
Super admin has send to review button in create event page

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1433]
![Image](https://github.com/user-attachments/assets/e575747d-177b-4099-96c5-5c2629b8358f)
Steps to reproduce :

1. Log in as a super admin.
2. Navigate to the create event page.
3. The button displays "Send to review" instead of "Publish" for the super admin, both for creating new events and editing existing ones.

Expected Behavior: The super admin should see "Publish" on the button, allowing them to publish the event directly without needing to send it for review. The functionality is correct as is; only the button text needs to be updated.

**Comment by troughc** [comment]
Tested: PASSED
