### ISSUE TITLE
Error in passing containsPlace and containedInPlace

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1438]
Create a place with all the necessary details ,make sure to add contains place and contained in place from the 'Import from Footlight' section.
Current Behaviour : The selected contains place and contained in place are not seen in the read only page and edit page for the saved place.

Expected Behaviour : The contains place and contained in place should be properly passed in payload for all the sources.
Note : This happens only for imports from footlight entities.

@AbhishekPAnil Please also check the creation of entities in the respective calendar ,from other calendars while using the imports from footlight section.

**Comment by AbhishekPAnil** [comment]
@troughc Please test this in the PR link for the expected behaviour.If everything is fine ,then please assign this back to me so that the fix can be deployed and I can check on with the additional changes required for the creation of import from footlight entities.

**Comment by troughc** [comment]
@sahalali according to our discussion today, the plan is to support adding a place to the "contained in" or "contains" fields from another footlight calendar in the same way as we do from Artsdata. Please confirm this is your understanding of what backend work is needed? I am assigning this issue to you.

cc @AbhishekPAnil

**Comment by troughc** [comment]
@sahalali @saumier here is a link to the [Guidelines for importing entities from external sources to Footlight CMS](https://docs.google.com/document/d/1tABz6n1Xh6-MMcvfUD5sYRAKwl6LJmbEbnnxFDUyUMc/edit?tab=t.0#heading=h.95lh9b7z6w2y)
cc @AbhishekPAnil

**Comment by troughc** [comment]
Oops @AbhishekPAnil I don't seem to be able to log into the PR.

**Comment by AbhishekPAnil** [comment]
@troughc You can test this in staging or in production.The changes are updated in both.

**Comment by troughc** [comment]
Tested in staging via Tout Culture and Signe Laval calendars. Seems to work as expected. PASSED.
