### ISSUE TITLE
sort events feature in CMS

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#144]
Add sort option to Search area at the top of the Events listing page.

## Test cases
- upon entry the default sort should be by event date ascending
- create a test event with an english title "A first" and french title "Z last".
- create another title "another first" and french title "z other last".
- set your UI Language to English.
- sort by event title ascending--> should sort using english titles, falling back on french title. The 2 test events should be near the top of the list "A first" and "another first".
- change the order to descending --> check that the order reversed.
- switch your UI language to French
- sort by event title ascending --> should sort using french titles, falling back on english title. The 2 test events should be near the bottom of the list "A first" and "another first".
- sort by created date ascending --> check
- sort by created date descending --> check
- sort by event date ascending --> check
- sort by event date descending --> check

![Image](https://user-images.githubusercontent.com/64489312/219501737-a6bb22ac-fbe5-46ab-a82f-193600b16023.png)

**Sorting Events options**

![Image](https://user-images.githubusercontent.com/64489312/223121878-0ccefe55-4f85-4ad1-a0ce-69c3cddbf438.png)

**Comment by saumier** [comment]
@troughc Can you please prioritize this by adding it to the To Do column at the right spot. Thx.

**Comment by troughc** [comment]
@saumier done. I am trying to group similar issues together for @AbhishekPAnil - I would like to review whether this makes sense at one of our upcoming morning meetings.

**Comment by AbhishekPAnil** [comment]
ESTIMATE **6** hrs

Subtasks 
1.Add the dropdown for sort 
2.Add the option and functionality to toggle between sort order.
3.Api integration for toggle and sort.

**Comment by AbhishekPAnil** [comment]
Completed the estimated tasks in frontend.After the respective backend support is complete ,the rest of the testing can carried out.

**Comment by saumier** [comment]
@troughc Please test this feature with the test cases and any other tests you can think of.

**Comment by AbhishekPAnil** [comment]
@troughc 
1."First, The default sort is by name - it should be by event date. Also, whenever you switch from one option to another (name to date created for example), the arrow to the right should return to the default direction, i.e. ascending."
2."Second The direction of the sort filter disappears "

I have updated the staging with the above changes.
=========================================================
3."There seems to be an issue with the 'Name' sort"----------->We can discuss this in our stand up with Suhail

**Comment by troughc** [comment]
@AbhishekPAnil Number 1. above is working well. I like the interaction. Number 3 is still not fixed right?

**Comment by AbhishekPAnil** [comment]
@troughc "Number 3 is still not fixed right? "------------->
Yes it is not yet fixed.I think we can open a separate issue for that since it is a backend update!
