### ISSUE TITLE
Taxonomy admin only fields bug

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1452]
Some admin only fields are correct in BE but are not displayed in the FE.The isAdminOnly is not returned properly .
![Image](https://github.com/user-attachments/assets/b26e63d4-16a4-4e46-8f90-a6e697e436cb)

![Image](https://github.com/user-attachments/assets/d2f8b1cc-157e-48ad-adca-8d753bf32867)

But once I updated the taxonomy,it returned the isAdminOnly boolean properly 

![Image](https://github.com/user-attachments/assets/68bd42df-ad4e-4928-9fb8-93a13f17d77a)

**Comment by troughc** [comment]
@sahalali can you look into this issue please?

**Comment by dev-aravind** [comment]
@troughc This is now fixed in [production](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/taxonomies/add-taxonomy?id=640f7796af65a800652da5f0).

**Comment by troughc** [comment]
Tested: PASSED
