### ISSUE TITLE
cannot remove virtual location from a saved event

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1469]
Bug discovered by Tout Culture Admin

[This event](https://toutculture.ca/en/event/marche-dart-et-metiers-dart-des-fetes-6745fc73b122e600649e102b/) was published as an event that can be attended either virtually or in person. 
The virtual location was recently canceled and the customer tried to remove it from the event form. They deleted the text and URL from the virtual event fields and saved. 
When the event is viewed again, the virtual event fields are still displayed in [the event form in the CMS](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6745fc73b122e600649e102b); they appear to be empty.
However, on the website the data still claims the event can be attended virtually (see website link at top); and in the developer tools view I see that the event is still tagged as a virtual event. **Below is a screenshot:**
I was able to reproduce this issue when creating a [draft or published event - see my list](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=upcomingEventDate&users=630a7cff5623170071a8b1ec).
**Steps to reproduce:**
create an event and add a virtual location. Click save. Reopen the event and remove the virtual location, then save. Reopen the event - it still has a virtual location (empty string).
Side question: i also noticed (in read-only view) that there is always a subtitle Location in the Location section even when I don't add any location to a draft event. Are we saving an empty string for the in-person location?

Expected behaviour: you can remove the virtual location anytime and the data will update.

![Image](https://github.com/user-attachments/assets/28d3b15f-c2f5-4c83-a868-cd966f116319)

**Comment by dev-aravind** [comment]
@SyamBabu-M The event sends a virtual location with empty values even when the location is removed on an update. Please hotfix this.

**Comment by troughc** [comment]
Thanks for the hotfix.
