### ISSUE TITLE
breadcrumb at the top of events is not clickable.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#150]
Cannot click the breadcrumb at the top of an event (and all entity pages as necessary) to navigate back to last location. I think Abhishek may already be fixing this @saumier ?

**Comment by AbhishekPAnil** [comment]
ESTIMATES 0.5-1 hr

**Comment by troughc** [comment]
TESTED staging in Chrome: PASSED.

**Comment by troughc** [comment]
@

**Comment by AbhishekPAnil** [comment]
@troughc Yes please
