### ISSUE TITLE
Create Elfsight widget with NAC osaka events.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1500]
Ref : https://github.com/culturecreates/footlight-app/issues/1499
We need to create an Elfsight widget to display events for NAC Osaka.

1. Integrate  google calendar from one of the culture creates google account.
2. Integrate the iCal link to the google calendar into the google account.
3. Check if the events are reflected in the Elfsight widget.

See the test versions of elfsight widget here :

https://e872182217fd4f93a0848c77afc676c9.elf.site/

https://1e2a0603c11d47c385d8847233cfd277.elf.site/

Please find the doc which contains instructions to setup an Elfsight widget with Google calendar.
https://docs.google.com/document/d/1dZ4i7rnkCS6Yfgs2R_AN4p7c8AtpKwx0Pv93n-riW7c/edit?usp=sharing

**Comment by troughc** [comment]
First challenge: Google calendar doesn't refresh on the fly (when ical feed is updated); initial research shows that some users have said that it doesn't refresh for 6-8 hours - which would be a limitation.

**Comment by saumier** [comment]
@dev-aravind Let me know when you setup the push to load NAC events into Artsdata. 

There are 2 ways to hide the data feed from the list of all data feeds in Artsdata:
- We can decide to use an existing optional parameter in the Databus API called `"register_only": "true"` that only adds the artifact to the Databus and does not load into a graph and display in the list of data feeds.  After the artifact is registered on the Databus I can load the graph manually. I would also do some work to add a button in Nebula so others could manually load an artifact into a graph (long overdue).
- Or we can push using the normal Databus parameters and then hide the artsdata-planet-foolight/nac graph from the list of data feeds by deleting the graph's `http://schema.org/name`. This method is the simplest, but the delete of the graph's name can only be done by Suhail or I.

Let me know your preference.  The other consideration is if you want to use the CMS exporter v1 or v2.  I think either would be fine but you may want to check with Suhail.

**Comment by saumier** [comment]
@AbhishekPAnil FYI I shared the test version of the elfsight widget using Indigenous events with Tammy and Caitlin. Thanks for setting that up.  This is a great first step.

**Comment by AbhishekPAnil** [comment]
@troughc What do you think about the styling of the widget ?Please let me know if you need anymore changes.Thanks !

**Comment by dev-aravind** [comment]
@saumier That depends on if this is a one time crawl or not, if it is a one time crawl the first option will be better as I can call the artsdata databus api on my machine. If not, I have a workflow that can be pushed to planet-footlight, I just need the artifact name that you want to use for the data.

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil 
Things to do

1. Check why the images are not showing in the widget.
2. Check if there is any difference in the code difference with code integration and integration using apps like (shopify,wordpress etc)
3. Write a procedure for creating and integrating an Elfsight widget with Google Calendar and setting up the Google Calendar to sync with an iCal feed. Document the steps clearly for ease of implementation.

**Comment by troughc** [comment]
> @troughc What do you think about the styling of the widget ?Please let me know if you need anymore changes.Thanks !

I think it is looking really good @AbhishekPAnil 👍

**Comment by saumier** [comment]
> @saumier That depends on if this is a one time crawl or not, if it is a one time crawl the first option will be better as I can call the artsdata databus api on my machine. If not, I have a workflow that can be pushed to planet-footlight, I just need the artifact name that you want to use for the data.

@dev-aravind I don't want to slow down the tests. If Google calendar needs a public SPARQL to sync events then I suggest you go ahead and push the data to Artsdata like normal.  In the morning I can hide the data feed from the list of data feeds in Artsdata.  That way no one in our time zone will see it (I will remove the graph label so the data feed will not show at all.) You can use the standard names for the artifact like the calendar slug `nac-osaka` (or the other is 'nac-cna') and the group `artsdata-footlight-cms`.  Sometime outside of the critical path we can add the optional parameter for "register only" to the Github Action. This parameter only registers the dataset on the Databus without importing the data into a graph. But you can go ahead and call the Databus as you normally would so the data can be imported and you can run your sparql.

**Comment by dev-aravind** [comment]
@saumier I used [artsdata-planet-footlight ](https://github.com/culturecreates/artsdata-planet-footlight/actions/workflows/export-nac-entities-to-artsdata-.yml)to create the [JSON-LD](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20nac-cnav2&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/nac-cnav2) (used V2 as V1 import was not working for me), also you can find the SPARQL used to transform the data for the iCal server [here](https://github.com/culturecreates/sparql-library/tree/master/artsdata/ical). 

Note: some addresses in NAC did not have some of the address data, so a small change was made in [iCal generator](https://github.com/culturecreates/artsdata-ical/commit/32b53ccb7f45dd5d4fbf9c05e1d13e03c90f8c2e).

**Comment by dev-aravind** [comment]
Tasks for @dev-aravind :

SPARQL updates:

- Get schema:Event only, EventSeries should be split into individual events.
- Performer name, performer image and the event image should go into the description of the Event.

**Comment by AbhishekPAnil** [comment]
> 2. Check if there is any difference in the code , with code integration and integration using apps like (shopify,wordpress etc)

Answers :
 There isn't any difference in the code but integration steps may be different according to the website's admin panel,which is specified in the elfsight website.

**Comment by troughc** [comment]
This looks good @AbhishekPAnil 
- locations are displaying correctly on the map: PASS
- event series at a single venue are showing up individually: PASS
- single date events look good: PASS
- Main image is displayed correctly in the list view: PASS
- Main image is displayed correctly in image details: Not consistent but not a showstopper (see question below).  
@saumier @dev-aravind I have a question:
- when you enter the event details, the video is displayed at the top of the Tanya Davis events (instead of the MAIN image). Shouldn't it be the MAIN image instead (the one of Tanya holding the flowers)? The Main image (with the flowers) is displayed on the listing page.

**Comment by troughc** [comment]
@AbhishekPAnil and @dev-aravind  I spoke with @saumier and this is okay as is. I am assigning it back to me.
