### ISSUE TITLE
Update data in staging for widget demo to NAC

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1514]
Please copy all data production to staging including images so we can show "Osaka Prod" calendar to NAC on our Tuesday. 

Please check that the widget works with that calendar. Here is the demo page which I created to show NAC. https://culturecreates.github.io/footlight-widget-demo/art-cms-widget.html

**Comment by sahalali** [comment]
The data has been copied, and the images are synchronized between the production and staging servers.

**Comment by saumier** [comment]
@AbhishekPAnil @sahalali @dev-aravind @SyamBabu-M Thanks team. This made for a fantastic demo on Monday to the National Arts Centre (NAC).  It really made a big difference to see the widgets with the images and events entered by the NAC.  They were very impressed! Here is the link to the Demo page I made with both our CMS widget and the Elfsight widget embedded in an NAC webpage.
