### ISSUE TITLE
UI display issue when browser less wide

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#156]
when you resize a browser widgets move and sometimes the spacing is off. See examples in screenshots:

### Example  - STILL TO DO
**Too much space when date type switcher moves from right to below the date-time fields:**

![Image](https://user-images.githubusercontent.com/64489312/220692915-8699f122-5d91-4734-a474-98af3a7b3a02.png)

### example - DONE
**No space when filters appear below search on Event listing page:**

![Image](https://user-images.githubusercontent.com/64489312/220692834-c46eb787-cc53-4ff1-b104-67fbf1d505cd.png)

**An example of correct spacing is shown in sprint 12, in the french screens section. (because at one point we will have too many filters to fit on one line)
Here is a screenshot of the figma:**

![Image](https://user-images.githubusercontent.com/64489312/220696238-eba018ec-096d-402f-ad75-49acc63b0a4e.png)

**Comment by AbhishekPAnil** [comment]
ESTIMATES 2-2.5hrs

Subtasks 
1.Add the spacing for filter buttons
2.Correct the general layout alignment for right side container in add/edit event page.

**Comment by AbhishekPAnil** [comment]
@troughc I have fixed the first example and updated it in staging .The second one is yet to fixed.
Thanks!

**Comment by saumier** [comment]
This has less priority. Let's move out.

**Comment by troughc** [comment]
@AbhishekPAnil is this one already covered elsewhere? Let's close this if we don't need it.

**Comment by AbhishekPAnil** [comment]
@troughc The first example will be resolved in #838 .The second example is yet to be fixed.

**Comment by troughc** [comment]
@SyamBabu-M I think the issue with the spacing on the event DETAILS page is the one that still needed an adjustement - and it should be fixed when you create the mobile/tablet views I think? Let's touch base tomorrow.

**Comment by troughc** [comment]
Tested in chrome and on Safari: PASSED

cc @SyamBabu-M
