### ISSUE TITLE
Keyboard behavior in fields

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#158]
Description to be developed
From tests:
 When I press enter during a search action in a field - for example, I press Enter when I type in a search name for an organization - we have it set up so that nothing happens.  

Preferred user experience - further research needed before confirming:
Type in a string and display results. Once there is only one result, highlight it. Press enter to select it, press escape to not select it and to close the dropdown.
Should the field also be cleared if I press escape?

**Comment by troughc** [comment]
@saumier this issue has now been logged by Signe Laval (Maude). It is support ticket #25

**Comment by troughc** [comment]
@SyamBabu-M did your enhancements to working in the form cover this? Please read description about field behavior, thanks!

**Comment by SyamBabu-M** [comment]
@troughc Pressing enter to select and escape to close is implemented in [#25](https://github.com/culturecreates/footlight-app/issues/25). But automatically highlighting only available element is not implemented.

**Comment by troughc** [comment]
@SyamBabu-M as per our discussion please complete the features here and those not covered by: https://github.com/culturecreates/tech-support-tickets/issues/25

**Comment by saumier** [comment]
@troughc @troughc This is not working for me when try searching for 'minimal' in staging and then I can't continue typing 'agency'.  I don't think it is very common UX. @troughc I'll wait for you to return before doing anything else on this one.

**Comment by troughc** [comment]
Tested in chrome and it doesn't always work when the single entity is selected (It is hit and miss). For example, in organizer field, when I typed agence minimal, it shows up, but when I select it the component is blank.

**Comment by troughc** [comment]
@SyamBabu-M maybe just have it work like this:
success would be: being able to navigate into a search field, type letters and then select from the dropdown using arrow keys and then press enter to close. And then be able to continue going through the form using the keyboard.
There shouldn't be an extra outline around the selected option. Is that possible?

**Comment by SyamBabu-M** [comment]
@troughc I have removed the outline around the focused item. Its up in staging now!

**Comment by troughc** [comment]
Tested in staging: Passed

**Comment by troughc** [comment]
@SyamBabu-M I am moving this back to To Do because I found a bug. 
Steps to reproduce:

1. In location field (in Event details), start typing. 
2. Keep adding letters. 
3. Problems can occur as you type: 
- when the dropdown list loads, the focus changes and you cannot type any more letters. you have to click in the field and it's buggy
-  If you pause in typing, the list loads and you can't type anymore (the focus moves to the list). Same issue. 
Please try it out by typing in the field at different rates of speed. In Tout Culture, try typing "Place des arts" (slowly, taking pauses). When the focus moves to the list (before you get to the end of the phrase), the selected entity is NOT place des arts and I can't continue typing.

Expected behavior: I should be able to easily type more letters if I have not finished entering the text and then select.

**Comment by troughc** [comment]
Tested in chrome and discovered a bug
When you type a phrase and hit enter without selecting someting in the dropdown an blank component is added (see first screenshot).
Then, when you click save to save the event, you get an error message (see screenshot 2 and 3)

### screenshot 1
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6ea7c645-b42b-452a-8364-272507a26cbc)

### screenshot 2 and 3 (so you see the error messages and error ID)


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a65f8605-0455-4492-9654-a83aaba34df4)



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/c2a12601-5553-4161-9682-83363a60ad41)

**Comment by SyamBabu-M** [comment]
@troughc Sorry, I missed an edge case. This is fixed and up in staging.

**Comment by troughc** [comment]
Tested bug on staging in chrome: FIXED and passed 
thank you @SyamBabu-M !
