### ISSUE TITLE
In Language standard field

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#187]
Add a "Event language" field to the section "Other information". This is a standard field that uses the inLanguage Taxonomy. It should be on the right side of the Event form be default. When added to the left side of the Event form by a user it should appear just above image.
**English** 
field name: Event language
default text: Select language of event
**French**
field name: Langue de l'événement
default text: Sélectionnez la langue de l'événement

**Comment by saumier** [comment]
@troughc Please read description and confirm placement of the "Language" field.  You can add it to the Figma if you want but it is not required in the Figma in my opinion.

**Comment by troughc** [comment]
Placement is good @saumier .  @AbhishekPAnil I have also added the default text (french and English) to the description. and the information text (french and english) to the Footlight CMS copy spreadsheet (field tooltips).

**Comment by troughc** [comment]
@saumier can we change the name of the taxonomy in Tout Culture? From "inLanguage" to "Event Language"?

**Comment by saumier** [comment]
yes. The name of the Taxonomy is not used for the CMS UI when the taxonomy is linked to a standard field. The field  inLanguage is a standard field (not a custom field).  If you want the user interface of the new CMS to change then you need to let Abhishek know. 

Gregory Saumier-Finch | CTO | La culture crée - Culture Creates | c. (514) 316-6973 | culturecreates.com <http://culturecreates.com/> 

Nous reconnaissons que notre travail, ainsi que celui de nos partenaires, a lieu sur les territoires autochtones dans tout le Canada.
We recognize that our work, and the work of our partners, takes place on Indigenous territories across Canada.

**Comment by troughc** [comment]
@AbhishekPAnil please note the name change of the standard field "inLanguage". In the new cms, this field has been renamed to "Event Language" / "Langue de l'événement" as per the description at the top.

This updated field name should also be reflected in the old cms Taxonomy section - please confirm if this is possible to update in the old cms, @saumier @SuhailAliyar

**Comment by AbhishekPAnil** [comment]
@troughc Could you please  add the tooltip information required for event language to the CMS copy sheet.Thanks.

**Comment by troughc** [comment]
@AbhishekPAnil the tooltip info is already there - I commented the cell for you: https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=0

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
Tested in Chrome: PASSED
