### ISSUE TITLE
Event List - Event Menu

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#19]
Event menu: 

if user does not have edit permission or is a guest --> hide menu completely (no 3 dots)

if user is Contributor or Editor or Admin:
   if the event is DRAFT or WAITING FOR APPROVAL --> Publish event, Delete event
   if the event is PUBLISHED --> Unpublish event, Delete event

**Comment by saumier** [comment]
### Guest - no menu anywhere in event listing page. They must go to event details in order to send for review.

### Contributor (=collaborator) 
- When my created event is draft: menu has publish event, delete event.
- When other creator event: no menu
- When my event is published :  menu has unpublish event, delete event.

### Editor
- When any event is draft: menu has publish event, delete event.
- When any event is published :  menu has unpublish event, delete event.

### Admin
same as editor

**Comment by saumier** [comment]
Please add a confirmation popup to confirm that the user wants to delete the event with buttons for ok and cancel.

**Comment by saumier** [comment]
@troughc Please test in production.

**Comment by troughc** [comment]
PASSED
