### ISSUE TITLE
Add description to event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#22]

**Comment by troughc** [comment]
Tested and passed - was able to copy in a description and word count is respected 

NOTE, right now, only ONE language is required to meet the word count restriction. If the other language doesn't, it still can be published. This is okay, we will see if this works for the customer. cc @saumier

**Comment by saumier** [comment]
@AbhishekPAnil Please add an H1 to the list of buttons in the editable field.

**Comment by saumier** [comment]
@troughc Please test the description field with the new H1.

**Comment by troughc** [comment]
Tested on Chrome and Safari. Pass with an issue @saumier 

I can apply h1 to a paragraph in the description, which is great.
However, I cannot copy/paste a description the way I think it should work.
As part of my test, I took a description from this page: https://signelaval.com/fr/evenements/20143/expositions-musee-deli-tetreault
The desription came in with everything INCLUDING background colour (see screenshot). I would expect it to be added without the background colour. Shouldn't that be stripped out?


![Image](https://user-images.githubusercontent.com/64489312/212151001-5f7d10c4-8e7b-4dd5-a615-7e24716f41bb.png)

**Comment by saumier** [comment]
@AbhishekPAnil Please strip "style" from the HTML so that the colour of the text is not copied into the description field.

**Comment by saumier** [comment]
@troughc Please take a look in staging or production, as this has already been deployed. If you find another bug with the description field please add it here.

**Comment by troughc** [comment]
Tested: PASSED
