### ISSUE TITLE
cannot log in because invitation/user account has been revoked by Admin

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#226]
2 new message alerts need to be added to log in screen:

- When an admin invites a user and then revoke the invitation: if the invitee clicks the email or tries to log in after accepting the invitation, the message should tell them to contact the administrator of the calendar (in the tout culture calendar, it is Culture Outaouais support email) for help.
- when an admin removes a user from the calendar: if they try to log in after that, they should be directed to contact the admin.

The messages have been added to  Footlight CMS copy for these 2 situations on User flow - Notifications tab here: https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=2114823229
(highlighted in yellow)

Current situation to update/fix:
Right now, In staging, a user who has had their account revoked by an admin goes to the log in screen and sees a message that says something went wrong with the contact being culture creates. Please replace this message with the two above, depending on the situation.

Note that A revoked message is still active in production (it takes you to the old cms) - if you want to take a look.

**Comment by saumier** [comment]
@troughc I am leaving this in the No Status column until we launch Signé Laval.

**Comment by troughc** [comment]
@saumier bringing this issue back to your attention.

**Comment by saumier** [comment]
Closing because this is a duplicate with https://github.com/culturecreates/footlight-app/issues/233
