### ISSUE TITLE
Add Date range

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#23]
As a user I can select a date range for my event with optional start and end times.

## Test cases
1. Create a new event
1. Select the "Date range" button --> Check that the "change to single date" link appears on the right
2. Switch to single date --> Check that the "change to date range" link appears on the right
3. Switch to date range and enter the start and end dates (no start time or end time)
4. Save the event --> check that the dates are displayed in the event list
5. Edit the event --> check that the dates are displayed as expected
6. Add a start time --> check that the start time is persisted
7. Add an end time --> check that the end time is persisted
8. switch to "single date" --> check that everything is blank
9. switch to "date range" --> check that everything is blank

**Comment by troughc** [comment]
Tested on CHROME
I can do all the steps 1-4



![Image](https://user-images.githubusercontent.com/64489312/210868568-ff5bae60-afe5-4879-af8c-1ac65e0d3cbc.png)


At step 5 (saving event after adding the date range), the date is wrong on the listing page (one day early) AND when I go back in the single date option is displayed. 



![Image](https://user-images.githubusercontent.com/64489312/210868653-2c5e1a46-71f7-4e3d-8988-7d5e292c2582.png)



![Image](https://user-images.githubusercontent.com/64489312/210868775-f799a3a9-3c8c-4789-890c-e6e6e55532fd.png)






I then switch to date range and my dates appear correctly. 



![Image](https://user-images.githubusercontent.com/64489312/210868859-af49bd71-50d2-468a-9aeb-d964b5606d52.png)



HOWEVER, when i save again, the date on the listing page is still incorrect.



![Image](https://user-images.githubusercontent.com/64489312/210869000-0f3730f6-efa7-4ec5-9df2-c28945f7b085.png)

**Comment by troughc** [comment]
FIRST TEST: **Test Event** is the name of the event I created.
FIRST: All the steps seem to work except that when I DO NOT add an end TIME, the end DATE is incorrect on the event listing page. It should be February 28. 


![Image](https://user-images.githubusercontent.com/64489312/211583509-99326963-c78d-4103-b961-284a2d1506ba.png)



If I add an end time of 8PM, the end DATE on the listing page is correct - February 28 (please try this yourself). Is there a time zone issue @SuhailAliyar @AbhishekPAnil ?

SECOND TEST: tested event **La Poésie des naufrages, une exposition de Sébastien Gaudette / The Poetry of Shipwrecks, an exhibition by Sébastien Gaudette** and **MARIANNA MAZZA** events

Events look okay in the cms when I add an end TIME to them (9PM). However, when I look at the events on (http://demo.staging-tout-culture.s3-website.ca-central-1.amazonaws.com/)  the end date is not displayed, instead I see with message Invalid Date for both events (see screenshot 1)

I then removed the end time from Marianna Mazza event. The end date for Marianna Mazza now appears properly (see second screenshot).

SCREENSHOT 1


![Image](https://user-images.githubusercontent.com/64489312/211582070-81aa5f4e-e4b1-40f1-9b7a-6b4db77d30f1.png)



SCREENSHOT 2



![Image](https://user-images.githubusercontent.com/64489312/211582121-ddc8d012-fb4c-438a-accd-b59afca25a44.png)

**Comment by saumier** [comment]
@troughc I fixed the demo's Invalid Date. It was independent of the other issues you reported.

**Comment by troughc** [comment]
One more thing @saumier @AbhishekPAnil : I cannot add a time (start or end) manually. I have to use the selector. Is this intentional?

**Comment by saumier** [comment]
From a UX point of view it should be possible to enter the time with a keyboard. On Jan 10, 2023, at 3:18 PM, troughc ***@***.***> wrote:﻿
One more thing @saumier @AbhishekPAnil : I cannot add a time (start or end) manually. I have to use the selector. Is this intentional?

**Comment by troughc** [comment]
Tested: Passed
