### ISSUE TITLE
Enhancement: Reviewing events in new cms - navigating/reviewing with filters persisting

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#235]
As a user, I want to be able to scroll through and review events, and then continue where I left off. I want my filters to persist until I click the Clear button because I am reviewing multiple events, which includes actions like: 
- scrolling through pages to look at high-level details.
- clicking a specific event, looking at its details, maybe making a change and then either saving or publishing it. 
- clicking a specific event and not making any changes, not saving it, not publishing - could want to click the breadcrumb or could use the back button to go back to the calendar list view.
- Clicking the Events in the left navigation to return to the list view

In all cases, when I return to the calendar list view (in any of the above scenarios), I want to be back where I left off, on the same page I was last on and with the same filters set. 
Power-up: I also want to to be able to share the URL that has all my filters selected - to simply copy paste the URL to give to a colleague. 

If I want to return to a past page (for example page 1 of 10), I can click the page number at the bottom. My filters would persist

If I want the calendar list view to be the the default view, I can click the Clear button. This would reset the calendar list view.

**Comment by troughc** [comment]
@saumier can you please take a look at this?

**Comment by troughc** [comment]
@saumier would implementing this enhancement also resolve #150 ?

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
@AbhishekPAnil when I uncheck a filter (like a publication option) without using the Clear option, it resets after I do a change on an event. I have to click Clear (I can't just uncheck the options). This is okay, but not ideal. cc @saumier 
Steps to reproduce:
1. Select Draft from Publication
2. unselect Draft from publication. 
3. Navigate to a draft event and then edit it.
4. Click Publish in the details page. When i am sent back to the listing page, Draft is now selected in my filter.
5. Repeat steps except, for step (2), click Clear and then do the same thing. When I click Publish, I am sent back to the listing page with no filters selected  (as expected).

**Comment by troughc** [comment]
@saumier this workflow issue of users wanting to simply deselect a filter was also raised by Signe Laval in this tech support issue https://github.com/culturecreates/tech-support-tickets/issues/5

cc @AbhishekPAnil

**Comment by saumier** [comment]
@troughc Please test in staging in production.

**Comment by troughc** [comment]
@saumier I just retested this with my steps as follows and it isn't fixed in staging for me. 

1. Select Draft from Publication filter.
2. Unselect Draft from publication filter.
3. Navigate to a draft event, open it and then edit it.
4. Click Publish in the details page. When i am sent back to the listing page, Draft is now selected in my Publication filter.
5. Repeat steps except, for step (2), click Clear and then do the same thing. When I click Publish, I am sent back to the listing page with no filters selected (as expected).

Using the Clear button clears ALL your filters, but you may only want to clear the one filter. This issue was noted by Maude too.

**Comment by saumier** [comment]
@troughc Please assign to Abhishek.

**Comment by troughc** [comment]
@AbhishekPAnil you can see my comment above about Draft events not working as expected.

**Comment by troughc** [comment]
Found one bug - when I click Events in the left navigation after setting up a subset of users, the list of selected users disappear (I did the aggregators for  tout culture).

**Comment by troughc** [comment]
@sahalali @SyamBabu-M did this get retested before closing? 
FYI I just tested it now and it works, but I want to. make sure that our issues are getting closed (and moved to done) at the right time (after testing). Thanks!

**Comment by SyamBabu-M** [comment]
@troughc 

> @AbhishekPAnil you can see my comment above about Draft events not working as expected.
> 
> copying here for your convenience: when I uncheck a filter (like a publication option) without using the Clear option, it resets after I do a change on an event. I have to click Clear (I can't just uncheck the options). This is okay, but not ideal. cc @saumier Steps to reproduce:
> 
> 1. Select Draft from Publication
> 2. unselect Draft from publication.
> 3. Navigate to a draft event and then edit it.
> 4. Click Publish in the details page. When i am sent back to the listing page, Draft is now selected in my filter.
> 5. Repeat steps except, for step (2), click Clear and then do the same thing. When I click Publish, I am sent back to the listing page with no filters selected (as expected).

@troughc the above was the issue first mentioned in the ticket. And it was completed. But I think during testing you found another bug in user selection, which you mentioned in a comment above and moved this ticket back to todo. This ticket was not taken up after the new bug was reported. I will make sure give extra priority to issues that comes back to to so that issues will not get closed without proper testing.
