### ISSUE TITLE
editing published events - edits must still meet minimum requirements to remain published.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#236]
When an event is already published, a user should not be able to remove required properties (according to the calendar configuration) and still have the event be published. 
- if a required property is removed from a published event, the user must either save the event as draft or not save the changes.
For example an image is removed from a Tout Culture published event or an edit to a description shortens it too much such that it fails to meet the word count minimum of 50. When the user click Save, the required properties warning appears "This event needs more information before it can be published." and the user is force to either
- Save as draft
- Cancel changes
- Fix the problem and then save (published).

I hope i have covered all scenarios :)

**Comment by troughc** [comment]
@saumier I added this issue to the priorities. Please take a look.

**Comment by saumier** [comment]
@AbhishekPAnil Please take into account that these required fields are DIFFERENT per calendar. Next week we need to start configuring the required fields for Singé Laval which are different than Tout Culture.

**Comment by troughc** [comment]
Tested in Chrome on two events by removing and then adding back required fields/minimum word counts. Everything worked okay except two things:
**More important:** I am not really sure what the bug is but: 
When I change the selected date type using the options on the right and I don't fill a date in, I was able to sometimes still save the event. But then it completely disappeared from the list. I tried this twice. One of the events is names "Caitlin - MULTIPLE DATES - test 2 weekly" (i can't find it by Search or User). One time, I was able to use the back button to get to the event and I think that the date section was reset to it's original state (default where you select your option) - another time, the date looked like it was set to a past date.

I then retested this with the Jam Trad – À la Dérive event. - a single date event: http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/641c37df7b9df310888fcc84
Different things happened. perhaps you could try it out too.
- when I switch from date range to single event and click save, nothing happened; when I switch to multiple dates, I got an error message (good), when I switch to date range, it's filled in. 
- I did not save, so next time I opened it the date range is set to the single date as it should be.


FYI only **Less important (can be fixed later, post launch):** The word count can be a bit wonky. It was 55 when I closed an event but then when I reopened it, it was 49. The reason is because extra spaces are removed from the end of a paragraph as I save the published event. So then when I reopen it, the wordcount doesn't meet the requirement and I get an error message that it cannot be published (even though it already is). For an example, see Jam Trad – À la Dérive event: http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/641c37df7b9df310888fcc84 
This event had extra spaces at the end of the last paragraph that allowed me to get the word count up to 50 words to publish it in the first place.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
