### ISSUE TITLE
Publishing events from Right-click menu

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#252]
When you try to publish an event from the right click menu in the calendar event list view: if the event is not publishable (doesn't meet minimum requirements), nothing happens (no warning, no change in publication status). The user would not understand what is wrong.
reminder: user rights determine whether the publish option appears. Guests don't see this option at all; contributors see it for their own events, etc...

Here are some suggestions for resolving this:
- the Publish option could be greyed out when an event does not meet minumum requirements for publishing
- a message cold appear that tells you the event cannot be published.

Image of right-click menu for a contributor

![Image](https://user-images.githubusercontent.com/64489312/229383158-65197fc9-9904-4e26-9e7b-dabc37b9cea2.png)

**Comment by troughc** [comment]
@saumier please let me know what you think of these suggestions. My preference is the first suggestion as it involves fewer interactions from the user.

**Comment by saumier** [comment]
Both work for me and I don’t have a preference. Please ask Abhishek his opinion. There might be something I am missing, one may be more work for him than the other, and then take the decision.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil let me know when you have time to discuss this one.

Today would be fine.Od its ok for you @troughc

**Comment by AbhishekPAnil** [comment]
> Today would be fine.If its ok

.

**Comment by troughc** [comment]
Tested on Chrome- PASSED
Tested an event on the first page - got message and stayed on the first page. PASSED
Tested an event on the third page - got message and stayed on the third page. PASSED
