### ISSUE TITLE
CMS: Required field configured by client

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#257]
Dependant on https://github.com/culturecreates/footlight-calendar-api/issues/330

**Comment by AbhishekPAnil** [comment]
Estimate : 14

1.Add the integration for getting the required field details from the calendar api.
2.Add the required field logic to the form fields.
3.Add the validation logic to form fields .
4.Update the validation on submit trigger. 
5.Test with Tout Culture and Signe laval Calendar.

**Comment by saumier** [comment]
@troughc If you have time, please test in staging, but if you don't have time I think this can be pushed to Production so you can demo it tomorrow.  I have asked @SuhailAliyar to push the latest versions of both back-end and front-end to production tomorrow so you can show Signé Laval.

**Comment by AbhishekPAnil** [comment]
> Validation text for description field mentions French/word count. Since they will not have a bilingual site (i.e. no bilingual fields in the cms) and no minimum word count, I updated the validation text in the cms copy document .

Also need to update Validation copy for Paid tickets. (See Footlight cms copy document, row 20)

Please update the validation text according to the document (see row 11, row 13 highlighted in yellow).

@troughc  This is related to https://github.com/culturecreates/footlight-app/issues/163.I can update the validation texts while working on the same.

**Comment by AbhishekPAnil** [comment]
> Validation text for description field mentions French/word count. Since they will not have a bilingual site (i.e. no bilingual fields in the cms) and no minimum word count, I updated the validation text in the cms copy document .

Also need to update Validation copy for Paid tickets. (See Footlight cms copy document, row 20)

Please update the validation text according to the document (see row 11, row 13 highlighted in yellow).

r @troughc  This is related to https://github.com/culturecreates/footlight-app/issues/163.I can update the validation texts while working on the same.

**Comment by AbhishekPAnil** [comment]
> Validation text for description field mentions French/word count. Since they will not have a bilingual site (i.e. no bilingual fields in the cms) and no minimum word count, I updated the validation text in the cms copy document .

Also need to update Validation copy for Paid tickets. (See Footlight cms copy document, row 20)

r

> Also need to update Validation copy for Paid tickets. (See Footlight cms copy document, row 20)

r

> Please update the validation text according to the document (see row 11, row 13 highlighted in yellow).

r 
@troughc This is related to https://github.com/culturecreates/footlight-app/issues/163 can update the validation texts while working on the same.

**Comment by AbhishekPAnil** [comment]
@troughc 

> @AbhishekPAnil as discussed, please hide the minimum word count sentence below the description field when the word count is one (to make description a required field).

This has been updated in staging.

**Comment by troughc** [comment]
> This has been updated in staging.

Looks great!

**Comment by troughc** [comment]
### Tested **Signe Laval** as a guest:

Save as draft: 
PASSED: was able to save as draft and then edit as expected
Send for review:
PASSED: was only able to send for review after I entered all required fields (image is not required for signe laval)

--------------------------------------------
### Tested **Tout Culture** as a guest - 
 Save as draft:
PASSED: was able to save as draft and then edit as expected
Send for review:
**PROBLEM:** Was able to send to review without an image. Image is required for Tout Culture. 
See http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/64398a0c77605c0064d25611
http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/643991e077605c0064d25b80

![Image](https://user-images.githubusercontent.com/64489312/232113292-26eba3c8-05fd-4438-b2f9-b446b60a66d6.png)

**Comment by troughc** [comment]
@SuhailAliyar @AbhishekPAnil here are my test results:
Logged in as GUEST 
- The Tout Culture event would not send to review when I did not add an image: GOOD
- When everything is there (all required fields) I cannot send any event to review. It seems to be hanging or something. NEEDS FIX
- Also noticed that when i add an image that is too large (over 5 mb), it takes a very long time for the "unable to complete the request" and 'try a different image' messages to appear (around 15 seconds)

See my test events here:
http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/643d49ef72c0360065a352fe (this is the event where I also tried to add a too large image)

http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/643d4afb72c0360065a35487

**Comment by AbhishekPAnil** [comment]
> When everything is there (all required fields) I cannot send any event to review. It seems to be hanging or something. Will only save as draft. NEEDS FIX

@troughc Was this a new event ?

**Comment by troughc** [comment]
@AbhishekPAnil regarding case 2: yes they were all new events. It is still happening - I cannot publish. I have tried with a few more events, logged in as an admin.

**Comment by saumier** [comment]
This is related to the required Ticket note field. I am closing this issue because it is a duplicate
