### ISSUE TITLE
Add Contact to Event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#26]
As a user, I can add contacts to my event by reusing the organizer's contact info, or create a custom contact for my event. There are no mandatory fields. Optional fields are name, title, email, phone, website url.

Note: Custom contacts for events cannot be reused. There is no search for contact. There is no drop-down with the list of all contact.

**Comment by saumier** [comment]
@troughc Please test in staging

**Comment by troughc** [comment]
Tested Chrome (published event) and Safari (draft event) - PASSED 
Published event displayed data correctly on the Display test site. Draft data appeared properly in different browsers. Both appear in oldcms.
