### ISSUE TITLE
CMS Organizations list and detail screens

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#266]
English Figma versions have been reviewed. French outstanding

related to https://github.com/culturecreates/footlight-app/issues/129

![Image](https://user-images.githubusercontent.com/419491/230089387-ff367947-f4cb-4d39-be16-00932043bb45.png)

![Image](https://user-images.githubusercontent.com/419491/230089624-b4b45909-ebb5-43c2-b077-44c51c6126cf.png)

**Comment by AbhishekPAnil** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Page | Task | Estimate
-- | -- | --
Listing page | Add the layout for organizations page | 3
Add / Reuse the listing component | 4
Add api integration to show the organizations | 4
Add the api integration to delete an organization only for admin | 4
Add the filter and search components | 2
Add the api integration to implement search | 3
Add the api integration to implement filter(sort and order) | 4
Add routing for add organization which also includes role based routing for GUEST,ADMIN,CONTRIBUTOR | 2
New organization search page | Add the layout and texts | 3
Add the api integration to search for organization | 4
Routing for new organization after clicking "create new organization" from dropdown | 2
Reuse the dropdown component from event details page | 4
Add the breadcrumb button and its functionality | 3
Create New Organization | Reuse the layout from add-event page | 5
Reuse the components from add event page for (Name,description,...etc). | 3.5
Add the necessary valdations for each component | 2
Add the api integration to add a new organization | 6
Add the api integration to add the image of the organization | 4
Add the scroll behaviour for the text on the right side | 2
Edit Organization | Add the relevant text need for edit organization page | 2
Api integration to get the details of the data source | 3
Api integration to get the current details of the organization and add the details to each and every component. | 6
Extra api integration for taxonomies if needed. | 4
Api integration to update an organization | 4
  |  
Read only page | Add the layout for read only page | 4
Reuse the components and css from the event read  only page | 4
Api integration to get the details of current organization | 4
Extra api integration for taxonomies if needed | 4


</body>
</html>

**Comment by troughc** [comment]
@AbhishekPAnil please add tasks.

**Comment by AbhishekPAnil** [comment]
https://docs.google.com/spreadsheets/d/1rGJThQZf-j9octZnyRkMXpX_noOT20CVYuuYMbF-dF0/edit#gid=0

Above is the link for the issues to be created .Thanks

**Comment by saumier** [comment]
@AbhishekPAnil Excellent. Thanks for the spreadsheet. 

I have a question. While reviewing your spreadsheet I saw several mentions of reuse which is great. So would it be better to do just the listing page for Organizations, People, Places, Users, and Taxomomies and after move on to the create/edit/read-only screens?  My idea is that you would have a better chance to analyze the commonalities before you code. For example, you could analyze the differences between the Organization listing page and the Person listing page so you can build those common parts with common names and components. 

Think about this and let me know your thoughts. I am fine either approach, meaning we could plan the sprints by class (Person, Organization, Place...) or by page (listing, search, create, edit, read-only), or a combination.  I am asking only because I noticed how similar the listing pages of People and Organization are and how it could be more fun to do it by class.

**Comment by saumier** [comment]
@AbhishekPAnil Please estimate effort for the following 3 groupings:

A. Develop Organization list and Organization read-only screen
OR 
B. Develop Organization, Person and Place lists and read-only screens together.

C. A rough guesstimate to develop the remaining search, create/edit, read-only for the 3 classes: Organization, Person, Place.

If the difference is not huge between A and B then we should do the 3 classes together since those are all needed by contributors, and then do the Users, Taxonomies and Calendar settings after we deliver the first 3.

**Comment by AbhishekPAnil** [comment]
Please fnd the updated estimates here :
https://docs.google.com/spreadsheets/d/17HbmO0v7T9INp4BoeugGTQrmAxXLiqzUh9LfTrzAuOs/edit?usp=sharing

**Comment by saumier** [comment]
@AbhishekPAnil I am closing this issue because you have provided the estimates and I have created separate issues for the work.
