### ISSUE TITLE
Add Facebook, video, event links to event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#27]
Add Facebook, video, event links to event.  The feature of "add more details" will be implemented later.

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
@saumier it seems to work - I add links, starting with www (see screenshot) and it saves no problem. However, in the old cms, the field expects an http(s):// to be manually entered. So it doesn't like it there. Question for you: is what I entered ok? Or does the user have to enter http:// too? (which wouldn't be the logical choice in the design of the new cms.

![Image](https://user-images.githubusercontent.com/64489312/212736232-045651bd-7fb1-4fad-8c11-401c3d3c9150.png)

**Comment by troughc** [comment]
@AbhishekPAnil Can you please ensure there is always a URL protocol when links are saved to the database. If the protocol is missing you can use https:// . 

NOTE: Even though you're doing this, you should also support these use cases:  

1. someone only enters www.website.com (add the protocol 
2.  someone enter http://www.event.com  (no need to add a protocol)
3.  https://www.eventpage.com  (no need to add a protocol)

**Comment by troughc** [comment]
Tested 3 cases in chrome and safari - PASSED.
