### ISSUE TITLE
Date UI updates

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#276]
1. When you select Date Range and set a start date and end date, a [number of occurences] appears. This should not happen. Events with date ranges are single events (1 occurence)
Please remove the number of occurences from the date range field. Make sure that the Date Range event appears as one event (not an event series with sub events)

2. Remove START TIME AND END TIME from Date Range options (screenshot at bottom)

3. When you switch from Date range to Multiple dates, can you please carry over the date range set in Date Range to Multiple Dates.

![Image](https://user-images.githubusercontent.com/64489312/231870708-fe618c3b-a25c-46b3-b73d-94f9bd950d9c.png)

**Comment by AbhishekPAnil** [comment]
Estimate: 4-6 hr
1.Remove the occurence .( 0.5 hr )
2.Remove the start time and end time and test the validations .(0.5 - 1 hr )
3.Carry over date range selection to multiple dates and check the tests and validations for it .(2-4 hr )

**Comment by AbhishekPAnil** [comment]
@troughc (1) and (2) cases are updated in staging.

**Comment by troughc** [comment]
After discussion with @AbhishekPAnil we won't do the third case until after launch when we can do extensive testing in a non-production environment.
I will move to a new issue.

**Comment by AbhishekPAnil** [comment]
@troughc I am moving this to review since the third case is a separate issue.

**Comment by troughc** [comment]
TESTED on chrome-  PASSED
