### ISSUE TITLE
layout issue: distance between Description | Image too large - Signe Laval

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#296]
For unilingual calendars, the distance between Description and Image is too large (because the translate button is hidden without reducing the space)

**Comment by SyamBabu-M** [comment]
@troughc could you provide a screenshot for this issue?

**Comment by troughc** [comment]
@SyamBabu-M given other adjustments that have been made to the UI, the spacing is acceptable. We will close this issue as not planned. Thanks for asking!
