### ISSUE TITLE
Add Event type and Audience type

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#30]
These fields are multi-select

**Comment by AbhishekPAnil** [comment]
@troughc The validations for the input type "Target Audience" is missing the in the docs .
https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=727653462
Could you please update that and let me know.

**Comment by troughc** [comment]
Thanks for finding this @AbhishekPAnil, I added the text to the document and commented you there. https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=727653462

**Comment by saumier** [comment]
@troughc Please test in staging

**Comment by saumier** [comment]
@AbhishekPAnil Please use the following AntD 4 widget to display the tree. Here is an example in code in Sand Box
https://0wflj2.csb.app/

**Comment by saumier** [comment]
@AbhishekPAnil Typing to search in the tree is not working as expected. When I type Jazz, the Jazz concept in the tree should highlight. Like in https://0wflj2.csb.app/.

**Comment by saumier** [comment]
@AbhishekPAnil Please open the tree view by default. Caitlin confirmed in Slack just now. Thx.

**Comment by saumier** [comment]
@troughc Please test in staging.  The search should work as well as the open tree by default.

**Comment by troughc** [comment]
Tested in chrome and safari - PASSED
