### ISSUE TITLE
bug: Publish creates duplicate events when not returned to event listing page

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#304]
When I tried to publish an event while tsting (ticket type with price only) it made duplicate drafts of the event. 
Screenshots from both calendars.

![Image](https://user-images.githubusercontent.com/64489312/234280517-a7288270-6177-4454-a691-a41c8ec72e6a.png)

![Image](https://user-images.githubusercontent.com/64489312/234280584-8cb56eac-600a-491b-ba92-47d111a1a263.png)

**Comment by troughc** [comment]
Deprioritizing: This one is not happening because of fix to required fields in event details page (we no longer get stuck in the details clicking the button multiple times).

cc @saumier @AbhishekPAnil

**Comment by saumier** [comment]
@AbhishekPAnil When I was using CMS in staging, I noticed that every time I edited an event and clicked "Save as draft" a duplicate event was created. I think something has introduced a new bug. 
Here are my repro steps...
1. Open any existing event
2. Check the title and click save --> The event is duplicated.

**Comment by troughc** [comment]
Note that this support issue may be the same: https://github.com/culturecreates/tech-support-tickets/issues/7

**Comment by AbhishekPAnil** [comment]
> Note that this support issue may be the same: culturecreates/tech-support-tickets#7

Yes @troughc This is same as the current issue.

**Comment by troughc** [comment]
@AbhishekPAnil  As per our discussion, this issue is partially fixed. However, we still need to address the issue clicking 2 or more times quickly produces duplicate events (if the call to the API has not been completed).

**Comment by saumier** [comment]
> @AbhishekPAnil When I was using CMS in staging, I noticed that every time I edited an event and clicked "Save as draft" a duplicate event was created. I think something has introduced a new bug. Here are my repro steps...
> 
> 1. Open any existing event
> 2. Check the title and click save --> The event is duplicated.

@troughc Please test these in staging

**Comment by troughc** [comment]
@AbhishekPAnil please block the user from clicking save/publish more than once during a API call and add the spinner that you already implemented.

**Comment by AbhishekPAnil** [comment]
@saumier I have also added the success notification messages for different event actions (publish,send to review and save as draft) with this issue.

**Comment by saumier** [comment]
@troughc I tested and pushed to production.

**Comment by troughc** [comment]
This issue came up again in this event: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6494ad65bee1c1006405fd40

I tried saving an event called test test caitlin test in staging, which had a larger image (2.4MB).  I was able to click the button (save) multiple times and ended up with multiple events.

**Comment by saumier** [comment]
@troughc Please test in staging with a new event and a large image.

**Comment by troughc** [comment]
Tested: PASSED
