### ISSUE TITLE
bug: recurring Times lost

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#309]
Times of custom recurring dates are lost.  The workaround is the save the event as draft and then enter the custom date/times.

Steps to reproduce:
1. Edit an event new created by the Aggregator - pick one in staging created by aggregator and that has not been edited yet
2. Add custom dates with times.
3. Add all required fields (name, description, ticket...)
4. Click publish.

Note: This only happens on new events created by the Aggregator. Once an event is saved as draft or published the bug disappears.

**Comment by saumier** [comment]
@troughc Please test in staging. I didn't test this myself. Abhishek pushed this into staging directly.

**Comment by troughc** [comment]
Tested in staging using two different approaches. PASSED
