### ISSUE TITLE
User profile: wrong message when i change my language and save

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#315]
I get the wrong message in staging new cms when i change my language and save (in user profile).
 I get the wrong message that my password has been successfully reset instead of this: 
Success! Your user profile has been updated.   
Succès ! Votre profil d'utilisateur a été mis à jour.

**Comment by AbhishekPAnil** [comment]
@troughc This is actually updated in staging while implementing https://github.com/culturecreates/footlight-app/issues/388.Please do test it out and let me know if there are any issues.

**Comment by troughc** [comment]
Tested in Chrome. The messages seemed right in each test I did (french and english). PASSED
