### ISSUE TITLE
Fix large image upload

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#318]

**Comment by SuhailAliyar** [comment]
As we discuss, let's implement functionality to upload images from Footlight CMS to AWS S3.
Before you push the object(image) to AWS S3, please consider the points below:
1. Create a UUID and change the name of the image with UUID.extension (eg: imageName: 643eb8036f70e40064e0e996.png).
2. You may use the imageName in place of entityId(for original, thumbnail and large) for the events,organization, place and person.
3. As the image server can do compression and caching we need not want to compress the image as in the current implementation.

This [documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html) will help you to implement this feature.

**Comment by SuhailAliyar** [comment]
@AbhishekPAnil  I can peer review this feature once you are done with the implementation.

**Comment by saumier** [comment]
@AbhishekPAnil @SuhailAliyar The image upload looks good. Please go ahead with our plan to do a complete update of CMS, Old CMS and Footlight API in production. :-)
