### ISSUE TITLE
Old cms- cannot delete a place from organization

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#323]
when I try to delete a place from an organization, it doesn't work. 

Steps:
1. open organization (For example Folklore Outaouais in Tout Culture calendar)
2. Go to Place field and try to delete it. The number is removed
3. Update the organization. 
4. Reenter the organization. The organization is back.

**Comment by saumier** [comment]
@AbhishekPAnil I didn't do a review of this and because its late I tried to test this and the other issues directly in staging. However, when I now try to edit an organization I get a white screen. I'm not sure if it is this issue or one of the other 2 that I tested today. Please investigate. Thx.

**Comment by AbhishekPAnil** [comment]
@saumier Have fixed this issue and updated it in staging.

**Comment by saumier** [comment]
@AbhishekPAnil I am still getting a white screen on "some" organizations in staging.

Repro steps:
1. Clear cache and log out.
2. Log in to staging CMS and select Tout Culture calendar
3. Select Organizations and click "Ville de Gatineau"
--> White screen with nothing dispalyed
[Error] Error: You are passing the `delta` object from the `onChange` event back as `value`. You most probably want `editor.getContents()` instead. See: https://github.com/zenoamaro/react-quill#using-deltas


Examples not working:
http://staging.oldcms.footlight.io/admin/add-organization/?id=6425cb44ede2c60065ca06ed
http://staging.oldcms.footlight.io/admin/add-organization/?id=6420c6292831190064570e71

**Comment by saumier** [comment]
@AbhishekPAnil I'd like to deploy the latest CMS to production because it includes many great fixes including the ability to edit the descriptions and search for places.  Let me know if you find the time to fix this before Monday and I will test and deploy. Thx.

**Comment by AbhishekPAnil** [comment]
> I'd like to deploy the latest CMS to production because it includes many great fixes including the ability to edit the descriptions and search for places. Let me know if you find the time to fix this before Monday and I will test and deploy. Thx.

@saumier  I have added a fix and raised a PR for the above.Please do check it out let me know if there any issues .Thanks.

**Comment by saumier** [comment]
@AbhishekPAnil Thanks so much. I am going to deploy to production now.
