### ISSUE TITLE
Missing button "copy contact" for existing event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#327]
The button to "copy contact" should appear when the user selects "+ add Contact" and the organizer has contact info.

Current behaviour: Creating a new event works well, but editing an existing event does not display the button "copy contact" after clicking "copy contact".

Example event:
Veillée dansante
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64413e297a29930064510e68

This event has an organizer and the organizer organization has contact info.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
