### ISSUE TITLE
CMS: Cannot open event "Bleu Jean Bleu"

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#329]
This event cannot be opened in production CMS

Calendar: Tout culture
Name: Bleu Jean Bleu
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64516c01e19f7200646d3c13

Unhandled Thrown Error!
o.toUpperCase is not a function. (In 'o.toUpperCase()', 'o.toUpperCase' is undefined)

**Comment by saumier** [comment]
@AbhishekPAnil Please look into this bug on Tuesday. I also wanted to ask you to add a "catch all" error page when unexpected Javascript errors occur so the UX looks a bit better.  Please treat the original bug as the priority, and suggest a separate issue for adding a "catch all" error page if that makes sense.

This is the message from React:
💿 Hey developer 👋
You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>

**Comment by AbhishekPAnil** [comment]
@saumier There was a malfunction in the data in performer,that's why the error was thrown from the frontend. @SuhailAliyar helped me fix this.Don't know what the exact cause of this problem,we will have to investigate on this.

And yes ,we can treat the "catch all" as a separate issue.

**Comment by troughc** [comment]
@saumier @AbhishekPAnil @SuhailAliyar I just checked the event and it is now published. Just FYI: there was no performer in the originating event or any other event I found via the Artsdata finder (I did see that there is an organization named bleu jeans bleu). Note that in Tout culture, the spelling is different than all other instances, i.e. there is no s on jean.
