### ISSUE TITLE
Front-end error page

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#330]
Add a "catch all" error page when unexpected Javascript errors occur so the UX looks a bit better. 

This is the message from React:
💿 Hey developer 👋
You can provide a way better UX than this when your app throws errors by providing your own errorElement props on

**Comment by saumier** [comment]
@saumier As discussed this morning, please let us know how many pages should be designed. We can start with one "catch all" but if you have ideas on others please propose them and a simple message so we know how to design it.

**Comment by troughc** [comment]
I will work on the design after we get this going.

**Comment by AbhishekPAnil** [comment]
Case : When the backend or api is unavailable
Message : The

**Comment by saumier** [comment]
@troughc Please come back to us with a design for these 2 pages. thx.

**Comment by saumier** [comment]
Current implementation...



![Image](https://github.com/culturecreates/footlight-app/assets/419491/644ee433-9134-4cef-9e35-e119d6dc9c71)

**Comment by saumier** [comment]
@AbhishekPAnil Have you fixed this by catching all errors that are thrown by React?  Without catching you get this message from React: 💿 Hey developer 👋 You can provide a way better UX than this...

**Comment by AbhishekPAnil** [comment]
>  Have you fixed this by catching all errors that are thrown by React? Without catching you get this message from React: 💿 Hey developer 👋 You can provide a way better UX than this...

This has not been fixed.

**Comment by SyamBabu-M** [comment]
Noted. I'll start working on it asap.

**Comment by SyamBabu-M** [comment]
Reassigning the ticket to @AbhishekPAnil.

Current status: The error page is completed. The app is configured to redirect to the error page upon entering the wrong URL or for any javascript error.

Pending: Could not navigate to the error page upon server-side errors(like 500). 

I implemented a middleware for the detection of async errors. Also configured a slice for handling errors and popups.

**Comment by AbhishekPAnil** [comment]
There are two issues related to this issue:
 https://github.com/culturecreates/footlight-app/issues/470 
https://github.com/culturecreates/footlight-app/issues/527

which needs to be resolved.

**Comment by AbhishekPAnil** [comment]
@troughc As discussed the changes for this issue is updated .Please test in staging and check if anything like the below error appears.If it does then its a bug.

Add a "catch all" error page when unexpected Javascript errors occur so the UX looks a bit better.

This is the message from React:
💿 Hey developer 👋
You can provide a way better UX than this when your app throws errors by providing your own errorElement props on

**Comment by troughc** [comment]
Tested staging on Chrome @AbhishekPAnil 

There are issues - it's not working for me. Maybe related to the "Something went wrong. Cannot read property 'split' of undefined" error?

Some examples 
### 1. I cannot see any places or persons (empty listings)


### 2. I got this error page when I was logged in as a GUEST

<img width="1006" alt="Screenshot 2023-08-17 at 11 32 26 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/babd011b-170d-4bfd-9219-84367649a5d0">
<img width="1352" alt="Screenshot 2023-08-17 at 11 37 46 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/7c6fcded-b305-4ca8-b625-15b5d32c50a8">


### 3. Logged in as ADMIN Organization details page -  test of a page that doesn't exist (404), it looks like it works. Logged in as ADMIN
screenshot: 
<img width="571" alt="Screenshot 2023-08-17 at 11 43 06 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/a36b580d-a356-4599-901e-57b4231716ac">
**However** when I click the back button (retour) I am not taken back. Instead, the error page just keeps reloading. And this is the URL that keeps reloading: http://staging.cms.footlight.io/*
screenshot of page: 

### 2. Logged in as ADMIN Event listing page with this bad url that I made up: http://staging.cms.footlight.io/dashboard/6308ef4a7fa/events?page=1&order=asc&sortBy=startDateTime
No error page loads. 
Instead I get this happening (2 screenshots, first one shows errors, the second one shows that no calendar is selected):
<img width="953" alt="Screenshot 2023-08-17 at 11 44 41 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/637711bf-cfcb-4d6f-99c0-20c15c34aa36">
<img width="1325" alt="Screenshot 2023-08-17 at 11 47 55 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/c67d4220-5685-40c7-824b-93358a4a766e">

To get out of it I had to select a calendar from the dropdown.

### 3. Logged in as ADMIN non-existing event details page with made up numbers in URL. **This happened between 11:50 and 12:03 my time.**
I changed the number for the Jam Trad event to this: https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/645bb7957db98f0065
- It generated the error, but then I couldn't go back to the main page (same block as #1); 
- I removed the * and went back to the listing page 
- I tried to go into the Jam trad event and I got the error page right away with the popup "Something went wrong.
Cannot read property 'split' of undefined" so I cannot get back into JamTrad. I tried to enter a different event, and I could not enter it either (got the error)
- did a hard cache reload and I still can't enter JamTrad
- logged out and logged back in - still doesn't work.
- closed the browser tab and came back - after awhile Jam Trad reloaded...

**Comment by troughc** [comment]
This is set up in an S3 bucket. (amazon)

**Comment by SyamBabu-M** [comment]
@troughc For any API that fails and returns a status 403(unauthorized),400(bad request), or 500(internal server error) errors we redirect the app to an Error Page with the heading "oops something went wrong". Please note that for these errors, the message we are showing is the same error message from the notification popup. Please let me know if any specific messages need to be displayed for each of these cases.
Page not found errors (when we search for incorrect URL) are redirected to the error page with a 404 error specific image.

**Comment by saumier** [comment]
![Image](https://github.com/culturecreates/footlight-app/assets/419491/151d7a8f-cd21-4abb-9b55-1246ed474e40)

**Comment by troughc** [comment]
Tested for the 404 errors: PASSED
Tested for internet cut at my end: PASSED
can't test other 500 errors so am closing.
