### ISSUE TITLE
Edit Custom dialog - update: days of week with dates on right side; always display selected year on left

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#335]
In the custom dialog dates 
on the RIGHT: 
- please show the days of the week with the date. for example, **Mon** May 22, **Tue** May 23 etc. 
- Also, when you select weekly and choose certain days, the dates are grouped by each day of the week (for example, Mondays, Tuesdays, Wednesdays etc). So it is important to show the days in order to navigate. 

**Format in English:**  `<shortform day name>, <month> <date>. <year>` like this (**with commas**):  
Mon, May 22, 2023
Sun, May 21, 2023

**Format in French:** `<shortform day name>. <date number> <month> <year>` like this (**with one period**): 
Lun. 22 mai 2023
Dim. 21 mai 2023

On the LEFT
- please always display the year selector that is at the top of the calendar, even when people are scrolling through the months (so they can change the year when they need)

**Comment by troughc** [comment]
caitlin to add format for english and french

**Comment by saumier** [comment]
@troughc Please test in staging.
