### ISSUE TITLE
Edit Custom Dates dialog - update: make entering time the same as everywhere else.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#337]
When you enter a time in the edit custom dialog that has only one digit at before the column you have to enter a 0 (you have to enter 2 digits). Make this work the same way as in the Date-Time module (you don't have to enter a 0 first in order to get the enter button to appear).

**Comment by SyamBabu-M** [comment]
@troughc Currently antd does not provide any provision to access the input while the user is typing in the Date-picker. Without getting the dates it's not possible to make the changes that are proposed in this issue.
I have found an [issue](https://github.com/ant-design/ant-design/issues/18743) created on antd's GitHub page that proposed a feature into the date picker that will help us implement this feature but unfortunately, they are not planning to implement it right now. 
We can look for workarounds but it will be a lengthy process and the result will be uncertain.

**Comment by troughc** [comment]
Given the current limitation in AntD mentioned above, we are closing without doing this issue.
