### ISSUE TITLE
calendar logo image gets distorted when you reduce the width of the browser

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#343]
![Image](https://user-images.githubusercontent.com/64489312/239356821-e780cf17-6bbc-4402-a7f6-19ffc1484a48.png)

**Comment by saumier** [comment]
@SyamBabu-M Reminder about the procedure. If you want this tested please assign to someone to test: usually Caitlin for UX or myself for API.

**Comment by saumier** [comment]
@SyamBabu-M I assigned this to @troughc Caitlin.

**Comment by troughc** [comment]
Tested in Chrome on STAGING: PASSED
