### ISSUE TITLE
Display localized pricing using comma for decimal symbol in fr

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#353]
Let's discuss. See https://github.com/culturecreates/footlight-app/issues/317

**Comment by AbhishekPAnil** [comment]
@saumier Would this be for french calendar or a user who has french interface ?

**Comment by AbhishekPAnil** [comment]
For estimate details please refer to #317

**Comment by saumier** [comment]
> @saumier Would this be for french calendar or a user who has french interface ?

This issue is the display for a user with a french interface (UI).  The data should always be stored with a decimal point in the database and then the UI can localize the display for different regions. Currently we only localize for 2 regions: Canada english (25.50) and Canadian french (25,50).

**Comment by troughc** [comment]
Tested in chrome and safari: looks good ! PASSED for me but assigning to @saumier to answer the question below

Question for @sahalali or @saumier : this is implementd by changing the display of price according the the UI language choice. so in english we use a period (.) and in french it's a comma (,)

Does it matter for the API and delivery to the frontend? For example, Signe laval is monoligual and I work in an English UI. So the price is displayed in the CMS with a period. But when it goes to the website, it has to be a comma. Is that what will happen? If yes, please move to done @saumier

**Comment by sahalali** [comment]
It will not make any impact in the backend until the datatype of the price sent to the backend is not changed. The price should be a number always.
I hope the change done here is just impacting how it is displayed but not any payloads.
cc @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
The change done here is just for display purpose.The payload data type has not changed ,it is the same as before.

**Comment by saumier** [comment]
@troughc @sahalali @AbhishekPAnil It looks like all questions have been answered so I can moving this to done.
