### ISSUE TITLE
Signé Laval event types not saved

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#354]
Check events by user cchanel
https://cms.footlight.io/dashboard/63457978637093005071a053/events?page=1&order=asc&sortBy=startDateTime&users=64650d25ad41e5006435552b

**Comment by AbhishekPAnil** [comment]
@dev-aravind This bug seems to occur only when the user tries to create an event and tries to save/publish for the first time.The dynamic fields somehow doesn't seem to persist in the backend
