### ISSUE TITLE
unexpectedly kicked out of CMS mid work

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#386]
If I leave Footlight CMS open over a long period of time (over 24 hours) the token will expire and I have to log in. 

Sometimes, I have been in a single sesssion for that long and I am working on an Event Details page (or I left it open in my browser on an event details page overnight and I am returning to work on it, i.e. I show the tab in my browser)

I start adding more event details and then, suddenly, I am forced out to the log in page with multiple non autorisé / not authorized messages being displayed. 
- this may be happening when I try to add another entity, or maybe event add a controlled vocabulary (the second case needs more testing to be confirmed).

As a user, I don't know what happened, i.e. I don't know that my token expired. I also am frustrated that I did more work that wasn't saved.
It would be better if I could be sent to the log in page right away (or if I could be logged in in place and my work not lost). 
I don't know what is possible. what options are available for either notifying a user right away or allowing them to save their work before they quick. 
Potential issue with saving their work a long time after they started it.
- if some other user made changes to the event in the interim, this would cause a conflict with which version is the most up to date.

**Comment by troughc** [comment]
@saumier please take a look at this issues and let me know if the description works for you guys. cc @AbhishekPAnil @dev-aravind

**Comment by saumier** [comment]
Gregory wants to check if how the token is set: max 24 hrs or 24 hrs inactivity.  It should be inactive for 24 hrs.

**Comment by saumier** [comment]
@SuhailAliyar Please create a sequence diagram to show how the session expiry works

**Comment by saumier** [comment]
Here is some reference: https://dekh.medium.com/the-complete-guide-to-json-web-tokens-jwt-and-token-based-authentication-32501cb5125c

Are we using access tokens and refresh tokens?  

Exerpt: Each token has its own lifetime, for example access: 30 min, refresh: 14 days.
This means that after 30 minutes the access token will expire and the client will try to renew the token, but if the user does not interact with our application within 14 days, the user will be automatically logged out.

**Comment by sahalali** [comment]
@AbhishekPAnil The backend changes are now merged to the develop branch and are now live in staging. 
Please use the new API to refresh the access token after timeout.

**Comment by troughc** [comment]
Test on chrome:
my token ran out and I was taken to the log in screen. This works fine for me.

**Comment by AbhishekPAnil** [comment]
@troughc Now ,ideally a user should only be redirected to the login page if he has not visited the cms for the past 14 days.Othewise the user will have continuous access to the cms without being logged out.

**Comment by sahalali** [comment]
I took into the issue and identified that the refresh token is expiring at the same time as the auth token. It was because of the configuration in the deployment script. 

The deployment scripts are updated and it looks good to me.

**Comment by troughc** [comment]
Test to see if I am logged out after 24 hours - PASSED (I am still logged in after 28 hours). Thanks!
