### ISSUE TITLE
multiple dates - occurrences with days of week not working properly for weekly / daily recurring events.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#387]
I tested this in Chrome and Safari, in production and staging.
After saving a multiple date event as draft (weekly recurring) two things are happening :
- when I reopen the event, the number of occurrences does not update when I try to add additonal days of the week.
- The number of occurences doesn't match the number of actual occurences

See these three events for examples:
in PRODUCTION (created in CHROME): 
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6478b5418b11c40064876f33 
- this one shows the wrong number of occurences: 17 instead of 8 in both event details and event listing.
- you can try to add additional days of the week, and nothing changs in the ui (event details). I didn't try saving after trying to add. (Adding additional days of the week won't change number of occurrences)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d0e735a8-0bdb-46a6-a6af-9ce901dff58c)

In staging (all created in SAFARI): 
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6478b5f5d7c48e0065a82a83
- 14 occurrences instead of 11. 
- Adding additional days of the week doesn't change number of occurrences

http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6478b47dd7c48e0065a8297d
- this one shows the correct number of occurrences. The only difference with this one is that I entered the Edit dialog (but didn't save my changes).
- Adding additional days of the week doesn't change number of occurrences

This is also happening iwth daily recurring. See this event, created in SAFARI:
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6478b916d7c48e0065a82bc8
- after saving as draft, the number of occurrences changed from the correct number (27) to a wrong number (30)

**Comment by saumier** [comment]
@troughc I am not sure I understand how to test this one. I deployed to staging so you could have a look and test. Thx.

**Comment by troughc** [comment]
Tested in Chrome: PASSED
Tested in SAFARI: PASSED
