### ISSUE TITLE
Cannot enter a row of custom dates

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#403]
As a user of CMS, when I am creating an event with custom dates, I cannot enter a week of dates.  When I click a single date, the calender jumps to the first month of the year. When I click and drag to select a week of dates in a row, the dates are added to the list on the right, but the calendar display has the week shifted back 1 day. When I try to click the last date again, it adds it to the calendar display but removes it from the right side list. See video.

Tested on  MacOS Monterey 12.6.5 with Chrome and Safari in the production environment.

https://youtu.be/WLPlUgsLOoY

**Comment by troughc** [comment]
@saumier FYI Abhishek and I looked at this together (in staging) in both Chrome and Safari. It is working in my browsers, yay! 
@AbhishekPAnil explained that the issue was caused by a date format.

**Comment by saumier** [comment]
@troughc @AbhishekPAnil Great news. That was a tough one. Really glad it is fixed. I'll deploy the latest CMS to production now... and close this issue.
