### ISSUE TITLE
Displaying logos in Edit event details page

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#408]
This issue is about displaying the logo for an organizer/performer/supporter if it has been added to the organization. 

A logo should be displayed in the Event details page when the organization with a logo is selected from a dropdown for Organizers, Performers, Supporters. If the logo has not been added to the organization that is selected, you would display the placeholder icon as is done today.

**Comment by AbhishekPAnil** [comment]
@sahalali @dev-aravind We need to add the (organizer and person) logo details in the "/entities" api .

**Comment by AbhishekPAnil** [comment]
Added support in the UI to display the organizer and person logo.

**Comment by AbhishekPAnil** [comment]
@sahalali Please assign it back to me after this has been udpated in staging.

**Comment by sahalali** [comment]
Added support to include image and logo details with person and organization respectively.

**Comment by troughc** [comment]
Tested staging in Chrome for all three fields (organizer/performer/supporter): PASSED
