### ISSUE TITLE
filter selection issue when log in as guest

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#412]
At 13:26 EST I logged into the footlight cms (production) several times as a guest:etroughton(guest) profile.
Each time I logged in the User filter displayed as having 1 option selected, but none are selected (I scrolled through the entire list of users and none are selected).
Also, no Events are displayed.
Screenshot:

![Image](https://user-images.githubusercontent.com/64489312/247640280-1f712d12-2093-4e89-826d-2de42c4535dc.png)

This is still true after doing a hard cache reload.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/b0a7a049-6d5d-421e-af16-a9f133930732)

Then, I cleared the filter (using the clear button). Here is the result.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/1550f51b-3be7-4045-aa6f-c7390a3c2ddd)

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by troughc** [comment]
Tested: this no longer seems to be happening. PASSED
