### ISSUE TITLE
Feature enhancement: Date filter design change - filter by timespan

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#413]
### User story:
I want to be able to quickly filter events as follows:
past events
upcoming events
all events
And I want to be able to select a specific date range. 

### Problem and Solution
Right now, it is hard to find the first three options. To make this easier we need to elevate the visibility of these options. New design of the Date filter would use a combination of a dropdown selection list, with one option that would open a date range calendar. Only one option can be selected at a time. 

The options for this new design are:

English:
All events
Past events
Upcoming events
Date range

French:
Tous les événements
Evénements passés
Événements à venir
Plage de dates

When one of the options is selected, the filter closes and displays the selection on the button.
Note that when Date range/Plage de dates is selected, a full date range calendar will be displayed for the user to select their date range (no intermediary click) before closing the filter.

**Link to Ready for DEV FIGMA**: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=6869-133033&mode=dev
Note: ignore what is shown in the Figma for the other filters. The only thing to change with this ticket is the date filter.

**Comment by troughc** [comment]
@saumier see design here: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4043-92912&mode=design&t=zbX54HV7fZtKrREp-4

**Comment by saumier** [comment]
@troughc  Thx for the link.

**Comment by AbhishekPAnil** [comment]
https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit?pli=1&disco=AAABAyG-MnE

**Comment by troughc** [comment]
@AbhishekPAnil just FYI - the translations are already in this issue at the top (first comment/description) - I am now adding them to the spreadsheet as well.

**Comment by AbhishekPAnil** [comment]
@troughc As per our discussion,please discuss with stephanie if she can use our existing date picker component in the date filter. Thanks

**Comment by troughc** [comment]
@AbhishekPAnil the date picker is updated in the figma.

**Comment by AbhishekPAnil** [comment]
As per our discussion, I am assigning this to you @troughc .Please meet with Stephanie regarding the calendar pop up restriction we have.

I will also search and find the calendar component that I found earlier which matches our purpose and add it to this issue. Thanks

**Comment by troughc** [comment]
@AbhishekPAnil I have added a comment and revision to the figma - please take a look.

**Comment by troughc** [comment]
@AbhishekPAnil the figma has been updated. we will use another approach - use the radio buttons and then, if you choose date range, the buttons go away an the current modal appears (without the 'All events' and 'Passed' at the bottom of the calendar. We can discuss if needed.

**Comment by AbhishekPAnil** [comment]
Estimation for adding antd design and functionality- 20-25h
1.Add the css to the calendar :10-16h
2.Add/Rework on the functionality of selecting the date filter : 6h
3.Implement the design in figma for date filter design pop : 3h

**Comment by AbhishekPAnil** [comment]
@troughc The changes are complete with new calendar component.I would like to demo it to you before updating it in staging.Thanks.

**Comment by troughc** [comment]
Tested staging on chrome and safari. PASSED
