### ISSUE TITLE
Listing page for Organization, Person, Place

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#418]
As a user of CMS, I can view the list of entities.

Tasks
=======

- [x] Add the layout which is common for Organization, Places,People
- [x] Create the listing component which can be reused in People,Places,...
- [x] Add api integration to show all the organizations including pagination.
- [x] Add the translations for respective texts.
- [x] Add routing for read only page
- [x] Add api integration to delete an organization,place or people.

Toggles
=======

We are planning to deliver all 3 entity classes together, so to avoid having too many toggles I propose a toggle called: 
REACT_APP_FEATURE_FLAG_ORG_PERSON_PLACE_**VIEW**=true

This will toggle the 3 menu items in the left navigation. When toggled on, the user will be able to click any of the 3 links to view organizations, people and places list and read-only screens.  But not edit or delete.

For editing including searching/creating/updating/deleting, which will be delivered to customers after we deliver the read-only views, we can use another toggle called:
REACT_APP_FEATURE_FLAG_ORG_PERSON_PLACE_**EDIT**=true

**Comment by AbhishekPAnil** [comment]
@dev-aravind 
1.Please add pagination and search options to organization ,person and places listing api.Also there is a filter for organization listing named "Member type" .
2.Also , please add the details of the  modifier for the organization ,person and places listing apis

**Comment by troughc** [comment]
@AbhishekPAnil  I noticed for the Organization listing page: the spacing is too big in between the title and the description for each org and the organization icons are also too big and too dark. Please check the Figma to see how to adjust the color. Places and people are okay so you can align it to those listing pages. Thanks

**Comment by dev-aravind** [comment]
@AbhishekPAnil I tested the getAllOrganizations API in the staging server by the URL https://staging.api.cms.footlight.io/organizations, with the calendar ID:6308ef4a7f771f00431d939a. The modified list was returned during the trial. Can you please check again and revert me back if you find you find any issues

**Comment by dev-aravind** [comment]
@AbhishekPAnil the pagination, search and modifier features have been updated in staging.

**Comment by AbhishekPAnil** [comment]
Updated the search and modifier details in UI.

**Comment by troughc** [comment]
Tested: 
there is a spacing issue after the subtitles on the Read only pages- I think there is extra space below the subtitle (for example, below "Details" on the People and Organization read only pages; below Address on the Place read only page)

**Comment by AbhishekPAnil** [comment]
> Tested:
there is a spacing issue after the subtitles on the Read only pages- I think there is extra space below the subtitle (for example, below "Details" on the People and Organization read only pages; below Address on the Place read only page)

Updated the spacing issue in staging

**Comment by troughc** [comment]
Tested in Chrome - PASSED ! :)
