### ISSUE TITLE
Read Only Page for Org, Person, Place

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#420]
As a user, I can click an entity in the list and view a read-only page of the details.

Tasks
=====

- [x] Add the layout for read only page which is common for Places and People
- [x] Reuse the components and css from the event read only page
- [x] Api integration to get the details of current organization
- [x] Extra api integration for taxonomies if needed

Toggles
=======

Same toggle as the listing pages

**Comment by AbhishekPAnil** [comment]
Reminder for @AbhishekPAnil 
Changes to be added:
1)Additional taxonomy field details for person and orgs.
2)Arts data link if present to be shown in people,places and orgs

**Comment by troughc** [comment]
@AbhishekPAnil I was playing around with the new read only views, and I have a question: for the Artsdata link at the top, are you using the disambiguating description?  I saw for some organisations, it says 'organisations'. I also noticed that there is a little spacing issue with the link icon (you may already know this). And that it's not displaying the info in the way I'd like it to (the figma wasn't consistent sorry) 
You can see these issues in this screenshot:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8d2bbcdd-19f8-4041-83ab-57afbd20cf91)

The way to display the links has been updated in the figma. Please take a look at the components section

And here are examples for displaying the data when the disambiguating descripition is short (from a read only page) or long  (from an Edit page)




![Image](https://github.com/culturecreates/footlight-app/assets/64489312/72995fe2-75db-478c-a23d-e7ba0874632f)





![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8abef51a-0ea3-4c3c-a02f-a398e1f06b92)


I am going to tag you to the components section in the figma. Thanks!

**Comment by AbhishekPAnil** [comment]
@troughc Yes I am using the disambiguating description .Some organizations have "organisation" as their disambiguating description.

**Comment by troughc** [comment]
Tested on chrome (staging): PASSED
- layout is good
- links work as expected
- artsdata blue link at top looks good
-
