### ISSUE TITLE
Event page - Read only is missing data

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#462]
When i view an event as a guest (therefore, read only), some of the entity blocks are missing. For example, in the screenshot below, the organizer and performer blocks are missing. I will show the Admin login view (edit) and then the guest login view (read only)

### Admin view SCREENSHOT:

![Image](https://user-images.githubusercontent.com/64489312/258459183-2f4da8af-da2f-4a3a-bf66-c8606446ab3d.png)

### Guest view SCREENSHOT:

![Image](https://user-images.githubusercontent.com/64489312/258459219-c603b673-2154-4679-82b7-c0ef44ca6c31.png)

### More Details

The following events (tout culture) are some examples that have discrepancies between the read only view and the edit view - maybe it is a permissions issue? 
UPDATE August 22, 2023 - only the following event is still in the database

mariana mazza (missing organizer and perfomer):
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64515af7e19f7200646d0c7a

**Comment by sahalali** [comment]
This looks like a UI related issue.
assigning to @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
@sahalali @troughc This was a UI related issue.I have fixed the issue and updated in staging .Please check and let me know if there are any issues.

**Comment by troughc** [comment]
Tested in Chrome (staging): PASSED

**Comment by saumier** [comment]
@AbhishekPAnil Please add a message somewhere with `closes #462` so when this gets merged to the main branch this issue will be closed.

**Comment by troughc** [comment]
Tested: PASSED

**Comment by AbhishekPAnil** [comment]
@saumier Added closes #462 as a description to the respective pull request.
