### ISSUE TITLE
Production release: latest version of Footlight backend / front end and old CMS on Monday August 7

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#463]
@sahalali  please go ahead and release the read only, quick create and listing pages as discussed on Monday during the release window. See you at the next standup!

**Comment by sahalali** [comment]
Updated production to the latest footlight calendar APIs, Footlight-admin (OLD CMS) and Footlight-app (new CMS). :tada:
Release notes:
[footlight-calendar-api v1.10.2](https://github.com/culturecreates/footlight-calendar-api/releases/tag/v1.10.2)
[footlight-admin v1.10.2](https://github.com/culturecreates/footlight-admin/releases/tag/v1.10.2)
[footlight-app v1.10.2](https://github.com/culturecreates/footlight-app/releases/tag/v1.10.2)

**Comment by troughc** [comment]
Thank you so much - it is looking awesome. One small thing: IN PRODUCTION: (cms.footlight.io), occupation is missing from the Signe Laval calendar Quick Create person. Can you fix when you have the chance @AbhishekPAnil or @SuhailAliyar (tomorrow is fine).

Screenshot of Quick Create Person (french UI) in **Signe Laval CMS**:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7368a4ea-0ce8-411e-858d-a4d2fba6a9f7)

Note: The occupation field is displayed for Tout Culture, just not for Signe Laval.
good screenshot of Tout Culture (english UI)



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/32c535c5-489d-4224-922d-e5db142790f4)

**Comment by sahalali** [comment]
@AbhishekPAnil Can you please look into this issue?

**Comment by AbhishekPAnil** [comment]
Added occupation taxonomy  for signe laval calendar in producation.

**Comment by sahalali** [comment]
@AbhishekPAnil Are we restricting the field if no taxonomy is linked to the standard field?
Example: If there is no taxonomy mapped to Class: Person and mappedToField: occupation, will "Occupation" not displayed in CMS? If yes, is this is identical in the other forms?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil Are we restricting the field if no taxonomy is linked to the standard field?
> Example: If there is no taxonomy mapped to Class: Person and mappedToField: occupation, will "Occupation" not displayed in CMS? If yes, is this is identical in the other forms?

Yes ,if there is no taxonomy mapped to a field then it wont be shown in the forms and yes it is identical in the event forms which we have done.I thought of continuing the same approach in the rest forms as well.
Is there a change needed?

**Comment by troughc** [comment]
> > @AbhishekPAnil Are we restricting the field if no taxonomy is linked to the standard field?
> > Example: If there is no taxonomy mapped to Class: Person and mappedToField: occupation, will "Occupation" not displayed in CMS? If yes, is this is identical in the other forms?
> 
> Yes ,if there is no taxonomy mapped to a field then it wont be shown in the forms and yes it is identical in the event forms which we have done.I thought of continuing the same approach in the rest of the forms as well. Is there a change needed?

@sahalali I closed this issue because fixed my bug. But then i realized you had an outstanding question - did I close it too soon? Feel free to reopen.

**Comment by sahalali** [comment]
@troughc That looks good to me. I am okay if the behavior is identical across all entities(forms).
