### ISSUE TITLE
Avoid multiple pop error messages

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#470]
Handle the multiple pop errors which occurs due to 400 or 500 series errors.For example : unauthorised errors,server down.
```[tasklist]
### Tasks
- [ ] Multiple pop up error
- [ ] Redirectig to Error page when the HTTP response code is 500.
```

**Comment by troughc** [comment]
Tested on chrome in staging:
@saumier,  it looks like I am only getting one popup when I generate an error, but I am not completely sure as  I am not confident about how to redirect to the error page (also to generate a code 500). Maybe we could test this together? Or I could pass it to you?  
Thanks!

**Comment by saumier** [comment]
@troughc This looks good for me so I would close it. My only comment from a UX point of view is that error messages that look very technical - like "o.toUpperCase is not a function. (In 'o.toUpperCase()', 'o.toUpperCase' is undefined)" - should be more hidden from the users. Visually I make them hidden inside an accordion with the label "Error message for developers" or something. This would be a low priority.
