### ISSUE TITLE
Calendar selection

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#50]
There are many errors related to switching calendars not behaving as expected.

**Consider a complete reboot of all states when the user changes calendar as this is a very rare event (does not need to be performant), and should really reset everything to a safe initial state including query params and pagination.**

Known errors:
- [x] First time user blank screen - when I log in for the first time ever (no history) no calendar is selected and I have a blank screen. Tammy had this experience and I can reproduce by clearing my browser. See screen grab below. 
- [x] Calendar list - when you switch to Signe Laval, the name 'Signe Laval' is missing. This is fixed in all versions except MOBILE - the name "Signe Laval" isn't displayed on mobile.
- [x] Calendar list (ENHANCEMENT) dropdown for calendars - if only one calendar, you don't need to use a dropdown menu; only use this dropdown component if the user has access to more than one calendar. 
- [ ] User can switch to other calendars when not a member - see repro steps below.  
- [x] Calendars not switching : when I am logged in as an Admin with access to both calendars, it doesn't switch properly from Tout Culture to Signe Laval if I am on PAGE 2 of the event list (Tout Culture). It takes me to a blank screen with no way to navigate. See repro steps below.

Caitlin's reproduction steps for Calendar dropdown bug:
1. I logged in as caitlin+guest (collaborator on tout culture but NOT on signe laval).
1. The dropdown is there and shows both calendars.
1. I switch from Tout Culture to Signe Laval and I STILL see the tout culture events.
1. I refresh the browser (reload) and the Event page is now blank for signe laval (no events are shown).
1. I switch back to tout culture and see my tout culture events (they are displayed).
1. I repeated these steps multiple times with always the same results.

One note: the main problem with the last issue (calendar dropdown) is: as caitlin+guest, I shouldn't be able to navigate to Signe Laval at all as I am NOT a member of that calendar.

Caitlin's reproduction steps for Calendars not switching bug:
1. Log into profile with access to 2 calendars.
1. start in tout culture. Go to page 2.
1. Switch to Signe Laval. No events are displayed and I cannot refresh to see anything.
1. I am stuck, I have to go back to tout culture, display page 1 and then switch. This properly displays signe laval events.

![Image](https://user-images.githubusercontent.com/419491/206512423-c417e758-2e3f-4c33-8d36-1913d21ce27f.png)

**Comment by saumier** [comment]
@troughc Please test and close if pass. You can test here http://staging.cms.footlight.io

**Comment by troughc** [comment]
Tested and passed! 💯
