### ISSUE TITLE
Quick Create - first dialog box not right for performer and supporter

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#523]
when I have to create a new organization or person for the event supporter or Performing group/artist/event animator fields, the title and sentence that appear at the top of the FIRST dialog box don't fit. Right now all fields that use quick create get this dialog first (titled 'Create an organizer'):

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/e0560a26-7036-4843-8923-6bb5ff90471c)

 Let's change it to something more generic that will work for all fields.

ENGLISH
Title: Quick Create
Sentence: What do you want to create?

FRENCH
Title: Création Rapide
Sentence: Quel type de profil voulez-vous créer ?

**Comment by troughc** [comment]
@AbhishekPAnil maybe I could make this change (since it is in the language file).

**Comment by AbhishekPAnil** [comment]
Tested in staging:Passed

**Comment by troughc** [comment]
@AbhishekPAnil the modal is correct in all cases (so in that sense this issue gets a PASS), but we have the error "Something went wrong. Cannot read property 'split' of undefined" 
Should I close this issue anyway as we are dealing with the error message separately?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil the modal is correct in all cases (so in that sense this issue gets a PASS), but we have the error "Something went wrong. Cannot read property 'split' of undefined" 
> Should I close this issue anyway as we are dealing with the error message separately?

I think we can close this issue since the  error that pops up is a separate issue.
