### ISSUE TITLE
Handle the backend downtime errors in frontend

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#527]
When the backend is deployed to production or staging during the deployment window, the corresponding downtime should be handled in frontend.Right now in the listing pages , "No content" is shown when the api response is 502.There should actually be an error message corresponding to this that should be shown in the UI.

**Comment by sahalali** [comment]
@troughc In this case, it makes more sense if we have a "Server under maintenance" page when the backend is down or under maintenance.

If you agree, can you please check if we have a design for the same?

**Comment by troughc** [comment]
This page is for the 502 error All other 500 series of errors to to something went wrong @SyamBabu-M 
502 Only displays this page

cc @sahalali

**Comment by troughc** [comment]
HI @sahalali, here is the design for the 502 error.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/1fc46dba-727a-4aab-b5b6-ffccf90242de)

**Comment by SyamBabu-M** [comment]
@sahalali I have created the page UI. Please add the necessary backend configurations.
