### ISSUE TITLE
Quick Create: latitude/longitude should be added automatically when the address is added

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#537]
When a user creates a place (using quick create), the latitude/longitude should be added automatically when the address is added. Right now, it is missing.

**Comment by troughc** [comment]
@AbhishekPAnil Please confirm - I think this is no longer an issue - it is already fixed right? I see coordinates when I add a new place, for example this one: http://staging.cms.footlight.io/dashboard/63457978637093005071a053/places/6526ac820f083100645c1635

**Comment by troughc** [comment]
As per our discussion - I missed that this is QUICK CREATE - so it is not yet done. Thanks @AbhishekPAnil . :)

**Comment by AbhishekPAnil** [comment]
> As per our discussion - I missed that this is QUICK CREATE - so it is not yet done. Thanks @AbhishekPAnil . :)

I tested it out while doing issue [#28](https://github.com/culturecreates/tech-support-tickets/issues/28) and i think it seems  working.

**Comment by troughc** [comment]
Tested  staging in Chrome - PASSED
