### ISSUE TITLE
Bug: 'o.toUpperCase' is undefined

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#566]
While in CMS, click on the event "The TWO" to view event details. Error: ['o.toUpperCase' is undefined]

http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=asc&sortBy=startDateTime&query=The+TWO

Happening in both staging and production.

**Comment by AbhishekPAnil** [comment]
@saumier This issue is fixed by @sahalali in staging .Please check and let me know if there are any more issues.

**Comment by saumier** [comment]
The event Salabarbes has a performer with multiple types http://artsdata-satellite-viewer.s3-website.ca-central-1.amazonaws.com/index.html?adid=K10-293

The event The TWO has a performer with multiple types: http://artsdata-satellite-viewer.s3-website.ca-central-1.amazonaws.com/index.html?adid=K10-539
