### ISSUE TITLE
Trim data entry fields

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#568]
When entering strings into forms, user's sometimes copy/paste with an extra space in front of the name. This is very hard for a human to see. But it causes problems for sorting, and searching for computers. 

The data entry fields should trim strings by removing blank spaces in front and also trailing.  This applies to all string fields including name, alternate name, etc.

Also trim '\n' which represent hitting enter to create a new line.

Related to alphabetical sort order issue: https://github.com/culturecreates/footlight-calendar-api/issues/386

**Comment by troughc** [comment]
@saumier is this still an issue?

**Comment by saumier** [comment]
@troughc Abhishek says this is still a feature.

**Comment by AbhishekPAnil** [comment]
Added the trim functionality to all multilingual and normal input fields.The changes are updated in staging .
Closes tag added to commit [2640d95](https://github.com/culturecreates/footlight-app/pull/871/commits/2640d952e58999cdb2a8d06f4c6e0101ae0c8855).

**Comment by troughc** [comment]
Tested staging on Chrome: PASSED
Tested staging on SAFARI: PASSED
