### ISSUE TITLE
unhandled error in production at 11:33 AM montreal time

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#572]
I get an unhandled error every time I try to open this event from the event list:
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af64683c19fa0064e772c7

Calendar: Tout Culture
Event name: Salebarbes\
Time: 11:33 AM montreal time
This event was updated by the aggregator earlier today. 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a5ad53b7-ba60-47b9-a079-e3df666b1d84)

**Comment by dev-aravind** [comment]
@troughc I've fixed this issue and it'll be up in staging once the changes are merged.

**Comment by saumier** [comment]
@troughc This is the same bug as issue #566 with event The TWO.

**Comment by troughc** [comment]
@saumier do I close this issue then since you are tracking it in https://github.com/culturecreates/footlight-app/issues/566?

**Comment by troughc** [comment]
In any case, it now seems fixed for my event: PASSED.
