### ISSUE TITLE
The CMS break if a virtual location has no name.

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-app#581]
The CMS break if a virtual location has no name.

**Comment by troughc** [comment]
I need more details to be able to do an appropriate test. Thanks.

**Comment by troughc** [comment]
Tested and I got an error when I tried to publish this event: http://staging.cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/64ff745ef9daec0064e82af2

Note that the error message from the backend is in English even though I am using the frenchUI


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a6df025a-b0a1-4126-98f3-715a0679c989)

**Comment by sahalali** [comment]
@troughc 
The errors from the backend are not language specific. All the error messages are in English.

**Comment by sahalali** [comment]
Update publish event logic for Virtual locations. We can now publish events having no physical place linked, but a virtual location with at least a name or URL.
