### ISSUE TITLE
Event page: performer with english name only not showing name in component

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#582]
For this event: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/64f95cf77d6aa80064356f1b
For this organization: https://cms.footlight.io/dashboard/63457978637093005071a053/organizations/64fec8e0a59a070066bd994f

The above event came in with an organization in the Performer role that only had a name@en "Comment Debord"
(the name in Artsdata was only available in name@en)

This meant that the name didn't appear when you were using the french UI. 

Signe Laval is a monolingual site - french only.

The bug is as follows: the name ALSO didn't appear when I switched to the English UI for Signe Laval (the component remained blank where the name should appear). 

I had to add the FRENCH name for the customer (in production) so unfortunately, we cannot reuse this event to debug this issue. Unless you can recreate the conditions in Staging. 

To debug and test this, we have to create an organization for Signe Laval that does NOT have the name(fr) field filled - only name(en).  I wasn't able to do this from the CMS (old or new). then we can see that the name also doesn't appear in the English UI.

cc @saumier

**Comment by saumier** [comment]
@troughc I think the UI should display the "english" name when the UI language is in French as well. Otherwise how can the user know which entity.

**Comment by AbhishekPAnil** [comment]
Fixed and updated in staging .
Added closes tag to commit [f80050a](https://github.com/culturecreates/footlight-app/pull/693/commits/f80050aa73b94a39677eaca95a0395e932c94ce5)

**Comment by troughc** [comment]
Tested staging in Chome:
I was able to see the name of an english organizaiton (wth no french language properties) that I imported from Artsdata: PASSED

Note: next step (different issue) will be to display the properities in the form (in the other language literal, in this case showing english language literals in a french only site). 
The organizaiton I imported is called Sanderson if you are curious (imported to Signe Laval staging).
