### ISSUE TITLE
Description missing from People design edit screens

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#609]
Description field is missing from People Edit screen - needs to be added to the FIGMA

Screenshot example of edit screen for a person (Christine Morency in Tout Culture) - MISSING the description field:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/875de554-b521-422a-bc0b-37a372690181)

screenshot of Read only screen of same person with a Description:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/efb18692-14db-4457-8b2b-4220a05fa38c)

**Comment by dev-aravind** [comment]
@troughc I've updated our form configuration to add the description field to the people page edit screen. Please test it out and let me know if you need any changes.

**Comment by troughc** [comment]
Tested staging in chrome: PASSED
tested descriptions in both calendars and language literals working as expected.
