### ISSUE TITLE
Add start/end time

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#61]
Add a start time to an event on a single date.

## Test Cases
1. Add a start time to an event --> Save the event and check that the start time was persisted
2. Remove the start time --> Save the event and check that the start time was removed
3. Add an end time --> Save the event and check that the end time was persisted
2. Remove the end time --> Save the event and check that the end time was removed
3. Check that the start and end times appear in the read-only screen

**Comment by troughc** [comment]
Tested on chrome (as ADMIN) and safari (AS GUEST)
1. PASSED
2. PASSED
3. IN BOTH BROWSERS: when I add an end time and save, I see the date on the listing page; however, when i go back into the event, the date of the event is blank. (the times are still there). Then, if I remove the end time (and add the date back in), the date persists. There is some kind of conflict when I add an end time and the date persisting. This is the same whether I am a guest or an Admin. So I cannot add and end time.
 
 See screenshots.


**Add end time before saving**

![Image](https://user-images.githubusercontent.com/64489312/210864495-3e764832-a7bb-4eed-a09e-2469c39c775b.png)



**List view of saved event with end time**

![Image](https://user-images.githubusercontent.com/64489312/210864744-8e8d09a0-30a3-453c-b827-7ff3a412df31.png)


**go back into event - date missing**

![Image](https://user-images.githubusercontent.com/64489312/210864726-aeb0ac3c-765c-4a44-827a-053b90999e24.png)



**removed end time, add date and then save - Go back into the event and looks right.**

![Image](https://user-images.githubusercontent.com/64489312/210864750-d19590bb-8349-4c42-b1e7-a8e0a6644ea7.png)
