### ISSUE TITLE
Add multiple calendar invites (including roles ) in user edit screen

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#619]

**Comment by troughc** [comment]
@AbhishekPAnil I am trying to remember why we created this issue. 
Is this for the bottom section of user settings edit view (which has already been implemented)?
If yes, I am going to delete this issue. :)


The 2 screenshots show the section at the bottom of the user profile (one is 'my own profile' the other an Admin view of another profile).

### Edit view of my own profile 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/aefaddca-113a-40cb-b51a-a886fa7c0afb)



### Edit view of an Admin displaying someone else's profile

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/39ece7df-4eaa-496d-b5f2-75cf590853be)

**Comment by troughc** [comment]
will not do this one
