### ISSUE TITLE
Add Custom fields in events

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#64]
Custom fields for events should appear in the first white box group (where title is) and always be displayed on the left (not on right side) and just below the Target Audience.  There can be zero, one or many custom fields. The custom field all use the same drop-down style as the audience and type fields.

In this screen grab, the field "Disciplines" is a custom field. 

![Image](https://user-images.githubusercontent.com/419491/221894727-a35931fd-5588-414a-b98a-c68115cdb3d8.png)

**Comment by saumier** [comment]
@saumier Add details

**Comment by saumier** [comment]
@AbhishekPAnil I added a screen grab and some details.

**Comment by AbhishekPAnil** [comment]
ESTIMATE 7 hrs

Subtasks:
1.Get the required fields from the event details api and display the fields.
2.Api integration to show the dropdown contents of the respective taxonomies.
3.Add the user entered data to the  add/update event api .

**Comment by AbhishekPAnil** [comment]
Addition to estimated subtasks:

4.Get the required fields from the event details api and display the fields in the read only page.

**Comment by saumier** [comment]
@troughc  Please test in staging,

**Comment by troughc** [comment]
Tested in staging chrome - added Recommended by le pressoire taxonomy to events. This worked
PASSED
