### ISSUE TITLE
Sidebar not reloading after user leaves a calendar.

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#645]
Sidebar is not reloading when a user leaves a calender (any calendar other than the one that he is not currently on). This causes the calendar selection dropdown to show the already left calendar.

Objective: The sidebar should reload and only subscribed calendars should be shown in the dropdown.

**Comment by saumier** [comment]
@SyamBabu-M It this quick complete please go ahead.

**Comment by troughc** [comment]
Tested staging on Chrome : PASSED
