### ISSUE TITLE
Warning to save doesn't appear when a user clicks on the breadcrumb "Back to previous screen"

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#646]
A user tries to create/update an entity from the edit screens(People,Place and Organization) and when the user clicks on the breadcrumb "back to previous screen",the user is not shown the pop up for warning to save.

**Comment by troughc** [comment]
@AbhishekPAnil is this still not working?

**Comment by AbhishekPAnil** [comment]
@troughc This is still an issue.We haven't fixed it.

**Comment by SyamBabu-M** [comment]
This issue was reopened because the warning popup fails to show if the user tries to move away from the page using the browser back button.

**Comment by troughc** [comment]
Maybe swiping doesn't work on mobile? breadcrumbs should

**Comment by troughc** [comment]
@SyamBabu-M where do I test this issue? I am not seeing it work in https://pr-956.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/taxonomies?page=1&order=asc&sortBy=name

**Comment by SyamBabu-M** [comment]
@troughc The link you quoted has expired. So I am not able to open it.

This issue can be tested [here](https://pr-960.dla06mbe0wyl7.amplifyapp.com/). The search is not showing the issue when trying to link the PR, thats why I am adding the link here.

How to test this:

1: Go to any entity form, add/edit some detail. 
2: Try to go back.

**Comment by troughc** [comment]
Tested in Safari and Chrome: Passed!
cc: @SyamBabu-M 
@sahalali this is ready for you.

**Comment by sahalali** [comment]
Closing this issue, as its deployed.
