### ISSUE TITLE
issue with invitation emails

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#647]
When testing the User settings the invitation I recieved was to an 'undefined' calendar (in the subject line and in the body text). I think that @SuhailAliyar knows how to fix this....this email problem should be treated as a separate issue (that I think may already exist).

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7369c82b-af27-4235-965c-0ebe5ed91106)

**Comment by dev-aravind** [comment]
@SyamBabu-M Please add invited user language along with the invitation API as header.

**Comment by SyamBabu-M** [comment]
Added close tag to commit message https://github.com/culturecreates/footlight-app/pull/691/commits/1ac9d31611e5eb1584103124488aa67f6c054298

**Comment by troughc** [comment]
Tested Staging in Chrome (with invitations to Tout Culture calendar): PASSED
