### ISSUE TITLE
got error when I tried to change the name of a place

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#648]
@AbhishekPAnil @sahalali I started testing and tried to change the name of a place and I got this error when I saved my change. now I cannot get back into places.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/1075d55a-5d37-46e2-8e74-c9ca57f98287)

It was the first or second place in Tout Culture  (Staging). The error is also happening in the Old CMS.

**Comment by AbhishekPAnil** [comment]
Added closes tag to PR https://github.com/culturecreates/footlight-app/pull/660

**Comment by troughc** [comment]
Tested Staging on chrome: PASSED
