### ISSUE TITLE
occupation taxonomy not showing up in People

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#649]
The occupation taxonomy not mapping to the occupation field. However, there is an occupation taxonomy in the old CMS. 
Also, In Gregory's profile, I see a UID entry for occupation - see screenshots.

### No taxonomy
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/3876ff55-0b74-47f5-b0a9-fbe025ca75e4)

### Gregory's profile

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d6ebf93c-98c4-423f-85a0-fd00b481ad39)

**Comment by saumier** [comment]
@troughc Moving to done.
