### ISSUE TITLE
ContainedIn Place doesn't search artsdata

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#664]
This issue was first mentioned in https://github.com/culturecreates/footlight-app/issues/607. I am logging it separately  from that issue.

The Contained In Place field only searches for Places that have are already in Footlight CMS - It doesn't search Artsdata.
Expected behavior - this dropdown functions like all other Search dropdowns (that search both footlight and Artsdata).

**Comment by AbhishekPAnil** [comment]
@sahalali @dev-aravind We may need backend changes to implement this.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The changes are up in staging

**Comment by AbhishekPAnil** [comment]
UI changes are updated in staging.
Closes tag added to commit message [94375c4](https://github.com/culturecreates/footlight-app/pull/680/commits/94375c43537fbf4690c2ca076120793c753d4013)

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
