### ISSUE TITLE
Disambiguating text at top of page too small

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#667]
The text size of the disambiguating phrase at the top of the read only pages (below the name of the entity) is too small. It should be the same size of the titles for each section, not the size of the field names. 
See example screenshot:
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7ede59b1-355d-49dc-883d-f53413b383ba)

**Comment by AbhishekPAnil** [comment]
Fixed and updated in staging.
Added close tag to PR https://github.com/culturecreates/footlight-app/pull/668

**Comment by troughc** [comment]
Tested Staging in Chrome: PASSED
