### ISSUE TITLE
Add the Edit option to components (in Events)

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#676]
Please add an edit option using this design for all components (people/place/organization).  You can find it in the FIGMA here (it is the 'Current Implementation' but WITHOUT roles): https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=6338-65980&mode=design&t=qZnZvzOgAO0ZCpSG-4

Here is an screenshot example of where to place the 'edit': 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/949df5ec-65b3-44d2-9fc3-a1f0c15f0ea3)

NOTE: not every user has the right to edit an existing person/place/organization. For example, a guest cannot edit an organization that was created by another user. An Admin can edit any and all of them. Therefore, that edit button should only appear for users who can actually edit the entity (see roles matrix).

Expected behaviour: 
1. When the user clicks Edit, the Edit page for the person/place/organization will open in the relevant workspace. 
TBD: If the page they are on has unsaved changes, the updates need to be either saved or discarded. Here are some different approaches that come to mind:
- the 'unsaved changes' warning appears so they can save or discard changes before they exit the page.
- the current page is automatically saved (and the user is informed)
- maybe the other workspace could open in a new tab? Could this cause a conflict?
2. After they do their work in the other workspace, they should be able to use the breadcrumb to go back to where they started.

These components are displayed in specific fields in most Edit pages, such as: 
Edit Event page -  fields are: Organizer, Performer, Location
Edit Place page - fields are: Contained in / Contains (this one is coming later)
Edit Organization page - fields are: Location
Edit People page: N/A (no fields show thsi component

**Comment by AbhishekPAnil** [comment]
@dev-aravind Could please add the creator details of performer,organizer ,collaborator and locations in the get by event id api.I need it to display the edit button according to the user role.Thanks.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The changes are up in staging right now. Please test it and let me know.

**Comment by AbhishekPAnil** [comment]
@troughcCan we discuss about the user navigation for this issue after our stand up.

**Comment by troughc** [comment]
@AbhishekPAnil yes, we can talk about this whenever works for you.

**Comment by AbhishekPAnil** [comment]
As per previous discussion I have updated staging with:
1.The user will be able to edit an orgs or place or person from create event page and after saving the entity ,the user will return to the respective  create event page.
2.The user will be able to edit an orgs from create event page and from here the user can edit selected place of the respective orgs .After saving the place the user will be redirected to respective create organization page and from there after saving, the user will return  to the create event page.

**Comment by troughc** [comment]
Tested in chrome with places

First:
If I go into an event that has a place that was previously created/previously existed and click the Edit option for the place, I am sent to the Place details as expected (and i see a message saying my event updated successfully).
However, if: 
- I have an event with all mandatory fields filled for a draft save action 
- And, I create a place for my event using quick create
-  And, then click the Edit option before saving the event for the first time, I am not  redirected to Place workspace. Instead, I get the same message saying my event was successfully updated BUT I stay in the event details page. I should be redirected to the Places workspace.

**Comment by AbhishekPAnil** [comment]
> I'm nost usre what the difference is between 1 and 2 in the previous comment?
It will be better If I show you this.Can we meet after the stand up?

**Comment by troughc** [comment]
@AbhishekPAnil should this ticket be assigned to you? I think so, as it is still in 'in progress'

**Comment by AbhishekPAnil** [comment]
Bug Found:
While creating a new event ,once the user tries to click on the edit button in organizer or performer or supporter or place he will be redirected to corresponding entities page.After saving the entity ,the user is redirected to the new event page instead of the respective saved event edit page.The is also happens while doing quick create.

**Comment by AbhishekPAnil** [comment]
The above issue is fixed and updated in staging.I had to rework on the navigation section in people ,place and organization forms including the breadcrumbs to solve this issue.

**Comment by troughc** [comment]
Tested in Chrome (staging)
One issue: when you add a PLACE to a new event and use the Edit option, you don't get back to the event you created when you click SAVE (for hte place). 
organizations and people work.
I discussed with Gregory and we agreed: Please do not hold back the deployment to fix this one bug. You can go ahead with the deployment and fix this one issue to deploy later
cc @saumier @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
> One issue: when you add a PLACE to a new event and use the Edit option, you don't get back to the event you created when you click SAVE (for hte place).

The reason why this was happening is because when we update a place we usually update the postal address as well.There are two cases for this ,adding a new postal address and updating an existing postal address.The previous fix only added to the first case and not for the second case,hence the bug happened.

This is now fixed and updated in staging and in production(Since we had a release today). @troughc After testing this in staging and in production we can close this issue.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
