### ISSUE TITLE
Quick Create: Add full details button

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#677]
Now that the Edit pages for people places and orgs are done please update the Quick Create modal with the Add Full Details button: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4732-63514&mode=design&t=e70Asbic2fiZ4VHE-4

**Comment by troughc** [comment]
@AbhishekPAnil can we discuss other updates to Quick Create:
https://github.com/culturecreates/tech-support-tickets/issues/28
https://github.com/culturecreates/tech-support-tickets/issues/33
These are all designed in the figma link above.

**Comment by troughc** [comment]
Tested staging on chrome

In general, the flow works correctly from Quick Create to Add full details (for people, places and orgs), as well as being able to navigate back.

2 things:

First:
If I have all the mandatory fields filled in the event form and I want to click add full details: the save event message isn't displayed long enough for me to see it so it's kind of flashy. I can't tell what I'm seeing. 
**It should be displayed long enough for me to read it before i am redirected to the other workspace**

Second:

If the mandatory fields are NOT filled, I do see the message. Here I noticed a couple things:

The title of the box is always Create new person no matter whether you are creating a person, place or organization: it should have the appropriate title in the language of the UI: create new person, create new organization, create new place...)

@AbhishekPAnil I think you already have this text/title and it's translation right?


Also, since the event cannot save unless you have the mandatory fields, you have to stay in the event to update the missing fields in order to save it (or cancel it). So the message hangs until you close it. Is there something else we could do here? 
Notes: 
- After you manually close it, the person/org/place is automatically added to the event
- When it's a place, if you haven't added the address (which is mandatory in the quick create module), the place will still be added in the event without any warning to the user - that the address is missing.

screenshot

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ce97ccee-eab0-4536-85cc-3df2000ac7bc)

**Comment by SyamBabu-M** [comment]
@troughc Can you share the text and title for the modal again? I couldn't find it in the document.

**Comment by troughc** [comment]
@SyamBabu-M I added text to the Footlight CMS copy document on two tabs but I going to put it here to make it easier for you.
### VALIDATION TEXT below fields in Quick Create modals
For Places only - Address is ALSO required (along with the name). So the validation text that appears below the Address field if it is empty (you either click Create or Add full details) is:
ENGLISH: Address is required.
FRENCH: L'adresse est requise.
For all three (orgs, people, places) - name is required so validation text is:
ENGLISH: Name is required.
FRENCH: Le nom est requis.

### Redirect modal for all three when you click Add full details button.
I simplified this so you can use the same modal in all situations (it is not specific to the type of entity).

ENGLISH
Title: Add full details 
Body: Saving and redirecting.

FRENCH
Title: Ajouter les détails complets
Body: Sauvegarde et redirection.

**Comment by troughc** [comment]
Additional comment @SyamBabu-M : To be consistent, the message that @AbhishekPAnil has appearing at the top of the person/place/oganization screen (where you add the full details) should also appear in this full.

Example: if you click Add full details for a new Place and the event you just successfully exited is a NEW event, this success message would briefly appear at the top of the Place details page: 
Success! Your event has been saved as draft.
If the event already existed as a draft or published event, this message would appear:
Success! Your event has been updated.

Hope this helps!  cc @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil Please refer this comment https://github.com/culturecreates/footlight-app/issues/676#issuecomment-1801084994

**Comment by troughc** [comment]
Tested 
Same one little issue: when you quick create a PLACE for a NEW event and use the Add full details option, you don't get back to the event you created when you click SAVE (for hte place). 
organizations and people work.
I discussed with Gregory and we agreed: Please do not hold back the deployment to fix this one bug. You can go ahead with the deployment and fix this one issue to deploy later
cc @saumier @AbhishekPAnil

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
