### ISSUE TITLE
wrong warning message for deleting people places and organizations

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#683]
Steps to reproduce. 
1. try to delete a place
2. The error message in the screenshot appears.
3. The message should be: Are you sure you want to permanently delete this [place]? This action will also delete all its associated data and everywhere it was used, including in events. [Delete] [Cancel]
4. For people and organizations, the wording differs slightly - please see https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=1720382151

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/08e44629-5aa1-4763-b648-e782e12e350d)

**Comment by SyamBabu-M** [comment]
Added closes tag to commit message https://github.com/culturecreates/footlight-app/pull/692/commits/7fb0834a42376e1f140c9d760aee9c3ad8aa6b3c

**Comment by troughc** [comment]
Tested staging in Chrome - looks good. PASSED
