### ISSUE TITLE
Empty fields are displayed in forms with no labels for standard  taxonomy fields.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#688]
Current Behaviour : If  there is no taxonomy  created to a standard mapped field then there is an empty field displayed in the form with no label (including in Quick Creates forms).

Expected Behaviour: If  there is no taxonomy  created to a standard mapped field then the field should be hidden across the forms.

Screenshots of what a Quick Create Places looks like today (not the expected behaviour):

<img width="535" alt="Screenshot 2023-10-16 at 10 22 35 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/a3235ec6-ce4b-491b-b40d-0942bdcae412">
<img width="533" alt="Screenshot 2023-10-16 at 10 22 43 AM" src="https://github.com/culturecreates/footlight-app/assets/64489312/ded37b97-63c5-4ef9-8b95-71b8f329f05b">

Expected behaviour: the Region field would not be displayed because there is no taxonomy associated with it.

**Comment by troughc** [comment]
@AbhishekPAnil is it possible to also hide the whole accessibility section in the Event and Place forms if no accessibility taxonomy is available? And show it when the taxonomy is created.

Also update the quick creates.

**Comment by AbhishekPAnil** [comment]
The above issue was caused because I forgot to add the condition to check if a taxonomy exist or not in the quick create section.I have fixed this as well managed to hide the accessibility section if corresponding taxonomy is not created.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED! :)
