### ISSUE TITLE
Settings bug: cannot deactivate/delete a pending user

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#697]
As an Admin, after I invite a user to my calendar, and their invitation is still pending, I cannot remove the user from the calendar. 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6887bba9-78ab-493d-b265-5105104cee40)

**Expected behaviour:** Acmin can use the right-click menut to deactivate a user even when the invitation is pending. Be able to then delete the user from the calendar.

**Comment by troughc** [comment]
@SyamBabu-M we have updated the figma with a new option and a message. Please find the designs here: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4205-98574&mode=dev
screenshots:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d4d57147-69f3-4f81-ac05-927ab1a80b93)

Popup that appears when you right-click Cancel invitation.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/21c2de0f-8abc-46ae-a1bd-a17c0476279d)

We added the translations to the CMS copy doucment. 


Also, I noticed that the right-click options for **activate** and **deactivate** a user isn't quite right. 
Right now it is dispayed like this:  "Activate/Deactivate" no matter the state of the user.

**Expected behaviour:** the option should toggle the display according to the user state
"Activate" when the user is Inactive 
"Deactivate" when the user is Active

This is consistent with the way it works in Events for "Feature this event" and "Unfeature this event"; "Publish event" and "Unpublish event".

**Comment by SyamBabu-M** [comment]
@troughc Thanks Caitlin. I have completed the tasks and updated the staging. Added closes tag to [80b2b8b](https://github.com/culturecreates/footlight-app/pull/713/commits/80b2b8bcd3f5ef5095da60bfbec5631c6c6bab3c)

**Comment by troughc** [comment]
Tested staging in Chrome: not working as expected. There is a little loophole problem when someone is invited to multiple calendars and the invitations are pending.

**What Works**
As an Admin, I can cancel invitations to my calendar. Examples
- I can cancel invitations to new users (new to CMS)
- I can cancel invitations to existing CMS users (those who have accepted invitations to other calendars), i.e. they won't be able to access my calendar after I cancel the invitation.


As an invitee:
I am already a member another calendar AND they have accepted an invitation to that other calendar. My account will still works if the Admin of a second calendar cancels my invitation to their calendar. I can still log into the first calendar.


What doesn't work
As an invitee and for the Admin:
If I have been invited to 2 calendars (calendar 1 and calendar 2) and both invitations are pending, there is an issue.

I cannot join calendar 2 if my invitation to the calendar 1 has been canceled.

Steps to reproduce:
As an admin
- Create a user for Tout Culture and invite
- Add the same user to Signe laval and invite
Both invitations are pending. As the Admin, cancel the invitation to Calendar 1.

The invitee is removed from that calendar (calendar 1) 
The invitation is still "pending" in calendar 2.
Screenshot example of calendar 2 (ctroughton3):


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/45a0f6e1-866f-4a69-9152-b2d5bc9a50c0)



Log out the Admin from Footlight CMS. 

Now, as the invitee, from the email invitation, click "Accept invitation" button. It doesn't work. 
Screenshot:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/fd2a651f-d8e2-4db4-a248-3b578a9aa436)




Log in as the Admin again. Right click the invitee name (pending) and copy invitation. 
Try to use it. It doesn't work.
Screenshot:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/78dcd1d5-8cfe-4e72-a447-3e050b5f0191)

**Comment by SyamBabu-M** [comment]
@dev-aravind Please look into this as it looks like a backend issue.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED!
