### ISSUE TITLE
Events: ticketing information is missiing from read only page when logged in as guest/contributor

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#711]
please see event in production (log in as guest): https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/64515b20e19f7200646d15b3
Read only page is not displaying Tickets info. Section is missing on read only.

**Comment by AbhishekPAnil** [comment]
The issue is fixed and updated in staging.

**Comment by troughc** [comment]
Tested in staging: PASSED
