### ISSUE TITLE
Open API Image not updated

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#715]
Image crop not getting updated in Open API. Head should not be cut off.

Note: I have updated the demo.tout-culture and demo.staging-tout-culture sites to display the 3 images sizes: thumbnail, large, original.  I also added a link after the images to open the same event in the CMS or Staging CMS depending on where you are.

https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64822015371b8f006491195b

http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com/events/event-details.html?eventId=64822015371b8f006491195b

![Image](https://github.com/culturecreates/footlight-app/assets/419491/b0652b21-3c28-4d46-9a28-7b0830af85ba)

![Image](https://github.com/culturecreates/footlight-app/assets/419491/aff8ad5a-f542-4d15-a2c9-36679ca79305)

**Comment by dev-aravind** [comment]
@saumier The changes are up in staging right now.

**Comment by troughc** [comment]
Tested in Chrome (staging) using an existing image and using a new image (new event). PASSED

**Comment by saumier** [comment]
@SuhailAliyar @dev-aravind It looks like this bug fix has not yet been pushed to production. It was tested by Caitlin and moved into "done" 5 days ago.  By now it should have been deployed as part of our CI/CD process. Unless there is a major update of the API that could break the front-end, these types of bug fixes should be deployed within 2 days of passing tests. Let me know if you agree.

**Comment by sahalali** [comment]
I agree. 

This is now deployed to production.

**Comment by saumier** [comment]
@sahalali Thx. I am closing this issue manually now that it is deployed to production.

**Comment by saumier** [comment]
@troughc Now that the image tool is working in production, please take a look and inform the clients as you see fit. If the aspect ratios configuration should be adjusted on Tout Culture or Signé Laval then please open another issue.
