### ISSUE TITLE
new user addition is buggy

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#741]
Steps to reproduce:

1. Caitlin invited Kim to Tout Culture production as a new user (after deleting a previous user for Kim that used a different email address - created by Gregory)
2. kim didn't receive the email invite 
3. Kim clicked the accepter invitaition button, but that didn't even open in a browser. 
4. So Caitlin copied and sent link to kim to log in.
Note: caitlin could navigate to the create user page but KIm could not...
What Caitlin sees: 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/425f7651-a529-4d2b-8f0c-a0beca9df846)

5 When Kim tried to log in using the link (copy invitation link) he was taken to the login page but with an error message displayed "something went wrong"
6. Kim then tried logging in to production using his staging login credentials. **This worked** (but it should not have worked).

7. As a result, in Production:  Kim sees his profile as active, and Caitlin sees it as pending. See screenshots.
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5db00db6-a499-4604-8248-c0f683d349ab)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/b12b7817-f3ca-47c7-b08c-5a01bd3e8603)

There are several issues happening. Please check it out.

**Comment by troughc** [comment]
Maybe this is happening because staging was copied to production at some point? @sahalali @saumier  do you know why this might be happening?

**Comment by troughc** [comment]
Update: Kim is logged into the staging database; however the URL shows him as being logged into production. 
In other words, the event list contains all the staging events (not the production events).

**Comment by troughc** [comment]
Test we did:
Kim copied the url and sent it to me - to an event that we know only exists in staging: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/651f964c9b39590064278e13
I tried it, got an error.
I added 'staging' in front of 'cms' and then it worked - sent me to the event in staging.

**Comment by kmdvs** [comment]
OK, the explanation for the second part (login in "production", staging database instead of production database, is that I had Docker running the staging DB and my hosts file was redirecting:
127.0.0.1 api.cms.footlight.io
So that part is not a bug, but a feature for testing for me :)

**Comment by sahalali** [comment]
@troughc What is the next step with this issue? I forgot what we discussed.

**Comment by troughc** [comment]
@SuhailAliyar I am not sure. @kmdvs let's discuss this issue at our next meeting to clarify what needs to be done.

**Comment by troughc** [comment]
I spoke with @kmdvs about this. We are closing this as we cannot reproduce any issues. I believe everything is working correctly.
