### ISSUE TITLE
First name user suggestion search pop up is not closing automatically.

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#747]
Once I enter the first name of the user in  the Invite new user page,the user suggestion-search pop doesn't automatically close after I leave the field.The pop up stays on .

![Image](https://github.com/culturecreates/footlight-app/assets/117100211/733dd174-6012-483b-afdc-121691e8da13)

**Comment by troughc** [comment]
Tested Staging in Chrome: PASSED
