### ISSUE TITLE
The admin/user who invited doesn't get a proper notification after a successful invitation has been sent

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#748]
The admin/user who has sent the invitation doesn't get the proper notification once a successful invitation has been sent to the new user.The admin/user is redirected to the user listing page without any notification.

**Comment by SyamBabu-M** [comment]
@troughc Could you please update the invitation message in the Excel file.

**Comment by troughc** [comment]
@AbhishekPAnil I added the text to row 3 of the "User flow - notifications/alerts" tab.
For your convenience: 
English: Success! Invitation sent.
French: Succès! L'invitation a été envoyée.

**Comment by troughc** [comment]
Test result:
I tried adding new users to each of the calendars in Staging, but I didn't get a popup message. Everything else seems to be working.
Can you please take another look @SyamBabu-M?

**Comment by troughc** [comment]
@sahalali this one isn't working for me yet. As an Admin, I am not getting a popup confirmation message (notification alert) when i create and invite a new user. cc @SyamBabu-M

**Comment by troughc** [comment]
Tested in Staging: PASSED
