### ISSUE TITLE
Switching calendars bug with user dropdown

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#752]
When I switch between calendars the user list doesn't update unless I manually refresh
Steps to repeat:

1. login wiht a user who is a member of both signe laval and tout culture
2. in the first loaded calendar (tout culture) display the list so you know the users
3. switch to other calendar (for me signe laval)
4. display the user filter - the tout culture users list appears.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/2c144f62-c1d6-4610-bbc4-6764bf09a6ab)

5. Refresh the browser (chrome in my case). the correct signe laval user list is now displayed

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d9fd8d3f-560c-42e7-8bac-93f17b0da01a)

Expected behavior: correct user list is displayed as soon as you switch calendars.

Note: In case this is related problem: filter selections also persist when you switch calendars (they are not cleared).

**Comment by troughc** [comment]
Tested staging in Chrome.
The list now updates per calendar correctly: PASSED
However, if I select a name in one calendar and then switch, the filter keeps a user selected and the list in the newly loaded calendar is empty (and no name is selected). 

Screenshot:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/9c14c91e-8119-424e-b6de-dbd4567e5b90)

Steps to reproduce:

1. In tout culture select a user to see their events (like aville de gatineau)


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/4d43e89b-4801-467e-84a5-afadfde9cc8c)


2. switch to Signe laval. The list is empty and one user is still selected.



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8464c035-19f7-45e2-b5e3-e82864f02a02)



3. switch back to Tout Culture. aville de gatineau is selected and the event list is filtered accordingly.

**Comment by troughc** [comment]
Tested in Staging: PASSED ! :)

**Comment by AbhishekPAnil** [comment]
@troughc While testing this I found out that the current fix for this issue affects the reloading of the page.When a user reloads the event listing page the filter are not persisting.Hence we are reverting the current fix and I am moving this to Todo. @SyamBabu-M is working on fixing this issue in a different way.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
Looks okay to me.
