### ISSUE TITLE
update image cropper

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#755]
Changes to the image cropper modal to improve user experience:

Current:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d0dd21a9-882d-4c0a-b09c-e7c51899b3b4)

Changes:

Add the correct french text for the title and other text. 
Title 
ENGLISH: Position image
FRENCH: Positionnement de l’image

Sentence in English: no chance
Sentence in French: Ajuster la position de l’image si nécessaire.

**Remove title "Saved frame sizes"** 

Note: if you cannot remove it, change the subtitle to
ENGLISH  
"Available image ratios"
FRENCH
"Ratios d'images disponibles"

**New text for ratio radio buttons.**
Please display text next to 2 radio buttons as follows in the following order:

ENGLISH
<ratio> Thumbnail image
<ratio> Large image

FRENCH
<ratio> Vignette
<ratio> Image grand format

Example (english)
3:2 Thumbnail image
5:3 Large image

The figma is up-to-date with both French and English text: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=6864-53959&mode=dev

**Comment by AbhishekPAnil** [comment]
Changes are updated in staging 
Added closes tag to commit [33d6295](https://github.com/culturecreates/footlight-app/pull/769/commits/33d62955d90f618d64f68133a5bfb411ad034582)

**Comment by troughc** [comment]
Tested in staging: PASSED
@AbhishekPAnil thanks for updating the text.  Whilst testing, I uncovered a bug with the positioning of the images - I will log it separately.
