### ISSUE TITLE
CMS: clear search bar when you exit a workspace

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#759]
Today, my search terms persist in every workspace that i add one (in the listing pages), after I exit the workspace, and even after I log out (it is still displayed and applied when I return to the workspace and/or I log back in). It isn't removed until I delete it myself. 

It sometimes persists from one calendar to another. 

Expected behavior - the search terms in listing pages are cleared when a user exits **the workspace.** 

IMPORTANT: this shoould not in any way conflict with the fix we did in [this issue](https://github.com/culturecreates/footlight-app/issues/235)

**Comment by troughc** [comment]
@SyamBabu-M I just tried to test this in staging but I think it hasn't been pushed yet maybe? 
I still see my search terms after I leave a workspace and come back - (and they persist across calendars). 
Note: this also occurs in the search fields for filters - for example, the Users filter (and Organizations filter) in the Event listing view.
I can check again tomorrow.

**Comment by SyamBabu-M** [comment]
@troughc "the search fields for filters - there are two - should look like other search fields as much as possible (with the little x to clear). Does this work?"
Can we tackle this as another issue?

I have fixed issue with search bar not clearing and updated staging today.

**Comment by SyamBabu-M** [comment]
close commit added to 2ad87cb941c7b178d824915380f461b4bf4d1a37

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED

**Comment by troughc** [comment]
@SyamBabu-M I created a separate issue for the little x so we can tackle it separately. :)
