### ISSUE TITLE
Display event status and virtual location

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#76]
Display event status as per image below, and name of virtual location (i.e. Virtual event) next to location as per third image below.

NOTE: Figma designs (french and english) can be found in Sprint 12.

1. **English showing different event status AND virtual event display (cancelled event):**

![Image](https://user-images.githubusercontent.com/64489312/221896240-d363287c-591b-4714-8e39-277589e38852.png)

2. **French showing different event status:**

![Image](https://user-images.githubusercontent.com/64489312/221896319-abba1bc9-ee98-46db-bc6f-a003e91620d8.png)

3. **English showing virtual location displayed:**

![Image](https://user-images.githubusercontent.com/419491/211669429-0f67943a-182c-4a09-8477-7746ce604a45.png)

**Comment by troughc** [comment]
By chance, while testing other issues, I noticed that, currently, when there is both a real locationa and a virtual location in an event, it looks like this (no space and no vertical bar (|) between the two. In case it is useful for reference, I am adding the image here so you can update it to what you see in the above description.

Example of wrong display when you have both a virtual and real location.

![Image](https://user-images.githubusercontent.com/64489312/220724971-4ae82b37-0a22-4650-af1c-b4b46913b00c.png)

**Comment by AbhishekPAnil** [comment]
ESTIMATE : **2** hrs 

Subtasks : 
1.Add event status and corresponding color tags to event list page.
2.Add virtual location .

**Comment by troughc** [comment]
Tested Staging environment on Chrome: PASSED.
