### ISSUE TITLE
Quick Create: Add full details french translation

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#774]
In french version of quick create modals, the text on the 'Add full details' button should be 'Ajouter les détails'

Please update the french modal.

FRENCH button in all Quick Create modals: 
Ajouter les détails

If possible, please include this in Monday's update to production. it's okay if you do it before I review it since it is only a text change.

**Comment by AbhishekPAnil** [comment]
@troughc The changes are updated in staging.

**Comment by troughc** [comment]
Tested in staging (and production): PASSED
