### ISSUE TITLE
Refactor loading Google Maps Place API

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#781]
Message in console:
Google Maps JavaScript API has been loaded directly without a callback. This is not supported and can lead to race conditions and suboptimal performance. For supported loading patterns please see https://goo.gle/js-api-loading

**Comment by AbhishekPAnil** [comment]
Estimated Tasks: 4h

1. Check on the recommended approach :1.5h
2. Add the recommended approach for google places search in all the existing the google place search fields.(Quick create place,Create new place) : 2.5h

**Comment by troughc** [comment]
@saumier take a look at this.

**Comment by troughc** [comment]
Also see this issue: https://github.com/culturecreates/footlight-calendar-api/issues/820

**Comment by AbhishekPAnil** [comment]
Updated staging with recommended approach and added restriction for search to country ( Canada - "ca" )

**Comment by saumier** [comment]
@saumier Restrict API in Google console.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil @sahalali @dev-aravind @SyamBabu-M I have added restrictions to the Google Places related APIs. I am restricting access by filtering on HTTP referrers. I have added 2 allowed referrers: *.footlight.io and localhost:3001.  Let me know if you would like to add more for your local development needs. I added localhost:3001 because that is the referrer when I  work on developing Footlight Console on my local machine. I didn't check which port is used by default on local for CMS front end, so let me know if you want me to add more referrers. I think it is important to be able to fully test everything on your local machines.
> 
> ![Image](https://github.com/culturecreates/footlight-app/assets/419491/a5b8a8eb-b636-4488-9f20-ad42371b47c3)
> 
> 

I will let you know regarding adding extra referrers.

**Comment by AbhishekPAnil** [comment]
I checked and the referrer restrictions are working fine.
In front end the default port used is localhost:3000,would be able to add localhost:3000 ?

**Comment by AbhishekPAnil** [comment]
@saumier Can we release this to production ?
