### ISSUE TITLE
Change the border to normal for bilingual fields in a unilingual calendar in all forms

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#784]
Currently the bilingual fields have a border of "border:4px solid rgb(232, 232, 232)" .When it comes to a unilingual calendar we dont have a tab view ,hence the bilingual fields are converged to a normal input field.Thus we need to change the border to "border: 1px solid #b6c1c9".

**Comment by AbhishekPAnil** [comment]
@troughc Please assign this back to me if you find the description is adequate.

**Comment by troughc** [comment]
Will confirm with Stephanie today.

**Comment by troughc** [comment]
@SyamBabu-M please check the borders for Description and Notes fields in all workspaces.  Thank you.

**Comment by troughc** [comment]
Tested: PASSED

**Comment by AbhishekPAnil** [comment]
@SyamBabu-M 


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/b3c8de8f-bc05-43ab-bc0a-43a47500f2c1)

There is an issue with the height of bilingual fields in the create place page.
