### ISSUE TITLE
Enhancement: make calendar/time entry more like other calendars (more user friendly)

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#788]
Moving this from Support issue #9
Please look into improving the user experience with entering/typing in times for events. The idea is to make the experience more like how it works when you add time to a Google scheduled meeting  on their calendar. For example, not having to enter a enter the colon when typing (please check out events on a google calendar)

**Comment by troughc** [comment]
@SyamBabu-M please provide an estimate. Let me know if you have any questions. Thanks!

**Comment by AbhishekPAnil** [comment]
@troughc I dont think I will be able to add an estimate for this because i don't have specific way to solve this at the moment.
I am trying different methods to solve this right now.

**Comment by troughc** [comment]
@AbhishekPAnil I played around with dates again on mobile. I have an idea for improving the experience of entering information (Including in the calendar).
 If we could have it such that the keyboard didn't obsure the date field (or any field) when you tap it that may be enough. Could the solution be to move the page up so that the UI is displayed above the keyboard? Let me know what you think.

**Comment by AbhishekPAnil** [comment]
@troughc We can try this implementation, it may work.

**Comment by SyamBabu-M** [comment]
@troughc Ok. In that case, we can take this up later. Should I assign this back to you?

**Comment by troughc** [comment]
As discussed at the standup I am setting priority to low as it may very well be resolved through responsive design issues. Low means it may not be completed this round. :)
