### ISSUE TITLE
Organizations: member field displaying ID instead of name in production

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#791]
For "Member of" field in organizations: The ID number is being displayed instead of the name (in both the read only and the edit screens).
Please check anywhere that we use IDs like this for custom fields - for example, if we use them in people or places.
### Read only example

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/7d4f81f5-d16f-4f57-a7a0-159dc6f39e52)

### Edit example

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a326d08e-71f0-460a-8297-f5075153f515)

**Comment by AbhishekPAnil** [comment]
Cause: When the changes for #768 were made ,the corresponding changes were not made for dynamic tree select fields hence bug occurred.

The issue is fixed and updated in staging and in production .

**Comment by troughc** [comment]
Tested staging and production in Chrome: PASSED
