### ISSUE TITLE
Customer request: Tout Culture required fields change

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#797]
FOR TOUT CULTURE ONLY
Tout Culture requests making the Organizer property in Events mandatory (required field). Please update the configuration for the Tout Culture calendar.

In the CMS:
- a star should be added next to the field title in French and English UIs
- A user cannot  publish /send for review until all mandatory fields are completed (now including the Organizer field) so the popup message should also appear if they click publish/send for review....
- If the Organizer property is missing when a user tries to publish the event or send for review, field feedback text (in red) should appear below the field.

The text is in the CMS copy document in the field feedback tab. For your convenience:
ENGLISH: An organizer is required.
FRENCH: Un organisateur est requise.

**Comment by troughc** [comment]
Question for Caitlin: do events that are already published need to have organizers.

**Comment by sahalali** [comment]
@AbhishekPAnil May please take up this for the frontend changes. 
please assign beck to @dev-aravind based on the answer for. "do events that are already published need to have organizers."

**Comment by troughc** [comment]
Hi @dev-aravind @AbhishekPAnil  there is no need to update events that are already published, that don't have organizers. these events can remain published. Confirmed by the client. Thanks!

**Comment by AbhishekPAnil** [comment]
The UI changes are updated in staging.

Added closes tag to commit [8349e7b](https://github.com/culturecreates/footlight-app/pull/818/commits/8349e7be13e6f7dd041ef34052760f9dcb64250c)

**Comment by troughc** [comment]
Tested on staging: PASSED
