### ISSUE TITLE
Toggle ON/OFF all editing

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#798]
**Design scheduled: FEBRUARY 2024**
[Link to Figma design](https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=8648%3A64053&mode=design&t=9KPCABKc65E0MniH-1)

As an admin of a calendar, I want to make my calendar READ ONLY so that users, including myself, CANNOT manually modify an entity in CMS. 

The Open API and Admin API continue to work as normal, and users with all roles can still login to the CMS and view all entities, but they cannot edit or create or quick create. 

If a user tries to edit or create an entity then the UI provides feedback. The buttons to create, such as "+ event", and in quick create, should somehow help the user understand that the database is currently not accepting changes. This means not just disabling the buttons (which looks like nothing is working), but also providing a message why the user cannot edit like "database is temporarily under maintenance and cannot be modified at this time".

Some use cases needing this feature:
1. If I want to do a large batch update and avoid having other users make changes that will be overwritten
2. If there is a major data corruption problem and we have to roll back the database temporarily to an older version of the data
3. If there is a major platform outage and we spin up a temporary server on another PAAS to maintain the clients front-end calendars running while we wait for the platform to be fixed.

Note: this may involve more than one toggle, and is an opportunity to review/refactor the toggle code and propose a new set.
Note: aggregator MAY continue to run since it can be rerun any time and will not complain about any lost work.
Note: backend swagger MUST continue to run so a batch download/upload can be performed.

**Comment by saumier** [comment]
@sahalali Ok. Please propose a design for this. When I re-read the use cases above, I realized that the idea of using "feature toggle" in the front-end will not work for the use case "as admin I want to do a large batch update".   For that use case, there should be a setting for the Admin to use in the CMS UI that temporarily blocks editing.

**Comment by sahalali** [comment]
Suggestion:
Add a setting to the calendar {"mode": "ReadOnly"}, by default, it will be ReadAndWrite. The user authorization will stop access to calendars in ReadOnly Mode if the API method is PUT, POST, or PATCH.

Limitation:
No users, including "aggregator" cannot update any entity within a calendar in ReadOnly mode.

For this, I am estimating 8 hours of effort in the backend.

**Comment by saumier** [comment]
@sahalali Looks good. Clean solution. The only exception should be the API that turns the mode back to "ReadAndWrite". 

@AbhishekPAnil Please estimate work in the front end. I think there are 2 parts:
1.  add a general message to inform the user of this special case when the backend returns a "read only" error. @Caitlin should be asked to supply the English and French messages.
2. add a UI button to the calendar settings for admin to set the {"mode": "ReadOnly"} or {"mode": "ReadAndWrite"}.

**Comment by AbhishekPAnil** [comment]
> add a general message to inform the user of this special case when the backend returns a "read only" error. @caitlin should be asked to supply the English and French messages.

Estimate UI tasks for :10h
1.Add the pop up modal with the required message.-2h
2.Check the calendar mode in all the edit pages with a general function(also check the calendar mode for all the edit/add button clicks)-6h
3.Test the approach- 2h




> add a UI button to the calendar settings for admin to set the {"mode": "ReadOnly"} or {"mode": "ReadAndWrite"}.

Right now I am not estimating this, since we haven't started implementing the calendar settings page

**Comment by troughc** [comment]
Question @sahalali @saumier regarding providing a button to the admin to toggle read only on and off:
What if WE set the calendar to read only? I guess this button would be disabled for the admin right?
Thanks

**Comment by troughc** [comment]
> add a general message to inform the user of this special case when the backend returns a "read only" error. @caitlin should be asked to supply the English and French messages.

@sahalali and @AbhishekPAnil here is the copy for the message:

ENGLISH: This Footlight CMS is  locked. Please try again later.
FRENCH: Ce CMS Footlight est verrouillé. Veuillez réessayer plus tard. 

Let's do this task in two distinct steps 
1.  implement read only for Culture Creates to use (with popup message and locked UI).
2. Add button for Admin to control read only.

**Comment by saumier** [comment]
@troughc Glad to see this moving forward. I just realized that it might also help us onboard a new client. For example, we don't want anyone at Culture Mauricie to be editing events in both Footlight and Caligram. So we could load a dump from Caligram into CMS with editing OFF.  Once Culture Mauricie stops editing their event in Caligram we load a final Caligram dump into CMS and then toggle ON editing.

**Comment by sahalali** [comment]
@troughc Please suggest the next step with this ticket

**Comment by troughc** [comment]
@sahalali I suggest we implement the ability for us (Culture Creates) to lock a specific CMS for a calendar and have the message pop up when any user logs in or tries to edit anything. 
Notes: 
- If the user is already logged in (for example, I often stay logged in over night without closing my browser), the message should pop up when the user displays the CMS.
- The user must NOT be able to make any changes in the CMS. Perhaps they shouldn't even be able to navigate through the UI. (my recommendation for this first phase) 
- Question: should a user be able to log out of a locked calendar? In my opinion, yes. 

Does this work for you @sahalali , @saumier ?

**Comment by troughc** [comment]
let's discuss how to do the front end @AbhishekPAnil

**Comment by troughc** [comment]
@AbhishekPAnil adding potential copy for the message here - to discuss and finalize tomorrow

ENGLISH: This Footlight CMS is locked. Please try again later.
FRENCH: Ce CMS Footlight est verrouillé. Veuillez réessayer plus tard.

OR

ENGLISH: This Footlight CMS is not available at the moment. Please try again later.
FRENCH: Ce CMS Footlight est non disponible pour l'instant. Veuillez réessayer plus tard.

**Comment by troughc** [comment]
Tested staging in Chrome Tout Culture with @sahalali , who made the calendar read only for me.
@AbhishekPAnil The backend was read only but not the front end - all the editable fields are there, so I can interact with them. However, when I complete an action (save an edited/new event, confirm delete and entity, use the right click menu to Unpublish), I get this error message confirming the back end is read only. **Please note** that the popup is the wrong message:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ca0c07bf-a204-45fd-ac63-afda661b0942)

The UI still looks like this after being set to read only (so I can interact with everything). No message telling me the calendar is read only appeared.:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a54a0bf6-4d26-43ad-af08-49b707eb82e9)

**Comment by troughc** [comment]
Tested all use cases including edge case where you have the URL of an edit event page: PASSED 
tested in chrome and safari
