### ISSUE TITLE
Enhancement:  Add language literal tags

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#805]
Please see link to Figma: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4213%3A98576&mode=design&t=fr6r3HnaRdmwaZYO-1

Challenge: When importing events, places, people, etc. from other sources, the language literals can be in other languages, or may not be translated into both English and French.  As a user of CMS I need to be able to see literals in other languages, fills forms with any available languages, and make translations if needed. 

Goal: display **literal language tags** in the edit forms when the literal is in a different language than the website (i.e. when an english title is imported into a french only website). 

**Literal language tags** is a new feature that lets the user translate literals in another language or just leave the literals in their original language. In most cases, the user will want to translate the literals, but in some case, such the name of an opera in Italian, they could decide to leave it in the original language.   

Use Case - Bilingual Calendar
==========
As an admin of a bilingual calendar (like Tout Culture), I import an organization (like "Sanderson") from Artsdata. The organization is imported with only an English name. On the edit page, I am able to see the "exclamation" icon on the "fr" tab. When I click the "fr" tab, I see the english name is displayed with the "en" tag. When I click into the field, the system assigns the correct language tag "fr" to the literal. Now when I save the event, the literal is saved with the "fr" tag.  I can edit the name, but just the fact of clicking into the field triggers the literal to be assigned the new language tag.

Use Case - French only calendar
=================
As an admin of a French only calendar (like Signé Laval), I import an event from Artsdata with a name only in "German". The event is imported with the name literal tagged "de". On the edit page, I am able to see the German name displayed with the "de" tag. When I click into the field, the system assigns the correct language tag "fr" to the literal, and the "fr" tag is hidden from view because it is the same as the calendar content language. I can edit the name if I choose. When I save the event, the literal is saved with the "fr" tag.  If I save the event without clicking into the name field, the name literal remains in the original language.

**Comment by troughc** [comment]
@saumier this is ready for an estimate so I am assigning this the @sahalali. Let me know if you would like to review the figma.

**Comment by sahalali** [comment]
@troughc 
I have a few questions:
1. If the data imported have labels in multiple languages other than English and French. For example, the labels are in Italian and German. Which Language should we display in that case? Should that be done with any priorities?
2. The other language label displaying is only while importing. And once the event is created should we keep the other labels?

**Comment by sahalali** [comment]
Any changes to open-api responses? Should we include a language other than English or French in the open-api response if a label in any third language is imported?

**Comment by troughc** [comment]
@saumier a question came up: what do we do when a text comes in WITHOUT a language tag? I'm not sure how to handle this case in the UI. Is this something you think should be handled in the backend? Should the text be assigned a language tag?

**Comment by troughc** [comment]
@saumier also please see questions in above comments. I am not sure what to prioritize if the literals are not in English or French.

**Comment by sahalali** [comment]
The current fallback-label configuration includes only {"enableLabelFallback" : Boolean, enableLabelFallback : [standardFields : [], dynamicFields:[]}. And this settings is within the **eventScheme** and its exclusively for Event form. This is the initial implementation before the data-centric approach.

The "eventSchema" field is not part of the above doc, as we are planning to migrate the eventSchema to forms(that includes organization, place and person form configs.).

I like the idea of fall back language list.

**Comment by sahalali** [comment]
Estimation: 
1. Add the fallback language config to calendar metadata. 2H
2. Update json-ld genration. -2H
2. Add a common method to support fallback language for labels. - 4H
3. Update open-api response - 4H (if any changes are needed)
4. Unit testing - 4H
5. Peer review - 2 H

Total: 18 H

**Comment by sahalali** [comment]
1. Add language de, es, @none to MultiLingualString class. We may need to add more languages to the list later.

2. Add languageFallback configuration. Please add a migration script to add this configuration to the calendar metadata
Please add the the model as follows.

Signe-laval (French only calendar):
	languageFallbacks : {"fr": [“en”, “@none”, ”es”]}
Tout-culture (Bilingual calendar):
	languageFallbacks : { "en": [“fr”, “@none”],  "fr":  [“en”, “@none”]}

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend changes are up in staging

**Comment by troughc** [comment]
Caitlin to add translations

**Comment by dev-aravind** [comment]
@SyamBabu-M  I did my first round of peer review and found the following bugs:

1: The banner shows "Some text does not match the language on your website. Review and update as needed." does not go away after editing all the affected fields.
2: The literal tag doesn't show up in the ticket price description.

**Comment by SyamBabu-M** [comment]
@dev-aravind I fixed the above issues. Please do a second round of peer review.

**Comment by dev-aravind** [comment]
@SyamBabu-M  I found 2 more bugs:

1: When you have a long name for an event, the language literal tag covers the text in the event name.

![Image](https://github.com/culturecreates/footlight-app/assets/132546883/47ed9a9e-9a02-4cca-bd19-6ee3022164df)

2. When you save an event which has both French and English field after removing it's French field, The next time you open the event, the the French field is empty. However, after saviing the event as draft again, the bug was fixed.

**Comment by SyamBabu-M** [comment]
@troughc 
For ease for testing you can use these entities - 
Events: 
1 - [The Grand Illusion - Styx Experience ](https://pr-1060.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/65bb376768f14b00644b42fd)
2 - [LA VIE : UN PEU, BEAUCOUP, PASSIONNÉMENT](https://pr-1060.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/65d6e76d79151d0064f46a25)

Places:
1 - [test](https://pr-1060.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/places/add-place?id=6617dd3de30e6d00a0613267)

Organization:
1 - [Distillerie du Square](https://pr-1060.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/organizations/add-organization?id=65f855dd997b810063733409)

People:
1 - [Beyries](https://pr-1060.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/people/add-person?id=64af643b3c19fa0064e76b84)


Inorder to see language literal in selected cards - 
1 - take Signe laval calendar and open any event.
2 - in the section to link location, organization or performer/organizer, search and select any one of the entities I listed above.

**Comment by troughc** [comment]
Tested on chrome:
@SyamBabu-M it's looking good, but can you please check the following, these ones are a bit tricky:
### when to stop displaying the missing literal message and literal tags
1.  Create an event in Tout Culture where the language literal is missing from the title and description fields. For example there is no french title or description. 
2. Go back into the event: the message is at the top and the literal for the missing language is displayed for the TITLE (which is using the ENGLISH title in the french field). The french description remains empty.  Do nothing to the fields, save and exit. 
3. The next time you go in: the message at the top is there but the title has no literal tag and is filled in; the system has added the english description to the FREnch description field for title.  However, the missing literal in event French Dexription (in the bilingual field) now displays the EN literal and the english text. Do nothing and save
4. Go back in and the message from the top is now gone. 
NOTES: 
I did not actually edit any fields, I only saved the event. So I don't think that the literal tag and literal message should go away until I EDIT all fields and save.
I don't know why the title and description don't update together (see step 2 and 3).

### Tested adding a place added to Signe Laval that has an english name and and undefined name
tested with this place: https://kg.artsdata.ca/entity.html?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK11-182
Instead of getting an English literal I got the question mark when I added it. Should it be the english literal? Please try in in Signe laval yourself.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/72e415f0-c2f6-4b1d-9567-f4de64a97358)

### Tested adding person from Artsdata to Signe Laval
Anthony Street - his name has no literal, so the question mark should be displayed: PASSED

### Tested adding organization from Artsdata to Signe Laval
Enana Ballet Academy Canada - the name is english but the question mark is displayed.

Thanks!

**Comment by SyamBabu-M** [comment]
@troughc 
1 - I fixed the issue with the tag showing a question mark instead of a language literal.
2 - when to stop displaying the missing literal message and literal tags - In the banner behavior mentioned in Figma, it's defined that the tag should go away once the event is saved. I am not sure about this one.

**Comment by troughc** [comment]
To do: determine how to handle publishing events with other language literals. What happens when a user clicks Publish (or save as)
Save As: updates whatever fields have been edited but keeps language literals for fields that were not touched /edited. User must at minimum put the cursor in the field.
Publish: Maybe display a warning that text is not in language of website. Team is exploring this option.

**Comment by AbhishekPAnil** [comment]
@troughc 
We discussed the implementation of a warning pop up in the data centric approach and we think that it is achievable as per the current implementation in the data centric approach.

**Comment by troughc** [comment]
Tested workflow with popup message, banner message and literal tags: PASSED
**Retested Anthony Street (person)** : https://kg.artsdata.ca/entity.html?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK12-155
- This person has no language literal at all for the NAME - so the **literal tag should be a question mark** (?)
-  the displayed literal tag is (en) instead on (?)
**Retested Enana Ballet Academy Canada**: this now works properly - displayed tag is (en)
@SyamBabu-M can you fix the small issue above easily?

**Comment by SyamBabu-M** [comment]
@troughc Anthony Street (person) has an English name. Since English is one of the fallback languages, it is shown in the French fields. I do not exactly understand the issue.

**Comment by troughc** [comment]
Thank you @SyamBabu-M you uncovered something I wasn't aware of!

In Artsdata, there is no English or French or any other language specified for the person named "Anthony Street" (his name in Artsdata has no language tag). You can see that here - his name has no en next to it: https://kg.artsdata.ca/entity.html?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK12-155

However, from the perspective of the CMS, Anthony Street has an english literal (an en attached to his name). I found this out by working with Gregory who sent me this [result from a query]([https://kg.artsdata.ca/dereference/external?uri=http%3A%2F%2Fapi.artsdata.ca%2Fquery[…]d_org_person_footlight%26sparql%3Dranked_org_person_footlight](https://kg.artsdata.ca/dereference/external?uri=http%3A%2F%2Fapi.artsdata.ca%2Fquery%3Fadid%3DK12-155%26format%3Djsonld%26frame%3Dranked_org_person_footlight%26sparql%3Dranked_org_person_footlight))

When sending to CMS, a 'transformation' has been applied to turn the name without a language literal into a name with an english literal. This is regularly done to solve an old issue.

Thanks again! let's deploy this and then decide when to stop doing the transformation (we will tackle that in a separate issue, in the future)

cc @saumier @sahalali
