### ISSUE TITLE
Notify Kim with each push to production environment

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#807]
Send Kim an email whenever there is a push to the MAIN branch of Footlight CMS so he can run the regression tests to support Caitlin.

For the next few weeks, Kim will run his regression tests from his local machine pointing to production environment. This will support Caitlin so she does not have to test all features to check if something has broken.

**Propose solution**: Add a workflow that will trigger on a push to MAIN branch and use an action to send the email to Kim. https://github.com/marketplace/actions/send-email

After a few weeks, we will have a discussion with the dev team (in a separate issue) on how to automate Kim's tests in a CI/CD approach.

**Comment by dev-aravind** [comment]
@saumier This is up in production right now, but I haven't set the email to which the notification should be sent. Can you ask Kim on which Email he would like to receive the notifications?

**Comment by sahalali** [comment]
@dev-aravind  I had a word with Kim regarding this. Kim agreed sending the email to taliesen@use.startmail.com.

**Comment by dev-aravind** [comment]
@sahalali I've updated the email to [taliesen@use.startmail.com](mailto:taliesen@use.startmail.com).

**Comment by saumier** [comment]
@dev-aravind 

Here is my feedback. We are almost there but I would like a couple of changes:

1. For the emails, it is impossible to know who it is sending to because you are using secrets when the email addresses are not secrets, and using secrets makes it difficult to maintain or change. For example, as as admin I cannot add my email. Please use the Github repository variables to store the email addresses (SENDGRID_FROM_EMAIL and SENDGRID_TO_EMAIL) and add mine to send to: gregory@culturecreates.com. 
2. Please use multiple lines for the workflow, so it is easier to read and maintain. 
3. I propose you also use repo variables for the html template. The html templates is a bit bulky for the yaml file making the workflow very long.  I think you already started in Github repository variables called NEW_RELEASE_HTML_PAGE

**Comment by dev-aravind** [comment]
@saumier All these issues are fixed in production right now. Also I've set support@culturecreates.com as the secondary mail to receive notifications as that seemed a little better. You can change it if you want. Let me know if you need any changes.

**Comment by saumier** [comment]
I am waiting to receive the next email when there is a new commit to main branch.
