### ISSUE TITLE
Mobile version for Event list view

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#828]
Mobile versions for list views are in Sprint 11, 12 and 13. They were done a long time ago so please take a look and let me know if you can work from these @SyamBabu-M (and @AbhishekPAnil )

**Comment by SyamBabu-M** [comment]
@troughc How will the user and organization filter selection be managed on the mobile screens? I couldn't find them in the Figma.
Also, I couldn't find how filters will be handled on other listing pages. Can we discuss this after the meeting?

**Comment by troughc** [comment]
@SyamBabu-M FYI: we have created new Figma design of the event workspace for mobile here: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7317%3A19842&mode=design&t=jFBruUO2Nlhx0a0H-1

The list view isn't quite ready - we still need to add a 'featured event' indicator to the event list view (since we won't have the thumbnail image in mobile view).  We also haven't done the other workspaces.

**Comment by troughc** [comment]
This one is now ready for yo @SyamBabu-M

**Comment by SyamBabu-M** [comment]
Estimate: 8h for css changes, and some design adjustments.

**Comment by troughc** [comment]
Testing staging on my phone: 
Toggle menu
- I can't switch calendars (I can't switch from Tout Culture to Signe Laval)
- the little down arrow is missing from the calendar name list (in the menu view)
- Username in the same menu isn't center aligned, nor the right font size and weight - should be bold
- rest looks good

Event listing mobile
1. when you go to the next page, you are at the bottom of it instead of the top. You should be at the top - **this is also happening on the desktop version**
2. Feature this event (right click menu) isn't working as expected. Examples:
- Unfeature event is not available in the right-click menu for featured events. Feature this event is there instead. 
- when I click "feature this event" on an event that is already featured, I got an error page (screenshot). After this action, all the events look like they are featured on mobile. On the desktop, nothing changed. I logged out and back in to both mobile and desktop and nothing changed (all events still appear to be featured on mobile and I cannot fix it in the list view, nor in the form)
- **Please test featured events to make sure it works.**

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/efb0b07e-11a2-4920-a9a3-e702531cde4f)

Event listing filter dropdown
- looks good, the Dates filter will need to be updated as @AbhishekPAnil is updating it in the desktop view.

**Comment by troughc** [comment]
@SyamBabu-M 
whilst testing the listing pages, I noticed a couple boo boos in Event form, mobile version. For example, the add more details sections are not being displayed as designed in the figma (with a + symbol in each section) and some of the fields are too big. 
Do we need to create an issue to validate the different forms on mobile (event, person, organizaiton, etc)? I dont' think we did this yet right?
cc @AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
No we don't need create different issue for validating form.The validation is common for all the screens

**Comment by AbhishekPAnil** [comment]
As per discussions in the stand up,we will create a new issue for the forms (mobile view).

**Comment by troughc** [comment]
> As per discussions in the stand up,we will create a new issue for the forms (mobile view).

done, please see issue https://github.com/culturecreates/footlight-app/issues/895

**Comment by troughc** [comment]
@SyamBabu-M  here is the description of the featured event problme.
Feature this event (right click menu) isn't working as expected. Examples:

1. When an event is already featured: **Unfeature event** is not displayed in the right-click menu - but it should be. "Feature this event" is displayed instead.
2. If you right-click "feature this event" on an event that is already featured, you get an error message (screenshot in previous comment). 
3. After the above action, all the events is the list have a blue star as if they are featured. This is on my mobile phone only. On the desktop, nothing changed (the status of being featured/unfeatured is correct). I logged out and back in to both mobile and desktop and nothing changed (all events still appear to be featured on mobile and I cannot fix it in the list view, nor in the form). If you go into the event details on mobile, the status is correct also.
4.NEW TEST: If you click an event that is NOT already featured, you get a success message. However, the event gets unpublished and some required info is removed (like location and ticketing info). 
5. the blue star has persisted even after dong a hard reload.

**Comment by troughc** [comment]
@sahalali  here are 2 events that were set to draft and had ticket prices and locations removed after I right-clicked them to feature event (test 4 above):
https://staging.cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/64415af2d6f5e7006431e503
https://staging.cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/64415af5d6f5e7006431e633

**Comment by troughc** [comment]
Tested staging on mobile: PASSED

### Toggle menu

I can't switch calendars (I can't switch from Tout Culture to Signe Laval): **FIXED**
the little down arrow is missing from the calendar name list (in the menu view):  **FIXED**
Username in the same menu isn't center aligned, nor the right font size and weight (should be bold):  **FIXED**

### Event listing mobile

when you go to the next page, you are at the bottom of it instead of the top. You should be at the top - this is also happening on the desktop version  **IGNORE FOR NOW**
Feature this event (right click menu) isn't working as expected.  **FIXED**

@SyamBabu-M I am assuming that this issue is for me because it is in for review. I assigned it to me, tested and passed the issue, and am now moving it to DONE. If I am incorrect, please assign it back to yourself. Have a good day!
