### ISSUE TITLE
IMAGES: different image dimension requirements for logos and images - right now they have both thumbnail and large (both do)

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#835]
from my research:
What is the standard size for a logo? The standard logo size for a horizontal website layout typically ranges from 250 to 400 pixels wide. A standard logo size for a vertical website header is 160px x 160px. 

Not all logos are equal in size and width so the website will have to accommodate different aspect ratios. 

The logo should be fully displayed within a grid. It could be resized, but never cropped. 
Having the abilty to place the logo within a frame (one option) could be quite useful for insuring all presenters / supporters / organizations obtain equal presence on a page (no brand looks more important than the next).

**Comment by AbhishekPAnil** [comment]
@troughc Right now the backend actually does a default crop for logo's.Since we are not doing any cropping in the frontend,we can close this issue!
