### ISSUE TITLE
Incorporate feedback from Design

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#838]
Link to Figma with feedback: https://www.figma.com/file/ic1fq2c6YmHEsgeMa539l2/Culture-Creates-CMS-QA?type=whiteboard&node-id=0-1&t=uWf5EAHI2ea05DgZ-0

@AbhishekPAnil how about creating a checklist of items from Figma that make sense to do? Or would you like to do another approach. 
cc @SyamBabu-M

**Comment by AbhishekPAnil** [comment]
@troughc I would prefer the checklist approach.

**Comment by troughc** [comment]
Reminder - add the issue of fixing the spacing between filters and search bar on the event listing page (to be consistent with everywhere else.

**Comment by troughc** [comment]
@AbhishekPAnil I added a couple comments to the figma for you.

**Comment by troughc** [comment]
Tested on chrome and safari

Some of the hover states are not yet done - for example, when you hover over hte calendar name and when you hover over an item in the Event list view. You can play the events figma (finals) to see the hover in action.
The white background is not implemented on the listing pages.


Change the dashboard page background color to white -15m
 Change the hover color for calendar displayed in sidebar-15m
 Show the chevron indicator for calendar in sidebar-30m
 Fix the dropdown width for filter all the listing page-1h
 Change display for long user names in the event listing page for user filter as mentioned in Caitlin's comment-30m
 Change the two coloumn approach for all the edit pages two single coloumn approach for larger screens.-4h
 For more details section in edit pages:Add hover on "+" button only-15m
 For more details section in edit pages: Make the "i" information symbol at the end of the text.-15m
 Align the hover state of buttons with that in the figma.-15m
 Change the pagination style in listing screens to that in the figma.-45m
 Add hover states to the three dots in the listing page and also add the respective click state(Once the user clicks the dots ,it should be highlighted as shown in the figma.-15m
 Change the featured event toggle position in edit event page.-15m
 For Selection Item component used in the search :Make the vertical alignment of the contencts inside the component centered and add padding to the bottom.-45m
 Add the spacing between the search bar and filters shown in the event listing page.-30m

**Comment by saumier** [comment]
Note by Gregory: 4 changes: background colour change, side bar drop down, click org/place/person the name of entity should be centered, event list page option to select (3 dots) colour.

**Comment by troughc** [comment]
Actually, the issue is that the hover colour doesn't appear on the Settings page.

**Comment by AbhishekPAnil** [comment]
@troughc  The changes are updated in staging.

> Actually, the issue is that the hover colour doesn't appear on the Settings page.

**Comment by troughc** [comment]
Tested on chrome and Safari (staging): PASSED
