### ISSUE TITLE
CMS event details: Description field word count - display wrong

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#847]
"1 mot" should be "0 mot" when no description has been added. See screenshot.

https://user-images.githubusercontent.com/64489312/214620367-75e009c0-ef18-49dc-b9a8-3cf0625cd0d3.png

**Comment by AbhishekPAnil** [comment]
@SyamBabu-M Also when we Press Enter after typing a word , the word count shown is wrong.

**Comment by troughc** [comment]
Tested in staging: PASSED
