### ISSUE TITLE
Change the inLanguage taxonomy from Place to Event Class in new CMS

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#850]
Currently,the inLanguage taxonomy is shown in the Class Place.

![Image](https://github.com/culturecreates/footlight-app/assets/117100211/adfaef57-1d61-4849-bbfb-49910d5f1c30)

Expected behaviour:
The inLanguage taxonomy should be shown inside the class Event.

**Comment by troughc** [comment]
Reviewed / tested in staging on chrome: PASSED
