### ISSUE TITLE
Invite user is missing disambiguation

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#851]
As an admin, when I invite an existing user, multiple first names appear. I don't know which first name is related to which email and last name. The dropdown should display first name, last name, email so I can disambiguate.

**Comment by troughc** [comment]
@saumier question: is this enhancement based on your user experience or did a client also request this? thanks.

**Comment by saumier** [comment]
@troughc This is something Suhail pointed out in a morning standup when he tried to invite you and I to the new Mauricie calendar.

**Comment by sahalali** [comment]
@troughc It's a small change. It may require some backend changes if the emails are not part of the user listing response.

**Comment by dev-aravind** [comment]
Assigning this to @AbhishekPAnil as no backend changes are needed.

**Comment by AbhishekPAnil** [comment]
> [@troughc](https://github.com/troughc) It's a small change. It may require some backend changes if the emails are not part of the user listing response.

@troughc Should the email be displayed inside the dropdown just below the first name + last name ?



![Image](https://github.com/culturecreates/footlight-app/assets/117100211/2c69847b-9f3d-4505-b83a-c3d3927665d4)

**Comment by troughc** [comment]
@AbhishekPAnil I would like you to add it to the dropdown. It can have the same look and feel as disambiguating descriptions have in search dropdowns for other entities. Make sense?

**Comment by saumier** [comment]
Looking great!
