### ISSUE TITLE
Bug:The user is able to quick create a place just by typing a text in the address

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#862]
Bug : A user is able to quick create a place just by typing a text inside the address field .This creates a postal address  with an empty payload.When we open the place inside the places edit page ,we see that there is no actual street address and postal code added.

Expected behaviour:The user should be allowed to quick create a place only after providing the required fields ,in this case the street address and postal code.For this to happen the user should actually select an item from the google place search dropdown.

**Comment by troughc** [comment]
@AbhishekPAnil there is another bug in STAGING, when I try to look for a place in Google places search bar, nothing appears. For this reason I am making this a higher priority.

**Comment by AbhishekPAnil** [comment]
@troughc Can you specify the search keywords used ?

**Comment by AbhishekPAnil** [comment]
@troughc Is this still a high priority issue ?

**Comment by troughc** [comment]
> @troughc Is this still a high priority issue ?

I reset priority to low.

**Comment by saumier** [comment]
Test passes.
