### ISSUE TITLE
Unable to publish a DRAFT event after the user adds the ticketing information

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#864]
Bug: The user is unable to publish an event after changing ticketing information in an event for the first time.
Edit an existing saved event which does not have a ticketing information.Add a ticketing information and try to publish it.The user is unable to publish the event.This is happening because the event is not saved after adding the ticketing information,hence the backend throws an error.

Expected behaviour:The event should be saved after an edit and the user should be able to publish it(If there are no validation errors) .

**Comment by dev-aravind** [comment]
@AbhishekPAnil update: The publish button doesn't work when we try to quick create an organization and publish the event directly without saving.

**Comment by AbhishekPAnil** [comment]
@troughc The issue is fixed and updated in staging .Please let me know if anymore changes are required.

**Comment by troughc** [comment]
tested 2 scenarios in staging:
- to test the original scenario described by @AbhishekPAnil: Added ticketing info to an [existing draft event](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65b93353efcb5d00a12a76e7) and then click Publish: **PASSED** 
- to test @dev-aravind comment on December 15:  created an [event from scratch](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65b9341defcb5d00a12a7928), add a quick create organizaton, add tickeing and click Publish (never saved the event): PASSED 

If I understand the steps to reproduce correctly. PASSED
