### ISSUE TITLE
Deploy single branch approach:Deploy to staging  & preview channels via GitHub pull requests

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#892]
Create preview channels for the footlight-app using GitHub Actions and Amazon S3. This workflow seamlessly integrates with AWS services, ensuring a way for testing.

Features:
Preview Channels for Pull Requests:
Automatically creates preview channels for pull requests.
Isolates and deploys pull request changes to unique S3 buckets for easy testing and review.

**Comment by AbhishekPAnil** [comment]
@saumier 
I would be implementing the aws amplify for this issue,which has all the preset functionalities for previewing a PR .To implement this I need an aws account which has the access to create "amplify:CreateApp".Would you be able to provide me one or add the permission to an existing IAM user.Thanks.

**Comment by saumier** [comment]
@AbhishekPAnil I created an IAM user for you, and added you to the group with permissions for amplify. 

You can sign-in to the console here: https://culture-creates.signin.aws.amazon.com/console

username: abhishek

See your email for password, then please change your password. Let me know if this works for your need.

**Comment by AbhishekPAnil** [comment]
This feature is now implemented for [culturecreates](https://github.com/culturecreates)
/
[footlight-app](https://github.com/culturecreates/footlight-app) repo.
Once a PR is raised ,the respective branch will be deployed to a aws amplify preview url. @troughc can test with this url.The url will be linked to the respective issue via development setting. @troughc you can see the linked PR from the issue which will redirect you to the PR page and you will see the peview url there.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/eada4d8d-446c-44cd-bf55-7a069f29ee96)



![Image](https://github.com/culturecreates/footlight-app/assets/117100211/f5102002-45a2-4824-8f28-e84a49f62dfe)

Please let us know if you want us to add the preview url explicitly in the issue. (Like this  example : https://github.com/culturecreates/footlight-app/issues/108#issuecomment-1917691775).

Once Caitlin tests and gives the confirmation we will merge it to staging.

cc @saumier

**Comment by AbhishekPAnil** [comment]
I have confirmed that after merging a particular PR the respective preview url will be deleted from aws amplify.
Tested using https://github.com/culturecreates/footlight-app/pull/934
