### ISSUE TITLE
navigating through pages using bottom navigation buttons and arrows

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#903]
On EVENTS AND USER SETTINGS list views only:
When I use the bottom navigation menu (numbers and arrows) to go to different pages in the list views for **Events** and **User management settings**,  the bottom of the page is always displayed (not the top). 

The CMS seems to retain my position on the page. Example: if i go to the last page in the list and it is shorter than the previous pages (i.e. it has just a couple of events) I can see both the bottom navigation and top of the page in my display. Then, when i use the navigation features at the bottom of the page to go to another page, it places me at the same spot (near the top). I then scroll to the bottom and use the nav, and I am placed at the bottom.

Expected behavior is to be at the top of each page.
For me, this happens on both mobile and on desktop.

**Comment by AbhishekPAnil** [comment]
@troughc Would you be able to show me this bug.I am unable to reproduce it.When I use the navigation in the bottom,I am always scroll to the top of the page.

**Comment by AbhishekPAnil** [comment]
Bug report :
The bug is caused because of a height given to the loading indicator component.
To reproduce the bug in any screen ,you can decrease the height of screen from developer settings.

**Comment by troughc** [comment]
I tested this in Staging on both settings and events. The positioning onb the page looks okay; however, I found a bug:the pagination number on those two workspaces seem to be moving in sync. For example, in Tout Culture: go to Events, page 5. Now switch to user management and you are also on page 5. change to page 19 and go to event workspace - page 19. Go to the last page of events and switch to user management settings - blank page.

**Comment by AbhishekPAnil** [comment]
@troughc I have fixed the issue with page number being same for events and users listing.
There was also another bug were the page number of taxonomy listing was not persisting. You can check this in staging or in production to confirm this bug.I have also fixed this in the PR.

**Comment by troughc** [comment]
Checked production about taxonomy issue: confirmed.
Tested in PR: PASSED ready to deploy
