### ISSUE TITLE
adding entities to events that come from Artsdata not saving

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#925]
issue raised by Signe Laval:
Maude cannot add a performer that is in Artsdata to an event and then save. In contrast, you can add a performer that is ALREADY in a footlight CMS database. 
I retested this and it is also true for organizers and supporters. I also tested adding entities from other Footlight calendars and found another bug. I will log this bug [in another issue and link it to this one](https://github.com/culturecreates/footlight-calendar-api/issues/878)

**Issue:** In the event form, a user cannot add an organizer, performer or supporter from Artsdata and then save the event. The save button doesn't work.

**Expected behaviour:** users should be able to add performers from Artsdata and then save successfully

Please see this video to see steps to reproduce (from Maude):
https://crclaval-my.sharepoint.com/:v:/g/personal/m_fraser_culturelaval_ca/EVOyP5wz3MJBm1z1pfE8SgsBazBOoZ312V_wlHsnB2ClBg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=6SxzQm

**Comment by AbhishekPAnil** [comment]
There seems to be an api error while adding a entity from artsdata.
`{"status":"error","error":"Not Found","message":"The entity identifier does not exists.","currentTime":"2024-01-30T05:58:52.146Z","path":"PATCH /events/64415af5d6f5e7006431e633"}`

**Comment by troughc** [comment]
Tested on Chrome and Safari: PASSED
Please push this fix to production during the deploy window @sahalali @dev-aravind 


Also, note that a new bug was uncovered and logged here: https://github.com/culturecreates/footlight-calendar-api/issues/880 
This is assigned to Dev.
