### ISSUE TITLE
New CMS - Warning symbol (yellow triangle) is missing from hidden fields when they are empty (see Figma)

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#93]
Missing from all bilingual fields (looking at french UI)

**Comment by saumier** [comment]
@troughc The warning symbol only shows once the event is saved. It does not show when you are first creating an event.  If we showed it when the event is being created, all english and french tabs would have the warning icon which doesn't make sense. Once an event is saved, the warning shows when there is a translation missing. For example, when some text in the english field but not in the french field.  Same idea when there is a french text without an english text.  Does this make sense? I can't see a better way to do this. It is not a validation tool, but rather a reminder. Think of it as a warning symbol to show you missing translations.

**Comment by troughc** [comment]
What if you save and publish at the same time @saumier (you create, save/pubish and event in one go)? Then you would never see the warning and might publish without realizing the translation is missing from the French Description....
So, could the icon appear when you leave a field for the first time, for example, when you leave the title field or leave the description field (after entering text in one of the languages)?

Also, the icon should only be shown on the tab of a HIDDEN field, not the DISPLAYED field tab. For example: the French tab for title is displayed (and empty); the English (hidden) tab for title is empty; the English tab would have the warning (not the French tab). So, not all the tabs would have a warning icon.

**Comment by saumier** [comment]
Closing issues because it is stale. The UI design has moved on.
