### ISSUE TITLE
Unable to send a duplicate event to review directly

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#937]
This is a frontend issue.
Steps to reproduce:
1.Create any duplicate event .
2.Try to send it for review without editing.
3.Gets an api error :
 {
    "status": "failed",
    "error": "Cannot read properties of null (reading 'id')",
    "currentTime": "2024-02-01T09:19:46.045Z",
    "path": "PATCH /events/undefined/toggle-publish"
}

This is happening because the event is not saved.
Here the save event api should be called first before calling the toggle-publish api instead it is calling the toggle publish api directly.

**Comment by troughc** [comment]
Tested: PASSED
