### ISSUE TITLE
Enhancement - taxonomy concept box should resize to display all top-level concepts without needing to scroll

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#945]
Sometimes there is a long list of top-level concepts. Admins may want to reorder their concepts according to specific criteria (reorder alphabetically, set in order of popularity, etc). When there are many in the list, it is difficult to do this task with the scrollbar.

### Example of long list: signe laval (see scroll bar)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/c3973ad8-68c4-4283-a0e5-49ec10e25c2f)

### Example of long list: Tout Culture l (see scroll bar)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/b49848f5-5bbc-4fbf-b5c5-f9e7842b2e1c)

### Enhancements
**1. To make it easier, the box should be longer for longer lists.**
Here are two approaches:
1. allow the user to drag the box to the length they want. Suggestion: the user should also be able to drag the width to the maximum width of the page.
2. Have the box automatically lengthen to accommodate the entire list of top-level concepts (with child concepts closed). In this option, there should be a minimum length (the length we have today) and a maximum length TBD). 

I think a combination of these two approaches would be great. We start with 2, and then allow the user to make it even larger if they need.

**2. For monolingual sites, the box of concepts be widened to take up the space** 
This will improve the user experience, especially when they open to view child concepts.

**Comment by SyamBabu-M** [comment]
@troughc 
Estimate: 
Method 1 - 3 days. Needs to research on making container draggable. Needs refactoring of current implementation. 
Method 2 - 2 hrs (style change). 0.5 hrs testing

**Comment by troughc** [comment]
@SyamBabu-M when you start working on this, let's decide together the maximum length the box can automatically lengthen to.

Also, let's do the following change (mentioned above) at the same time: _For monolingual sites, the box of concepts be widened to take up the space. This will improve the user experience, especially when they open to view child concepts._

**Comment by troughc** [comment]
Tested in Chrome and Safari: PASSED!
