### ISSUE TITLE
Accounts Automatically Switching When Changing URL Manually

### ISSUE THREAD

**Issue by dev-aravind** [culturecreates/footlight-app#947]
Steps to reproduce:

1. Login as an admin.
2. Open an event from the event listing page.
3. Change the URL to make the page a read only page (remove "/add-event")

the resulting page will have a different user logged in from which the one you started with sometimes.

Expected behaviour -  the user should not change when changing the URL manually.

Note: This happens only when the same browser is used to login to Footlight CMS on different accounts.

**Comment by troughc** [comment]
@AbhishekPAnil does this need to be scheduled?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil does this need to be scheduled?

Yes @troughc

**Comment by dev-aravind** [comment]
@troughc These are the detailed steps to recreate this bug.

1. Open 2 tabs of footlight, log in using 'Profile A' on both tabs.
2. Log out of tab 2 and login using 'Profile B' on the same tab.
3. Switch to tab 1 and open an event. 
4. Change the URL manually, in my case I changed https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/648b1d845526a70064502449 to https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/648b1d845526a70064502449
5. You can see on the top right corner that the account has switched to 'Profile B' even though we started off with 'Profile A' on tab 1.

**Comment by troughc** [comment]
Tested PASSED

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil  Deployed to production
