### ISSUE TITLE
Concept popup issues: wrong popups appear, sometimes label not pre-filled while editing.

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-app#951]
The concept label does not appear when a user tries to edit the concept label by clicking on the concept label from the list. However, it's working fine if the user clicks on the "pen" icon.

![Image](https://github.com/culturecreates/footlight-app/assets/139197166/b8d911f3-58fb-4726-92fe-fd3ef2815958)

Below show is the popup view when clicking on the label.
![Image](https://github.com/culturecreates/footlight-app/assets/139197166/db485faa-6b83-4fa8-8970-b1a8af63eaa4)

Below show is the popup view when clicking on the edit button (pen icon)
![Image](https://github.com/culturecreates/footlight-app/assets/139197166/d9b2bb2c-fcd8-43c8-935f-e2c1f1b5a50e)

**Comment by saumier** [comment]
@SyamBabu-M See comment in PR. Testing at this url https://pr-1006.dla06mbe0wyl7.amplifyapp.com/ the issue was not fixed. The popup still appeared with no label when clicking on the concept label to edit (clicking on pencil worked).

**Comment by SyamBabu-M** [comment]
@saumier the popup in the screenshot is for adding a new concept as a child to the concept that was clicked on.
As per our user story, 
1 - upon clicking on the pen icon a popup to edit the current concept is opened.
2 - upon clicking anywhere else on the card(this includes clicking on the label), a popup to add a new child concept is opened.
3 - upon clicking the "+ item" button, a popup to add a concept to the topmost level is opened.

Clicking on the label must open a popup to create a new concept as this is the only way to create a child concept as of now.

**Comment by SyamBabu-M** [comment]
@saumier Steps to reproduce bug in staging - 

1 - Go to any taxonomy edit form, click on the label of a concept. A popup with title "Add concept". This modal can be used to add a child concept.
2 - Close the popup. Click on edit icon of the concept. A popup with title "Edit concept" will open. The data will be prefilled in the popup. This modal can be used to edit the concept info.
3 - Close the popup. Click on the label again. The newly opened popup will have title "Edit concept". This is a bug the title should be "Add concept" and the popup should be for adding a concept.

You can follow the same steps while testing the PR.

**Comment by saumier** [comment]
@SyamBabu-M Thanks for the repo steps.

PASS
> 1 - Go to any taxonomy edit form, click on the label of a concept. A popup with title "Add concept". This modal can be used to add a child concept.
2 - Close the popup. Click on edit icon of the concept. A popup with title "Edit concept" will open. The data will be prefilled in the popup. This modal can be used to edit the concept info.
3 - Close the popup. Click on the label again. The newly opened popup will have title "Edit concept". This is a bug the title should be "Add concept" and the popup should be for adding a concept.
