### ISSUE TITLE
Places: Add image display to read only page

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#954]
Use the same layout as is used for organizations and people

**Comment by AbhishekPAnil** [comment]
@troughc I might have been wrong about this issue.We are already displaying the image for place in the read only page.I tried saving a place with an image it shows in the read only page with the same layout that of organization.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/0718c491-0c08-498b-9fb1-b1e414160d18)

**Comment by troughc** [comment]
Okay, so it may be okay. I did find [this event in production](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/64f8bc757d6aa8006435542d) @AbhishekPAnil where the image is in the wrong location on the read only page:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/24d54fc1-4ce3-43d1-9f15-e9527079f206)

**Comment by saumier** [comment]
@SyamBabu-M Looks good. Thx.
