### ISSUE TITLE
VirtualLocation Google bug

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#958]
Google requires that events with a location that is a type VirtualLocation.  

Problem: The CMS has a Virtual Location URL but it is missing in the JSON-LD.

Solution: When generating JSON-LD for an event, include the Virtual Location URL  ("Link for the online event" ) supplied in the data from the CMS. If there is no Virtual Location URL then leave it blank.

Example: JSON-LD missing Virtual Location URL 
CMS https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65a5860f9468f3006376cb89
Webpage https://toutculture.ca/evenement/initiation-au-dessin-manga-dessine-eevee-en-65a5860f9468f3006376cb89/?atelier

JSON-LD in Nebula viewer
https://artsdata-nebula-d1ec887e2637.herokuapp.com/dereference/external?uri=https%3A%2F%2Ftoutculture.ca%2Fevenement%2Finitiation-au-dessin-manga-dessine-eevee-en-65a5860f9468f3006376cb89%2F%3Fatelier

**Comment by sahalali** [comment]
@saumier I am not sure I understand the statement  "add a relative link to current page # for the VirtualPlace url ".
Can you please elaborate on this?

**Comment by saumier** [comment]
@SuhailAliyar I actually don't think my proposed solution works.  Can you think of a good solution? I'll describe the problem in more details here.

Take a look at the webpage https://signelaval.com/fr/evenements/65b2a0e18468f4006483220e/operations-secretes-de-la-cia-les-annees-70-et-80

This event on Signe Laval has our JSON-LD which you can view in [Nebula](https://artsdata-nebula-d1ec887e2637.herokuapp.com/dereference/external?uri=https%3A%2F%2Fsignelaval.com%2Ffr%2Fevenements%2F65b2a0e18468f4006483220e%2Foperations-secretes-de-la-cia-les-annees-70-et-80) or [validator.schema.com](https://validator.schema.org/#url=https%3A%2F%2Fsignelaval.com%2Ffr%2Fevenements%2F65b2a0e18468f4006483220e%2Foperations-secretes-de-la-cia-les-annees-70-et-80).

The problem is that an Event's location is a type VirtualLocation which Google [requires to have a schema:url](https://developers.google.com/search/docs/appearance/structured-data/event). The user didn't enter one as you can see in our [CMS here](https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/65b2a0e18468f4006483220e).

This causes as error in Google Search Console. There are currently 4 webpages reporting errors in the Event JSON-LD.
<img width="1509" alt="Screenshot 2024-02-13 at 9 48 57 PM" src="https://github.com/culturecreates/footlight-app/assets/419491/eefe40db-b789-411a-9726-a751339aae79">

An error is bad. A warning, like a missing presenter or offer is ok, meaning we can leave the warnings without fixing them. But an error is bad and makes the entire event not eligible for Google's search rich results. 

So to fix this, we need to add a schema:url to the VirtualLocation of the Event.  What can we add?  We could insist that the client enter a url for their VirtualLocation by making the url mandatory. I discussed this with Caitlin and she raised a good point that the client does not have a URL for this VirtualLocation, or does not know it yet.  

In these cases I thought we could fall back on the current webpage. But we don't know the URL of the current webpage in the CMS where we generate the JSON-LD. Next I thought we could use a relative path with "#" but I tried this in validator.schema.org and it doesn't seem to work. When I tried with  "url":"/" the validator added  "https://example-test.site/". You can try it as well to see if there are other ways to supply a relative url.

The other idea is to use the webpage url. Then I noticed that the url for this event is wrong. In validator.scheme.org is shows that the Event's url is "http://kg.footlight.io/".  There is no event url entered into the CMS. When there is no event url in the CMS then the property in the JSON-LD should be "" or not present at all.

Another idea I have is to use the AggregateOffer url if it is present. But this is probably hard to implement using the current setup and is not necessarily better.

So my conclusion after having looked at the options is to leave it as it. The event will be disqualified by Google because there is no VirtualLocation url. The only way to fix this as per Google's instructions is to add a "link to the online event" URL in the CMS.  We still should not make it mandatory. The website can still display the VirtualLocation name as it does today. 

So if you agree I propose we fix only the Event's url bug. I think this can be done in the context.

**Comment by saumier** [comment]
@troughc I assigned this to HIGH because of the errors reported by Eric at Minimal.

**Comment by sahalali** [comment]
Added URL to the location in the JSON-LD. The change is now deployed to staging.
Example: https://staging.api.footlight.io/events/65cf655478764100a266c752?include-json-ld=true

**Comment by sahalali** [comment]
@saumier I like the idea of handling it with the context. 
I've updated the context and deployed it to staging. Can you please review it?

**Comment by saumier** [comment]
@sahalali Looks great. I checked the event url (as entered in the CMS) and the VirtualLocation url and both worked as expected with and without urls.  Sorry about my confusion in the morning.
