### ISSUE TITLE
Enhance Responsive Design - Event screens

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#964]
Enhancing responsiveness of event screens.

Covers - 
1 - add/edit page
2 - read-only page

[estimate](https://docs.google.com/spreadsheets/d/1bcJQuIafrvokZ01MJT7jlrs9gwOHiD1im2QqhLtD5yw/edit#gid=0)

**Comment by troughc** [comment]
Feedback from meeting @SyamBabu-M your suggestion of how to implement the Calendar picker works for me and looks good. :)

**Comment by troughc** [comment]
![Screenshot_20240222-153614](https://github.com/culturecreates/footlight-app/assets/64489312/a2608949-2a2a-459f-af36-ff68d855e78d)

**Comment by troughc** [comment]
Tested design fix on my mobile (google pixel 6): PASSED
