### ISSUE TITLE
Enhance Responsive Design - Places screens

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#965]
Enhancing responsiveness of places screens.

Covers -
1 - add/edit page
2 - read-only page
3 - Place Listing
4 - Place search page

[estimate](https://docs.google.com/spreadsheets/d/1bcJQuIafrvokZ01MJT7jlrs9gwOHiD1im2QqhLtD5yw/edit#gid=0)

**Comment by troughc** [comment]
tested on my google phone: PASSED
