### ISSUE TITLE
Enhance Responsive Design - Organization screens

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#966]
Covers -
1 - add/edit page
2 - read-only page
3 - Listing
4 - search page

[estimate](https://docs.google.com/spreadsheets/d/1bcJQuIafrvokZ01MJT7jlrs9gwOHiD1im2QqhLtD5yw/edit#gid=0)

**Comment by troughc** [comment]
Everything looks great, thank you! PASSED

@SyamBabu-M there is a bug but I'm not sure it has anything to do with this: when I try to delete a new organization that I just created, i get this error:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5810db1d-0d2d-46a4-8f1c-aa52035e04f1)

I will log this separately as it is in staging too.

**Comment by SyamBabu-M** [comment]
@sahalali @troughc, This issue is not updated in staging currently. Its better to update [966](https://github.com/orgs/culturecreates/projects/2/views/1?pane=issue&itemId=53105998), [967](https://github.com/culturecreates/footlight-app/issues/967), and [965](https://github.com/orgs/culturecreates/projects/2/views/1?pane=issue&itemId=53105670) to staging together, as they are interdependent.
