### ISSUE TITLE
Enhance Responsive Design - People Screens

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#967]
Covers -
1 - add/edit page
2 - read-only page
3 - Listing
4 - search page

[estimate](https://docs.google.com/spreadsheets/d/1bcJQuIafrvokZ01MJT7jlrs9gwOHiD1im2QqhLtD5yw/edit#gid=0)

**Comment by troughc** [comment]
@SyamBabu-M can I test this? And where?

**Comment by SyamBabu-M** [comment]
@troughc this issue covers People screens only. We have a separate [issue](https://github.com/orgs/culturecreates/projects/2/views/1?filterQuery=resp&pane=issue&itemId=53105670) for Place screens.

**Comment by troughc** [comment]
OOPS! :)
Tested on my phone: PASSED
