### ISSUE TITLE
cannot change user type

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#969]
When logged in as an Admin, I cannot change anybody's user type. I get these errors when I try (after I change a user from one role to another and click save):

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ca518e2d-d33c-43fa-af24-a6df0250b279)

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/b5116564-7b6e-450b-9c8c-1edda3e98b12)

**Comment by dev-aravind** [comment]
@troughc This is fixed in production and in staging.

**Comment by troughc** [comment]
Tested in Safari and Chrome: PASSED. 
Also passed test point 1 from issue 971 mentioned above.
Will close as this issue has been implemented in Production.
