### ISSUE TITLE
blue text options (with info icon) issues in layout and interaction

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#972]
The blue text has two parts. When you hover over the  + or switch icon part (at the start of the line) the info popup appears. It doesn't appear when you hover over the part that is the blue text and i icon.
**Expected behavior:** the popup text should appear when you hover over the section with the i icon. 
Note that both sections can be clicked to add the field to the left (this is how it works today).

Sometimes the information icon is on a separate line. Please make sure that at least one word is next the info icon. I only saw this is two places in the English UI, but I'm not sure if it happens at different sizes.
Screenshots:

### tickets section
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/4f015331-5f7a-40c8-9dd2-fb9170d23193)

### other information section (supporter)
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f1ae84a6-1a31-4c6b-a269-739834432f3b)

**Comment by saumier** [comment]
@SyamBabu-M The info icons display a blue tooltip. But the text is sometimes longer than the fixed width of the blue box.



![Image](https://github.com/culturecreates/footlight-app/assets/419491/cdd8a100-8be0-4043-8c7e-ada966b22ff9)

**Comment by saumier** [comment]
@SyamBabu-M My tests did not pass:

1. Chrome:  The information icon is on a separate line (see screen grab).
2. Safari: The info popup for some appears as an illegible narrow tall box (see screen grab)

**Comment by troughc** [comment]
@SyamBabu-M in English only, something else has now moved: the last blue text "Event language" has the icon on the wrong line:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6093fa34-8fe4-41eb-ba05-8cc9a4425fc0)

**Comment by troughc** [comment]
Tested: PASSED
