### ISSUE TITLE
Enhancement: hide sections in UI display that are not available to specific user types

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#975]
Please update the UI to hide sections that are not used by specific user types.

### Examples of sections that are available to Admin only and should not appear in the UI for other users:
- Taxonomies (entire section) so 'Taxonomies' should be hidden in the left nav (and Settings would move up)
- in Settings: Calendar widget, Calendar settings, Mandatory fields. Note that all users can view the list of users  so it would remain as is.

### Design reasoning to choosing between disabling an option vs hiding:
- Disabled indicates that something needs to be done/ something needs to happen before the option can be enabled
- objects/options/parameters are hidden if they can never be used or interacted with by a user (the option is not intended for them).

**Comment by AbhishekPAnil** [comment]
Estimate : 2h
1.Add logic to show the respective tabs are shown only to admin.
2.Add the logic to restrict the uses from accessing the restricted pages directly ( useEffect ).

**Comment by troughc** [comment]
Tested guest, contributor, and editor users on chrome and safari: PASSED
Tested admin user on chrome and safari: PASSED
