### ISSUE TITLE
users saving entity without required fields

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#978]
This is related to when empty spaces are trimmed. They need to be trimmed before validating. 

Additional information regarding missing required fields in Places (specifically the address fields). This bug is also present in Tout Culture.
Example is [this place](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65c5247b7f90c70063659b14)

This place was created by [this GUEST user](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/settings/user-management/65c51fa97f90c7006365998f)

The only event this user created is in the past [here](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65c52a527f90c7006365a695)

And that event was updated by an ADMIN (Scott), who probably fixed the location - the event is linked to a different place ([a complete, correctly entered place at the same address](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/6499f9d03c19fa0064e4e162))

**Comment by troughc** [comment]
Caitlin will check with Tout Culture emails to see if she can find the issue

**Comment by troughc** [comment]
@SyamBabu-M I created a test PLACE with my GUEST user account and my ADMIN user account and entered a single space into the street address and a single space into the postal code. This allowed me to save the place without an address (address is a required field). This is the issue.

AS GUEST:
https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65faeda0660be000ac9b0e2c

AS ADMIN:
https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65faeee4660be000ac9b1030

Created using quick Create in an event (you don't need to save the event):
https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/places/65faef84660be000ac9b11b7


As you can see the places I created above exists even though they are missing required fields. I bet this also happens when you create a place using quick create

Steps to recreate.
1. Log in as a guest/admin or whatever
2. Create a new place
3. When creating add a space in the address field and add a space in the postal code field, then save (for quick create, simply add a space in the address field)
4. The place is saved successfully without the above required fields.
5. Go back in to EDIT the place and then click  save. Warning appears that required fields are missing. 
Because these places can be created, you can use them in an event. HOWEVER, they are missing required fields which will cause problems further downstream.

Hope this helps.

**Comment by troughc** [comment]
Tested adding a place using the steps above in the tout culture calendar.
One issue only:
With the bilingual calendar, if a field is empty for street address (in my case it was the english field), the place doesn't save. However, I don't see where the error is until I click the tab to show the english field.
steps to reproduce

1. Create a new place in Tout Culture. I created this one: https://pr-1066.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/places/add-place?id=661d5b0ae30e6d00a061bb8e
2. Name the place and fill in required fields including a street address and postal code. For the street address, only fill in French fields (not english tab). Note that the name you enter in the search bar is automatically used for both French and English versions.
3. Try to save the place. There is an error but you can't tell where it is. (because the tab is hidden).

Regarding "Note that the name you enter in the search bar is automatically used for both French and English versions" : this makes sense for people but I'm not sure it works for places and organizations. These often have different versions of their names in different languages. We can tackle this in a separate issue if needed.

**Comment by troughc** [comment]
Tested on chrome and safari: PASSED

**Comment by AbhishekPAnil** [comment]
Status : Deployed to production
