### ISSUE TITLE
UI Feature "Add more details to your event"

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#98]
Some Event properties (see Figma) appear by default on the right side when they are empty. The user can select a property on the right side to make it appear on the left side in a fixed order (see Figma). If the user adds data then the property remains on the left side. Otherwise, if there is no data entered, when the user leaves and returns to the event, the property appears back on the right side.

Some properties on the right side represent a single field, like "video link". Some represent a group of fields, like "contact" which expands into 4 fields (see second screen capture below).

![Image](https://user-images.githubusercontent.com/419491/221895871-c1f6279a-38af-4b75-968f-f545cd801e84.png)

Section of fully expanded properties showing order of fields.

![Image](https://user-images.githubusercontent.com/419491/221897403-0ea2e162-c303-4d34-9af8-c428d5f68285.png)

**Comment by AbhishekPAnil** [comment]
ESTIMATE  3.5 hrs

Subtasks:
1.Add the translations 
2.Add the right side content.
3.Add the functionality to add the field on the left side upon clicking the respective options on the right.

**Comment by AbhishekPAnil** [comment]
Actual Time taken to complete : 5.5 hrs

**Comment by AbhishekPAnil** [comment]
@troughc I have implemented the "scroll to the field" and updated it in staging. It took around 2hrs.Please do check it out and let me know if any additions are needed.
Thank you!

**Comment by troughc** [comment]
Tested the scroll - looks great! Passed.
