### ISSUE TITLE
cannot delete an organization

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#985]
Steps to repeat in STAGING:
As an admin, try to deletet an organization. Or create an organization and save, and then try to delete
You get this error:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/39a3bae4-8dfa-4f2f-a321-2d5f6327c67d)

**Comment by dev-aravind** [comment]
@troughc This is fixed in staging. Please test it out and let me know.

**Comment by troughc** [comment]
Tested: PASSED

**Comment by dev-aravind** [comment]
@troughc I think it was part of the release today so the fix is also pushed to production.

**Comment by troughc** [comment]
closing this issue, thanks!
