### ISSUE TITLE
Calendar widget logo

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#986]
Signe Laval requests we use the attached logo at the bottom of the widget, instead of the one that we currently are using.

At the same time, please check the logo sizing - it looks a bit small (height wise).

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/61f51eb3-f731-4b63-9bfc-ae8f68b373af)

**Comment by troughc** [comment]
@SyamBabu-M Question: where did the logo we are using for signe laval come from? Is it the same as the one in the calendar? I ask because the one in the calendar is round.

**Comment by sahalali** [comment]
@sahalali To change the Signe-laval calendar logo with the image provided in the issue.

**Comment by saumier** [comment]
@sahalali This is sadly funny. The logo is 4 px high and illegible.  I don't this is what the client is expecting.

I propose using the image to replace the text and logo.  Place the image to fit (without stretching) the full width of 84px. Using your graph design eye to make it look good.


![Image](https://github.com/culturecreates/footlight-app/assets/419491/b3d3f084-2be1-4382-8a60-c0d11ecda95c)

**Comment by sahalali** [comment]
Let's set the image height to 100% of the component and auto width for alignment with the calendar name, as discussed with @SyamBabu-M and @AbhishekPAnil.

Unless there is a specific client requirement for a very small image size, we can proceed with this approach. However, if necessary, we can engineer the image sizes. @saumier

**Comment by saumier** [comment]
@sahalali @SyamBabu-M I like the approach you have taken. Well done in thinking this through and finding the simplest solution.

@SyamBabu-M Thanks for fixing the bug I found on Safari during the standup. 

However, it looks like there is too much space now below the line "Calendar provided by..." in the footer of the mobile view.  Here are screen grabs.  Can the blank space be reduced so we see more of the events in the mobile version?



![Image](https://github.com/culturecreates/footlight-app/assets/419491/dbd3db2a-21a8-47bd-8bdf-14c930e2f72c)
![Image](https://github.com/culturecreates/footlight-app/assets/419491/4226f3b3-9824-43a6-aa6a-af62d1a03f78)

**Comment by saumier** [comment]
@SyamBabu-M After our meeting on Friday, I noticed something unexpected in the widget code snippet.  Please raise these issues in the next standup and request help from @SuhailAliyar and/or me as needed.
```
<iframe src="https://s3.ca-central-1.amazonaws.com/staging.cms-widget.footlight.io/index.html?eventUrl=https%253A%252F%252Ftoutculture.ca%252F%2524%257Blocale%257D%252Fevent-detail%252F%253Fevent%253D%2524%257BeventId%257D&searchEventsUrl=https%253A%252F%252Ftoutculture.ca%252F%2524%257Blocale%257D%252Ffilter-evenements%252F&logo=https%253A%252F%252Fcdn.footlight.io%252Fiiif%252F3%252Ftout-culture-logo.png%252F0%252C0%252C1620%252C1080%252F400%252C%252F0%252Fdefault.png&locale=en&limit=9&height=600&color=%23607EFC&calendar=tout-culture" width="100%" style={{ maxWidth: "1000px", border: 'none' }} height="600px"></iframe>
```

Issues that need to be fixed:
1. Bucket has "staging" in the name, this should not be using in production environment. Staging and production should have separate buckets and workflows.
2. The domain is amazonaws.com. This should be changed to a footlight.io domain to reduce coupling with AWS and make it easier to maintain, and shield the widget from infrastructure changes.
3. Style attribute is written in the wrong syntax and does not work as currently displayed `style={{ maxWidth: "1000px", border: 'none' }}`
4. Main branch is not being used. The main branch should have the code that of the widget in production.
5. Code in production should have a version.

Questions for improvement (maybe another future version)
1. Why are the parameter values percent encoded twice?  
1. Why are you passing eventUrl parameter in every iframe code? If the client's website changes, it will break the widget, and we will need to change every iframe code that was copy/pasted. If we have 100 widgets, how will we change each of these widgets on the customers website? Caitlin raised this concern in the initial design doc.
3. Same for searchEventsUrl.

**Comment by SyamBabu-M** [comment]
@saumier I have updated the main branch and added a production version for the widget to a newly created widget. I have changed the domain name also.

We can further discussed about the questions for improvement.

**Comment by saumier** [comment]
@SyamBabu-M Please give me 2 subdomains for the staging and production widgets so I can map them to `staging.widget.footlight.io` and `widget.footlight.io`.

**Comment by SyamBabu-M** [comment]
@saumier I have updated the styles. This will be reflected in staging.
I will open another issue to track the other issues mentioned.

**Comment by SyamBabu-M** [comment]
@saumier I have opened another issue to track other problems. Please take a look [into this](https://github.com/culturecreates/footlight-calendar-widget/issues/28)
