### ISSUE TITLE
Translate DeepL

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#99]
As a user, I need to translate my event description into French (or English).  I want to load my current English description into DeepL, automatically have it translated, and then copy/paste the translation back into the CMS. All with as few manual steps as possible.

**Client feedback**: DeepL translation button - [Caitlin] showed it to [Isabelle at Tout Culture] and the idea of how it would work (loading the description into the tool and translating it to be copied) and she liked it.

**The Figma design for this button is in sprint 12. Here are screenshots of it (French and English):**

![Image](https://user-images.githubusercontent.com/64489312/221928943-78efc941-d002-488a-9103-f3af3ecfaaca.png)

![Image](https://user-images.githubusercontent.com/64489312/221928968-bb913bfa-28b3-43bd-9fec-5df27081e6fb.png)

## Example

The following example I deduced by looking at the DeepL website. Without needing an API key, it is possible to call the DeepL website with  https://www.deepl.com/translator and indicate fr to en translation as follows:

[https://www.deepl.com/translator#fr/en/{text percent encoded}](https://www.deepl.com/translator#fr/en/16%20ans%20et%20plusLe%20deuxième%20spectacle%20de%20Mariana%20Mazza%20sappelle%20Impolie%20et%20pour%20respecter%20le%20titre,%20elle%20ne%20vous%20en%20dira%20pas%20plus.Mais%20ce%20quon%20peut%20vous%20dire,%20cest%20que%20le%20titre%20complet%20du%20spectacle%20est%20Impolie%20%20Pardonne-moi%20si%20je%20taime%20et%20que%20Mariana%20sest%20rendu%20compte%20avec%20les%20années%20que%20nous%20sommes%20tous%20limpoli%20de%20quelquun.%20Pour%20elle,%20cest%20lamour%20qui%20la%20rend%20impolie,%20car%20le%20fait%20dêtre%20aimée%20lui%20permet%20dêtre%20vulnérable%20et%20donc%20dêtre%20pleinement%20elle-même.%20Au%20fond,%20toute%20cette%20impolitesse%20nest%20que%20de%20lamour!%20Ce%20spectacle%20vous%20permettra%20davoir%20accès%20au%20plus%20authentique%20de%20Mariana,%20ce%20qui%20se%20veut%20autant%20hilarant,%20touchant%20que%20divertissant)

**Comment by saumier** [comment]
@saumier Add example of calling DeepL using GET call along with text in the description

**Comment by saumier** [comment]
@AbhishekPAnil I added the example above to show you DeepL can be called with the text and the language to translate into.

**Comment by AbhishekPAnil** [comment]
ESTIMATE 1-2 hrs

Subtasks 
1.Add button for translate 
2.Add api data for deepL .

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by AbhishekPAnil** [comment]
@saumier "I think the text needs to be percent encoded to things like "/" get passed through."------> 
I tried encoding the text but it still breaks on the forward slash.

**Comment by saumier** [comment]
@AbhishekPAnil 
https://www.deepl.com/translator#fr/en/hello/there

https://www.deepl.com/translator#fr/en/hello%2Fthere

**Comment by saumier** [comment]
@AbhishekPAnil This seems to work using %5C  in https://www.deepl.com/translator#en/fr/hello%5C%2Fthere%0A

**Comment by saumier** [comment]
@please test in staging. Thx.

**Comment by troughc** [comment]
Tested on Chrome - staging
PASSED
